### ISSUE TITLE
When I use accelerate and trying to create the Accelerator object , there always been wrong

### ISSUE THREAD

**Issue by pengjunfeng11** [huggingface/accelerate#1102]
### System Info

```Shell
- `Accelerate` version: 0.16.0
- Platform: Linux-4.15.0-189-generic-x86_64-with-glibc2.27
- Python version: 3.9.13
- Numpy version: 1.22.3
- PyTorch version (GPU?): 1.12.1 (False)
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: FSDP
        - mixed_precision: no
        - use_cpu: False
        - dynamo_backend: NO
        - num_processes: 8
        - machine_rank: 0
        - num_machines: 1
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - deepspeed_config: {}
        - fsdp_config: {'fsdp_auto_wrap_policy': 'TRANSFORMER_BASED_WRAP', 'fsdp_backward_prefetch_policy': 'BACKWARD_PRE', 'fsdp_offload_params': True, 'fsdp_sharding_strategy': 1, 'fsdp_state_dict_type': 'LOCAL_STATE_DICT', 'fsdp_transformer_layer_cls_to_wrap': 'berry_TEST_layer'}
        - megatron_lm_config: {}
        - downcast_bf16: no
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

All the code is here, and I has installed the NCLL in my computer

```
from accelerate import Accelerator

accelerator = Accelerator()

```

All the debug infomation is here 
```

Traceback (most recent call last):
  File "/home/ubuntu/Desktop/dev/练手/翻译/code/123.py", line 3, in <module>
    accelerator = Accelerator()
  File "/home/ubuntu/anaconda3/envs/pytorch39/lib/python3.9/site-packages/accelerate/accelerator.py", line 323, in __init__
    self.state = AcceleratorState(
  File "/home/ubuntu/anaconda3/envs/pytorch39/lib/python3.9/site-packages/accelerate/state.py", line 162, in __init__
    torch.distributed.init_process_group(backend="nccl", **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch39/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 602, in init_process_group
    default_pg = _new_process_group_helper(
  File "/home/ubuntu/anaconda3/envs/pytorch39/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 727, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL " "built in")
RuntimeError: Distributed package doesn't have NCCL built in
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 47775) of binary: /home/ubuntu/anaconda3/envs/pytorch39/bin/python3.9

```

Maybe this isn't a 'bug', but I have stock here for one day and I haven't find useful infomation on Google or Github. I'm a newbie， if this issue bother you, I will delete this issue, please let me know.

### Expected behavior

```Shell
Just want this code run successful.
```

**Comment by pengjunfeng11** [comment]
> 
I will try this command line , and thank you.

My operating system is ubuntu 18.04 , pure linux.

I can't figure out why the NCCL can't be found, and I has run the hugging face before , cuda can be used .

**Comment by pengjunfeng11** [comment]
> You need to install the cuda enabled pytorch version (I think), that's what this part means here as part of your `accelerate env`: `- PyTorch version (GPU?): 1.12.1 (False)`
> 
> (I _think_).
> 
> You can try:
> 
> ```shell
> pip install light-the-torch
> ltt install torch torchvision -U
> ```
> 
> to grab the right wheels
> 
> Can you tell me a bit more about your operating system? E.g. is this running on WSL? Windows? Or pure linux?

I will try this command line , and thank you.

My operating system is ubuntu 18.04 , pure linux.

I can't figure out why the NCCL can't be found, and I has run the hugging face before , cuda can be used .

**Comment by pengjunfeng11** [comment]
> You need to install the cuda enabled pytorch version (I think), that's what this part means here as part of your `accelerate env`: `- PyTorch version (GPU?): 1.12.1 (False)`
> 
> (I _think_).
> 
> You can try:
> 
> ```shell
> pip install light-the-torch
> ltt install torch torchvision -U
> ```
> 
> to grab the right wheels
> 
> Can you tell me a bit more about your operating system? E.g. is this running on WSL? Windows? Or pure linux?

Thank you !! Problem has been solved.
