### ISSUE TITLE
[feature request] notify the user when system wide config is used

### ISSUE THREAD

**Issue by stas00** [huggingface/accelerate#1133]
I just wasted a lot of time trying to figure out why accelerate ignores my instructions just to discover that it uses   `~/.cache/huggingface/accelerate/default_config.yaml` that was generated many moons ago and I had no idea it was even there until Zach told me to look for it.

This is evil :(

This feature request is to notify the user when the global config is used, so that silent action at a distance isn't performed w/o user's knowledge.

Thank you.

**Comment by stas00** [comment]
as I pasted on slack it doesn't work.

```
$ rm ~/.cache/huggingface/accelerate/default_config.yml

$ accelerate launch torch-distributed-gpu-test.py
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_processes` was set to a value of `1`
        `--num_machines` was set to a value of `1`
        `--mixed_precision` was set to a value of `'no'`
        `--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
Traceback (most recent call last):
  File "torch-distributed-gpu-test.py", line 61, in <module>
    local_rank = int(os.environ["LOCAL_RANK"])
  File "/home/stas/anaconda3/envs/py38-pt113/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'LOCAL_RANK'
Traceback (most recent call last):
  File "/home/stas/anaconda3/envs/py38-pt113/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/mnt/nvme0/code/huggingface/accelerate-master/src/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/mnt/nvme0/code/huggingface/accelerate-master/src/accelerate/commands/launch.py", line 878, in launch_command
    simple_launcher(args)
  File "/mnt/nvme0/code/huggingface/accelerate-master/src/accelerate/commands/launch.py", line 557, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/stas/anaconda3/envs/py38-pt113/bin/python', 'torch-distributed-gpu-test.py']' returned non-zero exit status 1.
```

**Comment by sgugger** [comment]
Let's avoid polluting the logs of every user for the basic use case recommended everywhere in the doc. If you do `accelerate env` you see your default config. We don't log that there is a GPU or the version of Accelerate used at each run either.
