### ISSUE TITLE
Arrow key input is environment dependent when `accelerate config`

### ISSUE THREAD

**Issue by p1atdev** [huggingface/accelerate#1142]
### System Info

```Shell
- `Accelerate` version: 0.15.0
- Platform: Windows-10-10.0.22621-SP0
- Python version: 3.10.6
- Numpy version: 1.24.2
- PyTorch version (GPU?): 1.12.1+cu116 (True)
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: NO
        - mixed_precision: bf16
        - use_cpu: False
        - dynamo_backend: NO
        - num_processes: 1
        - machine_rank: 0
        - num_machines: 1
        - gpu_ids: all
        - main_process_ip: None
        - main_process_port: None
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - deepspeed_config: {}
        - fsdp_config: {}
        - megatron_lm_config: {}
        - downcast_bf16: no
        - tpu_name: None
        - tpu_zone: None
        - command_file: None
        - commands: None
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

When I ran accelerate config in a windows Japanese environment, I got this error when I typed the arrow keys.

```
❯ accelerate config
-------------------------------------------------------------------------------------------------------------In which compute environment are you running?
This machine
-------------------------------------------------------------------------------------------------------------Which type of machine are you using?
Please select a choice using the arrow or number keys, and selecting with enter
Traceback (most recent call last):
  File "C:\Users\p1atdev\Anaconda3\envs\kohya\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\p1atdev\Anaconda3\envs\kohya\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\p1atdev\Anaconda3\envs\kohya\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\p1atdev\Anaconda3\envs\kohya\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\Users\p1atdev\Anaconda3\envs\kohya\lib\site-packages\accelerate\commands\config\config.py", line 67, in config_command
    config = get_user_input()
  File "C:\Users\p1atdev\Anaconda3\envs\kohya\lib\site-packages\accelerate\commands\config\config.py", line 40, in get_user_input
    config = get_cluster_input()
  File "C:\Users\p1atdev\Anaconda3\envs\kohya\lib\site-packages\accelerate\commands\config\cluster.py", line 45, in get_cluster_input
    distributed_type = _ask_options(
  File "C:\Users\p1atdev\Anaconda3\envs\kohya\lib\site-packages\accelerate\commands\config\config_utils.py", line 58, in _ask_options
    result = menu.run(default_choice=default)
  File "C:\Users\p1atdev\Anaconda3\envs\kohya\lib\site-packages\accelerate\commands\menu\selection_menu.py", line 118, in run
    choice = self.handle_input()
  File "C:\Users\p1atdev\Anaconda3\envs\kohya\lib\site-packages\accelerate\commands\menu\input.py", line 73, in handle_input
    char = get_character()
  File "C:\Users\p1atdev\Anaconda3\envs\kohya\lib\site-packages\accelerate\commands\menu\keymap.py", line 114, in get_character
    char = get_raw_chars()
  File "C:\Users\p1atdev\Anaconda3\envs\kohya\lib\site-packages\accelerate\commands\menu\keymap.py", line 77, in get_raw_chars
    if ch.encode(encoding) in (b"\x00", b"\xe0"):
UnicodeEncodeError: 'mbcs' codec can't encode characters in position 0--1: invalid character
```

Perhaps this is happening because the Windows command prompt does not support Unicode strings?

I changed the part where the error occurred as follows and the problem no longer occurs, but I am not sure if this is the correct solution.

https://github.com/p1atdev/accelerate/blob/ad9cf788b1aa6e80ef3e51acbef34b258ddcaed3/src/accelerate/commands/menu/keymap.py#L64-L97

```py
    if os.name == "nt":
        import msvcrt

        encoding = "mbcs"
        # Flush the keyboard buffer
        while msvcrt.kbhit():
            msvcrt.getch()
        if len(WIN_CH_BUFFER) == 0:
            # Read the keystroke
            ch = msvcrt.getch()

            # If it is a prefix char, get second part
            if ch in (b"\x00", b"\xe0"):
                ch2 = ch + msvcrt.getch()
                # Translate actual Win chars to bullet char types
                try:
                    chx = chr(WIN_KEYMAP[ch2])
                    WIN_CH_BUFFER.append(chr(KEYMAP["mod_int"]))
                    WIN_CH_BUFFER.append(chx)
                    if ord(chx) in (
                        KEYMAP["insert"] - 1 << 9,
                        KEYMAP["delete"] - 1 << 9,
                        KEYMAP["pg_up"] - 1 << 9,
                        KEYMAP["pg_down"] - 1 << 9,
                    ):
                        WIN_CH_BUFFER.append(chr(126))
                    ch = chr(KEYMAP["esc"])
                except KeyError:
                    ch = ch2[1]
            else:
                ch = ch.decode(encoding)
        else:
            ch = WIN_CH_BUFFER.pop(0)
```

Using getch() instead of getwch() seems to correctly accept input from non-English keyboards.

If this fix seems okay, I will create a PR

### Expected behavior

```Shell
Arrow key input from any language keyboard should be handled correctly when `accelerate config`.
```

**Comment by muellerzr** [comment]
Hi @p1atdev, this solution looks great to me! Feel free to open an PR for it :)
