### ISSUE TITLE
acclerate test --config_file myconifgfile get errors

### ISSUE THREAD

**Issue by leileilin** [huggingface/accelerate#117]
when i run this command

```
accelerate config --config_file myconfigfile
```

I choose this machine, multi-gpu, one-node, 6 process, FP16, then i run this command

```
accelerate test --config_file myconfigfile
```

i get the following errors.

stdout: All rng are properly synched.
stdout: 
stdout: **DataLoader integration test**
stderr: Traceback (most recent call last):
stderr:   File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/test_utils/test_script.py", line 225, in <module>
stderr: Traceback (most recent call last):
stderr:   File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/test_utils/test_script.py", line 225, in <module>
stderr: Traceback (most recent call last):
stderr:   File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/test_utils/test_script.py", line 225, in <module>
stderr: Traceback (most recent call last):
stderr:   File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/test_utils/test_script.py", line 225, in <module>
stderr: Traceback (most recent call last):
stderr:     main()  File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/test_utils/test_script.py", line 225, in <module>
stderr: 
stderr:   File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/test_utils/test_script.py", line 217, in main
stderr:     main()
stderr: dl_preparation_check()
stderr:   File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/test_utils/test_script.py", line 217, in main
stderr:   File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/test_utils/test_script.py", line 71, in dl_preparation_check
stderr:     split_batches=True,
stderr:   File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/data_loader.py", line 362, in prepare_data_loader
stderr:     dl_preparation_check()
stderr:   File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/test_utils/test_script.py", line 71, in dl_preparation_check
stderr: Traceback (most recent call last):
stderr:   File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/test_utils/test_script.py", line 225, in <module>
stderr:     split_batches=True,
stderr:   File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/data_loader.py", line 362, in prepare_data_loader
stderr:     f"Using `split_batches=True` requires that the batch size ({dataloader.batch_size}) "
stderr: ValueError: Using `split_batches=True` requires that the batch size (8) to be a round multiple of the number of processes (6).
stderr:         main()f"Using `split_batches=True` requires that the batch size ({dataloader.batch_size}) "
stderr: 
stderr:   File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/test_utils/test_script.py", line 217, in main
stderr: ValueError    : main()Using `split_batches=True` requires that the batch size (8) to be a round multiple of the number of processes (6).
stderr: 
stderr:   File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/test_utils/test_script.py", line 217, in main
stderr:     dl_preparation_check()
stderr:   File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/test_utils/test_script.py", line 71, in dl_preparation_check
stderr:     dl_preparation_check()
stderr:   File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/test_utils/test_script.py", line 71, in dl_preparation_check
stderr:         split_batches=True,main()
stderr:   File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/data_loader.py", line 362, in prepare_data_loader
stderr: 
stderr:   File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/test_utils/test_script.py", line 217, in main
stderr:     split_batches=True,
stderr:   File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/data_loader.py", line 362, in prepare_data_loader
stderr:     dl_preparation_check()
stderr:   File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/test_utils/test_script.py", line 71, in dl_preparation_check
stderr:     f"Using `split_batches=True` requires that the batch size ({dataloader.batch_size}) "
stderr:         f"Using `split_batches=True` requires that the batch size ({dataloader.batch_size}) "main()ValueError
stderr: 
stderr: : Using `split_batches=True` requires that the batch size (8) to be a round multiple of the number of processes (6).
stderr:   File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/test_utils/test_script.py", line 217, in main
stderr:     split_batches=True,
stderr:   File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/data_loader.py", line 362, in prepare_data_loader
stderr: ValueError: Using `split_batches=True` requires that the batch size (8) to be a round multiple of the number of processes (6).
stderr:     dl_preparation_check()
stderr:   File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/test_utils/test_script.py", line 71, in dl_preparation_check
stderr:     f"Using `split_batches=True` requires that the batch size ({dataloader.batch_size}) "
stderr:     split_batches=True,
stderr:   File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/data_loader.py", line 362, in prepare_data_loader
stderr: ValueError: Using `split_batches=True` requires that the batch size (8) to be a round multiple of the number of processes (6).
stderr:     f"Using `split_batches=True` requires that the batch size ({dataloader.batch_size}) "
stderr: ValueError: Using `split_batches=True` requires that the batch size (8) to be a round multiple of the number of processes (6).
stderr: Traceback (most recent call last):
stderr:   File "/home/ll/anaconda3/envs/generator/lib/python3.7/runpy.py", line 193, in _run_module_as_main
stderr:     "__main__", mod_spec)
stderr:   File "/home/ll/anaconda3/envs/generator/lib/python3.7/runpy.py", line 85, in _run_code
stderr:     exec(code, run_globals)
stderr:   File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/torch/distributed/launch.py", line 261, in <module>
stderr:     main()
stderr:   File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/torch/distributed/launch.py", line 257, in main
stderr:     cmd=cmd)
stderr: subprocess.CalledProcessError: Command '['/home/ll/anaconda3/envs/generator/bin/python', '-u', '/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/test_utils/test_script.py']' returned non-zero exit status 1.
stdout: *****************************************
stdout: Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
stdout: *****************************************
stderr: Traceback (most recent call last):
stderr:   File "/home/ll/anaconda3/envs/generator/bin/accelerate-launch", line 8, in <module>
stderr:     sys.exit(main())
stderr:   File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/commands/launch.py", line 319, in main
stderr:     launch_command(args)
stderr:   File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/commands/launch.py", line 307, in launch_command
stderr:     multi_gpu_launcher(args)
stderr:   File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/commands/launch.py", line 151, in multi_gpu_launcher
stderr:     raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
stderr: subprocess.CalledProcessError: Command '['/home/ll/anaconda3/envs/generator/bin/python', '-m', 'torch.distributed.launch', '--use_env', '--nproc_per_node', '6', '/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/test_utils/test_script.py']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/home/ll/anaconda3/envs/generator/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/commands/accelerate_cli.py", line 41, in main
    args.func(args)
  File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/commands/test.py", line 52, in test_command
    result = execute_subprocess_async(cmd, env=os.environ.copy())
  File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/test_utils/testing.py", line 135, in execute_subprocess_async
    f"'{cmd_str}' failed with returncode {result.returncode}\n\n"
RuntimeError: 'accelerate-launch --config_file=config.yml /home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/test_utils/test_script.py' failed with returncode 1

The combined stderr from workers follows:
Traceback (most recent call last):
  File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/test_utils/test_script.py", line 225, in <module>
Traceback (most recent call last):
  File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/test_utils/test_script.py", line 225, in <module>
Traceback (most recent call last):
  File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/test_utils/test_script.py", line 225, in <module>
Traceback (most recent call last):
  File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/test_utils/test_script.py", line 225, in <module>
Traceback (most recent call last):
    main()  File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/test_utils/test_script.py", line 225, in <module>

  File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/test_utils/test_script.py", line 217, in main
    main()
dl_preparation_check()
  File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/test_utils/test_script.py", line 217, in main
  File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/test_utils/test_script.py", line 71, in dl_preparation_check
    split_batches=True,
  File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/data_loader.py", line 362, in prepare_data_loader
    dl_preparation_check()
  File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/test_utils/test_script.py", line 71, in dl_preparation_check
Traceback (most recent call last):
  File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/test_utils/test_script.py", line 225, in <module>
    split_batches=True,
  File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/data_loader.py", line 362, in prepare_data_loader
    f"Using `split_batches=True` requires that the batch size ({dataloader.batch_size}) "
ValueError: Using `split_batches=True` requires that the batch size (8) to be a round multiple of the number of processes (6).
        main()f"Using `split_batches=True` requires that the batch size ({dataloader.batch_size}) "

  File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/test_utils/test_script.py", line 217, in main
ValueError    : main()Using `split_batches=True` requires that the batch size (8) to be a round multiple of the number of processes (6).

  File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/test_utils/test_script.py", line 217, in main
    dl_preparation_check()
  File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/test_utils/test_script.py", line 71, in dl_preparation_check
    dl_preparation_check()
  File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/test_utils/test_script.py", line 71, in dl_preparation_check
        split_batches=True,main()
  File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/data_loader.py", line 362, in prepare_data_loader

  File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/test_utils/test_script.py", line 217, in main
    split_batches=True,
  File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/data_loader.py", line 362, in prepare_data_loader
    dl_preparation_check()
  File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/test_utils/test_script.py", line 71, in dl_preparation_check
    f"Using `split_batches=True` requires that the batch size ({dataloader.batch_size}) "
        f"Using `split_batches=True` requires that the batch size ({dataloader.batch_size}) "main()ValueError

: Using `split_batches=True` requires that the batch size (8) to be a round multiple of the number of processes (6).
  File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/test_utils/test_script.py", line 217, in main
    split_batches=True,
  File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/data_loader.py", line 362, in prepare_data_loader
ValueError: Using `split_batches=True` requires that the batch size (8) to be a round multiple of the number of processes (6).
    dl_preparation_check()
  File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/test_utils/test_script.py", line 71, in dl_preparation_check
    f"Using `split_batches=True` requires that the batch size ({dataloader.batch_size}) "
    split_batches=True,
  File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/data_loader.py", line 362, in prepare_data_loader
ValueError: Using `split_batches=True` requires that the batch size (8) to be a round multiple of the number of processes (6).
    f"Using `split_batches=True` requires that the batch size ({dataloader.batch_size}) "
ValueError: Using `split_batches=True` requires that the batch size (8) to be a round multiple of the number of processes (6).
Traceback (most recent call last):
  File "/home/ll/anaconda3/envs/generator/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ll/anaconda3/envs/generator/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/ll/anaconda3/envs/generator/bin/python', '-u', '/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/test_utils/test_script.py']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/home/ll/anaconda3/envs/generator/bin/accelerate-launch", line 8, in <module>
    sys.exit(main())
  File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/commands/launch.py", line 319, in main
    launch_command(args)
  File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/commands/launch.py", line 307, in launch_command
    multi_gpu_launcher(args)
  File "/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/commands/launch.py", line 151, in multi_gpu_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/ll/anaconda3/envs/generator/bin/python', '-m', 'torch.distributed.launch', '--use_env', '--nproc_per_node', '6', '/home/ll/anaconda3/envs/generator/lib/python3.7/site-packages/accelerate/test_utils/test_script.py']' returned non-zero exit status 1.

it is strage. Because when i use 2 processes or 8 processes, i dont get the similar errors. Any one can help me?

Thank you.

**Comment by leileilin** [comment]
I have figured out that error.

**Comment by Opdoop** [comment]
@leileilin Hi, I'm facing the same problem. How to solve this bug?

**Comment by leileilin** [comment]
> @leileilin Hi, I'm facing the same problem. How to solve this bug?

Let your GPU devices divide your number of processes. such as you have 6 gpus, you can set 1 2 3 6 processes, not 4 5 proccesses.
Hope that can help you .

**Comment by Opdoop** [comment]
That works! Thank you!
