### ISSUE TITLE
torch.distributed.elastic.multiprocessing.errors.ChildFailedError when using linux screen

### ISSUE THREAD

**Issue by ocss884** [huggingface/accelerate#1213]
Hey! I'm new to this library. After I setup the config and successfully run the `accelerate test`. 
When I tried run `accelerate launch {script_name.py}` in linux screen, the following error raise:

```python
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -11) local_rank: 0 (pid: 1631595) of binary: /hpc/group/{}/anaconda3/bin/python
Traceback (most recent call last):
  File "/hpc/home/{}/.local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/hpc/home/{}/.local/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/hpc/home/{}/.local/lib/python3.8/site-packages/accelerate/commands/launch.py", line 906, in launch_command
    multi_gpu_launcher(args)
  File "/hpc/home/{}/.local/lib/python3.8/site-packages/accelerate/commands/launch.py", line 599, in multi_gpu_launcher
    distrib_run.run(args)
  File "/hpc/home/{}/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/hpc/home/{}/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/hpc/home/j{}/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
=========================================================
train.py FAILED
---------------------------------------------------------
Failures:
[1]:
  time      : 2023-03-18_20:44:21
  host      : {hide}
  rank      : 1 (local_rank: 1)
  exitcode  : -11 (pid: 1631600)
  error_file: <N/A>
  traceback : Signal 11 (SIGSEGV) received by PID 1631600
[2]:
  time      : 2023-03-18_20:44:21
  host      : {hide}
  rank      : 2 (local_rank: 2)
  exitcode  : -11 (pid: 1631601)
  error_file: <N/A>
  traceback : Signal 11 (SIGSEGV) received by PID 1631601
[3]:
  time      : 2023-03-18_20:44:21
  host      : {hide}
  rank      : 3 (local_rank: 3)
  exitcode  : -11 (pid: 1631602)
  error_file: <N/A>
  traceback : Signal 11 (SIGSEGV) received by PID 1631602
---------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-03-18_20:44:21
  host      : {hide}
  rank      : 0 (local_rank: 0)
  exitcode  : -11 (pid: 1631595)
  error_file: <N/A>
  traceback : Signal 11 (SIGSEGV) received by PID 1631595
=========================================================
```

However, the same command runs well when I run outside the screen. Is there any conflict with screen?

**Comment by ocss884** [comment]
Ok I find where is the problem. When starting a screen session, it seems deepspeed cannot specify my working virtual environment well although `which python` gives the correct directory. Anyone who meets this error in the future can check your deepspeed general environment setting with `ds_report`. To solve it just source your venv again

**Comment by jiangyuhangcn** [comment]
> Ok I find where is the problem. When starting a screen session, it seems deepspeed cannot specify my working virtual environment well although `which python` gives the correct directory. Anyone who meets this error in the future can check your deepspeed general environment setting with `ds_report`. To solve it just source your venv again

How to fix this error, please? What are the specific steps? thanks a lot!!

**Comment by ocss884** [comment]
> How to fix this error, please? What are the specific steps? thanks a lot!!

Try to deactivate and source your virtual environment again in the screen session before you start your program
