### ISSUE TITLE
Accelerate crashes unexpectedly with 30b+ Llama models

### ISSUE THREAD

**Issue by rajammanabrolu** [huggingface/accelerate#1214]
### System Info

```Shell
I am running on 5 x 8 GPU A100 80GB servers (40 GPUs total), 1TB System RAM each server, Infiniband interconnect.

- `Accelerate` version: 0.18.0.dev0
- Platform: Linux-5.15.0-60-generic-x86_64-with-glibc2.31
- Python version: 3.9.5
- Numpy version: 1.24.2
- PyTorch version (GPU?): 1.13.1+cu116 (True)
- `Accelerate` config passed:
	- compute_environment: LOCAL_MACHINE
	- distributed_type: FSDP
	- mixed_precision: bf16
	- use_cpu: True
	- num_processes: 40
        - main_process_ip: <private>
        - main_process_port: 29401 
	- machine_rank: 0
	- num_machines: 5
	- rdzv_backend: static
	- same_network: True
	- main_training_function: main
	- deepspeed_config: {}
	- fsdp_config: {'fsdp_auto_wrap_policy': 'TRANSFORMER_BASED_WRAP', 'fsdp_backward_prefetch_policy': 'BACKWARD_PRE', 'fsdp_offload_params': True, 'fsdp_sharding_strategy': 1, 'fsdp_state_dict_type': 'FULL_STATE_DICT', 'fsdp_transformer_layer_cls_to_wrap': 'LlamaDecoderLayer'}
	- megatron_lm_config: {}
	- downcast_bf16: no
	- tpu_use_cluster: False
	- tpu_use_sudo: False
	- tpu_env: []
	- dynamo_config: {}
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

Steps to reproduce, use the official [`run_clm.py`](https://github.com/huggingface/transformers/blob/main/examples/pytorch/language-modeling/run_clm.py) example:

Convert Llama weights/tokenizer with [convert](https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/convert_llama_weights_to_hf.py) script. Then run below.

`accelerate launch run_clm.py --model_name_or_path "llama-30b" --tokenizer_name "llama-tokenizer" --per_device_train_batch_size 1 --output_dir "../output" --overwrite_output_dir --fp16 --do_train --max_train_samples 128 --num_train_epochs 1 --dataset_name "wikitext" --dataset_config "wikitext-103-v1" --fsdp "full_shard offload auto_wrap" --fsdp_transformer_layer_cls_to_wrap "LlamaDecoderLayer" --optim "adamw_torch`

This works for 13B and below models but for Llama 30b and 65b I get below. The resources I have should be enough to load 30b loading at least with offloading etc right?

I've also tried setting the `low_cpu_mem_usage=True` option when calling `AutoModelForCausalLM.from_pretrained` with a --do-eval instead of --do-train flag on that same command above and that also gives the same error. (based on [this](https://huggingface.co/docs/accelerate/usage_guides/big_modeling))

```
Loading checkpoint shards: 100%|██████████| 61/61 [05:45<00:00,  5.66s/it]
 WARNING  Sending process 14 closing signal SIGTERM         api.py:699
 WARNING  Sending process 15 closing signal SIGTERM         api.py:699
 WARNING  Sending process 16 closing signal SIGTERM         api.py:699
 WARNING  Sending process 17 closing signal SIGTERM         api.py:699
 WARNING  Sending process 20 closing signal SIGTERM         api.py:699
 WARNING  Sending process 26 closing signal SIGTERM         api.py:699
 WARNING  Sending process 29 closing signal SIGTERM         api.py:699
 ERROR    failed (exitcode: -9) local_rank: 5 (pid: 22) of  api.py:673
 binary: /opt/conda/bin/python 
056444Z ╭───────────────────── Traceback (most recent call last) ──────────────────────╮
058181Z │                                                                              │
061458Z │ /opt/conda/bin/accelerate:8 in <module>                                      │
063432Z │                                                                              │
065546Z │   5 from accelerate.commands.accelerate_cli import main                      │
067260Z │   6 if __name__ == '__main__':                                               │
069203Z │   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])     │
086718Z │ ❱ 8 │   sys.exit(main())                                                     │
088482Z │   9                                                                          │
090075Z │ /opt/conda/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py │
092069Z │ :45 in main                                                                  │
093722Z │                                                                              │
095326Z │   42 │   │   exit(1)                                                         │
096929Z │   43 │                                                                       │
098552Z │   44 │   # Run                                                               │
100115Z │ ❱ 45 │   args.func(args)                                                     │
101728Z │   46                                                                         │
103322Z │   47                                                                         │
104905Z │   48 if __name__ == "__main__":                                              │
106648Z │                                                                              │
108262Z │ /opt/conda/lib/python3.8/site-packages/accelerate/commands/launch.py:906 in  │
109845Z │ launch_command                                                               │
111969Z │                                                                              │
113642Z │   903 │   │   args.deepspeed_fields_from_accelerate_config = ",".join(args.d │
115326Z │   904 │   │   deepspeed_launcher(args)                                       │
116919Z │   905 │   elif args.use_fsdp and not args.cpu:                               │
118532Z │ ❱ 906 │   │   multi_gpu_launcher(args)                                       │
120125Z │   907 │   elif args.use_megatron_lm and not args.cpu:                        │
121688Z │   908 │   │   multi_gpu_launcher(args)                                       │
123252Z │   909 │   elif args.multi_gpu and not args.cpu:                              │
124805Z │                                                                              │
126368Z │ /opt/conda/lib/python3.8/site-packages/accelerate/commands/launch.py:603 in  │
127911Z │ multi_gpu_launcher                                                           │
131909Z │                                                                              │
133652Z │   600 │   )                                                                  │
135246Z │   601 │   with patch_environment(**current_env):                             │
136829Z │   602 │   │   try:                                                           │
138392Z │ ❱ 603 │   │   │   distrib_run.run(args)                                      │
139975Z │   604 │   │   except Exception:                                              │
141558Z │   605 │   │   │   if is_rich_available() and debug:                          │
143242Z │   606 │   │   │   │   console = get_console()                                │
144825Z │                                                                              │
146528Z │ /opt/conda/lib/python3.8/site-packages/torch/distributed/run.py:753 in run   │
148091Z │                                                                              │
149654Z │   750 │   │   )                                                              │
151258Z │   751 │                                                                      │
153061Z │   752 │   config, cmd, cmd_args = config_from_args(args)                     │
154684Z │ ❱ 753 │   elastic_launch(                                                    │
156298Z │   754 │   │   config=config,                                                 │
157891Z │   755 │   │   entrypoint=cmd,                                                │
159524Z │   756 │   )(*cmd_args)                                                       │
161117Z │                                                                              │
163021Z │ /opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py:132 │
164574Z │ in __call__                                                                  │
166137Z │                                                                              │
167721Z │   129 │   │   self._entrypoint = entrypoint                                  │
169424Z │   130 │                                                                      │
171007Z │   131 │   def __call__(self, *args):                                         │
172600Z │ ❱ 132 │   │   return launch_agent(self._config, self._entrypoint, list(args) │
179584Z │   133                                                                        │
181218Z │   134                                                                        │
182781Z │   135 def _get_entrypoint_name(                                              │
184354Z │                                                                              │
185987Z │ /opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py:246 │
187570Z │ in launch_agent                                                              │
189173Z │                                                                              │
190877Z │   243 │   │   │   # if the error files for the failed children exist         │
192460Z │   244 │   │   │   # @record will copy the first error (root cause)           │
194063Z │   245 │   │   │   # to the error file of the launcher process.               │
195837Z │ ❱ 246 │   │   │   raise ChildFailedError(                                    │
197580Z │   247 │   │   │   │   name=entrypoint_name,                                  │
199174Z │   248 │   │   │   │   failures=result.failures,                              │
200747Z │   249 │   │   │   )                                                          │
202370Z ╰──────────────────────────────────────────────────────────────────────────────╯
```

### Expected behavior

```Shell
Model checkpoint loads and trains CausalLM
```

**Comment by sgugger** [comment]
What you are telling the computer to do by launching the code this way is to load the model on each GPU, which you don't have the memory for (30B model will take 120GB in full precision). You need to use DeepSpeed ZeRo--3 to fine-tune the model, not sure how to enable the same thing with FSDP but @pacman100 may know.

**Comment by rajammanabrolu** [comment]
Thanks for the clarification. I thought this was the case. It would be great to know what's the recommended way of training such (larger) models using Accelerate with FSDP and not just Deepspeed.

**Comment by pacman100** [comment]
Hello, the FSDP command seems correct. I currently don't yet have access to LLAMA weights, have applied for it, can only check once I get access to it. Also as per this comment https://github.com/huggingface/transformers/issues/21509#issuecomment-1422841064, CPU offload with mixed precision seems to hang indefinitely with FSDP. Could you try to use FSDp with CPU offload without mixed precision and see if that solves the issue?

**Comment by pacman100** [comment]
Also, for smaller models till 13B, were you able to successfully use FSDP with CPU offload using mixed precision?

**Comment by rajammanabrolu** [comment]
@pacman100 
I get the same error as my original post without mixed precision for 30b but am able to run it with lower models like 13b (without mixed precision, with mixed precision 13b hangs like you said in that comment)

**Comment by pacman100** [comment]
Hello @rajammanabrolu, you say accelerate creashes but the below command `accelerate launch run_clm.py --model_name_or_path "llama-30b" --tokenizer_name "llama-tokenizer" --per_device_train_batch_size 1 --output_dir "../output" --overwrite_output_dir --fp16 --do_train --max_train_samples 128 --num_train_epochs 1 --dataset_name "wikitext" --dataset_config "wikitext-103-v1" --fsdp "full_shard offload auto_wrap" --fsdp_transformer_layer_cls_to_wrap "LlamaDecoderLayer" --optim "adamw_torch` is for using Trainer. I'm a bit confused now and need clarity on your side for a minimal example to run.

**Comment by rajammanabrolu** [comment]
It's just the official script
https://github.com/huggingface/transformers/blob/main/examples/pytorch/language-modeling/run_clm.py
with Llama and the command as mentioned in my initial post, it gives the
error I had there. I thought Accelerate was supported with Trainer?

**Comment by pacman100** [comment]
So, you are using accelerate launch for launching distributed setup but using Trainer and trainer args for FSDP, is that understanding correct? Currently, I don't have access to multinodes with such high-end GPUs to test this out. And the fact that there is no error makes debugging very difficult. Are you using 3 nodes for 13B model as well or was that single node? If that was single node, then the issue for >=30B models might be the connection across nodes.

**Comment by rajammanabrolu** [comment]
Yes that understanding is correct. I'm using the same number of nodes (3+)
for 13b also and it works with torchrun too. I was thinking it has
something to do with how large models are loaded and want to make sure I'm
not trying to load a model per process based on that code? Unfortunately
that error message is all I have so I can't tell if this is what it is
doing.

**Comment by rajammanabrolu** [comment]
Also, to be clear, the error message is posted in the first message in this
error issue, it's an out of memory error.

**Comment by pacman100** [comment]
I don't think `ERROR    failed (exitcode: -9) local_rank: 5 (pid: 22) of  api.py:673` would be OOM error. Shouldn't it be something like "RuntimeError: CUDA out of memory. Tried to allocate **8.60 GiB** (GPU 0; 23.70 GiB total capacity; 3.77 GiB already allocated; **8.60 GiB** free; 12.92 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF"

**Comment by pacman100** [comment]
Actually, it might be the case that RAM might be running out. Let's take the Llama-30B model as an example. Before the `accelerate.prepare` call, when loading the pretrained model via `model = AutoModelForCausalLM.from-pretrained(model_name_or_path)`, it first loads the model on the RAM. Now, in a node with 8 GPUs, there would be 8 processes loading the same checkpoint on RAM. By default, FP32 ckpt is loaded, for 32B model it would be around 120GB (approx 4GB per 1B params when using FP32). So, the total RAM by 8 processes would amount to 120*8 = 960GB which might be causing RAM (1TB total per node, available might be a bit lower because of other processes running on the server) to blow up and when it exceeds the limit in my experience the process gets killed (-9) and the server becomes unresponsive.

**Comment by rajammanabrolu** [comment]
That makes sense though I'm still not sure how to fix that, should I be
using less processes per node? (But I thought it was one process per GPU
standard, how would I use all the GPUs on a node then?)

**Comment by pacman100** [comment]
You can try DeepSpeed which avoid this by using `zero_init`. Alternatively, one would need to only load the model on rank 0 and then use `sync_module_states=True` in FSDP object init call. I'll look into how to enable this with Accelerate but can take some time.

**Comment by jacklanda** [comment]
Does this issue figure out?

**Comment by jacklanda** [comment]
How to run `torchrun` with accelerate's `device_map = auto` arguments to implemente pipeline parallelism in a single node and do it for each nodes with distributed training.

**Comment by RonanKMcGovern** [comment]
Howdy @pacman100 , I'm still seeing this issue with 30B+ Llama models (e.g. codellama 34B). llama 2 7b works fine. Here is a demo script:
```
# Script from: https://github.com/huggingface/trl/issues/1303
# Run this with DDP with "accelerate launch test_sft.py"
from datasets import load_dataset
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig, AutoTokenizer
from peft import LoraConfig
from trl import SFTTrainer
from transformers import TrainingArguments
from accelerate import PartialState

# Load the dataset
dataset_name = "timdettmers/openassistant-guanaco"
dataset = load_dataset(dataset_name, split="train")

# Load the model + tokenizer
# model_name = "TinyLlama/TinyLlama-1.1B-intermediate-step-1431k-3T"
# model_name = "meta-llama/Llama-2-7b-hf"
model_name = "codellama/CodeLlama-34b-hf"
tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    trust_remote_code=True,
    cache_dir='',
    use_cache = False,
)

# PEFT config
lora_alpha = 8
lora_dropout = 0.1
lora_r = 32
peft_config = LoraConfig(
    lora_alpha=lora_alpha,
    lora_dropout=lora_dropout,
    r=lora_r,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules=["k_proj", "q_proj", "v_proj", "up_proj", "down_proj", "gate_proj"],
    modules_to_save=["embed_tokens", "input_layernorm", "post_attention_layernorm", "norm"],
)

# Args 
max_seq_length = 512
output_dir = "./results"
per_device_train_batch_size = 8
gradient_accumulation_steps = 2
optim = "adamw_torch"
save_steps = 10
logging_steps = 1
learning_rate = 2e-4
max_grad_norm = 0.3
max_steps = 1 # Approx the size of guanaco at bs 8, ga 2, 2 GPUs. 
warmup_ratio = 0.1
lr_scheduler_type = "cosine"
training_arguments = TrainingArguments(
    output_dir=output_dir,
    per_device_train_batch_size=per_device_train_batch_size,
    gradient_accumulation_steps=gradient_accumulation_steps,
    optim=optim,
    save_steps=save_steps,
    logging_steps=logging_steps,
    learning_rate=learning_rate,
    fp16=True,
    max_grad_norm=max_grad_norm,
    max_steps=max_steps,
    warmup_ratio=warmup_ratio,
    group_by_length=True,
    lr_scheduler_type=lr_scheduler_type,
    gradient_checkpointing=True,
    gradient_checkpointing_kwargs = {"use_reentrant": False}, #must be false for DDP
    report_to="wandb",
)

# Trainer 
trainer = SFTTrainer(
    model=model,
    train_dataset=dataset,
    peft_config=peft_config,
    dataset_text_field="text",
    max_seq_length=max_seq_length,
    tokenizer=tokenizer,
    args=training_arguments,
)

# handle PEFT+FSDP case
trainer.model.print_trainable_parameters()
if getattr(trainer.accelerator.state, "fsdp_plugin", None):
    from peft.utils.other import fsdp_auto_wrap_policy

    fsdp_plugin = trainer.accelerator.state.fsdp_plugin
    fsdp_plugin.auto_wrap_policy = fsdp_auto_wrap_policy(trainer.model)

# Train :)
trainer.train()
```

and here is the error:
```
special_tokens_map.json: 100%|██████████████| 411/411 [00:00<00:00, 1.01MB/s]
Loading checkpoint shards:  29%|████▎          | 2/7 [02:24<05:58, 71.62s/it][2024-04-08 20:36:50,275] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 4040 closing signal SIGTERM
[2024-04-08 20:36:50,276] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 4041 closing signal SIGTERM
[2024-04-08 20:36:50,276] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 4042 closing signal SIGTERM
[2024-04-08 20:36:54,495] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: -9) local_rank: 0 (pid: 4039) of binary: /workspace/ADVANCED-fine-tuning/trelisEnv/bin/python
Traceback (most recent call last):
  File "/workspace/ADVANCED-fine-tuning/trelisEnv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/workspace/ADVANCED-fine-tuning/trelisEnv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 46, in main
    args.func(args)
  File "/workspace/ADVANCED-fine-tuning/trelisEnv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1044, in launch_command
    multi_gpu_launcher(args)
  File "/workspace/ADVANCED-fine-tuning/trelisEnv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 702, in multi_gpu_launcher
    distrib_run.run(args)
  File "/workspace/ADVANCED-fine-tuning/trelisEnv/lib/python3.10/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/workspace/ADVANCED-fine-tuning/trelisEnv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/workspace/ADVANCED-fine-tuning/trelisEnv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
```
and here is how I'm doing `accelerate config`:
```
In which compute environment are you running?
This machine                                                                      
----------------------------------------------------------------------------------Which type of machine are you using?                                              
multi-GPU                                                                         
How many different machines will you use (use more than 1 for multi-node training)? [1]: 1                                                                          
Should distributed operations be checked while running for errors? This can avoid timeout issues but will be slower. [yes/NO]: NO                                   
Do you wish to optimize your script with torch dynamo?[yes/NO]:NO                 
Do you want to use DeepSpeed? [yes/NO]: NO                                        
Do you want to use FullyShardedDataParallel? [yes/NO]: yes
----------------------------------------------------------------------------------What should be your sharding strategy?
FULL_SHARD                                                                        
Do you want to offload parameters and gradients to CPU? [yes/NO]: NO              
----------------------------------------------------------------------------------What should be your auto wrap policy?                                             
TRANSFORMER_BASED_WRAP                                                            
Do you want to use the model's `_no_split_modules` to wrap. Only applicable for 🤗 Transformers [yes/NO]: yes                                                       
----------------------------------------------------------------------------------What should be your FSDP's backward prefetch policy?
BACKWARD_PRE                                                                      
----------------------------------------------------------------------------------What should be your FSDP's state dict type?                                       
SHARDED_STATE_DICT                                                                
Do you want to enable FSDP's forward prefetch policy? [yes/NO]: NO                
Do you want to enable FSDP's `use_orig_params` feature? [YES/no]: no             
Do you want to enable CPU RAM efficient model loading? Only applicable for 🤗 Transformers models. [YES/no]: YES
How many GPU(s) should be used for distributed training? [1]:4
----------------------------------------------------------------------------------Do you wish to use FP16 or BF16 (mixed precision)?
bf16
```
and I'm running with 4x A6000 (48 GB VRAM) with 38 vCPU 200 GB RAM and a docker container size of 50 GB.

**Comment by RonanKMcGovern** [comment]
Ok, I think the issue here was that I had use_reentrant = False and that seems to require a lot more memory.
