### ISSUE TITLE
`accelerate test` on TPU times out

### ISSUE THREAD

**Issue by CaoHaiNam** [huggingface/accelerate#1243]
### System Info

```Shell
accelerate version: 0.17.1
OS: linux, in TPU VM - TPU Research Cloud
python version: 3.8.15
numpy version: 1.19.5
torch version: 1.8.1
accelerate config:
	compute_environment: LOCAL_MACHINE
	deepspeed_config: {}
	distributed_type: TPU
	downcast_bf16: 'no'
	dynamo_config: {}
	fsdp_config: {}
	machine_rank: 0
	main_training_function: main
	megatron_lm_config: {}
	mixed_precision: 'no'
	num_machines: 1
	num_processes: 8
	rdzv_backend: static
	same_network: true
	tpu_env: []
	tpu_use_cluster: false
	tpu_use_sudo: false
	use_cpu: false
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

```
accelerate test
```

### Expected behavior

```Shell
run successfully without error!
```

**Comment by CaoHaiNam** [comment]
when I install library, I run:
```
accelerate test
```
and I get following error:
```
Running:  accelerate-launch /home/namch_hust1_gmail_com/.local/lib/python3.8/site-packages/accelerate/test_utils/scripts/test_script.py
stderr: Traceback (most recent call last):
stderr:   File "/home/namch_hust1_gmail_com/.local/bin/accelerate-launch", line 8, in <module>
stderr:     sys.exit(main())
stderr:   File "/home/namch_hust1_gmail_com/.local/lib/python3.8/site-packages/accelerate/commands/launch.py", line 921, in main
stderr:     launch_command(args)
stderr:   File "/home/namch_hust1_gmail_com/.local/lib/python3.8/site-packages/accelerate/commands/launch.py", line 892, in launch_command
stderr:     args, defaults, mp_from_config_flag = _validate_launch_command(args)
stderr:   File "/home/namch_hust1_gmail_com/.local/lib/python3.8/site-packages/accelerate/commands/launch.py", line 793, in _validate_launch_command
stderr:     args.tpu_cluster = defaults.tpu_cluster if args.tpu else False
stderr: AttributeError: 'ClusterConfig' object has no attribute 'tpu_cluster'
Traceback (most recent call last):
  File "/home/namch_hust1_gmail_com/.local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/namch_hust1_gmail_com/.local/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/namch_hust1_gmail_com/.local/lib/python3.8/site-packages/accelerate/commands/test.py", line 54, in test_command
    result = execute_subprocess_async(cmd, env=os.environ.copy())
  File "/home/namch_hust1_gmail_com/.local/lib/python3.8/site-packages/accelerate/test_utils/testing.py", line 359, in execute_subprocess_async
    raise RuntimeError(
RuntimeError: 'accelerate-launch /home/namch_hust1_gmail_com/.local/lib/python3.8/site-packages/accelerate/test_utils/scripts/test_script.py' failed with returncode 1

The combined stderr from workers follows:
Traceback (most recent call last):
  File "/home/namch_hust1_gmail_com/.local/bin/accelerate-launch", line 8, in <module>
    sys.exit(main())
  File "/home/namch_hust1_gmail_com/.local/lib/python3.8/site-packages/accelerate/commands/launch.py", line 921, in main
    launch_command(args)
  File "/home/namch_hust1_gmail_com/.local/lib/python3.8/site-packages/accelerate/commands/launch.py", line 892, in launch_command
    args, defaults, mp_from_config_flag = _validate_launch_command(args)
  File "/home/namch_hust1_gmail_com/.local/lib/python3.8/site-packages/accelerate/commands/launch.py", line 793, in _validate_launch_command
    args.tpu_cluster = defaults.tpu_cluster if args.tpu else False
AttributeError: 'ClusterConfig' object has no attribute 'tpu_cluster'
```

**Comment by muellerzr** [comment]
@CaoHaiNam install via git please, I believe we already put a fix in. `pip install git+https://github.com/huggingface/accelerate`

**Comment by CaoHaiNam** [comment]
@muellerzr  I did, but I have got a timeout. I have waited for more than 10 minutes but testing processing is still running.
This is accelerate version
```
Name: accelerate
Version: 0.18.0.dev0
Summary: Accelerate
Home-page: https://github.com/huggingface/accelerate
Author: The HuggingFace team
Author-email: sylvain@huggingface.co
License: Apache
Location: /home/namch_hust1_gmail_com/.local/lib/python3.8/site-packages
Requires: numpy, packaging, psutil, pyyaml, torch
Required-by: 
```

**Comment by CaoHaiNam** [comment]
Oh my god, @muellerzr, I forgot to run this script first:
```
export XRT_TPU_CONFIG="localservice;0;localhost:51011"
```
And now It works!
