### ISSUE TITLE
transformer_engine_extensions.cpython-38-x86_64-linux-gnu.so: undefined symbol

### ISSUE THREAD

**Issue by DogeWatch** [huggingface/accelerate#1282]
### System Info

```Shell
accelerate version: 0.18.0
docker from: nvcr.io/nvidia/pytorch:22.09-py3
run `import accelerate` get error:

>>> import accelerate
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/accelerate/__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "/opt/conda/lib/python3.8/site-packages/accelerate/accelerator.py", line 31, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "/opt/conda/lib/python3.8/site-packages/accelerate/checkpointing.py", line 24, in <module>
    from .utils import (
  File "/opt/conda/lib/python3.8/site-packages/accelerate/utils/__init__.py", line 106, in <module>
    from .launch import (
  File "/opt/conda/lib/python3.8/site-packages/accelerate/utils/launch.py", line 28, in <module>
    from ..utils.other import merge_dicts
  File "/opt/conda/lib/python3.8/site-packages/accelerate/utils/other.py", line 24, in <module>
    from .transformer_engine import convert_model
  File "/opt/conda/lib/python3.8/site-packages/accelerate/utils/transformer_engine.py", line 21, in <module>
    import transformer_engine.pytorch as te
  File "/opt/conda/lib/python3.8/site-packages/transformer_engine/__init__.py", line 7, in <module>
    from . import pytorch
  File "/opt/conda/lib/python3.8/site-packages/transformer_engine/pytorch/__init__.py", line 6, in <module>
    from .module import LayerNormLinear
  File "/opt/conda/lib/python3.8/site-packages/transformer_engine/pytorch/module.py", line 16, in <module>
    import transformer_engine_extensions as tex
ImportError: /opt/conda/lib/python3.8/site-packages/transformer_engine_extensions.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c106SymInt8toSymIntENS_13intrusive_ptrINS_14SymIntNodeImplENS_6detail34intrusive_target_default_null_typeIS2_EEEE
```
```


### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

run `import accelerate` get error:
```
>>> import accelerate
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/accelerate/__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "/opt/conda/lib/python3.8/site-packages/accelerate/accelerator.py", line 31, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "/opt/conda/lib/python3.8/site-packages/accelerate/checkpointing.py", line 24, in <module>
    from .utils import (
  File "/opt/conda/lib/python3.8/site-packages/accelerate/utils/__init__.py", line 106, in <module>
    from .launch import (
  File "/opt/conda/lib/python3.8/site-packages/accelerate/utils/launch.py", line 28, in <module>
    from ..utils.other import merge_dicts
  File "/opt/conda/lib/python3.8/site-packages/accelerate/utils/other.py", line 24, in <module>
    from .transformer_engine import convert_model
  File "/opt/conda/lib/python3.8/site-packages/accelerate/utils/transformer_engine.py", line 21, in <module>
    import transformer_engine.pytorch as te
  File "/opt/conda/lib/python3.8/site-packages/transformer_engine/__init__.py", line 7, in <module>
    from . import pytorch
  File "/opt/conda/lib/python3.8/site-packages/transformer_engine/pytorch/__init__.py", line 6, in <module>
    from .module import LayerNormLinear
  File "/opt/conda/lib/python3.8/site-packages/transformer_engine/pytorch/module.py", line 16, in <module>
    import transformer_engine_extensions as tex
ImportError: /opt/conda/lib/python3.8/site-packages/transformer_engine_extensions.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c106SymInt8toSymIntENS_13intrusive_ptrINS_14SymIntNodeImplENS_6detail34intrusive_target_default_null_typeIS2_EEEE
```

### Expected behavior

no error

**Comment by sgugger** [comment]
Looks like your install of `transformers-engine` is borked. You need to uninstall it or re-install it cleanly.

**Comment by DongchenZhou** [comment]
I reinstalled the transformers engine(pip install transformers) and the above situation still occurs， why？

**Comment by cgt-woailol** [comment]
> I reinstalled the transformers engine(pip install transformers) and the above situation still occurs， why？

You can try `pip uninstall transformers_engine`
