### ISSUE TITLE
Calling `wandb` on main process in multi-node scenario

### ISSUE THREAD

**Issue by zanussbaum** [huggingface/accelerate#1294]
### System Info

```Shell
- `Accelerate` version: 0.18.0
- Platform: Linux-5.15.0-52-generic-x86_64-with-glibc2.29
- Python version: 3.8.10
- Numpy version: 1.24.2
- PyTorch version (GPU?): 2.0.0+cu117 (True)
- `Accelerate` default config:
        Not found
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

In my code, I try to add a `wandb.watch(model)` to track outputs and gradients of the model. However, I get the following error
```
131.186.3.132: Traceback (most recent call last):                                                                                                                                                     
131.186.3.132:   File "train.py", line 231, in <module>                                                                                                                                               
localhost: No modifications detected for re-loaded extension module utils, skipping build step...                                                                                                     
131.186.3.132:     train(accelerator, config=config)                                                                                                                                                  
131.186.3.132:   File "train.py", line 141, in train                                                                                                                                                  
localhost: Loading extension module utils...                                                                                                                                                          
131.186.3.132:     wandb.watch(model, log_freq=config["log_grads_every"])                                                                                                                             
131.186.3.132:   File "/home/ubuntu/gpt4all/env/lib/python3.8/site-packages/wandb/sdk/wandb_watch.py", line 54, in watch                                                                              
131.186.3.132:     raise ValueError("You must call `wandb.init` before calling watch")                                                                                                                
131.186.3.132: ValueError: You must call `wandb.init` before calling watch                    
```
I'm using Deepspeed with `pdsh` and two nodes. I roughly follow [this guide](https://github.com/LambdaLabsML/examples/tree/main/gpt-neox-training) to setup the two nodes. I have verified that I can ssh to both of them from the main node.

In the code, I call 

```
# log gradients
    if accelerator.is_main_process and config["wandb"]:
    
        wandb.watch(model, log_freq=config["log_grads_every"])
```
but get the error from above. It seems odd that that is also running on the ip starting with 131 when the main node should be using `localhost`. This error only appears with multi-node training. The code seems to work in single node, multi-gpu settings

### Expected behavior

I can log the gradients on the main process

**Comment by zanussbaum** [comment]
Closing as this was an error on my end, make sure your code is synced on both nodes!
