### ISSUE TITLE
Accelerate FSDP errors when saving due to lr_scheduler pickling

### ISSUE THREAD

**Issue by PaulScotti** [huggingface/accelerate#1358]
### System Info

```Shell
- Accelerate version: 0.18.0
- PyTorch version: 2.0.0+cu117
- Platform: Linux-5.15.0-1023-aws-x86_64-with-glibc2.31
- Python version: 3.10.8
- Numpy version: 1.23.5

accelerate config:

compute_environment: LOCAL_MACHINE
distributed_type: FSDP
downcast_bf16: 'no'
fsdp_config:
  fsdp_auto_wrap_policy: SIZE_BASED_WRAP
  fsdp_backward_prefetch_policy: BACKWARD_PRE
  fsdp_min_num_params: 100000
  fsdp_offload_params: true
  fsdp_sharding_strategy: 1
  fsdp_state_dict_type: FULL_STATE_DICT
machine_rank: 0
main_training_function: main
mixed_precision: ‘no’
num_machines: 1
num_processes: 4
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

accelerator.save_state(output_dir=outdir) produces the following error only when using FSDP. @pacman100 

We likewise get the same error using torch.save(), but only if lr_scheduler.state_dict() is included in the torch.save() call.

Our lr_scheduler is

```
lr_scheduler = torch.optim.lr_scheduler.OneCycleLR(
        optimizer, 
        max_lr=max_lr,
        total_steps=total_steps,
        final_div_factor=1000,
        last_epoch=-1, pct_start=2/num_epochs
    )
```

and we prepare the model via

```
voxel2clip = accelerator.prepare(voxel2clip)
<code here that sets up optimizer, dataloaders, lr_scheduler>
optimizer, train_dl, val_dl, lr_scheduler = accelerator.prepare(
optimizer, train_dl, val_dl, lr_scheduler
)
accelerator.register_for_checkpointing(lr_scheduler)
```

Here is the error from accelerator.save_state():

```
Saving model to /fsx/proj-medarc/fmri/paulscotti/fMRI-reconstruction-NSD/train_logs/testing/pytorch_model.bin
Model saved to /fsx/proj-medarc/fmri/paulscotti/fMRI-reconstruction-NSD/train_logs/testing/pytorch_model.bin
/fsx/home-paulscotti/miniconda3/envs/medical-v1/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py:1110: UserWarning: ``FullyShardedDataParallel.full_optim_state_dict``is being deprecated and is replaced by ``FullyShardedDataParallel.optim_state_dict``. ``FullyShardedDataParallel.full_optim_state_dict`` may be removed after PyTorch 2.2.
  warnings.warn(
Traceback (most recent call last):
  File "/fsx/proj-medarc/fmri/paulscotti/fMRI-reconstruction-NSD/src/Brain_to_CLIP.py", line 693, in <module>
    save_ckpt('best')
  File "/fsx/proj-medarc/fmri/paulscotti/fMRI-reconstruction-NSD/src/Brain_to_CLIP.py", line 431, in save_ckpt
    accelerator.save_state(output_dir=outdir)
  File "/fsx/home-paulscotti/miniconda3/envs/medical-v1/lib/python3.10/site-packages/accelerate/accelerator.py", line 2283, in save_state
    save_custom_state(obj, output_dir, i)
  File "/fsx/home-paulscotti/miniconda3/envs/medical-v1/lib/python3.10/site-packages/accelerate/checkpointing.py", line 183, in save_custom_state
    torch.save(obj.state_dict(), save_location)
  File "/fsx/home-paulscotti/miniconda3/envs/medical-v1/lib/python3.10/site-packages/torch/serialization.py", line 441, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)
  File "/fsx/home-paulscotti/miniconda3/envs/medical-v1/lib/python3.10/site-packages/torch/serialization.py", line 653, in _save
    pickler.dump(obj)
TypeError: cannot pickle 'torch._C._distributed_c10d.ProcessGroup' object
```

### Expected behavior

accelerator.save_state(output_dir=outdir) and torch.save() should run without error. They do run without error when we are not using FSDP.

**Comment by sgugger** [comment]
cc @pacman100

**Comment by pacman100** [comment]
Hello, https://github.com/huggingface/accelerate/actions/runs/4804165250/jobs/8549378552#step:5:4226
tests FSDP with checkpointing and uses Lineardecay le scheduler and the test is passing.

Could you run below command and check if it is passing:
```
accelerate launch --num_processes=2 --num_machines=1 --machine_rank=0 --use_fsdp --mixed_precision=fp16 --fsdp_transformer_layer_cls_to_wrap=BertLayer --fsdp_sharding_strategy=1 --fsdp_state_dict_type=FULL_STATE_DICT accelerate/src/accelerate/test_utils/scripts/external_deps/test_checkpointing.py --output_dir=/tmp/tmp8pnu4sdf --partial_train_epoch=1
```

**Comment by PaulScotti** [comment]
> 

Yes, this does pass when i run it!

**Comment by pacman100** [comment]
cool, then it is able to save lr scheduler properly, could you provide with a minimal script that we can run to reproduce the issue?

**Comment by PaulScotti** [comment]
> 

Here is a script that reproduces the issue. Run it with

```
accelerate launch --num_processes=2 --num_machines=1 --machine_rank=0 --use_fsdp --mixed_precision='no' --fsdp_auto_wrap_policy=SIZE_BASED_WRAP --fsdp_backward_prefetch_policy=BACKWARD_PRE --fsdp_sharding_strategy=1 --fsdp_min_num_params=100 fsdptest.py
```

fsdptest.py

```
import os
import sys
import json
import torch
import torch.nn as nn
import torch.distributed as dist
from accelerate import Accelerator
# uses tf32 data type which is faster than standard float32
torch.backends.cuda.matmul.allow_tf32 = True
# Multi-GPU config #
accelerator = Accelerator()
print = accelerator.print # only print if local_rank=0
device = accelerator.device
print("device:",device)
num_devices = torch.cuda.device_count()
if num_devices==0: num_devices = 1
num_workers = num_devices
print(accelerator.state)
local_rank = accelerator.state.local_process_index
world_size = accelerator.state.num_processes
distributed = not accelerator.state.distributed_type == 'NO'
print("distributed =",distributed,"num_devices =", num_devices, "local rank =", local_rank, "world size =", world_size)

in_size = 200
seed = 42
batch_size = 8
num_epochs = 2

from functools import partial
class Network(nn.Module):
    def __init__(self, out_dim=768, in_dim=in_size, h=4096, n_blocks=4, norm_type='bn', act_first=True):
        super().__init__()
        norm_func = partial(nn.BatchNorm1d, num_features=h) if norm_type == 'bn' else partial(nn.LayerNorm, normalized_shape=h)
        act_fn = partial(nn.ReLU, inplace=True) if norm_type == 'bn' else nn.GELU
        act_and_norm = (act_fn, norm_func) if act_first else (norm_func, act_fn)
        self.temp = nn.Parameter(torch.tensor(.006))
        self.lin0 = nn.Sequential(
            nn.Linear(in_dim, h),
            *[item() for item in act_and_norm],
            nn.Dropout(0.5),
        )
            
        
        self.mlp = nn.ModuleList([
            nn.Sequential(
                nn.Linear(h, h),
                *[item() for item in act_and_norm],
                nn.Dropout(0.15)
            ) for _ in range(n_blocks)
        ])
        
        self.lin1 = nn.Linear(h, out_dim, bias=True)
        self.n_blocks = n_blocks
        
    def forward(self, x):
        '''
            bs, 1, 15724 -> bs, 32, h
            bs, 32, h -> bs, 32h
            b2, 32h -> bs, 768
        '''
        if x.ndim == 4:
            # case when we passed 3D data of shape [N, 81, 104, 83]
            assert x.shape[1] == 81 and x.shape[2] == 104 and x.shape[3] == 83
            # [N, 699192]
            x = x.reshape(x.shape[0], -1)

        x = self.lin0(x)  # bs, h
        residual = x
        for res_block in range(self.n_blocks):
            x = self.mlp[res_block](x)
            x += residual
            residual = x
        x = x.reshape(len(x), -1)
        x = self.lin1(x)
        return x
    
print("prep model")
model = Network(**dict(out_dim=in_size))
model = accelerator.prepare(model)
print(model)

print("prep optimizer and lr scheduler")
no_decay = ['bias', 'LayerNorm.bias', 'LayerNorm.weight']
opt_grouped_parameters = [
    {'params': [p for n, p in model.named_parameters() if not any(nd in n for nd in no_decay)], 'weight_decay': 1e-2},
    {'params': [p for n, p in model.named_parameters() if any(nd in n for nd in no_decay)], 'weight_decay': 0.0}
]
optimizer = torch.optim.AdamW(opt_grouped_parameters, lr=3e-4)
global_batch_size = batch_size * num_devices
total_steps=num_epochs*(32//global_batch_size)
lr_scheduler = torch.optim.lr_scheduler.OneCycleLR(
    optimizer, 
    max_lr=3e-4,
    total_steps=10000,
    final_div_factor=1000,
    last_epoch=-1, pct_start=2/num_epochs
)
    
optimizer, lr_scheduler = accelerator.prepare(
optimizer, lr_scheduler
)
accelerator.register_for_checkpointing(lr_scheduler)

mse = nn.MSELoss()
torch.cuda.empty_cache()
print("start training")

from tqdm import tqdm
epoch=0
progress_bar = tqdm(range(epoch,num_epochs), ncols=1200, disable=(local_rank!=0))
for epoch in range(epoch,num_epochs):

    model.train()
    optimizer.zero_grad()

    inp = torch.randn(batch_size,in_size).to(device)

    out = model(inp)

    loss = mse(inp,out)

    accelerator.backward(loss)
    optimizer.step()
    lr_scheduler.step()

    # save
    accelerator.wait_for_everyone()
    print("\nbegin saving..")
    accelerator.save_state(output_dir=os.getcwd())
    print("finished saving!\n")
    break

sys.exit(0)
```

**Comment by Muttermal** [comment]
hi, When I save the model using `accelerator.save_state`, I also get an error. The following are the details:
## System Info

> - Accelerate version: 0.18.0
> - PyTorch version: 2.0.0+cu117
> - Platform: Linux version 4.18.0-193.el8.x86_64 (gcc version 8.3.1 20191121)
> - Python version: 3.8.13
> - Numpy version: 1.22.4

accelerate config:
```yaml
compute_environment: LOCAL_MACHINE
deepspeed_config: {}
distributed_type: FSDP
downcast_bf16: 'no'
dynamo_backend: 'NO'
fsdp_config:
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_backward_prefetch_policy: BACKWARD_PRE
  fsdp_offload_params: false
  fsdp_sharding_strategy: 1
  fsdp_state_dict_type: FULL_STATE_DICT
  fsdp_transformer_layer_cls_to_wrap: Kosmos
machine_rank: 0
main_training_function: main
main_process_ip: null
main_process_port: 8090
megatron_lm_config: {}
mixed_precision: bf16
num_machines: 1
num_processes: 4
rdzv_backend: static
same_network: true
use_cpu: false
```
## Reproduction
my optimizer is:
```python
optimizer = AdamW8bit(model.parameters(),  lr=args.learning_rate,  weight_decay=args.weight_decay)
```
I use `accelerator.save_state(output_dir)` to save the trained model, the model file(.bin) has saved successfully, but when saving the optimizer, I got the following error:
```
/mnt/glusterfs/aicv/ainlp/zhangguangyi/BigModels/Kosmos/train_kosmos.py:176 in <module> 
  train(train_args)
/mnt/glusterfs/aicv/ainlp/zhangguangyi/BigModels/Kosmos/train_kosmos.py:155 in train  
  accelerator.save_state(                                                  
/mnt/glusterfs/aicv/ainlp/zhangguangyi/LLM/lib/python3.8/site-packages/accelerate/accelerator.py :2259 in save_state  
  self.state.fsdp_plugin.save_optimizer(self, opt, self._models[i], output_dir, i)
/mnt/glusterfs/aicv/ainlp/zhangguangyi/LLM/lib/python3.8/site-packages/accelerate/utils/dataclasses.py:926 in save_optimizer 
  optim_state = FSDP.full_optim_state_dict(model, optimizer, optim_input=optim_input)
/mnt/glusterfs/aicv/ainlp/zhangguangyi/LLM/lib/python3.8/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py:1330 in full_optim_state_dict 
  return FullyShardedDataParallel._optim_state_dict_impl(  
/mnt/glusterfs/aicv/ainlp/zhangguangyi/LLM/lib/python3.8/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py:1154 in _optim_state_dict_impl 
  return _optim_state_dict(  
/mnt/glusterfs/aicv/ainlp/zhangguangyi/LLM/lib/python3.8/site-packages/torch/distributed/fsdp/_o ptim_utils.py:1463 in _optim_state_dict
  unflat_state = _unflatten_optim_state(  
/mnt/glusterfs/aicv/ainlp/zhangguangyi/LLM/lib/python3.8/site-packages/torch/distributed/fsdp/_o ptim_utils.py:136 in _unflatten_optim_state  
  consolidated_state = _communicate_optim_state( 
/mnt/glusterfs/aicv/ainlp/zhangguangyi/LLM/lib/python3.8/site-packages/torch/distributed/fsdp/_optim_utils.py:209 in _communicate_optim_state
  dist.all_gather_into_tensor(
/mnt/glusterfs/aicv/ainlp/zhangguangyi/LLM/lib/python3.8/site-packages/torch/distributed/distrib uted_c10d.py:1436 in wrapper 
  return func(*args, **kwargs)
/mnt/glusterfs/aicv/ainlp/zhangguangyi/LLM/lib/python3.8/site-packages/torch/distributed/distrib uted_c10d.py:2517 in all_gather_into_tensor 
  work = group._allgather_base(output_tensor, input_tensor)
RuntimeError: output tensor size must be equal to world_size times input tensor size
```

**Comment by pacman100** [comment]
@Muttermal, your issue is different, please raise separate issue with a minimal script to reproduce the same

**Comment by pacman100** [comment]
@PaulScotti, thank you for the code,  I'm able to reproduce the issue. Interestingly, if I switch the le scheduler to the LinearDecay scheduler, it works without any issues. 

I don't think this issue is related to the integration. It would be great if you could raise the issue with PyTorch team for this.

**Comment by PaulScotti** [comment]
> 

Thanks for looking into it, knowing that switching to LinearDecay can get around the issue is very useful! I will raise the issue with PyTorch team.
