### ISSUE TITLE
accelerator.prepare() throws an exception when loading an 8-bit model and trying to train the model on multi-GPU

### ISSUE THREAD

**Issue by Silypie** [huggingface/accelerate#1412]
https://github.com/huggingface/accelerate/blob/d07fd959cc15afe5ab7d890e52f0a9fa85f3acd0/src/accelerate/accelerator.py#L1202
I'm using accelerator+peft+bitsandbytes to train a large language model, my model is initialized as follows:
```python
model = AutoModelForSeq2SeqLM.from_pretrained(
    args.model_name_or_path,
    config=config,
    load_in_8bit=True,
    device_map="auto"
)
model = prepare_model_for_int8_training(model)
model, optimizer, train_dataloader, eval_dataloader, lr_scheduler = accelerator.prepare(
    model, optimizer, train_dataloader, eval_dataloader, lr_scheduler
)
```
I would like to know how to use accelerator for int8 training on multiple GPUs.

```
model, optimizer, train_dataloader, eval_dataloader, lr_scheduler = accelerator.prepare(
                                                                        ^^^^^^^^^^^^^^^^^^^^
File "/data2/home/anaconda3/envs/pt2/lib/python3.11/site-packages/accelerate/accelerator.py", line 1094, in prepare
    result = tuple(
             ^^^^^^
  File "/data2/home/anaconda3/envs/pt2/lib/python3.11/site-packages/accelerate/accelerator.py", line 1095, in <genexpr>
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data2/home/anaconda3/envs/pt2/lib/python3.11/site-packages/accelerate/accelerator.py", line 949, in _prepare_one
    return self.prepare_model(obj, device_placement=device_placement)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data2/home/anaconda3/envs/pt2/lib/python3.11/site-packages/accelerate/accelerator.py", line 1143, in prepare_model
    raise ValueError(
ValueError: You can't train a model that has been loaded in 8-bit precision on multiple devices.
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 68507 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 68508) of binary: /data2/home/anaconda3/envs/pt2/bin/python
Traceback (most recent call last):
  File "/data2/home/anaconda3/envs/pt2/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/data2/home/anaconda3/envs/pt2/lib/python3.11/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/data2/home/anaconda3/envs/pt2/lib/python3.11/site-packages/accelerate/commands/launch.py", line 906, in launch_command
    multi_gpu_launcher(args)
  File "/data2/home/anaconda3/envs/pt2/lib/python3.11/site-packages/accelerate/commands/launch.py", line 599, in multi_gpu_launcher
    distrib_run.run(args)
  File "/data2/home/anaconda3/envs/pt2/lib/python3.11/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/data2/home/anaconda3/envs/pt2/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data2/home/anaconda3/envs/pt2/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError
```

**Comment by sgugger** [comment]
cc @younesbelkada

**Comment by younesbelkada** [comment]
@Silypie 
Thanks for the ping!
Currently this is not supported because the accelerator will automatically convert the model into a `DistributedDataParallel` and this lead to multiple errors in the past using 8bit models. 
however, I believe that we can address a fix, that I didn't implemented at that time. Let me get back to you on this
