### ISSUE TITLE
DDP multi node multi gpu inconsistent params

### ISSUE THREAD

**Issue by flckv** [huggingface/accelerate#1481]
### System Info

```Shell
### System Info


- Accelarate version:  0.19.0  
- OS: Ubuntu 20.04.4 LTS (x86_64)
- Python version: 3.11.3
- Numpy: 1.24.3
- PyTorch version: 2.0.1


- CUDA used to build PyTorch: 11.8
- Is CUDA available: True
- CUDA runtime version: 11.8.89
- CUDA_MODULE_LOADING set to: LAZY
- GPU models and configuration: 
- GPU 0: NVIDIA A100-SXM4-40GB
- GPU 1: NVIDIA A100-SXM4-40GB
- GPU 2: NVIDIA A100-SXM4-40GB
- GPU 3: NVIDIA A100-SXM4-40GB
- Huggingface_hub version: 0.14.1

- Nvidia driver version: 510.47.03


(I am using SLURM:)
- Accelarate’s config: (not sure which file you mean)
accelerate config
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------In which compute environment are you running?
Please select a choice using the arrow or number keys, and selecting with enter
 ➔  This machine
    AWS (Amazon SageMaker)

there was no option for the nodes I already assigned
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

1. based on the [SLURM-accelerate template](https://github.com/huggingface/accelerate/issues/1239#issuecomment-1494331155)

- 2 nodes
- 4 GPUs (per node)

2. I pre-train the [wav2vec demo on librispeech](https://github.com/huggingface/transformers/blob/main/examples/pytorch/speech-pretraining/README.md)

3. I started receiving error messages (tried 3+ times with restarting the pretraining)

@[alexeib](https://github.com/alexeib) @[rohan-varma](https://github.com/rohan-varma) @[mrshenli](https://github.com/mrshenli)
reported also in [pytroch issue](https://github.com/pytorch/pytorch/issues/102438#issue-1728785076) 

"RuntimeError: DDP expects same model across all ranks, but Rank 1 has 237 params, while rank 2 has inconsistent 0 params."

### Expected behavior

Expect to be able to pretrain a model using multi node and multi gpus.

**Comment by ys910111** [comment]
Hello, I am facing the same issue. Is there any solution/workaround?

**Comment by muellerzr** [comment]
@ys910111 do you have a reproducer?

**Comment by Xnhyacinth** [comment]
the same error, how to solve it?

**Comment by Xnhyacinth** [comment]
@muellerzr Full error is as follows:
```
[rank3]: Traceback (most recent call last):
[rank3]: File "/root/miniconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[rank3]: return _run_code(code, main_globals, None,
[rank3]: File "/root/miniconda3/lib/python3.10/runpy.py", line 86, in _run_code
[rank3]: exec(code, run_globals)
[rank3]: File "/workspace/bin/src/language_modeling/train.py", line 879, in <module>
[rank3]: main()
[rank3]: File "/workspace/bin/src/language_modeling/train.py", line 674, in main
[rank3]: model, optimizer, train_dataloader, lr_scheduler = accelerator.prepare(
[rank3]: File "/root/miniconda3/lib/python3.10/site-packages/accelerate/accelerator.py", line 1311, in prepare
[rank3]: result = tuple(
[rank3]: File "/root/miniconda3/lib/python3.10/site-packages/accelerate/accelerator.py", line 1312, in <genexpr>
[rank3]: self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
[rank3]: File "/root/miniconda3/lib/python3.10/site-packages/accelerate/accelerator.py", line 1188, in _prepare_one
[rank3]: return self.prepare_model(obj, device_placement=device_placement)
[rank3]: File "/root/miniconda3/lib/python3.10/site-packages/accelerate/accelerator.py", line 1452, in prepare_model
[rank3]: model = torch.nn.parallel.DistributedDataParallel(
[rank3]: File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 825, in __init__
[rank3]: _verify_param_shape_across_processes(self.process_group, parameters)
[rank3]: File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/utils.py", line 288, in _verify_param_shape_across_processes
[rank3]: return dist._verify_params_across_processes(process_group, tensors, logger)
[rank3]: RuntimeError: DDP expects same model across all ranks, but Rank 3 has 400 params, while rank 0 has inconsistent 399 params.
[rank2]: Traceback (most recent call last):
[rank2]: File "/root/miniconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[rank2]: return _run_code(code, main_globals, None,
[rank2]: File "/root/miniconda3/lib/python3.10/runpy.py", line 86, in _run_code
[rank2]: exec(code, run_globals)
[rank2]: File "/workspace/bin/src/language_modeling/train.py", line 879, in <module>
[rank2]: main()
[rank2]: File "/workspace/bin/src/language_modeling/train.py", line 674, in main
[rank2]: model, optimizer, train_dataloader, lr_scheduler = accelerator.prepare(
[rank2]: File "/root/miniconda3/lib/python3.10/site-packages/accelerate/accelerator.py", line 1311, in prepare
[rank2]: result = tuple(
[rank2]: File "/root/miniconda3/lib/python3.10/site-packages/accelerate/accelerator.py", line 1312, in <genexpr>
[rank2]: self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
[rank2]: File "/root/miniconda3/lib/python3.10/site-packages/accelerate/accelerator.py", line 1188, in _prepare_one
[rank2]: return self.prepare_model(obj, device_placement=device_placement)
[rank2]: File "/root/miniconda3/lib/python3.10/site-packages/accelerate/accelerator.py", line 1452, in prepare_model
[rank2]: model = torch.nn.parallel.DistributedDataParallel(
[rank2]: File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 825, in __init__
[rank2]: _verify_param_shape_across_processes(self.process_group, parameters)
[rank2]: File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/utils.py", line 288, in _verify_param_shape_across_processes
[rank2]: return dist._verify_params_across_processes(process_group, tensors, logger)
[rank2]: RuntimeError: DDP expects same model across all ranks, but Rank 2 has 400 params, while rank 0 has inconsistent 399 params.
[rank6]: Traceback (most recent call last):
[rank6]: File "/root/miniconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[rank6]: return _run_code(code, main_globals, None,
[rank6]: File "/root/miniconda3/lib/python3.10/runpy.py", line 86, in _run_code
[rank6]: exec(code, run_globals)
[rank6]: File "/workspace/bin/src/language_modeling/train.py", line 879, in <module>
[rank6]: main()
[rank6]: File "/workspace/bin/src/language_modeling/train.py", line 674, in main
[rank6]: model, optimizer, train_dataloader, lr_scheduler = accelerator.prepare(
[rank6]: File "/root/miniconda3/lib/python3.10/site-packages/accelerate/accelerator.py", line 1311, in prepare
[rank6]: result = tuple(
[rank6]: File "/root/miniconda3/lib/python3.10/site-packages/accelerate/accelerator.py", line 1312, in <genexpr>
[rank6]: self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
[rank6]: File "/root/miniconda3/lib/python3.10/site-packages/accelerate/accelerator.py", line 1188, in _prepare_one
[rank6]: return self.prepare_model(obj, device_placement=device_placement)
[rank6]: File "/root/miniconda3/lib/python3.10/site-packages/accelerate/accelerator.py", line 1452, in prepare_model
[rank6]: model = torch.nn.parallel.DistributedDataParallel(
[rank6]: File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 825, in __init__
[rank6]: _verify_param_shape_across_processes(self.process_group, parameters)
[rank6]: File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/utils.py", line 288, in _verify_param_shape_across_processes
[rank6]: return dist._verify_params_across_processes(process_group, tensors, logger)
[rank6]: RuntimeError: DDP expects same model across all ranks, but Rank 6 has 400 params, while rank 0 has inconsistent 399 params.
[rank0]: Traceback (most recent call last):
[rank0]: File "/root/miniconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[rank0]: return _run_code(code, main_globals, None,
[rank0]: File "/root/miniconda3/lib/python3.10/runpy.py", line 86, in _run_code
[rank0]: exec(code, run_globals)
[rank0]: File "/workspace/bin/src/language_modeling/train.py", line 879, in <module>
[rank0]: main()
[rank0]: File "/workspace/bin/src/language_modeling/train.py", line 674, in main
[rank0]: model, optimizer, train_dataloader, lr_scheduler = accelerator.prepare(
[rank0]: File "/root/miniconda3/lib/python3.10/site-packages/accelerate/accelerator.py", line 1311, in prepare
[rank0]: result = tuple(
[rank0]: File "/root/miniconda3/lib/python3.10/site-packages/accelerate/accelerator.py", line 1312, in <genexpr>
[rank0]: self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
[rank0]: File "/root/miniconda3/lib/python3.10/site-packages/accelerate/accelerator.py", line 1188, in _prepare_one
[rank0]: return self.prepare_model(obj, device_placement=device_placement)
[rank0]: File "/root/miniconda3/lib/python3.10/site-packages/accelerate/accelerator.py", line 1452, in prepare_model
[rank0]: model = torch.nn.parallel.DistributedDataParallel(
[rank0]: File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 825, in __init__
[rank0]: _verify_param_shape_across_processes(self.process_group, parameters)
[rank0]: File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/utils.py", line 288, in _verify_param_shape_across_processes
[rank0]: return dist._verify_params_across_processes(process_group, tensors, logger)
[rank0]: RuntimeError: DDP expects same model across all ranks, but Rank 0 has 399 params, while rank 1 has inconsistent 400 params.
[rank1]: Traceback (most recent call last):
[rank1]: File "/root/miniconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[rank1]: return _run_code(code, main_globals, None,
[rank1]: File "/root/miniconda3/lib/python3.10/runpy.py", line 86, in _run_code
[rank1]: exec(code, run_globals)
[rank1]: File "/workspace/bin/src/language_modeling/train.py", line 879, in <module>
[rank1]: main()
[rank1]: File "/workspace/bin/src/language_modeling/train.py", line 674, in main
[rank1]: model, optimizer, train_dataloader, lr_scheduler = accelerator.prepare(
[rank1]: File "/root/miniconda3/lib/python3.10/site-packages/accelerate/accelerator.py", line 1311, in prepare
[rank1]: result = tuple(
[rank1]: File "/root/miniconda3/lib/python3.10/site-packages/accelerate/accelerator.py", line 1312, in <genexpr>
[rank1]: self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
[rank1]: File "/root/miniconda3/lib/python3.10/site-packages/accelerate/accelerator.py", line 1188, in _prepare_one
[rank1]: return self.prepare_model(obj, device_placement=device_placement)
[rank1]: File "/root/miniconda3/lib/python3.10/site-packages/accelerate/accelerator.py", line 1452, in prepare_model
[rank1]: model = torch.nn.parallel.DistributedDataParallel(
[rank1]: File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 825, in __init__
[rank1]: _verify_param_shape_across_processes(self.process_group, parameters)
[rank1]: File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/utils.py", line 288, in _verify_param_shape_across_processes
[rank1]: return dist._verify_params_across_processes(process_group, tensors, logger)
[rank1]: RuntimeError: DDP expects same model across all ranks, but Rank 1 has 400 params, while rank 0 has inconsistent 399 params.
[rank7]: Traceback (most recent call last):
[rank7]: File "/root/miniconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[rank7]: return _run_code(code, main_globals, None,
[rank7]: File "/root/miniconda3/lib/python3.10/runpy.py", line 86, in _run_code
[rank7]: exec(code, run_globals)
[rank7]: File "/workspace/bin/src/language_modeling/train.py", line 879, in <module>
[rank7]: main()
[rank7]: File "/workspace/bin/src/language_modeling/train.py", line 674, in main
[rank7]: model, optimizer, train_dataloader, lr_scheduler = accelerator.prepare(
[rank7]: File "/root/miniconda3/lib/python3.10/site-packages/accelerate/accelerator.py", line 1311, in prepare
[rank7]: result = tuple(
[rank7]: File "/root/miniconda3/lib/python3.10/site-packages/accelerate/accelerator.py", line 1312, in <genexpr>
[rank7]: self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
[rank7]: File "/root/miniconda3/lib/python3.10/site-packages/accelerate/accelerator.py", line 1188, in _prepare_one
[rank7]: return self.prepare_model(obj, device_placement=device_placement)
[rank7]: File "/root/miniconda3/lib/python3.10/site-packages/accelerate/accelerator.py", line 1452, in prepare_model
[rank7]: model = torch.nn.parallel.DistributedDataParallel(
[rank7]: File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 825, in __init__
[rank7]: _verify_param_shape_across_processes(self.process_group, parameters)
[rank7]: File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/utils.py", line 288, in _verify_param_shape_across_processes
[rank7]: return dist._verify_params_across_processes(process_group, tensors, logger)
[rank7]: RuntimeError: DDP expects same model across all ranks, but Rank 7 has 400 params, while rank 0 has inconsistent 399 params.
[rank4]: Traceback (most recent call last):
[rank4]: File "/root/miniconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[rank4]: return _run_code(code, main_globals, None,
[rank4]: File "/root/miniconda3/lib/python3.10/runpy.py", line 86, in _run_code
[rank4]: exec(code, run_globals)
[rank4]: File "/workspace/bin/src/language_modeling/train.py", line 879, in <module>
[rank4]: main()
[rank4]: File "/workspace/bin/src/language_modeling/train.py", line 674, in main
[rank4]: model, optimizer, train_dataloader, lr_scheduler = accelerator.prepare(
[rank4]: File "/root/miniconda3/lib/python3.10/site-packages/accelerate/accelerator.py", line 1311, in prepare
[rank4]: result = tuple(
[rank4]: File "/root/miniconda3/lib/python3.10/site-packages/accelerate/accelerator.py", line 1312, in <genexpr>
[rank4]: self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
[rank4]: File "/root/miniconda3/lib/python3.10/site-packages/accelerate/accelerator.py", line 1188, in _prepare_one
[rank4]: return self.prepare_model(obj, device_placement=device_placement)
[rank4]: File "/root/miniconda3/lib/python3.10/site-packages/accelerate/accelerator.py", line 1452, in prepare_model
[rank4]: model = torch.nn.parallel.DistributedDataParallel(
[rank4]: File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 825, in __init__
[rank4]: _verify_param_shape_across_processes(self.process_group, parameters)
[rank4]: File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/utils.py", line 288, in _verify_param_shape_across_processes
[rank4]: return dist._verify_params_across_processes(process_group, tensors, logger)
[rank4]: RuntimeError: DDP expects same model across all ranks, but Rank 4 has 400 params, while rank 0 has inconsistent 399 params.
[rank5]: Traceback (most recent call last):
[rank5]: File "/root/miniconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[rank5]: return _run_code(code, main_globals, None,
[rank5]: File "/root/miniconda3/lib/python3.10/runpy.py", line 86, in _run_code
[rank5]: exec(code, run_globals)
[rank5]: File "/workspace/bin/src/language_modeling/train.py", line 879, in <module>
[rank5]: main()
[rank5]: File "/workspace/bin/src/language_modeling/train.py", line 674, in main
[rank5]: model, optimizer, train_dataloader, lr_scheduler = accelerator.prepare(
[rank5]: File "/root/miniconda3/lib/python3.10/site-packages/accelerate/accelerator.py", line 1311, in prepare
[rank5]: result = tuple(
[rank5]: File "/root/miniconda3/lib/python3.10/site-packages/accelerate/accelerator.py", line 1312, in <genexpr>
[rank5]: self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
[rank5]: File "/root/miniconda3/lib/python3.10/site-packages/accelerate/accelerator.py", line 1188, in _prepare_one
[rank5]: return self.prepare_model(obj, device_placement=device_placement)
[rank5]: File "/root/miniconda3/lib/python3.10/site-packages/accelerate/accelerator.py", line 1452, in prepare_model
[rank5]: model = torch.nn.parallel.DistributedDataParallel(
[rank5]: File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 825, in __init__
[rank5]: _verify_param_shape_across_processes(self.process_group, parameters)
[rank5]: File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/utils.py", line 288, in _verify_param_shape_across_processes
[rank5]: return dist._verify_params_across_processes(process_group, tensors, logger)
[rank5]: RuntimeError: DDP expects same model across all ranks, but Rank 5 has 400 params, while rank 0 has inconsistent 399 params.
```
