### ISSUE TITLE
When I use mixed precision, I encounter the issue of disappearing gradients in the self-conditioning setup.

### ISSUE THREAD

**Issue by elephantmipt** [huggingface/accelerate#1499]
### System Info

```Shell
2xA100 80GB GPU with CUDA 11.7

accelerate==0.19.0
torch==2.0.1
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

Script I am using:

```python
import torch
from torch import nn
from torch.utils.data import TensorDataset, DataLoader
from torch.nn import functional as F
from tqdm.auto import tqdm

import accelerate


class Diffusion(nn.Module):
    def __init__(self):
        super().__init__()
        self.layers = nn.Sequential(
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Linear(64, 64)
        )

    def forward(self, x, s_x=None):
        if s_x is None:
            s_x = torch.zeros_like(x)
        x_cat = torch.cat((x,s_x), dim=-1)
        res = self.layers(x_cat)
        return res


class DiffusionWrapper(nn.Module):
    def __init__(self, model):
        super().__init__()
        self.model = model

    def forward(self, x, y, self_conditioning):
        s_x = None
        if self_conditioning:
            with torch.no_grad():
                s_x = self.model(x)
                s_x = s_x.detach()
        res = self.model(x, s_x)
        loss = F.cross_entropy(res, y)
        return loss


def main():
    accelerator = accelerate.Accelerator(device_placement=True, split_batches=True)
    model = Diffusion()
    model = DiffusionWrapper(model)
    optimizer = torch.optim.Adam(model.parameters())
    model, optimizer = accelerator.prepare(model, optimizer)
    x = torch.randn(1600, 64)
    y = torch.ones(x.size(0), dtype=torch.long)
    dataset = TensorDataset(x, y)
    dataloader = DataLoader(dataset, batch_size=16)
    dataloader = accelerator.prepare(dataloader)
    pbar = tqdm(dataloader, total=100)
    for x, y in pbar:
        loss = model(x, y, True)
        accelerator.backward(loss)
        optimizer.step()
        optimizer.zero_grad()
        pbar.set_description(f"{loss.item()}")


if __name__ == "__main__":
    main()
```

The script above is a simplified reimplementation of self-conditioning for diffusion models. I launch this script with:

```bash
accelerate launch --multi_gpu debug.py
```
and everything works fine. But when I tried to use mixed precision
```bash
accelerate launch --mixed_precision "bf16" --multi_gpu debug.py
```
I encountered an error:
```
Traceback (most recent call last):
  File "/app/debug.py", line 64, in <module>
    main()
  File "/app/debug.py", line 57, in main
    accelerator.backward(loss)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/accelerator.py", line 1745, in backward
    loss.backward(**kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/opt/conda/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 210) of binary: /opt/conda/bin/python
...
```
on both gpu. 
Interestingly, when I do not use self-conditioning by passing `self_conditioning=False` in the training loop, I have no errors.

### Expected behavior

Example should work both with or without mixed precision.

**Comment by elephantmipt** [comment]
UPD: The bug also persists when using only one GPU.

**Comment by elephantmipt** [comment]
Found explanation here: https://discuss.pytorch.org/t/autocast-and-torch-no-grad-unexpected-behaviour/93475

Still tricky one
