### ISSUE TITLE
"ImportError: Megatron is not installed. please build it from source." when launching accelerate

### ISSUE THREAD

**Issue by Imsovegetable** [huggingface/accelerate#1590]
**System Info**
```
- `Accelerate` version: 0.21.0.dev0
- Platform: Linux-3.10.0-1160.24.1.el7.x86_64-x86_64-with-glibc2.17
- Python version: 3.11.4
- Numpy version: 1.24.3
- PyTorch version (GPU?): 2.0.1 (True)
- PyTorch XPU available: False
- System RAM: 754.38 GB
- GPU type: Tesla V100-SXM2-16GB
- `Accelerate` default config:
        Not found
```
**Information**

- [ ] The official example scripts
- [x] My own modified scripts

**Tasks**

- [x] My own task or dataset (give details below)

**Reproduction**

Hello! I am new here and I followed [the official installation steps](https://huggingface.co/docs/accelerate/main/en/usage_guides/megatron_lm#prerequisites) to build the environment. Besides, I installed `transformers` and `accelerate` using 
```
pip install git+https://github.com/huggingface/transformers
pip install git+https://github.com/huggingface/accelerate
```
Then I am trying to verify whether my environment is correct. So I run the command `accelerate launch --config_file config/megatron_test_config.yaml test/test.py` and unfortunately, got the error `ImportError: Megatron is not installed. please build it from source.` My code is really simple, which looks like this:
```
# test/test.py
from accelerate import Accelerator

accelerator = Accelerator()

print(accelerator.distributed_type)
```
and my configuration file of `accelerate` is almost the same as the official example:
```
# config/megatron_test_config.yaml
compute_environment: LOCAL_MACHINE
distributed_type: MEGATRON_LM
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
megatron_lm_config:
  megatron_lm_gradient_clipping: 1.0
  megatron_lm_pp_degree: 1
  megatron_lm_recompute_activations: true
  megatron_lm_sequence_parallelism: true
  megatron_lm_tp_degree: 2
  megatron_lm_use_distributed_optimizer: true
mixed_precision: bf16
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```
The complete error report is as follows:
```
(ml) [yuhanchen@gpu25 megatron]$ accelerate launch --config_file config/megatron_test_config.yaml test/test.py
Traceback (most recent call last):
  File "/users10/yuhanchen/megatron/test/test.py", line 4, in <module>
    accelerator = Accelerator()
                  ^^^^^^^^^^^^^
  File "/users10/yuhanchen/miniconda3/envs/ml/lib/python3.11/site-packages/accelerate/accelerator.py", line 315, in __init__
    raise ImportError("Megatron is not installed. please build it from source.")
ImportError: Megatron is not installed. please build it from source.
Traceback (most recent call last):
  File "/users10/yuhanchen/megatron/test/test.py", line 4, in <module>
    accelerator = Accelerator()
                  ^^^^^^^^^^^^^
  File "/users10/yuhanchen/miniconda3/envs/ml/lib/python3.11/site-packages/accelerate/accelerator.py", line 315, in __init__
    raise ImportError("Megatron is not installed. please build it from source.")
ImportError: Megatron is not installed. please build it from source.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 51907) of binary: /users10/yuhanchen/miniconda3/envs/ml/bin/python3.11
Traceback (most recent call last):
  File "/users10/yuhanchen/miniconda3/envs/ml/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/users10/yuhanchen/miniconda3/envs/ml/lib/python3.11/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/users10/yuhanchen/miniconda3/envs/ml/lib/python3.11/site-packages/accelerate/commands/launch.py", line 958, in launch_command
    multi_gpu_launcher(args)
  File "/users10/yuhanchen/miniconda3/envs/ml/lib/python3.11/site-packages/accelerate/commands/launch.py", line 649, in multi_gpu_launcher
    distrib_run.run(args)
  File "/users10/yuhanchen/miniconda3/envs/ml/lib/python3.11/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/users10/yuhanchen/miniconda3/envs/ml/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users10/yuhanchen/miniconda3/envs/ml/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
test/test.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-06-14_14:34:33
  host      : gpu25.cluster.com
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 51908)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-06-14_14:34:33
  host      : gpu25.cluster.com
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 51907)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```
I am sure that the megatron has been installed. So I am really confused why it happens and I have tried creating a new environment from scratch and installing all the dependencies several times.  How can I do to solve the problem? I show the information of  `conda list`, `nvcc --version` and `nvidia-smi` below, hope these help. Thanks!

- conda list

```
# packages in environment at /users10/yuhanchen/miniconda3/envs/ml:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
accelerate                0.21.0.dev0              pypi_0    pypi
apex                      0.1                      pypi_0    pypi
binutils_impl_linux-64    2.39                 he00db2b_1    conda-forge
binutils_linux-64         2.39                h5fc0e48_13    conda-forge
blas                      2.116                       mkl    conda-forge
blas-devel                3.9.0            16_linux64_mkl    conda-forge
brotli                    1.0.9                h166bdaf_8    conda-forge
brotli-bin                1.0.9                h166bdaf_8    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2023.5.7             hbcca054_0    conda-forge
certifi                   2023.5.7           pyhd8ed1ab_0    conda-forge
charset-normalizer        3.1.0              pyhd8ed1ab_0    conda-forge
click                     8.1.3                    pypi_0    pypi
cuda-cudart               11.7.99                       0    nvidia
cuda-cupti                11.7.101                      0    nvidia
cuda-libraries            11.7.1                        0    nvidia
cuda-nvrtc                11.7.99                       0    nvidia
cuda-nvtx                 11.7.91                       0    nvidia
cuda-runtime              11.7.1                        0    nvidia
ffmpeg                    4.3                  hf484d3e_0    pytorch
filelock                  3.12.2             pyhd8ed1ab_0    conda-forge
freetype                  2.12.1               hca18f0e_1    conda-forge
fsspec                    2023.6.0                 pypi_0    pypi
gcc_impl_linux-64         10.4.0              h5231bdf_19    conda-forge
gcc_linux-64              10.4.0              h9215b83_13    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
gmpy2                     2.1.2           py311h6a5fa03_1    conda-forge
gnutls                    3.6.13               h85f3911_1    conda-forge
gxx_impl_linux-64         10.4.0              h5231bdf_19    conda-forge
gxx_linux-64              10.4.0              h6e491c6_13    conda-forge
huggingface-hub           0.15.1                   pypi_0    pypi
icu                       72.1                 hcb278e6_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
joblib                    1.2.0                    pypi_0    pypi
jpeg                      9e                   h0b41bf4_3    conda-forge
kernel-headers_linux-64   2.6.32              he073ed8_15    conda-forge
lame                      3.100             h166bdaf_1003    conda-forge
lcms2                     2.15                 hfd0df8a_0    conda-forge
ld_impl_linux-64          2.39                 hcc3a1bd_1    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libblas                   3.9.0            16_linux64_mkl    conda-forge
libbrotlicommon           1.0.9                h166bdaf_8    conda-forge
libbrotlidec              1.0.9                h166bdaf_8    conda-forge
libbrotlienc              1.0.9                h166bdaf_8    conda-forge
libcblas                  3.9.0            16_linux64_mkl    conda-forge
libcublas                 11.10.3.66                    0    nvidia
libcufft                  10.7.2.124           h4fbf590_0    nvidia
libcufile                 1.6.1.9                       0    nvidia
libcurand                 10.3.2.106                    0    nvidia
libcusolver               11.4.0.1                      0    nvidia
libcusparse               11.7.4.91                     0    nvidia
libdeflate                1.17                 h0b41bf4_0    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-devel_linux-64     10.4.0              hd38fd1e_19    conda-forge
libgcc-ng                 13.1.0               he5830b7_0    conda-forge
libgfortran-ng            13.1.0               h69a702a_0    conda-forge
libgfortran5              13.1.0               h15d22d2_0    conda-forge
libgomp                   13.1.0               he5830b7_0    conda-forge
libhwloc                  2.9.1           nocuda_h7313eea_6    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
liblapack                 3.9.0            16_linux64_mkl    conda-forge
liblapacke                3.9.0            16_linux64_mkl    conda-forge
libnpp                    11.7.4.75                     0    nvidia
libnsl                    2.0.0                h7f98852_0    conda-forge
libnvjpeg                 11.8.0.2                      0    nvidia
libpng                    1.6.39               h753d276_0    conda-forge
libsanitizer              10.4.0              h5246dfb_19    conda-forge
libsqlite                 3.42.0               h2797004_0    conda-forge
libstdcxx-devel_linux-64  10.4.0              hd38fd1e_19    conda-forge
libstdcxx-ng              13.1.0               hfd8a6a1_0    conda-forge
libtiff                   4.5.0                h6adf6a1_2    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp-base              1.3.0                h0b41bf4_0    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxml2                   2.11.4               h0d562d8_0    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
llvm-openmp               16.0.5               h4dfa4b3_0    conda-forge
markupsafe                2.1.3           py311h459d7ec_0    conda-forge
megatron-lm               3.0.0                    pypi_0    pypi
mkl                       2022.1.0           h84fe81f_915    conda-forge
mkl-devel                 2022.1.0           ha770c72_916    conda-forge
mkl-include               2022.1.0           h84fe81f_915    conda-forge
mpc                       1.3.1                hfe3b2da_0    conda-forge
mpfr                      4.2.0                hb012696_0    conda-forge
mpmath                    1.3.0              pyhd8ed1ab_0    conda-forge
ncurses                   6.4                  hcb278e6_0    conda-forge
nettle                    3.6                  he412f7d_0    conda-forge
networkx                  3.1                pyhd8ed1ab_0    conda-forge
nltk                      3.8.1                    pypi_0    pypi
numpy                     1.24.3          py311h64a7726_0    conda-forge
openh264                  2.1.1                h780b84a_0    conda-forge
openjpeg                  2.5.0                hfec8fc6_2    conda-forge
openssl                   3.1.1                hd590300_1    conda-forge
packaging                 23.1               pyhd8ed1ab_0    conda-forge
pillow                    9.4.0           py311h50def17_1    conda-forge
pip                       23.1.2             pyhd8ed1ab_0    conda-forge
psutil                    5.9.5                    pypi_0    pypi
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pybind11                  2.10.4                   pypi_0    pypi
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.11.4          hab00c5b_0_cpython    conda-forge
python_abi                3.11                    3_cp311    conda-forge
pytorch                   2.0.1           py3.11_cuda11.7_cudnn8.5.0_0    pytorch
pytorch-cuda              11.7                 h778d358_5    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pyyaml                    6.0                      pypi_0    pypi
readline                  8.2                  h8228510_1    conda-forge
regex                     2023.6.3                 pypi_0    pypi
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
safetensors               0.3.1                    pypi_0    pypi
setuptools                67.7.2             pyhd8ed1ab_0    conda-forge
six                       1.16.0                   pypi_0    pypi
sympy                     1.12            pypyh9d50eac_103    conda-forge
sysroot_linux-64          2.12                he073ed8_15    conda-forge
tbb                       2021.9.0             hf52228f_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tokenizers                0.13.3                   pypi_0    pypi
torchaudio                2.0.2               py311_cu117    pytorch
torchtriton               2.0.0                     py311    pytorch
torchvision               0.15.2              py311_cu117    pytorch
tqdm                      4.65.0                   pypi_0    pypi
transformers              4.31.0.dev0              pypi_0    pypi
typing_extensions         4.6.3              pyha770c72_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
urllib3                   2.0.3              pyhd8ed1ab_0    conda-forge
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zlib                      1.2.13               hd590300_5    conda-forge
zstd                      1.5.2                h3eb15da_6    conda-forge
```

- nvcc --version

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_May__3_18:49:52_PDT_2022
Cuda compilation tools, release 11.7, V11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0
```

- nvidia-smi

```
Wed Jun 14 15:17:12 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla V100-SXM2-16GB            Off| 00000000:B1:00.0 Off |                    0 |
| N/A   42C    P0               58W / 300W|      0MiB / 16384MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2-16GB            Off| 00000000:B2:00.0 Off |                    0 |
| N/A   42C    P0               57W / 300W|      0MiB / 16384MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```

**Comment by sgugger** [comment]
cc @pacman100

**Comment by muellerzr** [comment]
Hi @Imsovegetable, try installing from main via `pip install git+https://github.com/huggingface/accelerate`, #1636 may have fixed this!
