### ISSUE TITLE
example/cv_example.py fp8 error

### ISSUE THREAD

**Issue by ehion** [huggingface/accelerate#1604]
### System Info

```Shell
Hopper GPU
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

RuntimeError: Tensors must be CUDA and dense

### Expected behavior

RuntimeError: Tensors must be CUDA and dense

**Comment by ehion** [comment]
Traceback (most recent call last):
  File "./cv_example.py", line 198, in <module>
    main()
  File "./cv_example.py", line 194, in main
    training_function(config, args)
  File "./cv_example.py", line 161, in training_function
    outputs = model(inputs).to(accelerator.device)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1533, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/distributed.py", line 1129, in forward
    self._sync_buffers()
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/distributed.py", line 1727, in _sync_buffers
    self._sync_module_buffers(authoritative_rank)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/distributed.py", line 1731, in _sync_module_buffers
    self._default_broadcast_coalesced(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/distributed.py", line 1754, in _default_broadcast_coalesced
    self._distributed_broadcast_coalesced(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/distributed.py", line 1668, in _distributed_broadcast_coalesced
    dist._broadcast_coalesced(
RuntimeError: Tensors must be CUDA and dense
