### ISSUE TITLE
Model breaks with new update

### ISSUE THREAD

**Issue by ElleLeonne** [huggingface/accelerate#1611]
### System Info

So I have a model that receives a list of strings as part of its operation. Sometimes the list is empty, sometimes it has data, and so the model is responsible for handling which layers this information gets distributed to.

As of this most recent update, I'm now getting an error:

```
Traceback (most recent call last):
  File "/home/lily/Desktop/Project/finetune_dynamic.py", line 304, in <module>
    fire.Fire(train)
  File "/home/lily/anaconda3/envs/emme/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/lily/anaconda3/envs/emme/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/lily/anaconda3/envs/emme/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/lily/Desktop/Emme (copy)/finetune_dynamic.py", line 295, in train
    trainer.train(resume_from_checkpoint=resume_from_checkpoint)
  File "/home/lily/anaconda3/envs/emme/lib/python3.10/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/home/lily/anaconda3/envs/emme/lib/python3.10/site-packages/transformers/trainer.py", line 1779, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "/home/lily/anaconda3/envs/emme/lib/python3.10/site-packages/accelerate/data_loader.py", line 553, in __iter__
    next_batch, next_batch_info = self._fetch_batches(main_iterator)
  File "/home/lily/anaconda3/envs/emme/lib/python3.10/site-packages/accelerate/data_loader.py", line 521, in _fetch_batches
    batch = concatenate(batches, dim=0)
  File "/home/lily/anaconda3/envs/emme/lib/python3.10/site-packages/accelerate/utils/operations.py", line 413, in concatenate
    return type(data[0])({k: concatenate([d[k] for d in data], dim=dim) for k in data[0].keys()})
  File "/home/lily/anaconda3/envs/emme/lib/python3.10/site-packages/accelerate/utils/operations.py", line 413, in <dictcomp>
    return type(data[0])({k: concatenate([d[k] for d in data], dim=dim) for k in data[0].keys()})
  File "/home/lily/anaconda3/envs/emme/lib/python3.10/site-packages/accelerate/utils/operations.py", line 411, in concatenate
    return honor_type(data[0], (concatenate([d[i] for d in data], dim=dim) for i in range(len(data[0]))))
  File "/home/lily/anaconda3/envs/emme/lib/python3.10/site-packages/accelerate/utils/operations.py", line 84, in honor_type
    return type(obj)(generator)
  File "/home/lily/anaconda3/envs/emme/lib/python3.10/site-packages/accelerate/utils/operations.py", line 411, in <genexpr>
    return honor_type(data[0], (concatenate([d[i] for d in data], dim=dim) for i in range(len(data[0]))))
  File "/home/lily/anaconda3/envs/emme/lib/python3.10/site-packages/accelerate/utils/operations.py", line 411, in concatenate
    return honor_type(data[0], (concatenate([d[i] for d in data], dim=dim) for i in range(len(data[0]))))
  File "/home/lily/anaconda3/envs/emme/lib/python3.10/site-packages/accelerate/utils/operations.py", line 84, in honor_type
    return type(obj)(generator)
  File "/home/lily/anaconda3/envs/emme/lib/python3.10/site-packages/accelerate/utils/operations.py", line 411, in <genexpr>
    return honor_type(data[0], (concatenate([d[i] for d in data], dim=dim) for i in range(len(data[0]))))
  File "/home/lily/anaconda3/envs/emme/lib/python3.10/site-packages/accelerate/utils/operations.py", line 415, in concatenate
    raise TypeError(f"Can only concatenate tensors but got {type(data[0])}")
TypeError: Can only concatenate tensors but got <class 'str'>
```

It appears accelerate is attempting to concatenate every single key in my input dictionary, regardless of what data type it is, and is then throwing a fit when it discovers that the data type isn't a list of tensors.

My question is whether or not there is a way to turn this functionality off or not. Accelerate doesn't need to handle my preprocessing, but I'm not even importing accelerate in my code, so I think this is something Huggingface is forcing on me.

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

To reproduce:

1. Create a model that takes a list of non-tensor inputs
2. Run a basic training shell, passing the non-tensor inputs as a key in the input dictionary

### Expected behavior

Accelerate should skip over the key that it can't process, rather than preventing the program from functioning.

**Comment by sgugger** [comment]
Can you give us a code reproducer please?

**Comment by ElleLeonne** [comment]
Sure, out of town today, but I should be able to mock something up shortly.

**Comment by PurvangL** [comment]
@sgugger I am also facing similar issue.
below I have provided reproducer.

```
>>> from datasets import load_dataset
>>> from torch.utils.data import DataLoader
>>> train_dataset = load_dataset("transformersbook/codeparrot-train", streaming=True)
Repo card metadata block was not found. Setting CardData to empty.
Resolving data files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 183/183 [00:00<00:00, 973.81it/s]
>>> eval_dataset = load_dataset("transformersbook/codeparrot-valid", streaming=True)
Repo card metadata block was not found. Setting CardData to empty.
>>> 
>>> train_dataloader = DataLoader(train_dataset['train'], batch_size=64)
>>> eval_dataloader = DataLoader(eval_dataset['validation'], batch_size=64)
>>> 
>>> from accelerate import Accelerator
>>> accelerator = Accelerator()
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
>>> train_dataloader, eval_dataloader = accelerator.prepare(train_dataloader, eval_dataloader)
>>> ti = iter(train_dataloader)
>>> next(ti)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/accelerate/data_loader.py", line 642, in __iter__
    next_batch, next_batch_info = self._fetch_batches(main_iterator)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/data_loader.py", line 605, in _fetch_batches
    batch = concatenate(batches, dim=0)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/utils/operations.py", line 519, in concatenate
    return type(data[0])({k: concatenate([d[k] for d in data], dim=dim) for k in data[0].keys()})
  File "/usr/local/lib/python3.8/dist-packages/accelerate/utils/operations.py", line 519, in <dictcomp>
    return type(data[0])({k: concatenate([d[k] for d in data], dim=dim) for k in data[0].keys()})
  File "/usr/local/lib/python3.8/dist-packages/accelerate/utils/operations.py", line 517, in concatenate
    return honor_type(data[0], (concatenate([d[i] for d in data], dim=dim) for i in range(len(data[0]))))
  File "/usr/local/lib/python3.8/dist-packages/accelerate/utils/operations.py", line 83, in honor_type
    return type(obj)(generator)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/utils/operations.py", line 517, in <genexpr>
    return honor_type(data[0], (concatenate([d[i] for d in data], dim=dim) for i in range(len(data[0]))))
  File "/usr/local/lib/python3.8/dist-packages/accelerate/utils/operations.py", line 521, in concatenate
    raise TypeError(f"Can only concatenate tensors but got {type(data[0])}")
TypeError: Can only concatenate tensors but got <class 'str'>

```

**Comment by YotamNitzan** [comment]
Also experiencing this issue

**Comment by muellerzr** [comment]
Again we can't do much without code here. Please provide us some details of how you are making your dataset and what your snippet of code looks like relative to making your dataloader. My best guess is are you tokenizing your dataset to turn it into tensors?

**Comment by PurvangL** [comment]
@muellerzr  mentioned [code snippet](https://github.com/huggingface/accelerate/issues/1611#issuecomment-1815433798) won't work to reproduce? it's standalone code to load dataset and describing error.

**Comment by muellerzr** [comment]
@PurvangL you need to tokenize the dataset and convert it to tensors. This is the issue

**Comment by irowberryFS** [comment]
I'm getting this error as well. I'm working with PyTorch Geometric Data objects, which are fed directly into a PyG Graph network. Is there anyway to bypass this behavior?
