### ISSUE TITLE
UnboundLocalError: local variable 'offload_index' referenced before assignment

### ISSUE THREAD

**Issue by MaggieK410** [huggingface/accelerate#1665]
Hello!
I am trying to load ClinT5 for finetuning but am getting this error, when loading it with device_map="auto":
UnboundLocalError: local variable 'offload_index' referenced before assignment. Additionally, when trying to simply import accelerate I get this error: ModuleNotFoundError: No module named 'transformers.modeling_outputs'
So I guess there is some compability issue with transformers and accelerate?

Accelerate Version: 0.20.3
Transformers Version: 4.31.0.dev0 (after having it installed from source, but prior to this, it was installed via pip install transformers, the error remains the same)

What versions do I need to have, to get device_map="auto" to work ? I would really appreciate any help!

**Comment by MaggieK410** [comment]
Sure! Here is the Stack Trace:

Traceback (most recent call last):
  File "/home/students/kulcsar/Bachelor/for_dataset/10000_diagnoses/t5_model.py", line 351, in <module>
    run()
  File "/home/students/kulcsar/Bachelor/for_dataset/10000_diagnoses/t5_model.py", line 42, in run
    model=T5ForConditionalGeneration.from_pretrained(args.model, from_flax=args.ff, device_map="auto")
  File "/home/students/kulcsar/anaconda3/envs/software_bubble_updated_accelerate/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2934, in from_pretrained
    kwargs = {"device_map": device_map, "offload_dir": offload_folder, "offload_index": offload_index}
UnboundLocalError: local variable 'offload_index' referenced before assignment



The function where the error is occuring is this:

 def run():
      logging.basicConfig(filename=args.log, level=logging.DEBUG)
      logging.info("Starting Training")
      print("Started Training")
      model=T5ForConditionalGeneration.from_pretrained(args.model, from_flax=args.ff, device_map="auto")
 
 My conda env:
 _libgcc_mutex             0.1                        main
_openmp_mutex             5.1                       1_gnu
abseil-cpp                20211102.0           hd4dd3e8_0
absl-py                   1.4.0              pyhd8ed1ab_0    conda-forge
accelerate                0.21.0.dev0              pypi_0    pypi
aiohttp                   3.8.3            py39h5eee18b_0
aiosignal                 1.3.1                    pypi_0    pypi
antlr-python-runtime      4.9.3              pyhd8ed1ab_1    conda-forge
appdirs                   1.4.4              pyhd3eb1b0_0
arrow                     1.2.3            py39h06a4308_1
arrow-cpp                 11.0.0           py39h613000e_0
async-timeout             4.0.2            py39h06a4308_0
attrs                     22.1.0           py39h06a4308_0
aws-c-common              0.4.57               he6710b0_1
aws-c-event-stream        0.1.6                h2531618_5
aws-checksums             0.1.9                he6710b0_0
aws-sdk-cpp               1.8.185              hce553d0_0
beautifulsoup4            4.12.2                   pypi_0    pypi
binaryornot               0.4.4              pyhd3eb1b0_1
bitarray                  2.7.3                    pypi_0    pypi
bitsandbytes              0.39.1                   pypi_0    pypi
blas                      1.0                         mkl
boost-cpp                 1.73.0              h7f8727e_12
boto3                     1.26.68                  pypi_0    pypi
botocore                  1.29.68                  pypi_0    pypi
bottleneck                1.3.5            py39h7deecbd_0
brotlipy                  0.7.0           py39h27cfd23_1003
bs4                       0.0.1                    pypi_0    pypi
bzip2                     1.0.8                h7b6447c_0
c-ares                    1.19.0               h5eee18b_0
ca-certificates           2023.5.7             hbcca054_0    conda-forge
certifi                   2023.5.7           pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py39h74dc2b5_0
chardet                   4.0.0           py39h06a4308_1003
charset-normalizer        2.0.4              pyhd3eb1b0_0
chex                      0.1.7              pyhd8ed1ab_0    conda-forge
click                     8.0.4            py39h06a4308_0
colorama                  0.4.6                    pypi_0    pypi
contourpy                 1.0.6                    pypi_0    pypi
cookiecutter              1.7.3              pyhd3eb1b0_0
cryptography              39.0.1           py39h9ce1e76_1
cuda                      11.7.1                        0    nvidia
cuda-cccl                 11.7.91                       0    nvidia
cuda-command-line-tools   11.7.1                        0    nvidia
cuda-compiler             11.7.1                        0    nvidia
cuda-cudart               11.7.99                       0    nvidia
cuda-cudart-dev           11.7.99                       0    nvidia
cuda-cuobjdump            11.7.91                       0    nvidia
cuda-cupti                11.7.101                      0    nvidia
cuda-cuxxfilt             11.7.91                       0    nvidia
cuda-demo-suite           11.8.86                       0    nvidia
cuda-documentation        11.8.86                       0    nvidia
cuda-driver-dev           11.7.99                       0    nvidia
cuda-gdb                  11.8.86                       0    nvidia
cuda-libraries            11.7.1                        0    nvidia
cuda-libraries-dev        11.7.1                        0    nvidia
cuda-memcheck             11.8.86                       0    nvidia
cuda-nsight               11.8.86                       0    nvidia
cuda-nsight-compute       11.8.0                        0    nvidia
cuda-nvcc                 11.7.99                       0    nvidia
cuda-nvdisasm             11.8.86                       0    nvidia
cuda-nvml-dev             11.7.91                       0    nvidia
cuda-nvprof               11.8.87                       0    nvidia
cuda-nvprune              11.7.91                       0    nvidia
cuda-nvrtc                11.7.99                       0    nvidia
cuda-nvrtc-dev            11.7.99                       0    nvidia
cuda-nvtx                 11.7.91                       0    nvidia
cuda-nvvp                 11.8.87                       0    nvidia
cuda-runtime              11.7.1                        0    nvidia
cuda-sanitizer-api        11.8.86                       0    nvidia
cuda-toolkit              11.7.1                        0    nvidia
cuda-tools                11.7.1                        0    nvidia
cuda-visual-tools         11.7.1                        0    nvidia
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
dataclasses               0.8                pyh6d0b6a4_7
datasets                  2.12.0           py39h06a4308_0
deepspeed                 0.9.4                    pypi_0    pypi
dill                      0.3.5.1                  pypi_0    pypi
dm-tree                   0.1.7            py39h1832856_0    conda-forge
einops                    0.6.1                    pypi_0    pypi
evaluate                  0.3.0            py39h06a4308_0
ffmpeg                    4.2.2                h20bf706_0
filelock                  3.9.0            py39h06a4308_0
flax                      0.6.1              pyhd8ed1ab_1    conda-forge
fonttools                 4.38.0                   pypi_0    pypi
freetype                  2.12.1               h4a9f257_0
frozenlist                1.3.3            py39h5eee18b_0
fsspec                    2023.4.0         py39h06a4308_0
gds-tools                 1.4.0.31                      0    nvidia
gflags                    2.2.2                he6710b0_0
giflib                    5.2.1                h5eee18b_3
glog                      0.5.0                h2531618_0
gmp                       6.2.1                h295c915_3
gnutls                    3.6.15               he1e5248_0
grpc-cpp                  1.46.1               h33aed49_1
hjson                     3.1.0                    pypi_0    pypi
huggingface               0.0.1                    pypi_0    pypi
huggingface_hub           0.14.1           py39h06a4308_0
hydra-core                1.3.1              pyhd8ed1ab_0    conda-forge
icd9cms                   0.2.1                    pypi_0    pypi
icu                       58.2                 he6710b0_3
idna                      3.4              py39h06a4308_0
importlib-metadata        6.0.0            py39h06a4308_0
importlib_metadata        6.0.0                hd3eb1b0_0
importlib_resources       5.2.0              pyhd3eb1b0_1
intel-openmp              2021.4.0          h06a4308_3561
jax                       0.3.25             pyhd8ed1ab_0    conda-forge
jaxlib                    0.3.25           py39h6a678d5_1
jinja2                    3.1.2            py39h06a4308_0
jinja2-time               0.2.0              pyhd3eb1b0_3
jmespath                  1.0.1                    pypi_0    pypi
joblib                    1.2.0            py39h06a4308_0
jpeg                      9e                   h5eee18b_1
kiwisolver                1.4.4            py39h6a678d5_0
krb5                      1.19.4               h568e23c_0
lame                      3.100                h7b6447c_0
lcms2                     2.12                 h3be6417_0
ld_impl_linux-64          2.38                 h1181459_1
lerc                      3.0                  h295c915_0
libboost                  1.73.0              h28710b8_12
libbrotlicommon           1.0.9                h5eee18b_7
libbrotlidec              1.0.9                h5eee18b_7
libbrotlienc              1.0.9                h5eee18b_7
libcublas                 11.11.3.6                     0    nvidia
libcublas-dev             11.11.3.6                     0    nvidia
libcufft                  10.9.0.58                     0    nvidia
libcufft-dev              10.9.0.58                     0    nvidia
libcufile                 1.4.0.31                      0    nvidia
libcufile-dev             1.4.0.31                      0    nvidia
libcurand                 10.3.0.86                     0    nvidia
libcurand-dev             10.3.0.86                     0    nvidia
libcurl                   7.88.1               h91b91d3_0
libcusolver               11.4.1.48                     0    nvidia
libcusolver-dev           11.4.1.48                     0    nvidia
libcusparse               11.7.5.86                     0    nvidia
libcusparse-dev           11.7.5.86                     0    nvidia
libdeflate                1.17                 h5eee18b_0
libedit                   3.1.20221030         h5eee18b_0
libev                     4.33                 h7f8727e_1
libevent                  2.1.12               h8f2d780_0
libffi                    3.3                  he6710b0_2
libgcc-ng                 11.2.0               h1234567_1
libgfortran-ng            11.2.0               h00389a5_1
libgfortran5              11.2.0               h1234567_1
libgomp                   11.2.0               h1234567_1
libidn2                   2.3.4                h5eee18b_0
libnghttp2                1.46.0               hce63b2e_0
libnpp                    11.8.0.86                     0    nvidia
libnpp-dev                11.8.0.86                     0    nvidia
libnvjpeg                 11.9.0.86                     0    nvidia
libnvjpeg-dev             11.9.0.86                     0    nvidia
libopus                   1.3.1                h7b6447c_0
libpng                    1.6.39               h5eee18b_0
libprotobuf               3.20.3               he621ea3_0
libssh2                   1.10.0               h8f2d780_0
libstdcxx-ng              11.2.0               h1234567_1
libtasn1                  4.19.0               h5eee18b_0
libthrift                 0.15.0               hcc01f38_0
libtiff                   4.5.0                h6a678d5_2
libunistring              0.9.10               h27cfd23_0
libvpx                    1.7.0                h439df22_0
libwebp                   1.2.4                h11a3e52_1
libwebp-base              1.2.4                h5eee18b_1
lxml                      4.9.2                    pypi_0    pypi
lz4-c                     1.9.4                h6a678d5_0
markdown-it-py            2.2.0              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.1            py39h7f8727e_0
matplotlib                3.6.2                    pypi_0    pypi
matplotlib-base           3.4.3            py39h2fa2bec_2    conda-forge
mdurl                     0.1.0              pyhd8ed1ab_0    conda-forge
mkl                       2021.4.0           h06a4308_640
mkl-service               2.4.0            py39h7f8727e_0
mkl_fft                   1.3.1            py39hd3c417c_0
mkl_random                1.2.2            py39h51133e4_0
msgpack-python            1.0.3            py39hd09550d_0
multidict                 6.0.2            py39h5eee18b_0
multiprocess              0.70.13                  pypi_0    pypi
ncurses                   6.4                  h6a678d5_0
nettle                    3.7.3                hbbd107a_1
ninja                     1.11.1                   pypi_0    pypi
ninja-base                1.10.2               hd09550d_5
nsight-compute            2022.3.0.22                   0    nvidia
numexpr                   2.8.4            py39he184ba9_0
numpy                     1.24.3           py39h14f4228_0
numpy-base                1.24.3           py39h31eccc5_0
omegaconf                 2.3.0              pyhd8ed1ab_0    conda-forge
openh264                  2.1.1                h4ff587b_0
openssl                   1.1.1u               h7f8727e_0
opt_einsum                3.3.0              pyhd8ed1ab_1    conda-forge
optax                     0.1.5              pyhd8ed1ab_0    conda-forge
orc                       1.7.4                hb3bc3d3_1
packaging                 23.0             py39h06a4308_0
pandas                    1.5.1                    pypi_0    pypi
peft                      0.4.0.dev0               pypi_0    pypi
pillow                    9.4.0            py39h6a678d5_0
pip                       23.0.1           py39h06a4308_0
pooch                     1.4.0              pyhd3eb1b0_0
portalocker               2.7.0                    pypi_0    pypi
poyo                      0.5.0              pyhd3eb1b0_0
protobuf                  3.20.3           py39h6a678d5_0
psutil                    5.9.5                    pypi_0    pypi
py-cpuinfo                9.0.0                    pypi_0    pypi
pyarrow                   10.0.0                   pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0
pydantic                  1.10.9                   pypi_0    pypi
pygments                  2.15.1             pyhd8ed1ab_0    conda-forge
pyopenssl                 23.0.0           py39h06a4308_0
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1            py39h06a4308_0
python                    3.9.0                hdb3f193_2
python-dateutil           2.8.2              pyhd3eb1b0_0
python-slugify            5.0.2              pyhd3eb1b0_0
python-xxhash             2.0.2            py39h5eee18b_1
python_abi                3.9                      2_cp39    conda-forge
pytorch                   1.13.0          py3.9_cuda11.7_cudnn8.5.0_0    pytorch
pytorch-cuda              11.7                 h67b0de4_0    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2022.6                   pypi_0    pypi
pyyaml                    6.0              py39h5eee18b_1
re2                       2022.04.01           h295c915_0
readline                  8.2                  h5eee18b_0
regex                     2022.7.9         py39h5eee18b_0
requests                  2.29.0           py39h06a4308_0
responses                 0.18.0                   pypi_0    pypi
rich                      13.4.1             pyhd8ed1ab_0    conda-forge
s3transfer                0.6.0                    pypi_0    pypi
sacrebleu                 2.3.1                    pypi_0    pypi
sacremoses                0.0.43             pyhd3eb1b0_0
safetensors               0.3.1                    pypi_0    pypi
scikit-learn              1.1.1            py39h6a678d5_0    anaconda
scipy                     1.10.1           py39h14f4228_0
sentencepiece             0.1.97                   pypi_0    pypi
setuptools                67.8.0           py39h06a4308_0
six                       1.16.0             pyhd3eb1b0_1
snappy                    1.1.9                h295c915_0
soupsieve                 2.4.1                    pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0
tabulate                  0.9.0                    pypi_0    pypi
text-unidecode            1.3                pyhd3eb1b0_0
threadpoolctl             2.2.0              pyh0d69192_0
tk                        8.6.12               h1ccaba5_0
tokenizers                0.13.3                   pypi_0    pypi
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
torchaudio                0.13.0               py39_cu117    pytorch
torchvision               0.14.0               py39_cu117    pytorch
tornado                   6.1              py39hb9d737c_3    conda-forge
tqdm                      4.65.0           py39hb070fc8_0
transformers              4.30.2                   pypi_0    pypi
trl                       0.4.6                    pypi_0    pypi
typing-extensions         4.5.0            py39h06a4308_0
typing_extensions         4.5.0            py39h06a4308_0
tzdata                    2023c                h04d1e81_0
unicode                   2.9                      pypi_0    pypi
unidecode                 1.2.0              pyhd3eb1b0_0
urllib3                   1.26.16          py39h06a4308_0
utf8proc                  2.6.1                h27cfd23_0
wheel                     0.38.4           py39h06a4308_0
x264                      1!157.20191217       h7b6447c_0
xxhash                    3.1.0                    pypi_0    pypi
xz                        5.4.2                h5eee18b_0
yaml                      0.2.5                h7b6447c_0
yarl                      1.8.1            py39h5eee18b_0
zipp                      3.11.0           py39h06a4308_0
zlib                      1.2.13               h5eee18b_0
zstd                      1.5.5                hc292b87_0

Does this help?
(PS: I have now downgraded the transformers version back to the latest stable version using pip install transformers, since T5ForConditionalGeneration could not be importet with the version transformers version installed from source)
