### ISSUE TITLE
Issue with FSDP and LLaMA models: AssertionError: Expects `BACKWARD_PRE` or `BACKWARD_POST` state but got HandleTrainingState.FORWARD

### ISSUE THREAD

**Issue by Joshuaclymer** [huggingface/accelerate#1675]
### System Info

```Shell
- `Accelerate` version: 0.21.0.dev0
- Platform: Linux-5.4.0-150-generic-x86_64-with-glibc2.31
- Python version: 3.10.10
- Numpy version: 1.24.3
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- PyTorch XPU available: False
- System RAM: 503.71 GB
- GPU type: NVIDIA A100 80GB PCIe
- `Accelerate` default config:
        Not found
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

Download either of the following models from huggingface:
- https://huggingface.co/decapoda-research/llama-7b-hf
- https://huggingface.co/huggyllama/llama-7b

Train the model using hugging face trainer and the following arguments:

```
default_training_args = {
    "seed": api.util.RANDOM_SEED,
    "auto_find_batch_size": True,
    "bf16": True,
    "num_train_epochs": 3,
    "gradient_accumulation_steps": 8,
    "evaluation_strategy": "no",
    "do_eval": False,
    "save_strategy": "steps",
    "save_steps": 2000,
    "save_total_limit": 1,
    "learning_rate": 2e-5,
    "weight_decay": 0.0,
    "warmup_ratio": 0.03,
    "optim": "adamw_torch",
    "lr_scheduler_type": "cosine",
    "fsdp": "full_shard auto_wrap",
    "remove_unused_columns": False,
    "logging_steps": 1,
    "tf32": True,
}
```

Run the python file with `accelerate launch` and specify the model as llama-7b (or the name of the llama model downloaded).

The full stack trace is as follows:
```
Traceback (most recent call last):
  File "/workspace/instruct-generalize/experiments/../api/train.py", line 256, in <module>
    train(**args_dict)
  File "/workspace/instruct-generalize/experiments/../api/train.py", line 164, in train
    trainer.train()
  File "/workspace/lib/python3.10/site-packages/transformers/trainer.py", line 1531, in train
    return inner_training_loop(
  File "/workspace/lib/python3.10/site-packages/accelerate/utils/memory.py", line 132, in decorator
    return function(batch_size, *args, **kwargs)
  File "/workspace/lib/python3.10/site-packages/transformers/trainer.py", line 1795, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/workspace/lib/python3.10/site-packages/transformers/trainer.py", line 2651, in training_step
    self.accelerator.backward(loss)
  File "/workspace/lib/python3.10/site-packages/accelerate/accelerator.py", line 1841, in backward
    loss.backward(**kwargs)
  File "/workspace/lib/python3.10/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/workspace/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/workspace/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/lib/python3.10/site-packages/torch/distributed/fsdp/_runtime_utils.py", line 678, in _post_backward_hook
    p_assert(
  File "/workspace/lib/python3.10/site-packages/torch/distributed/fsdp/_utils.py", line 118, in p_assert
    raise AssertionError(s)
AssertionError: Expects `BACKWARD_PRE` or `BACKWARD_POST` state but got HandleTrainingState.FORWARD
```

**Ablations**
- I've tried multiple datasets. I think this is probably not dataset dependent.
- The issue does not occur for gpt2 or for facebook/opt-2.7b.
- I've also tried specifying the layer to wrap with "fsdp": "full_shard" and "fsdp_transformer_layer_cls_to_wrap": 'LlamaDecoderLayer' and got the same result.

### Expected behavior

Training should complete successfully.

**Comment by Joshuaclymer** [comment]
Can't reproduce the issue when using https://github.com/tatsu-lab/stanford_alpaca.
It's reasonably likely then that this is an issue with my own code or environment.
