### ISSUE TITLE
AttributeErrorAttributeError: module 'torch._C' has no attribute '_cuda_setDevice': module 'torch._C' has no attribute '_cuda_setDevice'

### ISSUE THREAD

**Issue by ArtificialZeng** [huggingface/accelerate#1686]
### System Info

```Shell
File "D:\ai_zeng\ChatGLM-Efficient-Tuning\src\train_sft.py", line 28, in main
model_args, data_args, training_args, finetuning_args = prepare_args(stage="sft")
model_args, data_args, training_args, finetuning_args = prepare_args(stage="sft") File "D:\ai_zeng\ChatGLM-Efficient-Tuning\src\utils\common.py", line 295, in prepare_args

  File "D:\ai_zeng\ChatGLM-Efficient-Tuning\src\utils\common.py", line 295, in prepare_args
model_args, data_args, training_args, finetuning_args = parser.parse_args_into_dataclasses()
File "D:\ProgramData\anaconda3\envs\py10\lib\site-packages\transformers\hf_argparser.py", line 346, in parse_args_into_dataclasses
model_args, data_args, training_args, finetuning_args = parser.parse_args_into_dataclasses()
obj = dtype(**inputs) File "D:\ProgramData\anaconda3\envs\py10\lib\site-packages\transformers\hf_argparser.py", line 346, in parse_args_into_dataclasses

  File "<string>", line 116, in __init__
obj = dtype(**inputs)
File "", line 116, in init
File "D:\ProgramData\anaconda3\envs\py10\lib\site-packages\transformers\training_args.py", line 1340, in post_init File "D:\ProgramData\anaconda3\envs\py10\lib\site-packages\transformers\training_args.py", line 1340, in post_init and (self.device.type != "cuda")and (self.device.type != "cuda")

File "D:\ProgramData\anaconda3\envs\py10\lib\site-packages\transformers\training_args.py", line 1764, in device
File "D:\ProgramData\anaconda3\envs\py10\lib\site-packages\transformers\training_args.py", line 1764, in device
return self._setup_devices
return self._setup_devices File "D:\ProgramData\anaconda3\envs\py10\lib\site-packages\transformers\utils\generic.py", line 54, in get

  File "D:\ProgramData\anaconda3\envs\py10\lib\site-packages\transformers\utils\generic.py", line 54, in __get__
cached = self.fget(obj) cached = self.fget(obj)

File "D:\ProgramData\anaconda3\envs\py10\lib\site-packages\transformers\training_args.py", line 1695, in _setup_devices
File "D:\ProgramData\anaconda3\envs\py10\lib\site-packages\transformers\training_args.py", line 1695, in _setup_devices
self.distributed_state = PartialState(backend=self.ddp_backend)self.distributed_state = PartialState(backend=self.ddp_backend)

File "D:\ProgramData\anaconda3\envs\py10\lib\site-packages\accelerate\state.py", line 197, in init
File "D:\ProgramData\anaconda3\envs\py10\lib\site-packages\accelerate\state.py", line 197, in init
torch.cuda.set_device(self.device)torch.cuda.set_device(self.device)

File "D:\ProgramData\anaconda3\envs\py10\lib\site-packages\torch\cuda_init_.py", line 350, in set_device
File "D:\ProgramData\anaconda3\envs\py10\lib\site-packages\torch\cuda_init_.py", line 350, in set_device
torch._C._cuda_setDevice(device)torch._C._cuda_setDevice(device)

AttributeErrorAttributeError: module 'torch._C' has no attribute '_cuda_setDevice': module 'torch._C' has no attribute '_cuda_setDevice'

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 26208) of binary: D:\ProgramData\anaconda3\envs\py10\python.exe
Traceback (most recent call last):
File "D:\ProgramData\anaconda3\envs\py10\lib\runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "D:\ProgramData\anaconda3\envs\py10\lib\runpy.py", line 86, in run_code
exec(code, run_globals)
File "D:\ProgramData\anaconda3\envs\py10\Scripts\accelerate.exe_main.py", line 7, in
File "D:\ProgramData\anaconda3\envs\py10\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
args.func(args)
File "D:\ProgramData\anaconda3\envs\py10\lib\site-packages\accelerate\commands\launch.py", line 928, in launch_command multi_gpu_launcher(args)
File "D:\ProgramData\anaconda3\envs\py10\lib\site-packages\accelerate\commands\launch.py", line 627, in multi_gpu_launcher
distrib_run.run(args)
File "D:\ProgramData\anaconda3\envs\py10\lib\site-packages\torch\distributed\run.py", line 785, in run
elastic_launch(
File "D:\ProgramData\anaconda3\envs\py10\lib\site-packages\torch\distributed\launcher\api.py", line 134, in call
return launch_agent(self._config, self._entrypoint, list(args))
File "D:\ProgramData\anaconda3\envs\py10\lib\site-packages\torch\distributed\launcher\api.py", line 250, in launch_agent
raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
src/train_sft.py FAILED
Failures:
[1]:
time : 2023-07-03_23:45:01
host : XTZJ-20210729YS
rank : 1 (local_rank: 1)
exitcode : 1 (pid: 26228)
error_file: <N/A>
traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
Root Cause (first observed failure):
[0]:
time : 2023-07-03_23:45:01
host : XTZJ-20210729YS
rank : 0 (local_rank: 0)
exitcode : 1 (pid: 26208)
error_file: <N/A>
traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

is accelerate only spport distributed traing on NVlink?

### Expected behavior

start training

**Comment by muellerzr** [comment]
You haven't installed pytorch with a GPU-build, you've installed the CPU wheels. Please reinstall pytorch with the right wheels. (One way is to use `light-the-torch`, via `pip install light-the-torch; ltt install torch`) https://github.com/pytorch/pytorch/issues/33655
