### ISSUE TITLE
load_checkpoint_and_dispatch gets OOM on Tesla P4

### ISSUE THREAD

**Issue by DannyP0** [huggingface/accelerate#1750]
### System Info

```Shell
- `Accelerate` version: 0.21.0
- Platform: Linux-5.15.0-76-generic-x86_64-with-glibc2.29
- Python version: 3.8.10
- Numpy version: 1.24.4
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 31.26 GB
- GPU type: Tesla P4
- `Accelerate` default config:
        Not found
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

run: python test.py
```
import torch
from transformers import AutoTokenizer, AutoModel, AutoConfig
from accelerate import init_empty_weights, load_checkpoint_and_dispatch, infer_auto_device_map

tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True)
config = AutoConfig.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True)

with init_empty_weights():
    model = AutoModel.from_config(config, trust_remote_code=True)

_device_map = infer_auto_device_map(model, max_memory={0: "4GiB", "cpu": "30GiB"})
model = load_checkpoint_and_dispatch(
    model, "THUDM/chatglm-6b",
    #no_split_module_classes=["GLMBlock"],
    dtype=torch.float,
    device_map=_device_map,
    #max_memory={0:"4GiB", "cpu":"30GiB"}
)
print(model.hf_device_map)

model = model.eval()
with torch.no_grad():
    response, history = model.chat(tokenizer, "hello", history=[])

print(response)
```
and I got this error 
```
The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.
The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.
{'transformer.word_embeddings': 0, 'transformer.layers.0': 0, 'transformer.layers.1': 0, 'transformer.layers.2': 0, 'transformer.layers.3': 0, 'transformer.layers.4': 0, 'transformer.layers.5.input_layernorm': 0, 'transformer.layers.5.attention': 0, 'transformer.layers.5.post_attention_layernorm': 0, 'transformer.layers.6': 'cpu', 'transformer.layers.7': 'cpu', 'transformer.layers.8': 'cpu', 'transformer.layers.9': 'cpu', 'transformer.layers.10': 'cpu', 'transformer.layers.11': 'cpu', 'transformer.layers.12': 'cpu', 'transformer.layers.13': 'cpu', 'transformer.layers.14': 'cpu', 'transformer.layers.15': 'cpu', 'transformer.layers.16': 'cpu', 'transformer.layers.17': 'cpu', 'transformer.layers.18': 'cpu', 'transformer.layers.19': 'cpu', 'transformer.layers.20': 'cpu', 'transformer.layers.21': 'cpu', 'transformer.layers.22': 'cpu', 'transformer.layers.23': 'cpu', 'transformer.layers.24': 'cpu', 'transformer.layers.25': 'cpu', 'transformer.layers.26': 'cpu', 'transformer.layers.27': 'cpu', 'transformer.final_layernorm': 'cpu', 'lm_head': 'cpu', 'transformer.layers.5.mlp': 'cpu'}
The dtype of attention mask (torch.int64) is not bool
Traceback (most recent call last):
  File "test_mix.py", line 28, in <module>
    response, history = model.chat(tokenizer, "hello", history=[])
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/6b/modeling_chatglm.py", line 1285, in chat
    outputs = self.generate(**inputs, **gen_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/generation/utils.py", line 1588, in generate
    return self.sample(
  File "/usr/local/lib/python3.8/dist-packages/transformers/generation/utils.py", line 2642, in sample
    outputs = self(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/6b/modeling_chatglm.py", line 1204, in forward
    lm_logits = self.lm_head(hidden_states).permute(1, 0, 2).contiguous()
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/hooks.py", line 160, in new_forward
    args, kwargs = module._hf_hook.pre_forward(module, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/hooks.py", line 286, in pre_forward
    set_module_tensor_to_device(
  File "/usr/local/lib/python3.8/dist-packages/accelerate/utils/modeling.py", line 298, in set_module_tensor_to_device
    new_value = value.to(device)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.99 GiB (GPU 0; 7.43 GiB total capacity; 6.00 GiB already allocated; 890.25 MiB free; 6.00 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

### Expected behavior

infer with both GPU and CPU, no GPU Out of Memory error

**Comment by sgugger** [comment]
You should the Transformer integration for Transformer models. Here it's possible you are getting OOM because the weights are not properly tied (see the beginning of your error message) and in any case the model won't run since you commented out `#no_split_module_classes=["GLMBlock"]` which means that layer might end up being split on different devices.

You can pass `device_map="auto"` and `max_memory` to the `from_pretrained` method directly.

**Comment by DannyP0** [comment]
ok,  I tried several times and finally succeeded. Just reduce `4GiB` to `2GiB` in my case. Both `load_checkpoint_and_dispatch()` and `from_pretrained()` work.
`max_memory` appears to be used to limit the maximum memory when loading weights, but inference also takes memory.

**Comment by sgugger** [comment]
Yes it does :-)
