### ISSUE TITLE
The second execution of the same code on the same 4 gpus will result in an OOM

### ISSUE THREAD

**Issue by LYMDLUT** [huggingface/accelerate#1754]
### System Info

```Shell
- `Accelerate` version: 0.21.0
- Platform: Linux-3.10.0-1160.24.1.el7.x86_64-x86_64-with-glibc2.17
- Python version: 3.8.16
- Numpy version: 1.22.3
- PyTorch version (GPU?): 1.12.1+cu113 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 251.39 GB
- GPU type: GeForce RTX 3090
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: MULTI_GPU
        - mixed_precision: bf16
        - use_cpu: False
        - num_processes: 4
        - machine_rank: 0
        - num_machines: 1
        - gpu_ids: all
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

CUDA_VISIBLE_DEVICES=0,1,2,3 accelerate launch ddpm_copy.py
CUDA_VISIBLE_DEVICES=0,1,2,3 accelerate launch  --config_file second_config.yaml   --main_process_port=52339    ddpm_copy.py

I ensure that the graphics memory is sufficient.

### Expected behavior

Traceback (most recent call last):
  File "ddpm_copy.py", line 278, in <module>
    train_loop(*args)
  File "ddpm_copy.py", line 199, in train_loop
    model, optimizer, train_dataloader, lr_scheduler = accelerator.prepare(
  File "/data2/lym/anaconda3/envs/diffusers/lib/python3.8/site-packages/accelerate/accelerator.py", line 1202, in prepare
    result = tuple(
  File "/data2/lym/anaconda3/envs/diffusers/lib/python3.8/site-packages/accelerate/accelerator.py", line 1203, in <genexpr>
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
  File "/data2/lym/anaconda3/envs/diffusers/lib/python3.8/site-packages/accelerate/accelerator.py", line 1030, in _prepare_one
    return self.prepare_model(obj, device_placement=device_placement)
  File "/data2/lym/anaconda3/envs/diffusers/lib/python3.8/site-packages/accelerate/accelerator.py", line 1293, in prepare_model
    model = model.to(self.device)
  File "/data2/lym/anaconda3/envs/diffusers/lib/python3.8/site-packages/torch/nn/modules/module.py", line 927, in to
    return self._apply(convert)
  File "/data2/lym/anaconda3/envs/diffusers/lib/python3.8/site-packages/torch/nn/modules/module.py", line 579, in _apply
    module._apply(fn)
  File "/data2/lym/anaconda3/envs/diffusers/lib/python3.8/site-packages/torch/nn/modules/module.py", line 602, in _apply
    param_applied = fn(param)
  File "/data2/lym/anaconda3/envs/diffusers/lib/python3.8/site-packages/torch/nn/modules/module.py", line 925, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by LYMDLUT** [comment]
![4170bfe384c833e900b5d16b2aa7ec9](https://github.com/huggingface/accelerate/assets/70597027/d2c7776b-14bb-4c76-8716-45703e3ea330)

**Comment by LYMDLUT** [comment]
The second time CUDA_VISIBLE_DEVICES=4,5,6,7 accelerate launch ddpm_copy.py is OK,but  CUDA_VISIBLE_DEVICES=0,1,2,3 is not OK

**Comment by sgugger** [comment]
You can't use the same GPUs in two different training scripts running concurrently.
