### ISSUE TITLE
ERROR:torch.distributed.elastic.multiprocessing.api:failed - super weird behavior of using "accelerate launch"

### ISSUE THREAD

**Issue by Huan-Wang-S4** [huggingface/accelerate#1793]
Hi, 

I'm seeing some super weird behavior of using `accelerate launch`. I have been troubleshooting for days but I couldn't figure it out. I'd really appreciate help here. 

Here is how I define my model

```
class TransformerModel(nn.Module):
    def __init__(self, data_type, note_embedding_dim, note_embed_time_diff, num_classes, embed_pool_method, 
                 nhead, nlayer, hidden_dim, loss_function):
        super(TransformerModel, self).__init__()
        
        self.data_type = data_type
        self.transformer_encoder_bundle_1 = TransformerEncoderBundle(note_embedding_dim, note_embed_time_diff, embed_pool_method, nhead, nlayer)
        if data_type == "text" or data_type == "all":
            self.transformer_encoder_bundle_2 = TransformerEncoderBundle(note_embedding_dim, note_embed_time_diff, embed_pool_method, nhead, nlayer)
        self.hidden_dim = hidden_dim
        self.loss_fn = loss_function
        
        if note_embed_time_diff:
            
            if hidden_dim > 0:
                if data_type == 'text' or data_type == "all":
                    self.ffn = nn.Sequential(nn.Linear(2*note_embedding_dim - 2, hidden_dim),nn.ReLU(),)
                elif data_type == "note" or data_type == 'lab':
                    self.ffn = nn.Sequential(nn.Linear(note_embedding_dim - 1, hidden_dim),nn.ReLU(),)
                self.linear = nn.Linear(hidden_dim, num_classes)
                
            elif hidden_dim == 0:
                if data_type == 'text' or data_type == "all":
                    self.linear = nn.Linear(2*note_embedding_dim - 2, num_classes)
                elif data_type == "note" or data_type == 'lab':
                    self.linear = nn.Linear(note_embedding_dim - 1, num_classes)
        else:
            
            if hidden_dim > 0:
                if data_type == 'text' or data_type == "all":
                    self.ffn = nn.Sequential(nn.Linear(2*note_embedding_dim, hidden_dim),nn.ReLU(),)
                elif data_type == "note" or data_type == 'lab':
                    self.ffn = nn.Sequential(nn.Linear(note_embedding_dim, hidden_dim),nn.ReLU(),)
                self.linear = nn.Linear(hidden_dim, num_classes)
                
            elif hidden_dim == 0:
                if data_type == 'text' or data_type == "all":
                    self.linear = nn.Linear(2*note_embedding_dim, num_classes)    
                elif data_type == "note" or data_type == 'lab':
                    self.linear = nn.Linear(note_embedding_dim, num_classes)
                                           
        
    def forward(self, inputs):
        print("Forward pass starting")
        inputs_dim = len(inputs)
        
        if self.data_type == "text" or self.data_type == "all":
            print("input length: {}".format(inputs_dim))
            assert inputs_dim == 5, "Model inputs features are not compatible with input data type"
            
            noteEmbedTime, mask_note, labEmbedTime, mask_lab, labels = inputs 
            x_note = self.transformer_encoder_bundle_1(noteEmbedTime, mask_note)
            x_lab = self.transformer_encoder_bundle_2(labEmbedTime, mask_lab)
            x = torch.cat((x_note, x_lab), dim = 1) 
            
        elif self.data_type == "text" or self.data_type == "all":
            print("input length: {}".format(inputs_dim))
            assert inputs_dim == 3, "Model inputs features are not compatible with input data type"
            
            EmbedTime, mask, labels = inputs       
            x = self.transformer_encoder_bundle_1(EmbedTime, mask)

        print("Transformer bundle finished")
        
        if self.hidden_dim > 0:
            x = self.ffn(x)
        x = self.linear(x)
        
        if labels is not None:
            loss = self.loss_fn(x, labels.unsqueeze(1))
            return loss, x
        else:
            return x
```

The design is that 
1) `dataloader_train` and `dataloader_valid` will prepare the batch data in a way that depends on `data_type`. If `data_type` == `text` or `all`, each batch would be of 5 tensors. And if `data_type` == `note` or `lab`, each batch would be of 3 tensors. 
2) if `data_type` == `text` or `all`, the model will be initialized with two customized `TransformerEncoderBundle`. The `inputs` would be a batch of 5 tensors. The first and second tensors correspond to one type of embeddings with mask, and the third and forth tensors correspond to another type of embeddings with mask, and the last tensor is the labels. The model will process the two  `TransformerEncoderBundle` in parallel, and concatenate the output of the two bundles, and then perform ffn (if hidden_dim is specified > 0 ) with a final linear layer. 
3) if `data_type` == `note` or `lab`, the model will be initialized with only one `TransformerEncoderBundle`. The `inputs` would be a batch of only 3 tensors. The first and second tensors are the embeddings with mask, and the third would be labels. Then the model still go through ffn and final layer. 

Below is the example of how I use accelerate to train the model. 

```
accelerate launch --multi_gpu --num_processes=8 --config_file /code/accelerate_config_file.yaml /code/transformer_accelerate_training.py --input_datatype "text" --train_size 1024 --valid_size 256 --per_device_batch_size 2 --gradient_accumulation_step 4 --num_epochs 3 --force_dataloader_CPU 1  > /results/train.log 2> /results/train.err
```

`--input_datatype` corresponds to `data_type` I used to initiate  `TransformerModel`. 

Here is my training loop

```

    accelerator = Accelerator()
    accelerator.print("\nAccelerate using {} processes\n".format(accelerator.num_processes))
    device = accelerator.device
     
    model = TransformerModel(data_type = dataType,
                            note_embedding_dim = noteTimeEmbedDim, 
                            note_embed_time_diff = noteEmbedTimeDiff, 
                            num_classes = numClass, 
                            embed_pool_method = embedPoolMethod, 
                            nhead = nHead, 
                            nlayer = nLayer, 
                            hidden_dim = hiddenDim, 
                            loss_function = lossFn)

    model = model.to(accelerator.device)

    trainSteps = (len(dataloader_train) * nEpoch) // gradAccumStep
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)
    lr_scheduler = get_linear_schedule_with_warmup(
        optimizer=optimizer,
        num_warmup_steps=max(int(trainSteps*0.01), 0),
        num_training_steps=trainSteps,
    )
    
    model, optimizer, dataloader_train, dataloader_valid, lr_scheduler = accelerator.prepare(
    model, optimizer, dataloader_train, dataloader_valid, lr_scheduler)

    for epoch in range(nEpoch):
        t = time.time()
        accelerator.print("\nTraining epoch: {}".format(epoch + 1))
        
        model.train()
        
        for step, batch in enumerate(dataloader_train):

            labels = batch[-1]
            loss, logits = model(batch)
            loss = loss / gradAccumStep

            accelerator.backward(loss)  # Use accelerator.backward instead of loss.backward

            if (step + 1) % gradAccumStep == 0 or step == len(dataloader_train) - 1:
                optimizer.step()
                lr_scheduler.step() 
                optimizer.zero_grad()
```

My issue is that whenever I set `input_datatype` to `text` in running `accelerate launch` via command line, everything is fine. However, whenever I set it to be `note` or `lab`, it gives error below. 

```
Traceback (most recent call last):
  File "/code/transformer_accelerate_training.py", line 388, in <module>
    main()
  File "/code/transformer_accelerate_training.py", line 380, in main
    training_function(df_input, args, class_weights, False)
  File "/code/transformer_accelerate_training.py", line 207, in training_function
    loss, logits = model(batch)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/utils/operations.py", line 553, in forward
    return model_forward(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/utils/operations.py", line 541, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/opt/conda/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1148, in forward
    self._sync_buffers()
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1748, in _sync_buffers
    self._sync_module_buffers(authoritative_rank)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1752, in _sync_module_buffers
    self._default_broadcast_coalesced(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1775, in _default_broadcast_coalesced
    self._distributed_broadcast_coalesced(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1689, in _distributed_broadcast_coalesced
    dist._broadcast_coalesced(
RuntimeError: unsupported operation: some elements of the input tensor and the written-to tensor refer to a single memory location. Please clone() the tensor before performing the operation.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 24) of binary: /opt/conda/bin/python3.10
Traceback (most recent call last):
  File "/opt/conda/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/launch.py", line 932, in launch_command
    multi_gpu_launcher(args)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/launch.py", line 627, in multi_gpu_launcher
    distrib_run.run(args)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
```

So the error comes from the line `loss, logits = model(batch)`. What's really weird is that the line `print("Forward pass starting")` I set inside the model definition under `def forward (self, inputs)` for tracking the root cause won't even get executed when the error happens, meaning I don't see `Forward pass starting` in standard out "train.log". It seems like the input isn't even processed at all. And this ONLY occurs when `input_datatype` is set to be `note` or `lab`. Everything works fine when it's set to be `text` or `all`. Why?

I would truly truly appreciate help here. It's driving me nuts!!!

**Comment by Huan-Wang-S4** [comment]
Can anyone please help take a look here? I appreciate it! Thanks

**Comment by Huan-Wang-S4** [comment]
Hi, @sgugger . Sorry about tagging you here, but I would really appreciate some help here. Please let me know if I can provide anything else to help troubleshoot here. Thanks!

**Comment by IncludeMathH** [comment]
I also encountered a similar problem, did you find a good solution?
