### ISSUE TITLE
accelerate config failed

### ISSUE THREAD

**Issue by dp-0809** [huggingface/accelerate#1797]
when i go for accelerate config reported an error
I have tried to reinstall google and protobuf but error remained
Traceback (most recent call last):
  File "/public/home/linhy/.local/bin/accelerate", line 5, in <module>
    from accelerate.commands.accelerate_cli import main
  File "/public/home/linhy/.local/lib/python3.8/site-packages/accelerate/__init__.py", line 7, in <module>
    from .accelerator import Accelerator
  File "/public/home/linhy/.local/lib/python3.8/site-packages/accelerate/accelerator.py", line 35, in <module>
    from .tracking import LOGGER_TYPE_TO_CLASS, GeneralTracker, filter_trackers
  File "/public/home/linhy/.local/lib/python3.8/site-packages/accelerate/tracking.py", line 48, in <module>
    import wandb
  File "/public/home/linhy/.local/lib/python3.8/site-packages/wandb/__init__.py", line 26, in <module>
    from wandb import sdk as wandb_sdk
  File "/public/home/linhy/.local/lib/python3.8/site-packages/wandb/sdk/__init__.py", line 9, in <module>
    from .wandb_init import _attach, init  # noqa: F401
  File "/public/home/linhy/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 28, in <module>
    from . import wandb_login, wandb_setup
  File "/public/home/linhy/.local/lib/python3.8/site-packages/wandb/sdk/wandb_login.py", line 23, in <module>
    from .wandb_settings import Settings, Source
  File "/public/home/linhy/.local/lib/python3.8/site-packages/wandb/sdk/wandb_settings.py", line 38, in <module>
    from wandb.sdk.wandb_setup import _EarlyLogger
  File "/public/home/linhy/.local/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 28, in <module>
    from . import wandb_manager
  File "/public/home/linhy/.local/lib/python3.8/site-packages/wandb/sdk/wandb_manager.py", line 12, in <module>
    from wandb.sdk.lib.proto_util import settings_dict_from_pbmap
  File "/public/home/linhy/.local/lib/python3.8/site-packages/wandb/sdk/lib/proto_util.py", line 7, in <module>
    from wandb.proto import wandb_internal_pb2 as pb
  File "/public/home/linhy/.local/lib/python3.8/site-packages/wandb/proto/wandb_internal_pb2.py", line 5, in <module>
    from google.protobuf import descriptor as _descriptor
ModuleNotFoundError: No module named 'google.protobuf'
(ldm) [linhy@login01 custom-diffusion]$ accelerate config
Traceback (most recent call last):
  File "/public/home/linhy/.local/lib/python3.8/site-packages/accelerate/tracking.py", line 41, in <module>
    from torch.utils import tensorboard
  File "/public/home/linhy/.local/lib/python3.8/site-packages/torch/utils/tensorboard/__init__.py", line 12, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
  File "/public/home/linhy/.local/lib/python3.8/site-packages/torch/utils/tensorboard/writer.py", line 9, in <module>
    from tensorboard.compat.proto.event_pb2 import SessionLog
  File "/public/home/linhy/.local/lib/python3.8/site-packages/tensorboard/compat/proto/event_pb2.py", line 5, in <module>
    from google.protobuf.internal import enum_type_wrapper
ModuleNotFoundError: No module named 'google.protobuf'

**Comment by sgugger** [comment]
The errors comes from a bad install of `wandb` looking at the traceback. You should try a fresh install!
