### ISSUE TITLE
accelerator.prepare() error: DistributedDataParallel device_ids and output_device arguments only work with single-device/multiple-device GPU modules or CPU modules

### ISSUE THREAD

**Issue by nebrelbug** [huggingface/accelerate#1802]
### System Info

```Shell
- `Accelerate` version: 0.21.0
- Platform: Linux-5.4.0-58-generic-x86_64-with-glibc2.29
- Python version: 3.8.10
- Numpy version: 1.24.4
- PyTorch version (GPU?): 2.0.1+cu118 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 1510.57 GB
- GPU type: Tesla V100-SXM3-32GB
- `Accelerate` default config:
        Not found
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

Here's some code that loads LLaMA weights and then calls `accelerator.prepare(model, optimizer, dataloader)`. It's part of a training loop I wrote, but the sample below is sufficient to cause an error. I'm just a beginner :sweat_smile:, so I may have made a mistake somehow, but the code works fine without using Accelerate.

**Training Code**

```python
from transformers import LlamaForCausalLM, LlamaTokenizer
from torch.utils.data import Dataset, DataLoader
from torch.optim import AdamW

from accelerate import Accelerator
import json

accelerator = Accelerator()

# MODEL LOADING

MODEL_PATH = "//mnt/pccfs2/backed_up/models/llama/hf/llama-7b-hf"

tokenizer = LlamaTokenizer.from_pretrained(MODEL_PATH, legacy=False)

model = LlamaForCausalLM.from_pretrained(MODEL_PATH, device_map="auto")

optimizer = AdamW(model.parameters(), lr=3e-5)

model.train()  # tell model you're training

# DATALOADER


class StringDataset(Dataset):
    def __init__(self, string_list, tokenizer):
        self.string_list = string_list
        self.tokenizer = tokenizer

    def __len__(self):
        return len(self.string_list)

    def __getitem__(self, idx):
        text = self.string_list[idx]
        tokens = self.tokenizer(
            text,
            padding="max_length",
            truncation=True,
            return_tensors="pt",
        ).to("cuda")

        tokens["input_ids"] = tokens["input_ids"].squeeze()
        tokens["attention_mask"] = tokens["attention_mask"].squeeze()
        return tokens


# LOAD DATALOADER

with open("alpaca_data.json", "r") as f:
    alpaca_data = json.load(f)

alpaca_data = [item for item in alpaca_data if len(item["input"]) == 0]

eval_mark = int(len(alpaca_data) * 0.05)

training_data = alpaca_data[:eval_mark]

processed_training_data = [
    """
### Instruction:
{instruction}

### Response:
{response}
""".format(
        instruction=input["instruction"], response=input["output"]
    ).strip()
    for input in training_data
]

dataset = StringDataset(processed_training_data, tokenizer)
dataloader = DataLoader(dataset, batch_size=8, shuffle=True)

model, optimizer, dataloader = accelerator.prepare(model, optimizer, dataloader)
```

**Run Command**

`accelerate launch --num_processes=1 accelerate_test.py`

**Output**

```
[2023-07-31 22:52:39,569] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
The following values were not passed to `accelerate launch` and had defaults used instead:
                More than one GPU was found, enabling multi-GPU training.
                If this was unintended please pass in `--num_processes=1`.
        `--num_machines` was set to a value of `1`
        `--mixed_precision` was set to a value of `'no'`
        `--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
[2023-07-31 22:52:46,614] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Loading checkpoint shards: 100%|█████████████████████| 2/2 [00:34<00:00, 17.41s/it]
Traceback (most recent call last):
  File "mre.py", line 74, in <module>
    model, optimizer, dataloader = accelerator.prepare(model, optimizer, dataloader)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/accelerator.py", line 1202, in prepare
    result = tuple(
  File "/usr/local/lib/python3.8/dist-packages/accelerate/accelerator.py", line 1203, in <genexpr>
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/accelerator.py", line 1030, in _prepare_one
    return self.prepare_model(obj, device_placement=device_placement)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/accelerator.py", line 1340, in prepare_model
    model = torch.nn.parallel.DistributedDataParallel(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/distributed.py", line 603, in __init__
    self._log_and_throw(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/distributed.py", line 769, in _log_and_throw
    raise err_type(err_msg)
ValueError: DistributedDataParallel device_ids and output_device arguments only work with single-device/multiple-device GPU modules or CPU modules, but got device_ids [0], output_device 0, and module parameters {device(type='cuda', index=0), device(type='cuda', index=1), device(type='cuda', index=2), device(type='cuda', index=3), device(type='cuda', index=4), device(type='cuda', index=5), device(type='cuda', index=6), device(type='cuda', index=7), device(type='cuda', index=8), device(type='cuda', index=9), device(type='cuda', index=10), device(type='cuda', index=11)}.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 83560) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 970, in launch_command
    multi_gpu_launcher(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 646, in multi_gpu_launcher
    distrib_run.run(args)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
mre.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-31_22:54:12
  host      : 454a5ef84db3
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 83560)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

### Expected behavior

The code should load a pretrained LLaMA model, set up a dataloader, and then set up `accelerate` by calling `accelerator.prepare(model, optimizer, dataloader)`.

**Comment by sgugger** [comment]
cc @muellerzr Looks like passing `--num_processes 1` did not cancel the auto multi-GPU select.

**Comment by muellerzr** [comment]
@nebrelbug can you try installing via `pip install git+https://github.com/huggingface/accelerate@num-procs-1` and rerun the same command?

**Comment by nebrelbug** [comment]
@muellerzr this fixes my issue with --num_processes=1!

```
[2023-08-02 19:31:15,683] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_machines` was set to a value of `1`
        `--mixed_precision` was set to a value of `'no'`
        `--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
[2023-08-02 19:31:21,511] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████| 2/2 [00:36<00:00, 18.42s/it]
```

Unfortunately, it's still erroring with --num_processes=2.

```
[2023-08-02 19:33:02,463] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
The following values were not passed to `accelerate launch` and had defaults used instead:
                More than one GPU was found, enabling multi-GPU training.
                If this was unintended please pass in `--num_processes=1`.
        `--num_machines` was set to a value of `1`
        `--mixed_precision` was set to a value of `'no'`
        `--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
[2023-08-02 19:33:10,320] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-08-02 19:33:10,393] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████| 2/2 [00:39<00:00, 19.77s/it]
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████| 2/2 [00:41<00:00, 20.95s/it]
Traceback (most recent call last):
  File "mre.py", line 74, in <module>
    model, optimizer, dataloader = accelerator.prepare(model, optimizer, dataloader)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/accelerator.py", line 1260, in prepare
    result = tuple(
  File "/usr/local/lib/python3.8/dist-packages/accelerate/accelerator.py", line 1261, in <genexpr>
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/accelerator.py", line 1084, in _prepare_one
    return self.prepare_model(obj, device_placement=device_placement)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/accelerator.py", line 1397, in prepare_model
    model = torch.nn.parallel.DistributedDataParallel(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/distributed.py", line 603, in __init__
    self._log_and_throw(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/distributed.py", line 769, in _log_and_throw
    raise err_type(err_msg)
ValueError: DistributedDataParallel device_ids and output_device arguments only work with single-device/multiple-device GPU modules or CPU modules, but got device_ids [0], output_device 0, and module parameters {device(type='cuda', index=0), device(type='cuda', index=1), device(type='cuda', index=2), device(type='cuda', index=3), device(type='cuda', index=4), device(type='cuda', index=5), device(type='cuda', index=6), device(type='cuda', index=7), device(type='cuda', index=8), device(type='cuda', index=9), device(type='cuda', index=10), device(type='cuda', index=11)}.
Traceback (most recent call last):
  File "mre.py", line 74, in <module>
    model, optimizer, dataloader = accelerator.prepare(model, optimizer, dataloader)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/accelerator.py", line 1260, in prepare
    result = tuple(
  File "/usr/local/lib/python3.8/dist-packages/accelerate/accelerator.py", line 1261, in <genexpr>
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/accelerator.py", line 1084, in _prepare_one
    return self.prepare_model(obj, device_placement=device_placement)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/accelerator.py", line 1397, in prepare_model
    model = torch.nn.parallel.DistributedDataParallel(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/distributed.py", line 603, in __init__
    self._log_and_throw(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/distributed.py", line 769, in _log_and_throw
    raise err_type(err_msg)
ValueError: DistributedDataParallel device_ids and output_device arguments only work with single-device/multiple-device GPU modules or CPU modules, but got device_ids [1], output_device 1, and module parameters {device(type='cuda', index=0), device(type='cuda', index=1), device(type='cuda', index=2), device(type='cuda', index=3), device(type='cuda', index=4), device(type='cuda', index=5), device(type='cuda', index=6), device(type='cuda', index=7), device(type='cuda', index=8), device(type='cuda', index=9), device(type='cuda', index=10), device(type='cuda', index=11)}.
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 265482 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 265483) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 973, in launch_command
    multi_gpu_launcher(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 646, in multi_gpu_launcher
    distrib_run.run(args)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
mre.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-08-02_19:34:50
  host      : 454a5ef84db3
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 265483)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

**Comment by muellerzr** [comment]
@nebrelbug can you share your output of `nvidia-smi`?

**Comment by nebrelbug** [comment]
```
Thu Aug  3 18:07:10 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.80.02    Driver Version: 450.80.02    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM3...  On   | 00000000:34:00.0 Off |                    0 |
| N/A   33C    P0    49W / 350W |      0MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM3...  On   | 00000000:36:00.0 Off |                    0 |
| N/A   31C    P0    48W / 350W |      0MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM3...  On   | 00000000:39:00.0 Off |                    0 |
| N/A   42C    P0    50W / 350W |      0MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM3...  On   | 00000000:3B:00.0 Off |                    0 |
| N/A   42C    P0    49W / 350W |      0MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   4  Tesla V100-SXM3...  On   | 00000000:57:00.0 Off |                    0 |
| N/A   31C    P0    48W / 350W |      0MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   5  Tesla V100-SXM3...  On   | 00000000:59:00.0 Off |                    0 |
| N/A   39C    P0    51W / 350W |      0MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   6  Tesla V100-SXM3...  On   | 00000000:5C:00.0 Off |                    0 |
| N/A   32C    P0    50W / 350W |      0MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   7  Tesla V100-SXM3...  On   | 00000000:5E:00.0 Off |                    0 |
| N/A   40C    P0    53W / 350W |      0MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   8  Tesla V100-SXM3...  On   | 00000000:B7:00.0 Off |                    0 |
| N/A   32C    P0    51W / 350W |      0MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   9  Tesla V100-SXM3...  On   | 00000000:B9:00.0 Off |                    0 |
| N/A   32C    P0    49W / 350W |      0MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|  10  Tesla V100-SXM3...  On   | 00000000:BC:00.0 Off |                    0 |
| N/A   39C    P0    51W / 350W |      0MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|  11  Tesla V100-SXM3...  On   | 00000000:BE:00.0 Off |                    0 |
| N/A   40C    P0    53W / 350W |      0MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|  12  Tesla V100-SXM3...  On   | 00000000:E0:00.0 Off |                    0 |
| N/A   31C    P0    51W / 350W |      0MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|  13  Tesla V100-SXM3...  On   | 00000000:E2:00.0 Off |                    0 |
| N/A   32C    P0    52W / 350W |      0MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|  14  Tesla V100-SXM3...  On   | 00000000:E5:00.0 Off |                    0 |
| N/A   40C    P0    51W / 350W |      0MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|  15  Tesla V100-SXM3...  On   | 00000000:E7:00.0 Off |                    0 |
| N/A   39C    P0    52W / 350W |      0MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by sgugger** [comment]
```
model = LlamaForCausalLM.from_pretrained(MODEL_PATH, device_map="auto")
```
You need to remove `device_map="auto"` if you want to use DistributedDataParallel. You can't use both at the same time. So either use `device_map="auto"` and launch your script with `--num_processes=1` or remove it to launch it with `--num_processes=2`.

**Comment by muellerzr** [comment]
@nebrelbug this PR will raise an explicit error for this as well: https://github.com/huggingface/accelerate/pull/1810

**Comment by nebrelbug** [comment]
@sgugger ok, that makes sense! Thanks so much for the prompt resolution. So to clarify:

If a model fits on 1 GPU, it's possible to train it across multiple GPUs concurrently using `--num_processes=X`.

If a model can't fit on 1 GPU, you can only train 1 instance across each machine using `--num_processes=1` and `device_map="

**Comment by nebrelbug** [comment]
@sgugger ok, that makes sense! Thanks so much for the quick resolution. So to clarify:

If a model fits on 1 GPU, it's possible to train it across multiple GPUs concurrently using `--num_processes=X`.

If a model can't fit on 1 GPU, you can only train 1 instance across each machine using `--num_processes=1` and `device_map="auto"`?

**Comment by sgugger** [comment]
That's correct! (deleted the duplicate comment just to keep the thread clean :-) )

**Comment by nebrelbug** [comment]
Makes sense! I'll close this issue now then. Thanks for the help!
