### ISSUE TITLE
Finetuning with Accelerate and Deepspeed: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!

### ISSUE THREAD

**Issue by nebrelbug** [huggingface/accelerate#1815]
### System Info

```Shell
- `Accelerate` version: 0.22.0.dev0
- Platform: Linux-3.10.0-1160.92.1.el7.x86_64-x86_64-with-glibc2.29
- Python version: 3.8.10
- Numpy version: 1.24.4
- PyTorch version (GPU?): 2.0.1+cu118 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 2003.87 GB
- GPU type: NVIDIA A100-SXM4-80GB
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: DEEPSPEED
        - mixed_precision: fp16
        - use_cpu: False
        - debug: False
        - num_processes: 1
        - machine_rank: 0
        - num_machines: 1
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - deepspeed_config: {'gradient_accumulation_steps': 1, 'offload_optimizer_device': 'cpu', 'offload_param_device': 'cpu', 'zero3_init_flag': True, 'zero3_save_16bit_model': True, 'zero_stage': 3}
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

I've written a very simple training loop to finetune LLaMA. Below is the code:

`loop.py`
```py
from transformers import LlamaForCausalLM, LlamaTokenizer, Trainer, TrainingArguments
from utils.dataloader import load_data

MODEL_PATH = "/.../llama-30b-hf"

tokenizer = LlamaTokenizer.from_pretrained(MODEL_PATH, legacy=False)
tokenizer.pad_token = tokenizer.eos_token

model = LlamaForCausalLM.from_pretrained(MODEL_PATH, device_map="auto")

train_dataset, eval_dataset = load_data(tokenizer)

training_args = TrainingArguments(
    output_dir="./results",
    num_train_epochs=3,
    learning_rate=2e-5,
    logging_steps=10,
    fp16=True,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
)

trainer.train()
trainer.evaluate()

model.save_pretrained("/.../llama-7b-tinyllama")
tokenizer.save_pretrained("/.../llama-7b-tinyllama")
```

`utils/dataloader.py`
```py
from torch.utils.data import Dataset
import json

with open("utils/alpaca_data.json", "r") as f:
    alpaca_data = json.load(f)

alpaca_data = [item for item in alpaca_data if len(item["input"]) == 0]

eval_mark = int(len(alpaca_data) * 0.8)

class StringDataset(Dataset):
    def __init__(self, string_list, tokenizer, max_sequence_length):
        self.string_list = string_list
        self.tokenizer = tokenizer
        self.max_sequence_length = max_sequence_length

    def __len__(self):
        return len(self.string_list)

    def __getitem__(self, idx):
        text = self.string_list[idx]
        tokens = self.tokenizer(
            text,
            padding="max_length",
            truncation=True,
            max_length=self.max_sequence_length,
            return_tensors="pt",
        )

        tokens["input_ids"] = tokens["input_ids"].squeeze()
        tokens["labels"] = tokens["input_ids"]
        tokens["attention_mask"] = tokens["attention_mask"].squeeze()
        return tokens

def process_data(data):
    return [
    """
### Instruction:
{instruction}

### Response:
{response}
""".format(
        instruction=input["instruction"], response=input["output"]
    ).strip()
    for input in data
]

training_data = process_data(alpaca_data[:eval_mark])
eval_data = process_data(alpaca_data[eval_mark:])

# Create datasets
def load_data(tokenizer):
    train_dataset = StringDataset(training_data, tokenizer, max_sequence_length=200)
    eval_dataset = StringDataset(eval_data, tokenizer, max_sequence_length=200)

    return train_dataset, eval_dataset
```

My DeepSpeed and Accelerate configs can be found above.

When I launch my script normally using `python3 loop.py`, the model loads across my 8 GPUs as expected and begins a functional training loop. Loss, learning rate both go down as expected.

When I launch my script using `accelerate launch loop.py`, however, I get the following error:

```
[2023-08-05 15:01:10,274] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-08-05 15:01:15,632] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Loading checkpoint shards: 100%|███████| 7/7 [01:14<00:00, 10.69s/it]
[2023-08-05 15:02:35,183] [WARNING] [comm.py:152:init_deepspeed_backend] NCCL backend in DeepSpeed not yet implemented
[2023-08-05 15:02:35,184] [INFO] [comm.py:616:init_distributed] cdb=None
[2023-08-05 15:02:35,184] [INFO] [comm.py:643:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
CODECARBON : No CPU tracking mode found. Falling back on CPU constant mode.
CODECARBON : Failed to match CPU TDP constant. Falling back on a global constant.
/transformers/src/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
Using /home/bgubler7/.cache/torch_extensions/py38_cu118 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/bgubler7/.cache/torch_extensions/py38_cu118/cpu_adam/build.ninja...
Building extension module cpu_adam...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module cpu_adam...
Time to load cpu_adam op: 2.9528276920318604 seconds
Parameter Offload: Total persistent parameters: 805376 in 121 params
wandb: Tracking run with wandb version 0.15.7
wandb: W&B syncing is set to `offline` in this directory.  
wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
  0%|                                       | 0/9399 [00:00<?, ?it/s]Traceback (most recent call last):
  File "loop.py", line 28, in <module>
    trainer.train()
  File "/transformers/src/transformers/trainer.py", line 1532, in train
    return inner_training_loop(
  File "/transformers/src/transformers/trainer.py", line 1805, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/transformers/src/transformers/trainer.py", line 2648, in training_step
    loss = self.compute_loss(model, inputs)
  File "/transformers/src/transformers/trainer.py", line 2673, in compute_loss
    outputs = model(**inputs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/runtime/engine.py", line 1769, in forward
    loss = self.module(*inputs, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/transformers/src/transformers/models/llama/modeling_llama.py", line 810, in forward
    outputs = self.model(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/transformers/src/transformers/models/llama/modeling_llama.py", line 698, in forward
    layer_outputs = decoder_layer(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/transformers/src/transformers/models/llama/modeling_llama.py", line 410, in forward
    hidden_states = self.input_layernorm(hidden_states)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/transformers/src/transformers/models/llama/modeling_llama.py", line 89, in forward
    return self.weight * hidden_states.to(input_dtype)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!
```

This error also results in a CPU lockup (`kernel:NMI watchdog: BUG: soft lockup - CPU#84 stuck for 22s! [python3:89639]`) but my guess is that that is a problem with my RHEL version and not directly due to this library.

### Expected behavior

I'd expect Accelerate to run the finetuning loop, using all 8 GPUs and using the CPUs for DeepSpeed offload. The model seems to load correctly and parameters to offload correctly, but the issue comes during training.

**Comment by sgugger** [comment]
You cannot use `device_map="auto"` with any data parallel training, it's to use model parallelism. You should remove this argument and use DeepSpeed ZerO-3 to put your model on several devices for training if your model is big.
