### ISSUE TITLE
Deepspeed learning rate is set as a string instead of float

### ISSUE THREAD

**Issue by ikergarcia1996** [huggingface/accelerate#1828]
### System Info

```Shell
- `transformers` version: 4.32.0.dev0
- Platform: Linux-4.18.0-305.19.1.el8_4.x86_64-x86_64-with-glibc2.28
- Python version: 3.9.7
- Huggingface_hub version: 0.14.1
- Safetensors version: 0.3.1
- Accelerate version: 0.21.0
- Accelerate config: 	- compute_environment: LOCAL_MACHINE
	- distributed_type: NO
	- mixed_precision: fp16
	- use_cpu: False
	- num_processes: 1
	- machine_rank: 0
	- num_machines: 1
	- rdzv_backend: static
	- same_network: False
	- main_training_function: main
	- downcast_bf16: False
	- tpu_use_cluster: False
	- tpu_use_sudo: False
- PyTorch version (GPU?): 2.1.0.dev20230523+cu117 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: Yes
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

I am trying to use the Hugging Face Trainer together with deepspeed. I am opening the issue in Accelerate because the Trainer uses accelerate to setup deepspeed. 
I use a `config.yalm` file as TrainingArguments with the following arguments for the optimizer:

```yalm
optim: adamw_torch
learning_rate: 1e-5
weight_decay: 0
num_train_epochs: 3
lr_scheduler_type: cosine
warmup_ratio: 0.03
adam_epsilon: 1e-7

torch_dtype: bfloat16
bf16: true
fp16: false

per_device_train_batch_size: 1
per_device_eval_batch_size: 1
gradient_accumulation_steps: 8
generation_num_beams: 1
```

I also set the argument `deepspeed: /configs/deepspeed_configs/deepspeed_zero3.json` to use deepspeed zero3. I am using the following deepspeed configuration
```json
{
  "fp16": {
    "enabled": "auto",
    "loss_scale": 0,
    "loss_scale_window": 1000,
    "initial_scale_power": 16,
    "hysteresis": 2,
    "min_loss_scale": 1
  },
  "bf16": {
    "enabled": "auto"
  },
  "optimizer": {
    "type": "AdamW",
    "params": {
      "lr": "auto",
      "betas": "auto",
      "eps": "auto",
      "weight_decay": "auto"
    }
  },
  "scheduler": {
    "type": "WarmupDecayLR",
    "params": {
      "warmup_min_lr": "auto",
      "warmup_max_lr": "auto",
      "warmup_num_steps": "auto",
      "warmup_type": "cosine",
      "total_num_steps": "auto"
    }
  },
  "zero_optimization": {
    "stage": 3,
    "overlap_comm": true,
    "contiguous_gradients": true,
    "sub_group_size": 1e9,
    "reduce_bucket_size": "auto",
    "stage3_prefetch_bucket_size": "auto",
    "stage3_param_persistence_threshold": "auto",
    "stage3_max_live_parameters": 1e9,
    "stage3_max_reuse_distance": 1e9,
    "stage3_gather_16bit_weights_on_model_save": true
  },
  "gradient_accumulation_steps": "auto",
  "gradient_clipping": "auto",
  "steps_per_print": 2000,
  "train_batch_size": "auto",
  "train_micro_batch_size_per_gpu": "auto",
  "wall_clock_breakdown": false
}
```

I launch the script with the following command
```bash
torchrun --standalone  --nproc_per_node=4 src/run.py ${CONFIGS_FOLDER}/LLaMa2_deepspeed.yaml
```

However, I get the error `TypeError: multi_tensor_adam(): incompatible function arguments`. Which is caused because the learning rate and eps arguments are a string `(1e-5', 0.9, 0.999, '1e-7',`) instead of a float as shown in the last line of the Traceback. 

```bash
Traceback (most recent call last):
  File "/ikerlariak/igarcia945/CoLLIE/src/run.py", line 347, in <module>
    train_collie(
  File "/ikerlariak/igarcia945/CoLLIE/src/run.py", line 124, in train_collie
    trainer.train(resume_from_checkpoint=training_args.resume_from_checkpoint)
  File "/ikerlariak/osainz006/venvs/collie/lib/python3.9/site-packages/transformers/trainer.py", line 1526, in train
    return inner_training_loop(
  File "/ikerlariak/osainz006/venvs/collie/lib/python3.9/site-packages/transformers/trainer.py", line 1646, in _inner_training_loop
    model, self.optimizer, self.lr_scheduler = self.accelerator.prepare(
  File "/ikerlariak/osainz006/venvs/collie/lib/python3.9/site-packages/accelerate/accelerator.py", line 1198, in prepare
    result = self._prepare_deepspeed(*args)
  File "/ikerlariak/osainz006/venvs/collie/lib/python3.9/site-packages/accelerate/accelerator.py", line 1537, in _prepare_deepspeed
    engine, optimizer, _, lr_scheduler = deepspeed.initialize(**kwargs)
  File "/ikerlariak/osainz006/venvs/collie/lib/python3.9/site-packages/deepspeed/__init__.py", line 171, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/ikerlariak/osainz006/venvs/collie/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 310, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/ikerlariak/osainz006/venvs/collie/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1205, in _configure_optimizer
    self.optimizer = self._configure_zero_optimizer(basic_optimizer)
  File "/ikerlariak/osainz006/venvs/collie/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1503, in _configure_zero_optimizer
    optimizer = DeepSpeedZeroOptimizer_Stage3(
  File "/ikerlariak/osainz006/venvs/collie/lib/python3.9/site-packages/deepspeed/runtime/zero/stage3.py", line 324, in __init__
    self._setup_for_real_optimizer()
  File "/ikerlariak/osainz006/venvs/collie/lib/python3.9/site-packages/deepspeed/runtime/zero/stage3.py", line 421, in _setup_for_real_optimizer
    self.initialize_optimizer_states()
  File "/ikerlariak/osainz006/venvs/collie/lib/python3.9/site-packages/deepspeed/runtime/zero/stage3.py", line 931, in initialize_optimizer_states
    self._optimizer_step(i)
  File "/ikerlariak/osainz006/venvs/collie/lib/python3.9/site-packages/deepspeed/runtime/zero/stage3.py", line 856, in _optimizer_step
    self.optimizer.step()
  File "/ikerlariak/osainz006/venvs/collie/lib/python3.9/site-packages/torch/optim/optimizer.py", line 280, in wrapper
    out = func(*args, **kwargs)
  File "/ikerlariak/osainz006/venvs/collie/lib/python3.9/site-packages/deepspeed/ops/adam/fused_adam.py", line 191, in step
    multi_tensor_applier(self.multi_tensor_adam, self._dummy_overflow_buf, [g_32, p_32, m_32, v_32],
  File "/ikerlariak/osainz006/venvs/collie/lib/python3.9/site-packages/deepspeed/ops/adam/multi_tensor_apply.py", line 17, in __call__
    return op(self.chunk_size, noop_flag_buffer, tensor_lists, *args)
TypeError: multi_tensor_adam(): incompatible function arguments. The following argument types are supported:
    1. (arg0: int, arg1: torch.Tensor, arg2: List[List[torch.Tensor]], arg3: float, arg4: float, arg5: float, arg6: float, arg7: int, arg8: int, arg9: int, arg10: float) -> None

Invoked with: 65536, tensor([0], device='cuda:0', dtype=torch.int32), [[tensor([0., 0., 0.,  ..., 0., 0., 0.], device='cuda:0')], [tensor([ 1.2517e-06, -1.7881e-06, -4.3511e-06,  ...,  2.1210e-03,
         5.7983e-03,  1.8188e-02], device='cuda:0')], [tensor([0., 0., 0.,  ..., 0., 0., 0.], device='cuda:0')], [tensor([0., 0., 0.,  ..., 0., 0., 0.], device='cuda:0')]], '1e-5', 0.9, 0.999, '1e-7', 1, 1, 1, 0
```

I got a similar issue with FSDP that was fixed overriding the Trainer `__init__` to ensure that the optimizer arguments are floats 

```python
args.set_optimizer(
    name=args.optim,
    learning_rate=float(args.learning_rate),
    weight_decay=float(args.weight_decay),
    beta1=float(args.adam_beta1),
    beta2=float(args.adam_beta2),
    epsilon=float(args.adam_epsilon),
    args=args.optim_args,
)
```

In the case of deepspeed this "trick" doesn't work, the values are still passed to deepspeed as a string. 

### Expected behavior

The learnign rate and eps values should be passed to deepspeed as a float value. Accelerate should ensure that those values are floats when using both FSDP and Deepspeed.

**Comment by pacman100** [comment]
Hello @ikergarcia1996 , you should pass the correct values when creating the `TrainingArguments` object. The loading of the config yaml and conversion to correct dtype should be done by the user code. Hoe are you passing the values to `TrainingArguments`
