### ISSUE TITLE
Unclear errors when trying to set CUDA_DEVICES_VISIBLE via `os.environ` to control GPUs accessible to `accelerate launch`

### ISSUE THREAD

**Issue by xhluca** [huggingface/accelerate#1917]
### System Info

```Shell
Python: 3.8.16
Accelerate: 0.22.0
OS: Ubuntu
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

I derived from the Chapter 7's MT translation example. Here's the `run.py` script that contains the trainer:

```python
# Source: https://huggingface.co/learn/nlp-course/chapter7/4
import os
from pathlib import Path

import torch
from datasets import load_dataset
import transformers
from transformers import (
    AutoTokenizer, AutoModelForSeq2SeqLM, DataCollatorForSeq2Seq, Seq2SeqTrainingArguments, Seq2SeqTrainer
)

def main():
    model_checkpoint = "Helsinki-NLP/opus-mt-en-fr"
    model = AutoModelForSeq2SeqLM.from_pretrained(model_checkpoint)
    tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)
    data_collator = DataCollatorForSeq2Seq(tokenizer, model=model)

    def preprocess_function(examples, max_length=128):
        inputs = [ex["en"] for ex in examples["translation"]]
        targets = [ex["fr"] for ex in examples["translation"]]
        model_inputs = tokenizer(
            inputs, text_target=targets, max_length=max_length, truncation=True
        )
        return model_inputs

    # Use accelerate to get number of gpus assigned
    from accelerate import Accelerator
    accelerator = Accelerator()
    print(f"Number of devices: {accelerator.num_processes}")

    raw_datasets = load_dataset("kde4", lang1="en", lang2="fr")
    split_datasets = raw_datasets["train"].train_test_split(train_size=0.9, seed=20)
    split_datasets["validation"] = split_datasets.pop("test")

    cache_dir = Path('.cache/huggingface/')
    tokenized_datasets = split_datasets.map(
        preprocess_function,
        batched=True,
        remove_columns=split_datasets["train"].column_names,
    )

    args = Seq2SeqTrainingArguments(
        "marian-finetuned-kde4-en-to-fr",
        evaluation_strategy="no",
        save_strategy="epoch",
        learning_rate=2e-5,
        per_device_train_batch_size=32,
        per_device_eval_batch_size=64,
        weight_decay=0.01,
        save_total_limit=3,
        num_train_epochs=3,
        predict_with_generate=True,
        fp16=True,
    )

    trainer = Seq2SeqTrainer(
        model,
        args,
        train_dataset=tokenized_datasets["train"],
        eval_dataset=tokenized_datasets["validation"],
        data_collator=data_collator,
        tokenizer=tokenizer,
    )
    
    trainer.train()

if __name__ == "__main__":
    main()
```

If I run this with accelerate:
```bash
accelerate launch --num_processes 4 -m run
```

It will train fine:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 520.56.06    Driver Version: 520.56.06    CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA RTX A6000    Off  | 00000000:01:00.0 Off |                  N/A |
| 30%   36C    P2   179W / 300W |   7273MiB / 49140MiB |     81%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA RTX A6000    Off  | 00000000:24:00.0 Off |                  N/A |
| 30%   35C    P2   165W / 300W |  10553MiB / 49140MiB |     82%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA RTX A6000    Off  | 00000000:41:00.0 Off |                  Off |
| 30%   36C    P2   171W / 300W |   7307MiB / 49140MiB |     86%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA RTX A6000    Off  | 00000000:61:00.0 Off |                  Off |
| 30%   37C    P2   178W / 300W |   9865MiB / 49140MiB |     91%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

However, if we try setting the `CUDA_VISIBLE_DEVICES` in the script via `os.environ`:
```python
def main():
    os.environ["CUDA_VISIBLE_DEVICES"] = "0,1,2,3"
    # ...
```

It will cause an error:
```
torch.cuda.DeferredCudaCallError: CUDA call failed lazily at initialization with error: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at "../aten/src/ATen/cuda/CUDAContext.cpp":50, please report a bug to PyTorch. 
```

Full error:
```
CUDA call was originally invoked at:

['  File "/home/username/.pyenv/versions/3.8.16/lib/python3.8/runpy.py", line 194, in _run_module_as_main\n    return _run_code(code, main_globals, None,\n', '  File "/home/username/.pyenv/versions/3.8.16/lib/python3.8/runpy.py", line 87, in _run_code\n    exec(code, run_globals)\n', '  File "/home/username/dev/simple-seq2seq-trainer-example/run.py", line 5, in <module>\n    import torch\n', '  File "<frozen importlib._bootstrap>", line 991, in _find_and_load\n', '  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked\n', '  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked\n', '  File "<frozen importlib._bootstrap_external>", line 843, in exec_module\n', '  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed\n', '  File "/home/username/dev/simple-seq2seq-trainer-example/venv/lib/python3.8/site-packages/torch/__init__.py", line 1146, in <module>\n    _C._initExtension(manager_path())\n', '  File "<frozen importlib._bootstrap>", line 991, in _find_and_load\n', '  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked\n', '  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked\n', '  File "<frozen importlib._bootstrap_external>", line 843, in exec_module\n', '  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed\n', '  File "/home/username/dev/simple-seq2seq-trainer-example/venv/lib/python3.8/site-packages/torch/cuda/__init__.py", line 197, in <module>\n    _lazy_call(_check_capability)\n', '  File "/home/username/dev/simple-seq2seq-trainer-example/venv/lib/python3.8/site-packages/torch/cuda/__init__.py", line 195, in _lazy_call\n    _queued_calls.append((callable, traceback.format_stack()))\n']
Traceback (most recent call last):
  File "/home/username/dev/simple-seq2seq-trainer-example/venv/lib/python3.8/site-packages/torch/cuda/__init__.py", line 260, in _lazy_init
    queued_call()
  File "/home/username/dev/simple-seq2seq-trainer-example/venv/lib/python3.8/site-packages/torch/cuda/__init__.py", line 145, in _check_capability
    capability = get_device_capability(d)
  File "/home/username/dev/simple-seq2seq-trainer-example/venv/lib/python3.8/site-packages/torch/cuda/__init__.py", line 381, in get_device_capability
    prop = get_device_properties(device)
  File "/home/username/dev/simple-seq2seq-trainer-example/venv/lib/python3.8/site-packages/torch/cuda/__init__.py", line 399, in get_device_properties
    return _get_device_properties(device)  # type: ignore[name-defined]
RuntimeError: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at "../aten/src/ATen/cuda/CUDAContext.cpp":50, please report a bug to PyTorch. 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/username/.pyenv/versions/3.8.16/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/username/.pyenv/versions/3.8.16/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/username/dev/simple-seq2seq-trainer-example/run.py", line 67, in <module>
    main()
  File "/home/username/dev/simple-seq2seq-trainer-example/run.py", line 27, in main
    accelerator = Accelerator()
  File "/home/username/dev/simple-seq2seq-trainer-example/venv/lib/python3.8/site-packages/accelerate/accelerator.py", line 364, in __init__
    self.state = AcceleratorState(
  File "/home/username/dev/simple-seq2seq-trainer-example/venv/lib/python3.8/site-packages/accelerate/state.py", line 724, in __init__
    PartialState(cpu, **kwargs)
  File "/home/username/dev/simple-seq2seq-trainer-example/venv/lib/python3.8/site-packages/accelerate/state.py", line 200, in __init__
    torch.cuda.set_device(self.device)
  File "/home/username/dev/simple-seq2seq-trainer-example/venv/lib/python3.8/site-packages/torch/cuda/__init__.py", line 350, in set_device
    torch._C._cuda_setDevice(device)
  File "/home/username/dev/simple-seq2seq-trainer-example/venv/lib/python3.8/site-packages/torch/cuda/__init__.py", line 264, in _lazy_init
    raise DeferredCudaCallError(msg) from e
torch.cuda.DeferredCudaCallError: CUDA call failed lazily at initialization with error: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at "../aten/src/ATen/cuda/CUDAContext.cpp":50, please report a bug to PyTorch. 
```

### Expected behavior

We should be able to specify the GPUs IDs being used, either inside the Trainer, or via `os.environ`, as mentioned in [this comment](https://discuss.huggingface.co/t/how-to-use-specified-gpus-with-accelerator-to-train-the-model/10967/15). Using the command line `--gpu_ids` would not make it compatible with tools like `hydra`, which relies on a `cfg` accessed in the `main(cfg)` function.

If there are technical limitations, there should be a way to notify the user that this is not possible through an explicit Exception, as the current error messages do not help and may waste many hours of debugging.

**Comment by muellerzr** [comment]
As you mentioned, this is a technical limitation that requires careful setup. You can see an example with hydra here: https://github.com/yuvalkirstain/PickScore/tree/main

**Comment by muellerzr** [comment]
Which if you notice, requires the use of `submitit`/SLURM, as you can't control this from inside the python instance (and why torch gives you a very clear error about the device not being able to be called because the starting device, and ending device numbers differ)
