### ISSUE TITLE
gil problem when using multiple gpu 

### ISSUE THREAD

**Issue by tianlianghai** [huggingface/accelerate#1923]
### System Info

```Shell
- `Accelerate` version: 0.22.0
- Platform: Linux-4.15.0-200-generic-x86_64-with-glibc2.27
- Python version: 3.10.12
- Numpy version: 1.24.1
- PyTorch version (GPU?): 2.1.0.dev20230901+cu118 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 377.58 GB
- GPU type: Tesla V100-PCIE-16GB-LS
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: MULTI_GPU
        - mixed_precision: fp16
        - use_cpu: False
        - debug: False
        - num_processes: 2
        - machine_rank: 0
        - num_machines: 1
        - gpu_ids: all
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

      import torch
      import torch.nn as nn
      import torch.optim as optim
      from torchvision import datasets, transforms
      from torch.utils.data import DataLoader
      from tqdm.auto import tqdm
      from accelerate import Accelerator
      # from torchvision.utils import make_grid
      import torch.distributed
      
      
      def conv_bn_act(in_channels, out_channels):
          return nn.Sequential(
              nn.Conv2d(in_channels, out_channels, 3, 1, 1, bias=False),
              nn.BatchNorm2d(out_channels),
              nn.ReLU6(inplace=True)
          )
      
      
      class MyModel(nn.Module):
          block_settings = [32, 64, 128]
          def __init__(self, img_channels = 1, *args, **kwargs) -> None:
              super().__init__(*args, **kwargs)
              in_channels = 32
              self.bn = nn.BatchNorm2d(img_channels)
              self.conv1 = conv_bn_act(img_channels, in_channels)
              self.pool = nn.MaxPool2d(2)
              self.layers = nn.ModuleList()
              for block_channel in self.block_settings:
                  self.layers.append(conv_bn_act(in_channels, block_channel))
                  self.layers.append(nn.MaxPool2d(2))
                  in_channels = block_channel
              self.cls = nn.Sequential(
                  nn.AdaptiveAvgPool2d(1),
                  
                  nn.Flatten(),
                  nn.Linear(128, 10)
              )
                  
          def forward(self, x):
              x = self.bn(x)
              x = self.conv1(x)
              x = self.pool(x)
              for layer in self.layers:
                  x = layer(x)
                  
              x = self.cls(x)
              return x
          
      def process_batch(data):
          x1, y1 = data[0]
          x2, y2 =  data[1]
         
          
      def main():
          accelerator = Accelerator()
          # Define the transformations
          transform = transforms.Compose([
              transforms.RandomResizedCrop(28, scale=(0.64,1)),
              transforms.ToTensor()])
          val_transform = transforms.ToTensor()
          # Create datasets and data loaders
          train_set = datasets.FashionMNIST("/root/data", train=True, transform=transform, download=True)
          val_set = datasets.FashionMNIST('/root/data', train=False, transform=val_transform, download=True)
      
          batch_size = 128
          num_workers=4
          train_loader = DataLoader(train_set, batch_size=batch_size, shuffle=True, drop_last=True, num_workers=num_workers, persistent_workers=True)
          
          val_loader = DataLoader(val_set, batch_size=batch_size, shuffle=False, drop_last=False, num_workers=num_workers)
          print(f'there are {len(train_set.classes)} classes')
          # Initialize the model, loss function, and optimizer
          # model = resnet18(num_classes=len(train_set.classes))
          model = MyModel()
          # model = nn.SyncBatchNorm.convert_sync_batchnorm(model)
          criterion = nn.CrossEntropyLoss()
          optimizer = optim.Adam(model.parameters(), lr=0.001)
      
          model, optimizer, train_loader, val_loader = accelerator.prepare(model, optimizer, train_loader, val_loader)
          # Training loop
          num_epochs = 100
          for epoch in range(num_epochs):
              model.train()
              running_loss = 0.0
              train_bar = tqdm(train_loader, ncols=100, disable=not accelerator.is_local_main_process)
              # train_bar = tqdm(zip(train_loader, train_loader), ncols=100)
              
              # train_bar = tqdm(train_loader, ncols=100)
              
              # for (images, labels), (_, _) in train_bar:
              for images, labels in train_bar:
                  optimizer.zero_grad()
                  outputs = model(images)
                  loss = criterion(outputs, labels)           
      
                  
              # for (images, labels) in train_bar:
              #     optimizer.zero_grad()
              #     outputs = model(images)
              #     loss = criterion(outputs, labels)
                  # torch.distributed.barrier()
                  
                  # accelerator.wait_for_everyone()
                  accelerator.backward(loss)
                  optimizer.step()
                  running_loss += loss.item()
                  train_bar.set_description_str(f'{loss.item()}')
                  
              
              # Print training loss for this epoch
              print(f"Epoch {epoch+1}/{num_epochs}, Loss: {running_loss / len(train_loader)}")
      
              # Validation loop
              model.eval()
              correct = 0
              total = 0
              with torch.no_grad():
                  for images, labels in val_loader:
                      outputs = model(images)
                      _, predicted = torch.max(outputs.data, 1)
                      total += labels.size(0)
                      correct += (predicted == labels).sum().item()
      
              # Calculate validation accuracy
              accuracy = 100 * correct / total
              print(f"Validation Accuracy: {accuracy:.2f}%")
      
      if __name__ == '__main__':
          # torch.autograd.set_detect_anomaly(True)
          main()

### Expected behavior

After training for a while (randomly, could be long or short), it report a GIL problem, and terminate training.
i tried use wait_for_everyone, tune num_workers to 1 or 4, this still happen.

      (nightly) root@094a3af38c4f:~/code/tlhengine# accelerate launch demo/use_accelerate.py 
      there are 10 classes
      there are 10 classes
      0.5631638169288635:  97%|███████████████████████████████████████▉ | 228/234 [00:07<00:00, 62.40it/s]Epoch 1/100, Loss: 0.5761416672896116
      0.4797173738479614: 100%|█████████████████████████████████████████| 234/234 [00:07<00:00, 30.17it/s]
      Epoch 1/100, Loss: 0.5743326854247314
      Validation Accuracy: 86.04%
      Validation Accuracy: 86.15%
      0.38343197107315063: 100%|████████████████████████████████████████| 234/234 [00:03<00:00, 66.41it/s]
      Epoch 2/100, Loss: 0.4051745284316886
      Epoch 2/100, Loss: 0.40634573760450393
      Validation Accuracy: 86.99%
      Validation Accuracy: 87.23%
      0.2712210416793823:  97%|███████████████████████████████████████▉ | 228/234 [00:03<00:00, 66.90it/s]Epoch 3/100, Loss: 0.3669060920802956
      0.2688101828098297: 100%|█████████████████████████████████████████| 234/234 [00:03<00:00, 66.87it/s]
      Epoch 3/100, Loss: 0.3674185712877502
      Validation Accuracy: 88.38%
      Validation Accuracy: 89.06%
      0.22112873196601868:  38%|███████████████▌                         | 89/234 [00:01<00:02, 63.99it/s]Fatal Python error: take_gil: PyCOND_WAIT(gil->cond) failed
      Python runtime state: initialized
      
      Thread 0x00007f7fb6ffd700 (most recent call first):
        <no Python frame>
      
      Thread 0x00007f7fb77fe700 (most recent call first):
        <no Python frame>
      
      Thread 0x00007f7fb7fff700 (most recent call first):
        File "/root/env/mamba/envs/nightly/lib/python3.10/threading.py", line 320 in wait
        File "/root/env/mamba/envs/nightly/lib/python3.10/multiprocessing/queues.py", line 231 in _feed
        File "/root/env/mamba/envs/nightly/lib/python3.10/threading.py", line 953 in run
        File "/root/env/mamba/envs/nightly/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
        File "/root/env/mamba/envs/nightly/lib/python3.10/threading.py", line 973 in _bootstrap
      
      Thread 0x00007f7fecb21700 (most recent call first):
        File "/root/env/mamba/envs/nightly/lib/python3.10/threading.py", line 320 in wait
        File "/root/env/mamba/envs/nightly/lib/python3.10/multiprocessing/queues.py", line 231 in _feed
        File "/root/env/mamba/envs/nightly/lib/python3.10/threading.py", line 953 in run
        File "/root/env/mamba/envs/nightly/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
        File "/root/env/mamba/envs/nightly/lib/python3.10/threading.py", line 973 in _bootstrap
      
      Thread 0x00007f7fed322700 (most recent call first):
        File "/root/env/mamba/envs/nightly/lib/python3.10/threading.py", line 320 in wait
        File "/root/env/mamba/envs/nightly/lib/python3.10/multiprocessing/queues.py", line 231 in _feed
        File "/root/env/mamba/envs/nightly/lib/python3.10/threading.py", line 953 in run
        File "/root/env/mamba/envs/nightly/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
        File "/root/env/mamba/envs/nightly/lib/python3.10/threading.py", line 973 in _bootstrap
      
      Current thread 0x00007f8004903700 (most recent call first):
        File "/root/env/mamba/envs/nightly/lib/python3.10/threading.py", line 320 in wait
        File "/root/env/mamba/envs/nightly/lib/python3.10/multiprocessing/queues.py", line 231 in _feed
        File "/root/env/mamba/envs/nightly/lib/python3.10/threading.py", line 953 in run
        File "/root/env/mamba/envs/nightly/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
        File "/root/env/mamba/envs/nightly/lib/python3.10/threading.py", line 973 in _bootstrap
      
      Thread 0x00007f8006908700 (most recent call first):
        File "/root/env/mamba/envs/nightly/lib/python3.10/threading.py", line 324 in wait
        File "/root/env/mamba/envs/nightly/lib/python3.10/threading.py", line 607 in wait
        File "/root/env/mamba/envs/nightly/lib/python3.10/site-packages/tqdm/_monitor.py", line 60 in run
        File "/root/env/mamba/envs/nightly/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
        File "/root/env/mamba/envs/nightly/lib/python3.10/threading.py", line 973 in _bootstrap
      
      Thread 0x00007f80bd226740 (most recent call first):
        File "/root/env/mamba/envs/nightly/lib/python3.10/site-packages/torch/_ops.py", line 448 in __call__
        File "/root/env/mamba/envs/nightly/lib/python3.10/site-packages/torch/autograd/profiler.py", line 648 in __exit__
        File "/root/env/mamba/envs/nightly/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 626 in __next__
        File "/root/env/mamba/envs/nightly/lib/python3.10/site-packages/accelerate/data_loader.py", line 394 in __iter__
        File "/root/env/mamba/envs/nightly/lib/python3.10/site-packages/tqdm/std.py", line 1170 in __iter__
        File "/root/code/tlhengine/demo/use_accelerate.py", line 91 in main
        File "/root/code/tlhengine/demo/use_accelerate.py", line 130 in <module>
      
      Extension modules: numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, torch._C, torch._C._fft, torch._C._linalg, torch._C._nested, torch._C._nn, torch._C._sparse, torch._C._special, PIL._imaging, PIL._imagingft, yaml._yaml (total: 23)
      [2023-09-02 21:57:57,793] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 23917 closing signal SIGTERM
      [2023-09-02 21:57:58,008] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: -6) local_rank: 1 (pid: 23918) of binary: /root/env/mamba/envs/nightly/bin/python3.10
      Traceback (most recent call last):
        File "/root/env/mamba/envs/nightly/bin/accelerate", line 8, in <module>
          sys.exit(main())
        File "/root/env/mamba/envs/nightly/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
          args.func(args)
        File "/root/env/mamba/envs/nightly/lib/python3.10/site-packages/accelerate/commands/launch.py", line 977, in launch_command
          multi_gpu_launcher(args)
        File "/root/env/mamba/envs/nightly/lib/python3.10/site-packages/accelerate/commands/launch.py", line 646, in multi_gpu_launcher
          distrib_run.run(args)
        File "/root/env/mamba/envs/nightly/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
          elastic_launch(
        File "/root/env/mamba/envs/nightly/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
          return launch_agent(self._config, self._entrypoint, list(args))
        File "/root/env/mamba/envs/nightly/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
          raise ChildFailedError(
      torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
      ======================================================
      demo/use_accelerate.py FAILED
      ------------------------------------------------------
      Failures:
        <NO_OTHER_FAILURES>

**Comment by muellerzr** [comment]
Can you perhaps try running again with `ACCELERATE_DEBUG_MODE=1`? This *might* give us a different trace. Thanks for the clear report!

**Comment by tianlianghai** [comment]
should i set it in sys env or accelerate env?

**Comment by tianlianghai** [comment]
i set both but i don't see any futher error info
    compute_environment: LOCAL_MACHINE
    debug: true
    distributed_type: MULTI_GPU
    downcast_bf16: 'no'
    gpu_ids: all
    machine_rank: 0
    main_training_function: main
    mixed_precision: fp16
    num_machines: 1
    num_processes: 2
    rdzv_backend: static
    same_network: true
    tpu_env: []
    tpu_use_cluster: false
    tpu_use_sudo: false
    use_cpu: false
    # ACCELERATE_DEBUG_MODE: 1
  
  
  (nightly) root@094a3af38c4f:~/code/tlhengine# ACCELERATE_DEBUG_MODE=1 accelerate launch demo/use_accelerate.py 
  Traceback (most recent call last):
    File "/root/env/mamba/envs/nightly/bin/accelerate", line 8, in <module>
      sys.exit(main())
    File "/root/env/mamba/envs/nightly/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
      args.func(args)
    File "/root/env/mamba/envs/nightly/lib/python3.10/site-packages/accelerate/commands/launch.py", line 964, in launch_command
      args, defaults, mp_from_config_flag = _validate_launch_command(args)
    File "/root/env/mamba/envs/nightly/lib/python3.10/site-packages/accelerate/commands/launch.py", line 821, in _validate_launch_command
      defaults = load_config_from_file(args.config_file)
    File "/root/env/mamba/envs/nightly/lib/python3.10/site-packages/accelerate/commands/config/config_args.py", line 72, in load_config_from_file
      return config_class.from_yaml_file(yaml_file=config_file)
    File "/root/env/mamba/envs/nightly/lib/python3.10/site-packages/accelerate/commands/config/config_args.py", line 140, in from_yaml_file
      return cls(**config_dict)
  TypeError: ClusterConfig.__init__() got an unexpected keyword argument 'ACCELERATE_DEBUG_MODE'
  (nightly) root@094a3af38c4f:~/code/tlhengine# ACCELERATE_DEBUG_MODE=1 accelerate launch demo/use_accelerate.py 
  there are 10 classes
  there are 10 classes
  0.5035167932510376:  98%|████████████████████████████████████████▎| 230/234 [00:07<00:00, 65.04it/s]Epoch 1/100, Loss: 0.5808913645326582
  0.48801320791244507: 100%|████████████████████████████████████████| 234/234 [00:07<00:00, 29.43it/s]
  Epoch 1/100, Loss: 0.5838512933661795
  Validation Accuracy: 85.68%
    0%|                                                                       | 0/234 [00:00<?, ?it/s]Validation Accuracy: 85.86%
  0.42275989055633545:  97%|██████████████████████████████████████▋ | 226/234 [00:03<00:00, 66.16it/s]Epoch 2/100, Loss: 0.4068261887400578
  0.38834309577941895: 100%|████████████████████████████████████████| 234/234 [00:03<00:00, 62.27it/s]
  Epoch 2/100, Loss: 0.4085390548675488
  Validation Accuracy: 87.03%
    0%|                                                                       | 0/234 [00:00<?, ?it/s]Validation Accuracy: 87.17%
  0.28061729669570923:  97%|██████████████████████████████████████▋ | 226/234 [00:03<00:00, 66.30it/s]Epoch 3/100, Loss: 0.3677534813172797
  0.3418693244457245: 100%|█████████████████████████████████████████| 234/234 [00:03<00:00, 65.03it/s]
  Epoch 3/100, Loss: 0.3667591916572334
  Validation Accuracy: 89.08%
    0%|                                                                       | 0/234 [00:00<?, ?it/s]Validation Accuracy: 88.54%
  0.31929463148117065:  58%|███████████████████████▏                | 136/234 [00:02<00:01, 70.37it/s]Fatal Python error: take_gil: PyCOND_WAIT(gil->cond) failed
  Python runtime state: initialized
  
  Thread 0x00007f6dfaffd700 (most recent call first):
    <no Python frame>
  
  Thread 0x00007f6dfb7fe700 (most recent call first):
    <no Python frame>
  
  Thread 0x00007f6dfbfff700 (most recent call first):
    File "/root/env/mamba/envs/nightly/lib/python3.10/threading.py", line 320 in wait
    File "/root/env/mamba/envs/nightly/lib/python3.10/multiprocessing/queues.py", line 231 in _feed
    File "/root/env/mamba/envs/nightly/lib/python3.10/threading.py", line 953 in run
    File "/root/env/mamba/envs/nightly/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
    File "/root/env/mamba/envs/nightly/lib/python3.10/threading.py", line 973 in _bootstrap
  
  Thread 0x00007f6e34b21700 (most recent call first):
    File "/root/env/mamba/envs/nightly/lib/python3.10/threading.py", line 320 in wait
    File "/root/env/mamba/envs/nightly/lib/python3.10/multiprocessing/queues.py", line 231 in _feed
    File "/root/env/mamba/envs/nightly/lib/python3.10/threading.py", line 953 in run
    File "/root/env/mamba/envs/nightly/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
    File "/root/env/mamba/envs/nightly/lib/python3.10/threading.py", line 973 in _bootstrap
  
  Current thread 0x00007f6e35322700 (most recent call first):
    File "/root/env/mamba/envs/nightly/lib/python3.10/threading.py", line 320 in wait
    File "/root/env/mamba/envs/nightly/lib/python3.10/multiprocessing/queues.py", line 231 in _feed
    File "/root/env/mamba/envs/nightly/lib/python3.10/threading.py", line 953 in run
    File "/root/env/mamba/envs/nightly/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
    File "/root/env/mamba/envs/nightly/lib/python3.10/threading.py", line 973 in _bootstrap
  
  Thread 0x00007f6e50916700 (most recent call first):
    File "/root/env/mamba/envs/nightly/lib/python3.10/threading.py", line 320 in wait
    File "/root/env/mamba/envs/nightly/lib/python3.10/multiprocessing/queues.py", line 231 in _feed
    File "/root/env/mamba/envs/nightly/lib/python3.10/threading.py", line 953 in run
    File "/root/env/mamba/envs/nightly/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
    File "/root/env/mamba/envs/nightly/lib/python3.10/threading.py", line 973 in _bootstrap
  
  Thread 0x00007f6e5211a700 (most recent call first):
    File "/root/env/mamba/envs/nightly/lib/python3.10/threading.py", line 324 in wait
    File "/root/env/mamba/envs/nightly/lib/python3.10/threading.py", line 607 in wait
    File "/root/env/mamba/envs/nightly/lib/python3.10/site-packages/tqdm/_monitor.py", line 60 in run
    File "/root/env/mamba/envs/nightly/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
    File "/root/env/mamba/envs/nightly/lib/python3.10/threading.py", line 973 in _bootstrap
  
  Thread 0x00007f6f051a1740 (most recent call first):
    File "/root/env/mamba/envs/nightly/lib/python3.10/site-packages/torch/_ops.py", line 448 in __call__
    File "/root/env/mamba/envs/nightly/lib/python3.10/site-packages/torch/autograd/profiler.py", line 648 in __exit__
    File "/root/env/mamba/envs/nightly/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 626 in __next__
    File "/root/env/mamba/envs/nightly/lib/python3.10/site-packages/accelerate/data_loader.py", line 394 in __iter__
    File "/root/env/mamba/envs/nightly/lib/python3.10/site-packages/tqdm/std.py", line 1182 in __iter__
    File "/root/code/tlhengine/demo/use_accelerate.py", line 91 in main
    File "/root/code/tlhengine/demo/use_accelerate.py", line 130 in <module>
  
  Extension modules: numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, torch._C, torch._C._fft, torch._C._linalg, torch._C._nested, torch._C._nn, torch._C._sparse, torch._C._special, PIL._imaging, PIL._imagingft, yaml._yaml (total: 23)
  [2023-09-02 22:20:29,199] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 44187 closing signal SIGTERM
  [2023-09-02 22:20:29,364] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: -6) local_rank: 0 (pid: 44186) of binary: /root/env/mamba/envs/nightly/bin/python3.10
  Traceback (most recent call last):
    File "/root/env/mamba/envs/nightly/bin/accelerate", line 8, in <module>
      sys.exit(main())
    File "/root/env/mamba/envs/nightly/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
      args.func(args)
    File "/root/env/mamba/envs/nightly/lib/python3.10/site-packages/accelerate/commands/launch.py", line 977, in launch_command
      multi_gpu_launcher(args)
    File "/root/env/mamba/envs/nightly/lib/python3.10/site-packages/accelerate/commands/launch.py", line 646, in multi_gpu_launcher
      distrib_run.run(args)
    File "/root/env/mamba/envs/nightly/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
      elastic_launch(
    File "/root/env/mamba/envs/nightly/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
      return launch_agent(self._config, self._entrypoint, list(args))
    File "/root/env/mamba/envs/nightly/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
      raise ChildFailedError(
  torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
  ======================================================
  demo/use_accelerate.py FAILED
  ------------------------------------------------------
  Failures:
    <NO_OTHER_FAILURES>
  ------------------------------------------------------
  Root Cause (first observed failure):
  [0]:
    time      : 2023-09-02_22:20:29
    host      : 094a3af38c4f
    rank      : 0 (local_rank: 0)
    exitcode  : -6 (pid: 44186)
    error_file: <N/A>
    traceback : Signal 6 (SIGABRT) received by PID 44186
  ======================================================

**Comment by tianlianghai** [comment]
I've also tuned the debug in config to true, but don't see any further debug info in the output
    compute_environment: LOCAL_MACHINE
    debug: true
    distributed_type: MULTI_GPU
    downcast_bf16: 'no'
    gpu_ids: all
    machine_rank: 0
    main_training_function: main
    mixed_precision: fp16
    num_machines: 1
    num_processes: 2
    rdzv_backend: static
    same_network: true
    tpu_env: []
    tpu_use_cluster: false
    tpu_use_sudo: false
    use_cpu: false
    # ACCELERATE_DEBUG_MODE: 1

**Comment by tianlianghai** [comment]
thanks for your help, I solved this problem by reinstall pytorch with pip, installing pytorch with conda lead to this problem and a slower training speed for unknown reason.

**Comment by tianlianghai** [comment]
thanks for your help, I solved this problem by reinstall pytorch with pip, installing pytorch with conda lead to this problem and a slower training speed for unknown reason.

**Comment by AisingioroHao0** [comment]
@muellerzr Hi, I have a similar problem when using "with accelerator.main_process_first()". I need to call datasets.map in the main process. It takes a lot of time and causes a timeout error. Is there any way to avoid it? My current solution is to train on a single GPU first, then force quit the datasets.map and then train on multiple GPUs, which is a bit troublesome.

**Comment by muellerzr** [comment]
You can expand the timeout parameter argument. See `DistributedDataParallelKwargs` iirc and pass this to the `Accelerator`

**Comment by AisingioroHao0** [comment]
@muellerzr I didn't see this parameter in the constructor of DistributedDataParallelKwargs

**Comment by muellerzr** [comment]
Apologies @aihao2000, you should use the `InitProcessGroupKwargs` with the `timeout` parameter
