### ISSUE TITLE
ModuleNotFoundError: No module named 'omegaconf'

### ISSUE THREAD

**Issue by lcmmai** [huggingface/accelerate#1928]
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    from omegaconf import OmegaConf
ModuleNotFoundError: No module named 'omegaconf'

It can work when I use "python main.py", but report this Error when I use "accelerate launch main.py".
I have downloaded 'omegaconf', and I do not know why it appears.

All error information:
(lora) jingbang@AmaxTRT:/data/Limo/mydiffusion$ CUDA_VISIBLE_DEVICES=0,1 accelerate launch main.py
The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `2`
		More than one GPU was found, enabling multi-GPU training.
		If this was unintended please pass in `--num_processes=1`.
	`--num_machines` was set to a value of `1`
	`--mixed_precision` was set to a value of `'no'`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    from omegaconf import OmegaConf
ModuleNotFoundError: No module named 'omegaconf'
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    from omegaconf import OmegaConf
ModuleNotFoundError: No module named 'omegaconf'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 98106) of binary: /home/ruitao/anaconda3/bin/python
Traceback (most recent call last):
  File "/home/jingbang/.local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/jingbang/.local/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/jingbang/.local/lib/python3.8/site-packages/accelerate/commands/launch.py", line 977, in launch_command
    multi_gpu_launcher(args)
  File "/home/jingbang/.local/lib/python3.8/site-packages/accelerate/commands/launch.py", line 646, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/jingbang/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/jingbang/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/jingbang/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py"

**Comment by lcmmai** [comment]
I have solved this problem. It requires activating the base environment and pip install omegaconf. It's really strange, maybe my Python level is not enough.
