### ISSUE TITLE
Accelerate FSDP throws error with BLOOM model: AttributeError: 'BloomForCausalLM' object has no attribute 'word_embeddings'

### ISSUE THREAD

**Issue by LuciusLan** [huggingface/accelerate#1945]
### System Info

```Shell
- `Accelerate` version: 0.22.0
- Platform: Linux-4.15.0-142-generic-x86_64-with-glibc2.27
- Python version: 3.10.12
- Numpy version: 1.25.2
- PyTorch version (GPU?): 2.0.1 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 376.55 GB
- GPU type: Tesla V100-PCIE-32GB

Accelerate Config:
`compute_environment: LOCAL_MACHINE
deepspeed_config: {}
distributed_type: FSDP
downcast_bf16: 'no'
fsdp_config:
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_backward_prefetch_policy: BACKWARD_PRE
  fsdp_offload_params: false
  fsdp_sharding_strategy: 1
  fsdp_state_dict_type: FULL_STATE_DICT
  fsdp_transformer_layer_cls_to_wrap: BloomBlock #LlamaDecoderLayer
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
mixed_precision: 'no'
num_machines: 1
num_processes: 2
use_cpu: false`
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

```
accelerator = Accelerator()
tokenizer = AutoTokenizer.from_pretrained('bigscience/bloomz-1b1')
model = AutoModelForCausalLM.from_pretrained('bigscience/bloomz-1b1')
```

Before even executing the `model=accelerator.prepare()` block, the scripts throws `AttributeError: 'BloomForCausalLM' object has no attribute 'word_embeddings'` at line 3. 

Following is traceback of the error
```
Traceback (most recent call last):
  File "/home/me/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 3489, in <module>
    main()
  File "/home/me/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 3482, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/me/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2510, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/home/me/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2517, in _exec
    globals = pydevd_runpy.run_path(file, globals, '__main__')
  File "/home/me/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/me/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/me/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "main.py", line 38, in <module>
    model = AutoModelForCausalLM.from_pretrained('bigscience/bloomz-1b1')
  File "/home/me/miniconda3/envs/py310/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 516, in from_pretrained
    return model_class.from_pretrained(
  File "/home/me/miniconda3/envs/py310/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3091, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/home/me/miniconda3/envs/py310/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3492, in _load_pretrained_model
    set_module_tensor_to_device(
  File "/home/me/miniconda3/envs/py310/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 265, in set_module_tensor_to_device
    new_module = getattr(module, split)
  File "/home/me/miniconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'BloomForCausalLM' object has no attribute 'word_embeddings'
```

### Expected behavior

I have run test with DeepSpeed, Default DDP strategies with the same piece of code and can train without any error or exception.

I have tried changing to SIZE_BASED_WRAP and the error preserves.

**When changing the `num_processes` from 2 to 1 in the config file (FSDP), the script can run without error.** I assume the error occurs at the very first step of sharding model across 2 gpus? I am totally clueless on what's going behind the distributed computing libraries and can't dig deeper into this

**Comment by pacman100** [comment]
Hello, this has been resolved by https://github.com/huggingface/transformers/pull/25820. Could you try using the main branch of Accelerate and Transformers?
