### ISSUE TITLE
TorchDynamo backends

### ISSUE THREAD

**Issue by pratogab** [huggingface/accelerate#1977]
### System Info

```Shell
accelerate v0.22.0
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

There seems to be a discrepancy between the backends listed on the torch doc and huggingface doc

According to the [doc](https://huggingface.co/docs/transformers/perf_train_gpu_one#using-torchcompile:~:text=Training%20%26%20inference%20backends%3A):
> **Training & inference backends:**  
dynamo.optimize("inductor") - Uses TorchInductor backend with AotAutograd and cudagraphs by leveraging codegened Triton kernels Read more  
dynamo.optimize("nvfuser") - nvFuser with TorchScript. Read more  
dynamo.optimize("aot_nvfuser") - nvFuser with AotAutograd. Read more  
dynamo.optimize("aot_cudagraphs") - cudagraphs with AotAutograd. Read more

But in the torch [doc](https://pytorch.org/docs/stable/dynamo/get-started.html#:~:text=Training%20%26%20inference%20backends%3A):
> **Training & inference backends:**  
torch.compile(m, backend="inductor") - Uses TorchInductor backend. Read more  
torch.compile(m, backend="aot_ts_nvfuser") - nvFuser with AotAutograd/TorchScript. Read more  
torch.compile(m, backend=""nvprims_nvfuser") - nvFuser with PrimTorch. Read more  
torch.compile(m, backend="cudagraphs") - cudagraphs with AotAutograd. Read more

Only `inductor` is common. Setting any other backend leads to an error. For example, setting `nvfuser` in the accelerate config results in:
```
Traceback (most recent call last):                                                                                                                                                                 
  File "example_script.py", line 314, in <module>
    main()                                                                                                                                                                                                 
  File "example_script.py", line 49, in main
    model, optimizer, lr_scheduler, train_dataloader, eval_dataloader = accelerator.prepare(model, optimizer, lr_scheduler, train_dataloader, eval_dataloader)
  File "/home/miniconda3/envs/hf-torch2/lib/python3.10/site-packages/accelerate/accelerator.py", line 1270, in prepare
    result = tuple(                                                                                                                                          
  File "/home/miniconda3/envs/hf-torch2/lib/python3.10/site-packages/accelerate/accelerator.py", line 1271, in <genexpr>                      
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)                             
  File "/home/miniconda3/envs/hf-torch2/lib/python3.10/site-packages/accelerate/accelerator.py", line 1083, in _prepare_one
    return self.prepare_model(obj, device_placement=device_placement)                                                                   
  File "/home/miniconda3/envs/hf-torch2/lib/python3.10/site-packages/accelerate/accelerator.py", line 1440, in prepare_model
    model = torch.compile(model, **self.state.dynamo_plugin.to_kwargs())                                                                   
  File "/home/miniconda3/envs/hf-torch2/lib/python3.10/site-packages/torch/__init__.py", line 1441, in compile
    return torch._dynamo.optimize(backend=backend, nopython=fullgraph, dynamic=dynamic, disable=disable)(model)                             
  File "/home/miniconda3/envs/hf-torch2/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 424, in optimize
    backend = get_compiler_fn(backend)                                                                                        
  File "/home/miniconda3/envs/hf-torch2/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 363, in get_compiler_fn
    compiler_fn = lookup_backend(compiler_fn)                                                                                           
  File "/home/miniconda3/envs/hf-torch2/lib/python3.10/site-packages/torch/_dynamo/backends/registry.py", line 59, in lookup_backend
    compiler_fn = _BACKENDS[compiler_fn]                                                                                                       
KeyError: 'nvfuser' 
```

and using a backend specified in the torch doc also results in an error:
```
Traceback (most recent call last):
  File "/home/miniconda3/envs/hf-torch2/lib/python3.10/site-packages/accelerate/utils/launch.py", line 90, in prepare_simple_launcher_cmd_env
    dynamo_backend = DynamoBackend(args.dynamo_backend.upper())
  File "/home/miniconda3/envs/hf-torch2/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/home/miniconda3/envs/hf-torch2/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 'AOT_TS_NVFUSER' is not a valid DynamoBackend
```

### Expected behavior

Accelerate should support the torchdynamo backends.

**Comment by SunMarc** [comment]
Hi @pratogab , thanks for the report. This should be fixed in the PR above.

**Comment by pratogab** [comment]
How is accelerate going to handle the customizing the settings of each individual backend if they offer different hyperparameters?

**Comment by SunMarc** [comment]
Hi @pratogab, we try to handle the most common settings. We welcome PR if you would like to contribute !
