### ISSUE TITLE
AssertionError: No inf checks were recorded for this optimizer.

### ISSUE THREAD

**Issue by ishaansharma** [huggingface/accelerate#1990]
### System Info

```Shell
- `Accelerate` version: 0.22.0
- Platform: Linux-6.2.0-31-generic-x86_64-with-glibc2.17
- Python version: 3.8.16
- Numpy version: 1.22.3
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 251.38 GB
- GPU type: NVIDIA GeForce RTX 3090
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: NO
        - mixed_precision: fp16
        - use_cpu: False
        - debug: False
        - num_processes: 1
        - machine_rank: 0
        - num_machines: 1
        - gpu_ids: all
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

I am trying to finetune a classification model from a custom falcon based pretrained model this code. 

```
def start_finetuning(resume_training=False):
<CODE>
    args = {
        "train_batch_size": TRAIN_BATCH_SIZE,
        "valid_batch_size": EVAL_BATCH_SIZE,
        "weight_decay": 0.01,
        "learning_rate": 5e-5,
        "lr_scheduler_type": "linear",
        "gradient_accumulation_steps": 1,
        "gradient_checkpointing": True,
        "num_warmup_steps": 5,
        "max_train_steps": 50,
        "max_eval_steps": 50,
        "seq_length": FINETUNE_SEQ_LENGTH,
        "seed": 42,
        "save_checkpoint_steps": 250,
    }

    # load_pretrained_tokenizer
    tokenizer = AutoTokenizer.from_pretrained(PRETRAINED_MODEL_NAME_PATH)
    tokenizer.pad_token = tokenizer.eos_token

    # Load pretrained model
    model = FalconForSequenceClassification.from_pretrained(
        PRETRAINED_MODEL_NAME_PATH, num_labels=15
    )
    model.config.pad_token_id = model.config.eos_token_id
    model.config.use_cache = False
    model.config.gradient_checkpointing = True

    accelerator = Accelerator()
    acc_state = {str(k): str(v) for k, v in accelerator.state.__dict__.items()}

    args = Namespace(**args, **acc_state)
    samples_per_step = accelerator.state.num_processes * args.train_batch_size
    set_seed(args.seed)

    if args.gradient_checkpointing:
        model.gradient_checkpointing_enable()

    optimizer = torch.optim.AdamW(
        get_grouped_params(args, model), lr=args.learning_rate
    )
    lr_scheduler = get_scheduler(
        name=args.lr_scheduler_type,
        optimizer=optimizer,
        num_warmup_steps=args.num_warmup_steps,
        num_training_steps=args.max_train_steps,
    )

    # Resume training from the last checkpoint
    if resume_training:
        # Load the last checkpoint
        model = FalconForSequenceClassification.from_pretrained(FINETUNED_MODEL_NAME_PATH)
        # model.load_state_dict(torch.load(os.path.join(FINETUNED_MODEL_NAME_PATH, 'model.pt')))
        optimizer.load_state_dict(
            torch.load(os.path.join(FINETUNED_MODEL_NAME_PATH, "optimizer.pt"))
        )
        optimizer.zero_grad(set_to_none=False)
        lr_scheduler.load_state_dict(
            torch.load(os.path.join(FINETUNED_MODEL_NAME_PATH, "scheduler.pt"))
        )

        print("optimizer: ",optimizer)
        # sys.exit()

    logger, tb_writer, run_name = setup_logging(
        args, accelerator, project_name.split("/")[1]
    )
    logger.info(accelerator.state)

    train_dataloader, eval_dataloader = create_dataloaders(args, DATASET)

    model, optimizer, train_dataloader, eval_dataloader = accelerator.prepare(
        model, optimizer, train_dataloader, eval_dataloader
    )

    # Train model
    model.train()
    completed_steps = 0

    for step, batch in enumerate(train_dataloader, start=1):
        if completed_steps >= args.max_train_steps:
            break
        inputs = tokenizer(
            batch["text"],
            padding="max_length",
            truncation=True,
            return_tensors="pt",
            max_length=args.seq_length,
        )
        labels = batch["label"].to(model.device)
        inputs = {k: v.to(model.device) for k, v in inputs.items()}
        outputs = model(**inputs, labels=labels)
        loss = outputs.loss
        loss = loss / args.gradient_accumulation_steps
        accelerator.backward(loss)
        log_metrics(
            step,
            {
                "lr": get_lr(optimizer),
                "samples": step * samples_per_step,
                "steps": completed_steps,
                "loss/train": loss.item(),
            },
            accelerator,
            tb_writer,
        )
        if step % args.gradient_accumulation_steps == 0:
            # accelerator.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            lr_scheduler.step()
            optimizer.zero_grad()
            completed_steps += 1
        if step % args.save_checkpoint_steps == 0:
            logging.info("Evaluating and saving model checkpoint")
            eval_loss, accuracy, precision, recall, f1 = evaluate(
                args, eval_dataloader, model, accelerator, tokenizer
            )
            log_metrics(
                step,
                {
                    "accuracy": accuracy,
                    "precision": precision,
                    "recall": recall,
                    "f1": f1,
                    "loss/eval": eval_loss,
                },
                accelerator,
                tb_writer,
            )
            accelerator.wait_for_everyone()
            unwrapped_model = accelerator.unwrap_model(model)
            
            if accelerator.is_main_process:
                # Save the model in the main folder
                save_model(
                    unwrapped_model,
                    optimizer,
                    lr_scheduler,
                    FINETUNED_MODEL_NAME_PATH,
                    step,
                )

                # Save the model in one of the checkpoint folders
                checkpoint_folder = os.path.join(
                    FINETUNED_MODEL_NAME_PATH,
                    f"checkpoint-{completed_steps // args.save_checkpoint_steps % 3}",
                )
                os.makedirs(checkpoint_folder, exist_ok=True)
                save_model(
                    unwrapped_model, optimizer, lr_scheduler, checkpoint_folder, step
                )
            model.train()
        
    # Evaluate and save the last checkpoint
    logging.info("Evaluating and saving model after training")
    eval_loss, accuracy, precision, recall, f1 = evaluate(
        args, eval_dataloader, model, accelerator, tokenizer
    )
    log_metrics(
        step,
        {
            "accuracy": accuracy,
            "precision": precision,
            "recall": recall,
            "f1": f1,
            "loss/eval": eval_loss,
        },
        accelerator,
        tb_writer,
    )
    accelerator.wait_for_everyone()
    unwrapped_model = accelerator.unwrap_model(model)
    if accelerator.is_main_process:
        save_model(
            unwrapped_model, optimizer, lr_scheduler, FINETUNED_MODEL_NAME_PATH, step
        )


if __name__ == "__main__":
    start_finetuning(resume_training=True)
```

### Expected behavior

When the finetuning code is run for the first time without resuming enabled its running without any error. 
but when I am trying to restart the training from the checkpoint by loading the optimizer its giving an error :

```
09/19/2023 17:13:19 - INFO - __main__ - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda

Mixed precision type: fp16

The current implementation of Falcon calls `torch.scaled_dot_product_attention` directly, this will be deprecated in the future in favor of the `BetterTransformer` API. Please install the latest optimum library with `pip install -U optimum` and call `model.to_bettertransformer()` to benefit from `torch.scaled_dot_product_attention` and future performance optimizations.
09/19/2023 17:13:21 - INFO - root - Step 1: {'lr': 0.0, 'samples': 1, 'steps': 0, 'loss/train': 1.2626953125}
Traceback (most recent call last):
  File "002_finetune_classification.py", line 526, in <module>
    start_finetuning(resume_training=True)
  File "002_finetune_classification.py", line 448, in start_finetuning
    optimizer.step()
  File "/home//miniconda3/envs/ailab/lib/python3.8/site-packages/accelerate/optimizer.py", line 132, in step
    self.scaler.step(self.optimizer, closure)
  File "/home//.local/lib/python3.8/site-packages/torch/cuda/amp/grad_scaler.py", line 372, in step
    assert len(optimizer_state["found_inf_per_device"]) > 0, "No inf checks were recorded for this optimizer."
AssertionError: No inf checks were recorded for this optimizer.
```

And when I have set mixed precision value as "no" of "bf16" in accelerate config . It is running but the learning rate is 0.0 throughout the training steps. Something like this :

```
09/19/2023 11:54:00 - INFO - __main__ - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cpu

Mixed precision type: bf16

The current implementation of Falcon calls `torch.scaled_dot_product_attention` directly, this will be deprecated in the future in favor of the `BetterTransformer` API. Please install the latest optimum library with `pip install -U optimum` and call `model.to_bettertransformer()` to benefit from `torch.scaled_dot_product_attention` and future performance optimizations.
09/19/2023 11:54:01 - INFO - root - Step 1: {'lr': 0.0, 'samples': 1, 'steps': 0, 'loss/train': 1.0519447326660156}
09/19/2023 11:54:01 - INFO - root - Step 2: {'lr': 0.0, 'samples': 2, 'steps': 1, 'loss/train': 0.24455031752586365}
09/19/2023 11:54:01 - INFO - root - Step 3: {'lr': 0.0, 'samples': 3, 'steps': 2, 'loss/train': 1.344581127166748}
09/19/2023 11:54:01 - INFO - root - Step 4: {'lr': 0.0, 'samples': 4, 'steps': 3, 'loss/train': 1.4392719268798828}
09/19/2023 11:54:02 - INFO - root - Step 5: {'lr': 0.0, 'samples': 5, 'steps': 4, 'loss/train': 1.6045118570327759}
09/19/2023 11:54:02 - INFO - root - Step 6: {'lr': 0.0, 'samples': 6, 'steps': 5, 'loss/train': 1.1934038400650024}
09/19/2023 11:54:02 - INFO - root - Step 7: {'lr': 0.0, 'samples': 7, 'steps': 6, 'loss/train': 0.31220710277557373}
09/19/2023 11:54:02 - INFO - root - Step 8: {'lr': 0.0, 'samples': 8, 'steps': 7, 'loss/train': 0.31070658564567566}
09/19/2023 11:54:03 - INFO - root - Step 9: {'lr': 0.0, 'samples': 9, 'steps': 8, 'loss/train': 0.35791054368019104}
09/19/2023 11:54:03 - INFO - root - Step 10: {'lr': 0.0, 'samples': 10, 'steps': 9, 'loss/train': 0.45526689291000366}
```

**Comment by ishaansharma** [comment]
@SunMarc let me know if I can help in anyway possible . 

> Hi @ishaansharma , thanks for reporting. There is indeed an issue when resuming the training. We will fix it asap.

**Comment by LWprogramming** [comment]
Hi, has there been any change to this bug as of the latest accelerate release in https://pypi.org/project/accelerate/0.24.0/?

**Comment by SunMarc** [comment]
Hi @LWprogramming , I've added more context in my previous messages. If you are able to provide a minimal reproducer, that would help a lot.

**Comment by SunMarc** [comment]
@ishaansharma, you are probably not saving it the right way. you should use `accelerate.save_state` instead. You can refer to this [example](https://github.com/huggingface/transformers/blob/main/examples/research_projects/codeparrot/scripts/codeparrot_training.py).

**Comment by ishaansharma** [comment]
This worked. Thanks @SunMarc . 

> @ishaansharma, you are probably not saving it the right way. you should use `accelerate.save_state` instead. You can refer to this [example](https://github.com/huggingface/transformers/blob/main/examples/research_projects/codeparrot/scripts/codeparrot_training.py).
