### ISSUE TITLE
[FP8] RuntimeError on dtype Mismatch in Llama2 Training with H100

### ISSUE THREAD

**Issue by adamlin120** [huggingface/accelerate#2039]
### System Info

```Shell
Accelerate Configuration:

Compute Environment: LOCAL_MACHINE
Distributed Type: DEEPSPEED
Mixed Precision: fp8
Num Machines: 2
Num Processes: 8


AWS Environment:

Node Configuration: 2 nodes of 8*H100
Communication: AWS EFA


DeepSpeed Configuration:

Gradient Accumulation Steps: Auto
Zero Stage: 2
Offload Optimizer Device: None
Offload Param Device: None
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

The scripts are modified from [Hugging Face's FSDP Blog](https://huggingface.co/blog/ram-efficient-pytorch-fsdp). The error can be reproduced with:

Deepspeed config
```yaml
compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  deepspeed_multinode_launcher: standard
  gradient_accumulation_steps: auto
  offload_optimizer_device: none
  offload_param_device: none
  zero3_init_flag: false
  zero_stage: 2
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
mixed_precision: 'fp8'
num_machines: 1
num_processes: 8
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

```bash
# Setting up environment variables and running the training
export LAUNCHER="accelerate launch \
    --config_file /apps/llm-training/trl/deepspeed_zero2.yaml \
    --main_process_ip $MASTER_ADDR \
    --main_process_port $MASTER_PORT \
    --machine_rank \$SLURM_PROCID \
    --num_processes $NUM_PROCESSES \
    --num_machines $NNODES \
    "

export PROGRAM="\
${PROJECT_DIR}/sft_trainer.py \
  --model_name meta-llama/Llama-2-7b-hf \
  --output_dir /fsx/LLM-7B-v2.0-chat \
  --seq_length 1024 \
  --num_train_epochs 3 \
  --gradient_accumulation_steps 8 \
  --batch_size 64 \
"
```

Error message:
```
0: Traceback (most recent call last):
0:   File "/apps/llm-training/trl//sft_trainer.py", line 411, in <module>
0:     trainer.train()
0:   File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1591, in train
0:     return inner_training_loop(
0:   File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1892, in _inner_training_loop
0:     tr_loss_step = self.training_step(model, inputs)
0:   File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 2776, in training_step
0:     loss = self.compute_loss(model, inputs)
0:   File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 2801, in compute_loss
0:     outputs = model(**inputs)
0:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1505, in _wrapped_call_impl
0:     return self._call_impl(*args, **kwargs)
0:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1514, in _call_impl
0:     return forward_call(*args, **kwargs)
0:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
0:     ret_val = func(*args, **kwargs)
0:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/engine.py", line 1801, in forward
0:     loss = self.module(*inputs, **kwargs)
0:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1505, in _wrapped_call_impl
0:     return self._call_impl(*args, **kwargs)
0:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1514, in _call_impl
0:     return forward_call(*args, **kwargs)
0:   File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/modeling_llama.py", line 1038, in forward
0:     outputs = self.model(
0:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1505, in _wrapped_call_impl
0:     return self._call_impl(*args, **kwargs)
0:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1514, in _call_impl
0:     return forward_call(*args, **kwargs)
0:   File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/modeling_llama.py", line 921, in forward
0:     layer_outputs = torch.utils.checkpoint.checkpoint(
0:   File "/usr/local/lib/python3.10/dist-packages/torch/_compile.py", line 24, in inner
0:     return torch._dynamo.disable(fn, recursive)(*args, **kwargs)
0:   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/eval_frame.py", line 294, in _fn
0:     return fn(*args, **kwargs)
0:   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/external_utils.py", line 17, in inner
0:     return fn(*args, **kwargs)
0:   File "/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py", line 440, in checkpoint
0:     return CheckpointFunction.apply(function, preserve, *args)
0:   File "/usr/local/lib/python3.10/dist-packages/torch/autograd/function.py", line 506, in apply
0:     return super().apply(*args, **kwargs)  # type: ignore[misc]
0:   File "/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py", line 223, in forward
0:     outputs = run_function(*args)
0:   File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/modeling_llama.py", line 917, in custom_forward
0:     return module(*inputs, past_key_value, output_attentions, padding_mask=padding_mask)
0:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1505, in _wrapped_call_impl
0:     return self._call_impl(*args, **kwargs)
0:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1514, in _call_impl
0:     return forward_call(*args, **kwargs)
0:   File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/modeling_llama.py", line 635, in forward
0:     hidden_states, self_attn_weights, present_key_value = self.self_attn(
0:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1505, in _wrapped_call_impl
0:     return self._call_impl(*args, **kwargs)
0:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1514, in _call_impl
0:     return forward_call(*args, **kwargs)
0:   File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/modeling_llama.py", line 494, in forward
0:     attn_output = self.o_proj(attn_output)
0:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1505, in _wrapped_call_impl
0:     return self._call_impl(*args, **kwargs)
0:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1514, in _call_impl
0:     return forward_call(*args, **kwargs)
0:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/linear.py", line 114, in forward
0:     return F.linear(input, self.weight, self.bias)
0: RuntimeError: expected mat1 and mat2 to have the same dtype, but got: c10::Half != float
```

### Expected behavior

I expect the training to proceed seamlessly using FP8 precision on  H100 without dtype issues.

**Comment by muellerzr** [comment]
@adamlin120 out of curiosity can you try again via `pip install git+https://github.com/huggingface/accelerate@fix-fp8`? I wonder if that also solved this issue

**Comment by PABannier** [comment]
@adamlin120 Were you able to solve the problem? I'm facing a similar issue (#3290 ).
