### ISSUE TITLE
accelerate launch error 

### ISSUE THREAD

**Issue by danyow-cheung** [huggingface/accelerate#2046]
### System Info

```Shell
- `Accelerate` version: 0.23.0
- Platform: Linux-6.2.0-32-generic-x86_64-with-glibc2.35
- Python version: 3.11.4
- Numpy version: 1.26.0
- PyTorch version (GPU?): 2.1.0+cu121 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 31.08 GB
- GPU type: NVIDIA GeForce RTX 4090
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: NO
        - mixed_precision: fp16
        - use_cpu: False
        - debug: False
        - num_processes: 1
        - machine_rank: 0
        - num_machines: 1
        - gpu_ids: 0
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
        - dynamo_config: {'dynamo_backend': 'INDUCTOR', 'dynamo_mode': 'default', 'dynamo_use_dynamic': True, 'dynamo_use_fullgraph': True}
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

followed by the link https://huggingface.co/docs/peft/task_guides/dreambooth_lora#fine-tuning-dreambooth
using  the scripts
```
accelerate launch train_dreambooth.py \
  --pretrained_model_name_or_path=$MODEL_NAME  \
  --instance_data_dir=$INSTANCE_DIR \
  --class_data_dir=$CLASS_DIR \
  --output_dir=$OUTPUT_DIR \
  --train_text_encoder \
  --with_prior_preservation --prior_loss_weight=1.0 \
  --instance_prompt="a photo of sks dog" \
  --class_prompt="a photo of dog" \
  --resolution=512 \
  --train_batch_size=1 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --num_class_images=200 \
  --use_lora \
  --lora_r 16 \
  --lora_alpha 27 \
  --lora_text_encoder_r 16 \
  --lora_text_encoder_alpha 17 \
  --learning_rate=1e-4 \
  --gradient_accumulation_steps=1 \
  --gradient_checkpointing \
  --max_train_steps=500
```

### Expected behavior

here is the full error log 

```
Traceback (most recent call last):
  File "/home/hs/combine_lora/peft/examples/lora_dreambooth/train_dreambooth.py", line 1092, in <module>
    main(args)
  File "/home/hs/combine_lora/peft/examples/lora_dreambooth/train_dreambooth.py", line 931, in main
    encoder_hidden_states = text_encoder(batch["input_ids"])[0]
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 328, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 490, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 133, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 389, in _convert_frame_assert
    return _compile(
           ^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 569, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/utils.py", line 189, in time_wrapper
    r = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 491, in compile_inner
    out_code = transform_code_object(code, transform)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/bytecode_transformation.py", line 1028, in transform_code_object
    transformations(instructions, code_options)
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 458, in transform
    tracer.run()
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2074, in run
    super().run()
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 724, in run
    and self.step()
        ^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 688, in step
    getattr(self, inst.opname)(inst)
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 392, in wrapper
    return inner_fn(self, inst)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 1155, in CALL_FUNCTION_EX
    self.call_function(fn, argsvars.items, kwargsvars.items)
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 562, in call_function
    self.push(fn.call_function(self, args, kwargs))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/variables/user_defined.py", line 383, in call_function
    return self.call_method(tx, "__call__", args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/variables/user_defined.py", line 301, in call_method
    ).call_function(tx, args, kwargs)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/variables/functions.py", line 307, in call_function
    return super().call_function(tx, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/variables/functions.py", line 261, in call_function
    return super().call_function(tx, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/variables/functions.py", line 90, in call_function
    return tx.inline_user_function_return(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 598, in inline_user_function_return
    result = InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2179, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2286, in inline_call_
    tracer.run()
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 724, in run
    and self.step()
        ^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 688, in step
    getattr(self, inst.opname)(inst)
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 392, in wrapper
    return inner_fn(self, inst)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 1155, in CALL_FUNCTION_EX
    self.call_function(fn, argsvars.items, kwargsvars.items)
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 562, in call_function
    self.push(fn.call_function(self, args, kwargs))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/variables/functions.py", line 261, in call_function
    return super().call_function(tx, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/variables/functions.py", line 90, in call_function
    return tx.inline_user_function_return(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 598, in inline_user_function_return
    result = InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2179, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2232, in inline_call_
    InliningInstructionTranslator.check_inlineable(func)
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2213, in check_inlineable
    unimplemented(
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/exc.py", line 172, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: inline in skipfiles: PeftModel.forward  | decorate_autocast /home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/amp/autocast_mode.py

from user code:
   File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/accelerate/utils/operations.py", line 636, in forward
    return model_forward(*args, **kwargs)
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/accelerate/utils/operations.py", line 624, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

Steps:   0%|                                                                                                                                    | 0/500 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/hs/combine_lora/lora_venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/accelerate/commands/launch.py", line 986, in launch_command
    simple_launcher(args)
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/hs/combine_lora/lora_venv/bin/python', 'train_dreambooth.py', '--pretrained_model_name_or_path=/home/hs/combine_lora/peft/stable-diffusion-v1-5', '--instance_data_dir=/home/hs/combine_lora/peft/temp/20231011_corgi', '--class_data_dir=/home/hs/combine_lora/peft/CLASS_DIR', '--output_dir=/home/hs/combine_lora/peft/OUTPUT_DIR', '--train_text_encoder', '--with_prior_preservation', '--prior_loss_weight=1.0', '--instance_prompt=a photo of sks dog', '--class_prompt=a photo of dog', '--resolution=512', '--train_batch_size=1', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--num_class_images=200', '--use_lora', '--lora_r', '16', '--lora_alpha', '27', '--lora_text_encoder_r', '16', '--lora_text_encoder_alpha', '17', '--learning_rate=1e-4', '--gradient_accumulation_steps=1', '--gradient_checkpointing', '--max_train_steps=500']' returned non-zero exit status 1.

```

-------------
I added these two lines  
```
import torch._dynamo
torch._dynamo.config.suppress_errors = True 
```
in the `train_dreambooth.py`,still got the error 

```
Traceback (most recent call last):
  File "/home/hs/combine_lora/peft/examples/lora_dreambooth/train_dreambooth.py", line 1093, in <module>
    main(args)
  File "/home/hs/combine_lora/peft/examples/lora_dreambooth/train_dreambooth.py", line 932, in main
    encoder_hidden_states = text_encoder(batch["input_ids"])[0]
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 328, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 490, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 133, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 389, in _convert_frame_assert
    return _compile(
           ^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 569, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/utils.py", line 189, in time_wrapper
    r = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 491, in compile_inner
    out_code = transform_code_object(code, transform)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/bytecode_transformation.py", line 1028, in transform_code_object
    transformations(instructions, code_options)
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 458, in transform
    tracer.run()
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2074, in run
    super().run()
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 724, in run
    and self.step()
        ^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 688, in step
    getattr(self, inst.opname)(inst)
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 392, in wrapper
    return inner_fn(self, inst)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 1155, in CALL_FUNCTION_EX
    self.call_function(fn, argsvars.items, kwargsvars.items)
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 562, in call_function
    self.push(fn.call_function(self, args, kwargs))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/variables/user_defined.py", line 383, in call_function
    return self.call_method(tx, "__call__", args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/variables/user_defined.py", line 301, in call_method
    ).call_function(tx, args, kwargs)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/variables/functions.py", line 307, in call_function
    return super().call_function(tx, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/variables/functions.py", line 261, in call_function
    return super().call_function(tx, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/variables/functions.py", line 90, in call_function
    return tx.inline_user_function_return(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 598, in inline_user_function_return
    result = InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2179, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2286, in inline_call_
    tracer.run()
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 724, in run
    and self.step()
        ^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 688, in step
    getattr(self, inst.opname)(inst)
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 392, in wrapper
    return inner_fn(self, inst)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 1155, in CALL_FUNCTION_EX
    self.call_function(fn, argsvars.items, kwargsvars.items)
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 562, in call_function
    self.push(fn.call_function(self, args, kwargs))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/variables/functions.py", line 261, in call_function
    return super().call_function(tx, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/variables/functions.py", line 90, in call_function
    return tx.inline_user_function_return(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 598, in inline_user_function_return
    result = InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2179, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2232, in inline_call_
    InliningInstructionTranslator.check_inlineable(func)
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2213, in check_inlineable
    unimplemented(
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/_dynamo/exc.py", line 172, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: inline in skipfiles: PeftModel.forward  | decorate_autocast /home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/torch/amp/autocast_mode.py

from user code:
   File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/accelerate/utils/operations.py", line 636, in forward
    return model_forward(*args, **kwargs)
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/accelerate/utils/operations.py", line 624, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information

Steps:   0%|                                                                                                                                                                             | 0/500 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/hs/combine_lora/lora_venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/accelerate/commands/launch.py", line 986, in launch_command
    simple_launcher(args)
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/hs/combine_lora/lora_venv/bin/python', 'train_dreambooth.py', '--pretrained_model_name_or_path=/home/hs/combine_lora/peft/stable-diffusion-v1-5', '--instance_data_dir=/home/hs/combine_lora/peft/temp/20231011_corgi', '--class_data_dir=/home/hs/combine_lora/peft/CLASS_DIR', '--output_dir=/home/hs/combine_lora/peft/OUTPUT_DIR', '--train_text_encoder', '--with_prior_preservation', '--prior_loss_weight=1.0', '--instance_prompt=a photo of sks dog', '--class_prompt=a photo of dog', '--resolution=512', '--train_batch_size=1', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--num_class_images=200', '--use_lora', '--lora_r', '16', '--lora_alpha', '27', '--lora_text_encoder_r', '16', '--lora_text_encoder_alpha', '17', '--learning_rate=1e-4', '--gradient_accumulation_steps=1', '--gradient_checkpointing', '--max_train_steps=500']' returned non-zero exit status 1.
```

**Comment by danyow-cheung** [comment]
Update: using 
```
TORCH_LOGS="+dynamo" TORCHDYNAMO_VERBOSE=1 accelerate launch train_dreambooth.py \
  --pretrained_model_name_or_path=$MODEL_NAME  \
  --instance_data_dir=$INSTANCE_DIR \
  --class_data_dir=$CLASS_DIR \
  --output_dir=$OUTPUT_DIR \
  --train_text_encoder \
  --with_prior_preservation --prior_loss_weight=1.0 \
  --instance_prompt="a photo of sks dog" \
  --class_prompt="a photo of dog" \
  --resolution=512 \
  --train_batch_size=1 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --num_class_images=200 \
  --use_lora \
  --lora_r 16 \
  --lora_alpha 27 \
  --lora_text_encoder_r 16 \
  --lora_text_encoder_alpha 17 \
  --learning_rate=1e-4 \
  --gradient_accumulation_steps=1 \
  --gradient_checkpointing \
  --max_train_steps=500
```
Now  there are errors 
```
Traceback (most recent call last):
  File "/home/hs/combine_lora/lora_venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/accelerate/commands/launch.py", line 986, in launch_command
    simple_launcher(args)
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/hs/combine_lora/lora_venv/bin/python', 'train_dreambooth.py', '--pretrained_model_name_or_path=/home/hs/combine_lora/peft/stable-diffusion-v1-5', '--instance_data_dir=/home/hs/combine_lora/peft/temp/20231011_corgi', '--class_data_dir=/home/hs/combine_lora/peft/CLASS_DIR', '--output_dir=/home/hs/combine_lora/peft/OUTPUT_DIR', '--train_text_encoder', '--with_prior_preservation', '--prior_loss_weight=1.0', '--instance_prompt=a photo of sks dog', '--class_prompt=a photo of dog', '--resolution=512', '--train_batch_size=1', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--num_class_images=200', '--use_lora', '--lora_r', '16', '--lora_alpha', '27', '--lora_text_encoder_r', '16', '--lora_text_encoder_alpha', '17', '--learning_rate=1e-4', '--gradient_accumulation_steps=1', '--gradient_checkpointing', '--max_train_steps=500']' returned non-zero exit status 1.
```

**Comment by muellerzr** [comment]
cc @SunMarc

**Comment by SunMarc** [comment]
Hi @danyow-cheung thanks for reporting. This seems to be a problem with torch dynamo and the model. In the meantime, you can train the model without torch dynamo by recreating the accelerate config file using `accelerate config `.

**Comment by danyow-cheung** [comment]
> Hi @danyow-cheung thanks for reporting. This seems to be a problem with torch dynamo and the model. In the meantime, you can train the model without torch dynamo by recreating the accelerate config file using `accelerate config `.

Thank you SunMarc,I changed my `accelerate config` and still got the errors.
```
- `Accelerate` version: 0.23.0
- Platform: Linux-6.2.0-32-generic-x86_64-with-glibc2.35
- Python version: 3.11.4
- Numpy version: 1.26.0
- PyTorch version (GPU?): 2.1.0+cu121 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 31.08 GB
- GPU type: NVIDIA GeForce RTX 4090
- `Accelerate` default config:
	- compute_environment: LOCAL_MACHINE
	- distributed_type: NO
	- mixed_precision: fp16
	- use_cpu: False
	- debug: False
	- num_processes: 1
	- machine_rank: 0
	- num_machines: 1
	- gpu_ids: 0
	- rdzv_backend: static
	- same_network: True
	- main_training_function: main
	- downcast_bf16: no
	- tpu_use_cluster: False
	- tpu_use_sudo: False
	- tpu_env: []

```

**Error**
```
TypeError: Linear.forward() got an unexpected keyword argument 'scale'
Steps:   0%|                                                                                                                                     | 0/800 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "/home/hs/combine_lora/lora_venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/accelerate/commands/launch.py", line 986, in launch_command
    simple_launcher(args)
  File "/home/hs/combine_lora/lora_venv/lib/python3.11/site-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/hs/combine_lora/lora_venv/bin/python', 'train_dreambooth.py', '--pretrained_model_name_or_path=/home/hs/combine_lora/peft/stable-diffusion-v1-5', '--instance_data_dir=/home/hs/combine_lora/peft/temp/20231011_corgi', '--class_data_dir=/home/hs/combine_lora/peft/CLASS_DIR', '--output_dir=/home/hs/combine_lora/peft/OUTPUT_DIR', '--train_text_encoder', '--with_prior_preservation', '--prior_loss_weight=1.0', '--instance_prompt=a photo of sks dog', '--class_prompt=a photo of dog', '--resolution=512', '--train_batch_size=1', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--num_class_images=200', '--use_lora', '--lora_r', '16', '--lora_alpha', '27', '--lora_text_encoder_r', '16', '--lora_text_encoder_alpha', '17', '--learning_rate=1e-4', '--gradient_accumulation_steps=1', '--gradient_checkpointing', '--max_train_steps=800']' returned non-zero exit status 1.

```

**Comment by danyow-cheung** [comment]
issue solved https://github.com/huggingface/peft/issues/879
