### ISSUE TITLE
Finetune Falcon 40B - OOM when load the model 

### ISSUE THREAD

**Issue by ronyadgar** [huggingface/accelerate#2079]
### System Info

```Shell
- `Accelerate` version: 0.23.0
- Platform: Linux-5.15.0-1045-aws-x86_64-with-glibc2.31
- Python version: 3.9.18
- Numpy version: 1.26.1
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 747.93 GB
- GPU type: NVIDIA A10G
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: DEEPSPEED
        - mixed_precision: fp16
        - use_cpu: False
        - debug: False
        - num_processes: 8
        - machine_rank: 0
        - num_machines: 1
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - deepspeed_config: {'gradient_accumulation_steps': 4, 'offload_optimizer_device': 'none', 'offload_param_device': 'cpu', 'zero3_init_flag': True, 'zero_stage': 2}
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

Running accelerate launch main.py (script below) for model_name: "tiiuae/falcon-40b-instruct", result Out Of Memory, on g5x48 (8 gpu!)
Note that running with python script is work when setting device_map = "auto" (but very slow)
Use FSDP with deep speed integration (zero stage 2)

```python
import sys
import os


# Get the current working directory
current_path = os.getcwd()

# Get the parent directory
parent_path = os.path.dirname(current_path)

# Add the parent directory to sys.path
sys.path.append(parent_path)

from accelerate import Accelerator
import hydra
from omegaconf import DictConfig, OmegaConf
import transformers
from transformers import AutoTokenizer, AutoModelForCausalLM, EvalPrediction, BitsAndBytesConfig
from peft import prepare_model_for_kbit_training
import os
import torch



from custom_trainer import CustomTrainer
from falcon.data_preparation import load_data

torch.cuda.empty_cache()
# import wandb

from accelerate import FullyShardedDataParallelPlugin
from torch.distributed.fsdp.fully_sharded_data_parallel import (
    FullOptimStateDictConfig,
    FullStateDictConfig,
)


from transformers import TrainingArguments
from transformers import Trainer

from utils import get_lora_model, timer_decorator


# set the wandb project where this run will be logged
os.environ["WANDB_PROJECT"] = "finetune"

# save your trained model checkpoint to wandb
os.environ["WANDB_LOG_MODEL"] = "true"

# turn off watch to log faster
os.environ["WANDB_WATCH"] = "false"


@hydra.main(version_base=None, config_path="conf", config_name="config")
def my_app(config: DictConfig) -> None:

    config=OmegaConf.to_object(config)
    trainer_args = dict(config.get("training_args", {}))
    tokenizer_args = dict(config.get("tokenizer", {}))  # TODO check why not use

    fsdp_plugin = FullyShardedDataParallelPlugin(
        state_dict_config=FullStateDictConfig(offload_to_cpu=False, rank0_only=False),
        optim_state_dict_config=FullOptimStateDictConfig(
            offload_to_cpu=False, rank0_only=False
        ),
    )

    log_with = "wandb" if config['disable_wandb'] == False else None

    accelerator = Accelerator(
        fsdp_plugin=fsdp_plugin, log_with=log_with, project_dir="/home/ubuntu/logs"
    )
    if config['disable_wandb'] == False:
        accelerator.init_trackers("finetune")

    # quantization_config = BitsAndBytesConfig(
    #     load_in_4bit=True,
    #     bnb_4bit_compute_dtype=torch.float16,
    #     bnb_4bit_quant_type="nf4",
    #     bnb_4bit_use_double_quant=True,
    # )

    model = AutoModelForCausalLM.from_pretrained(config['model_name'], load_in_4bit=True)
          #if you want to load the 8-bit model
        # device_map='auto',

    tokenizer = AutoTokenizer.from_pretrained(config['model_name'])
    tokenizer.pad_token = tokenizer.eos_token

    with accelerator.main_process_first():
        dataset_train, dataset_test = load_data(tokenizer)

    model.gradient_checkpointing_enable()
    model = prepare_model_for_kbit_training(model)

    if config.get("use_lora", False):

        model = get_lora_model(model, config["lora_config"])

    if config.get("custom_trainer", False):

        ct = CustomTrainer(
            model,
            dataset_train,
            dataset_test,
            trainer_args,
            accelerator=accelerator,
            tokenizer=tokenizer,
        )
        ct.train()
    else:


        training_args = TrainingArguments(**trainer_args)
        accelerator.print(training_args)

        trainer = Trainer(

            model=model,
            args=training_args,
            train_dataset=dataset_train,
            eval_dataset=dataset_test,
            data_collator=transformers.DataCollatorForLanguageModeling(
                tokenizer, mlm=False
            ),
           #compute_metrics=compute_metrics,
        )

        model.config.use_cache = False

        trainer.train()
        torch.cuda.empty_cache()
        accelerator.wait_for_everyone()
        # Evaluate the model
        # eval_result = trainer.evaluate()
        # print(eval_result)
        accelerator.wait_for_everyone()
        # try:
        #     accelerator.save_state("ckpt")
        # except:
        #     print("Failed to save checkpoint")

        unwrapped_model = accelerator.unwrap_model(model)

        from deepspeed.checkpoint.utils import clone_tensors_for_torch_save

        state_dict = clone_tensors_for_torch_save(unwrapped_model.state_dict())

        unwrapped_model.save_pretrained(
            "./lora_test40",
            is_main_process=accelerator.is_main_process,
            save_function=accelerator.save,
            state_dict=state_dict,
        )


if __name__ == "__main__":
    my_app()



```
When run estimate memory, get 
```bash
(ft-llm) ubuntu@ip-172-31-89-151:~/llm-ft/falcon$ accelerate estimate-memory "tiiuae/falcon-40b-instruct"
Loading pretrained config for `tiiuae/falcon-40b-instruct` from `transformers`...
┌──────────────────────────────────────────────────────┐
│Memory Usage for loading `tiiuae/falcon-40b-instruct` │
├───────┬─────────────┬──────────┬─────────────────────┤
│ dtype │Largest Layer│Total Size│ Training using Adam │
├───────┼─────────────┼──────────┼─────────────────────┤
│float32│   2.53 GB   │153.87 GB │      615.47 GB      │
│float16│   1.27 GB   │ 76.93 GB │      307.73 GB      │
│  int8 │  648.03 MB  │ 38.47 GB │      153.87 GB      │
│  int4 │  324.02 MB  │ 19.23 GB │       76.93 GB      │
└───────┴─────────────┴──────────┴─────────────────────┘
```

### Expected behavior

```bash

t-llm) ubuntu@ip-172-31-89-151:~/llm-ft/falcon$ accelerate launch main.py
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
/home/ubuntu/anaconda3/envs/ft-llm/lib/python3.9/site-packages/accelerate/utils/dataclasses.py:641: UserWarning: DeepSpeed Zero3 Init flag is only applicable for ZeRO Stage 3. Setting it to False.
  warnings.warn("DeepSpeed Zero3 Init flag is only applicable for ZeRO Stage 3. Setting it to False.")
/home/ubuntu/anaconda3/envs/ft-llm/lib/python3.9/site-packages/accelerate/utils/dataclasses.py:641: UserWarning: DeepSpeed Zero3 Init flag is only applicable for ZeRO Stage 3. Setting it to False.
  warnings.warn("DeepSpeed Zero3 Init flag is only applicable for ZeRO Stage 3. Setting it to False.")
/home/ubuntu/anaconda3/envs/ft-llm/lib/python3.9/site-packages/accelerate/utils/dataclasses.py:641: UserWarning: DeepSpeed Zero3 Init flag is only applicable for ZeRO Stage 3. Setting it to False.
  warnings.warn("DeepSpeed Zero3 Init flag is only applicable for ZeRO Stage 3. Setting it to False.")
/home/ubuntu/anaconda3/envs/ft-llm/lib/python3.9/site-packages/accelerate/utils/dataclasses.py:641: UserWarning: DeepSpeed Zero3 Init flag is only applicable for ZeRO Stage 3. Setting it to False.
  warnings.warn("DeepSpeed Zero3 Init flag is only applicable for ZeRO Stage 3. Setting it to False.")
/home/ubuntu/anaconda3/envs/ft-llm/lib/python3.9/site-packages/accelerate/utils/dataclasses.py:641: UserWarning: DeepSpeed Zero3 Init flag is only applicable for ZeRO Stage 3. Setting it to False.
  warnings.warn("DeepSpeed Zero3 Init flag is only applicable for ZeRO Stage 3. Setting it to False.")
/home/ubuntu/anaconda3/envs/ft-llm/lib/python3.9/site-packages/accelerate/utils/dataclasses.py:641: UserWarning: DeepSpeed Zero3 Init flag is only applicable for ZeRO Stage 3. Setting it to False.
  warnings.warn("DeepSpeed Zero3 Init flag is only applicable for ZeRO Stage 3. Setting it to False.")
/home/ubuntu/anaconda3/envs/ft-llm/lib/python3.9/site-packages/accelerate/utils/dataclasses.py:641: UserWarning: DeepSpeed Zero3 Init flag is only applicable for ZeRO Stage 3. Setting it to False.
  warnings.warn("DeepSpeed Zero3 Init flag is only applicable for ZeRO Stage 3. Setting it to False.")
[2023-10-24 12:31:17,179] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-10-24 12:31:17,180] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/home/ubuntu/anaconda3/envs/ft-llm/lib/python3.9/site-packages/accelerate/utils/dataclasses.py:641: UserWarning: DeepSpeed Zero3 Init flag is only applicable for ZeRO Stage 3. Setting it to False.
  warnings.warn("DeepSpeed Zero3 Init flag is only applicable for ZeRO Stage 3. Setting it to False.")
[2023-10-24 12:31:17,247] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-10-24 12:31:17,248] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-10-24 12:31:17,249] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-10-24 12:31:17,249] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-10-24 12:31:17,250] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-10-24 12:31:17,279] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-10-24 12:31:19,043] [INFO] [comm.py:637:init_distributed] cdb=None
[2023-10-24 12:31:19,043] [INFO] [comm.py:637:init_distributed] cdb=None
[2023-10-24 12:31:19,044][torch.distributed.distributed_c10d][INFO] - Added key: store_based_barrier_key:1 to store for rank: 2
[2023-10-24 12:31:19,045][torch.distributed.distributed_c10d][INFO] - Added key: store_based_barrier_key:1 to store for rank: 5
[2023-10-24 12:31:19,103] [INFO] [comm.py:637:init_distributed] cdb=None
[2023-10-24 12:31:19,105][torch.distributed.distributed_c10d][INFO] - Added key: store_based_barrier_key:1 to store for rank: 7
[2023-10-24 12:31:19,116] [INFO] [comm.py:637:init_distributed] cdb=None
[2023-10-24 12:31:19,117][torch.distributed.distributed_c10d][INFO] - Added key: store_based_barrier_key:1 to store for rank: 6
[2023-10-24 12:31:19,131] [INFO] [comm.py:637:init_distributed] cdb=None
[2023-10-24 12:31:19,132] [INFO] [comm.py:637:init_distributed] cdb=None
[2023-10-24 12:31:19,132][torch.distributed.distributed_c10d][INFO] - Added key: store_based_barrier_key:1 to store for rank: 3
[2023-10-24 12:31:19,133][torch.distributed.distributed_c10d][INFO] - Added key: store_based_barrier_key:1 to store for rank: 4
[2023-10-24 12:31:19,140] [INFO] [comm.py:637:init_distributed] cdb=None
[2023-10-24 12:31:19,140] [INFO] [comm.py:668:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
[2023-10-24 12:31:19,141][torch.distributed.distributed_c10d][INFO] - Added key: store_based_barrier_key:1 to store for rank: 0
[2023-10-24 12:31:19,149] [INFO] [comm.py:637:init_distributed] cdb=None
[2023-10-24 12:31:19,150][torch.distributed.distributed_c10d][INFO] - Added key: store_based_barrier_key:1 to store for rank: 1
[2023-10-24 12:31:19,150][torch.distributed.distributed_c10d][INFO] - Rank 1: Completed store-based barrier for key:store_based_barrier_key:1 with 8 nodes.
[2023-10-24 12:31:19,152][torch.distributed.distributed_c10d][INFO] - Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 8 nodes.
[2023-10-24 12:31:19,153][torch.distributed.distributed_c10d][INFO] - Rank 3: Completed store-based barrier for key:store_based_barrier_key:1 with 8 nodes.
[2023-10-24 12:31:19,153][torch.distributed.distributed_c10d][INFO] - Rank 4: Completed store-based barrier for key:store_based_barrier_key:1 with 8 nodes.
[2023-10-24 12:31:19,156][torch.distributed.distributed_c10d][INFO] - Rank 7: Completed store-based barrier for key:store_based_barrier_key:1 with 8 nodes.
[2023-10-24 12:31:19,156][torch.distributed.distributed_c10d][INFO] - Rank 2: Completed store-based barrier for key:store_based_barrier_key:1 with 8 nodes.
[2023-10-24 12:31:19,157][torch.distributed.distributed_c10d][INFO] - Rank 5: Completed store-based barrier for key:store_based_barrier_key:1 with 8 nodes.
[2023-10-24 12:31:19,158][torch.distributed.distributed_c10d][INFO] - Rank 6: Completed store-based barrier for key:store_based_barrier_key:1 with 8 nodes.
Loading checkpoint shards:  89%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                 | 8/9 [01:30<00:11, 11.34s/it]
Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/ubuntu/llm-ft/falcon/main.py", line 83, in my_app
    model = AutoModelForCausalLM.from_pretrained(config['model_name'], load_in_4bit=True)
  File "/home/ubuntu/anaconda3/envs/ft-llm/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 565, in from_pretrained
    return model_class.from_pretrained(
  File "/home/ubuntu/anaconda3/envs/ft-llm/lib/python3.9/site-packages/transformers/modeling_utils.py", line 3333, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/home/ubuntu/anaconda3/envs/ft-llm/lib/python3.9/site-packages/transformers/modeling_utils.py", line 3723, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
  File "/home/ubuntu/anaconda3/envs/ft-llm/lib/python3.9/site-packages/transformers/modeling_utils.py", line 752, in _load_state_dict_into_meta_model
    set_module_quantized_tensor_to_device(
  File "/home/ubuntu/anaconda3/envs/ft-llm/lib/python3.9/site-packages/transformers/integrations/bitsandbytes.py", line 98, in set_module_quantized_tensor_to_device
    new_value = bnb.nn.Params4bit(new_value, requires_grad=False, **kwargs).to(device)
  File "/home/ubuntu/anaconda3/envs/ft-llm/lib/python3.9/site-packages/bitsandbytes/nn/modules.py", line 179, in to
    return self.cuda(device)
  File "/home/ubuntu/anaconda3/envs/ft-llm/lib/python3.9/site-packages/bitsandbytes/nn/modules.py", line 156, in cuda
    w = self.data.contiguous().half().cuda(device)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 512.00 MiB (GPU 1; 22.19 GiB total capacity; 21.00 GiB already allocated; 323.50 MiB free; 21.58 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Loading checkpoint shards:  89%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                 | 8/9 [01:33<00:11, 11.60s/it]WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 29178 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 29180 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 29181 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 29182 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 29183 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 29184 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 29185 closing signal SIGTERM
^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[AERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 29179) of binary: /home/ubuntu/anaconda3/envs/ft-llm/bin/python
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/ft-llm/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/anaconda3/envs/ft-llm/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/home/ubuntu/anaconda3/envs/ft-llm/lib/python3.9/site-packages/accelerate/commands/launch.py", line 971, in launch_command
    deepspeed_launcher(args)
  File "/home/ubuntu/anaconda3/envs/ft-llm/lib/python3.9/site-packages/accelerate/commands/launch.py", line 687, in deepspeed_launcher
    distrib_run.run(args)
  File "/home/ubuntu/anaconda3/envs/ft-llm/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/ubuntu/anaconda3/envs/ft-llm/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ubuntu/anaconda3/envs/ft-llm/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
main.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-10-24_12:32:53
  host      : ip-172-31-89-151.ec2.internal
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 29179)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
(ft-llm) ubuntu@ip-172-31-89-151:~/llm-ft/falcon$

```

**Comment by OriMoWix** [comment]
Got the same error

**Comment by muellerzr** [comment]
cc @pacman100
