### ISSUE TITLE
 Single-machine 4-card 3090 machine training can run normally on a single GPU, but if the gradient is turned on at the same time, an error will be reported

### ISSUE THREAD

**Issue by diaojunxian** [huggingface/accelerate#2101]
### System Info

```Shell
- `Accelerate` version: 0.24.1
- Platform: Linux-5.15.0-87-generic-x86_64-with-glibc2.31
- Python version: 3.10.13
- Numpy version: 1.26.1
- PyTorch version (GPU?): 2.1.0+cu121 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 251.77 GB
- GPU type: NVIDIA GeForce RTX 3090
- `Accelerate` default config:
	- compute_environment: LOCAL_MACHINE
	- distributed_type: MULTI_GPU
	- mixed_precision: fp16
	- use_cpu: False
	- debug: False
	- num_processes: 4
	- machine_rank: 0
	- num_machines: 1
	- gpu_ids: all
	- rdzv_backend: static
	- same_network: True
	- main_training_function: main
	- downcast_bf16: no
	- tpu_use_cluster: False
	- tpu_use_sudo: False
	- tpu_env: []
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

1. use the https://github.com/hiyouga/LLaMA-Factory/ sample.
2. When running a single card, the command is
```
CUDA_VISIBLE_DEVICES=1 python src/train_bash.py \
    --stage pt \
    --model_name_or_path /data/chatglm3-6b/ \
    --do_train \
    --do_eval \
    --dataset wiki_demo \
    --template chatglm3 \
    --finetuning_type lora \
    --lora_target query_key_value \
    --output_dir output_pt_dir \
    --overwrite_cache \
    --overwrite_output_dir \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 1 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 1000 \
    --learning_rate 5e-5 \
    --num_train_epochs 1000.0 \
    --plot_loss \
    --report_to tensorboard \
    --fp16
```
3. then use the accelerate 
```
accelerate launch src/train_bash.py \
    --stage pt \
    --model_name_or_path /data/chatglm3-6b/ \
    --do_train \
    --do_eval \
    --dataset wiki_demo \
    --template chatglm3 \
    --finetuning_type lora \
    --lora_target query_key_value \
    --output_dir output_pt_dir \
    --overwrite_cache \
    --overwrite_output_dir \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 1 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 1000 \
    --learning_rate 5e-5 \
    --num_train_epochs 1000.0 \
    --plot_loss \
    --report_to tensorboard \
    --fp16
```
it reported `RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)``

my accelerate env is 

- `Accelerate` version: 0.24.1
- Platform: Linux-5.15.0-87-generic-x86_64-with-glibc2.31
- Python version: 3.10.13
- Numpy version: 1.26.1
- PyTorch version (GPU?): 2.1.0+cu121 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 251.77 GB
- GPU type: NVIDIA GeForce RTX 3090
- `Accelerate` default config:
	- compute_environment: LOCAL_MACHINE
	- distributed_type: MULTI_GPU
	- mixed_precision: fp16
	- use_cpu: False
	- debug: False
	- num_processes: 4
	- machine_rank: 0
	- num_machines: 1
	- gpu_ids: all
	- rdzv_backend: static
	- same_network: True
	- main_training_function: main
	- downcast_bf16: no
	- tpu_use_cluster: False
	- tpu_use_sudo: False
	- tpu_env: []

### Expected behavior

how to solve it?

**Comment by BenjaminBossan** [comment]
Could you please paste the full error message? Also, could you please monitor GPU memory usage and check if it's possible that you run out of memory?

> but if the gradient is turned on at the same time

I assume the gradient is always turned on, for both of your experiments.

**Comment by diaojunxian** [comment]
@BenjaminBossan hi, when train in the single GPU by this command
```
CUDA_VISIBLE_DEVICES=1 python src/train_bash.py     --stage pt     --model_name_or_path /data/chatglm3-6b/     --do_train     --do_eval     --dataset wiki_demo     --template chatglm3     --finetuning_type lora     --lora_target query_key_value     --output_dir output_pt_dir     --overwrite_cache     --overwrite_output_dir     --per_device_train_batch_size 4     --gradient_accumulation_steps 2     --lr_scheduler_type cosine     --logging_steps 10     --save_steps 1000     --learning_rate 5e-5     --num_train_epochs 800.0     --plot_loss     --report_to tensorboard     --fp16
```
![image](https://github.com/huggingface/accelerate/assets/19700467/6446ecb8-656e-42e3-951e-25eccbaf5a43)

when train in multiple GPUs by the command:
```
accelerate launch src/train_bash.py \
    --stage pt \
    --model_name_or_path /data/chatglm3-6b/ \
    --do_train \
    --dataset wiki_demo \
    --template chatglm3 \
    --finetuning_type lora \
    --lora_target query_key_value \
    --output_dir output_pt_dir \
    --overwrite_cache \
    --overwrite_output_dir \
    --per_device_train_batch_size 4 \
    --gradient_accumulation_steps 2 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 1000 \
    --learning_rate 5e-5 \
    --num_train_epochs 500.0 \
    --plot_loss \
    --report_to tensorboard \
    --fp16
```
![image](https://github.com/huggingface/accelerate/assets/19700467/7571cda9-3ff1-4128-8024-3950c7bcd994)

the output console log is:
```
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`
Traceback (most recent call last):
  File "/data/sd/LLaMA-Factory/src/train_bash.py", line 14, in <module>
    main()
  File "/data/sd/LLaMA-Factory/src/train_bash.py", line 5, in main
    run_exp()
  File "/data/sd/LLaMA-Factory/src/llmtuner/tuner/tune.py", line 24, in run_exp
    run_pt(model_args, data_args, training_args, finetuning_args, callbacks)
  File "/data/sd/LLaMA-Factory/src/llmtuner/tuner/pt/workflow.py", line 40, in run_pt
    train_result = trainer.train(resume_from_checkpoint=training_args.resume_from_checkpoint)
  File "/home/m1l03053/.local/lib/python3.10/site-packages/transformers/trainer.py", line 1591, in train
    return inner_training_loop(
  File "/home/m1l03053/.local/lib/python3.10/site-packages/transformers/trainer.py", line 1892, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/m1l03053/.local/lib/python3.10/site-packages/transformers/trainer.py", line 2776, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/m1l03053/.local/lib/python3.10/site-packages/transformers/trainer.py", line 2801, in compute_loss
    outputs = model(**inputs)
  File "/home/m1l03053/.conda/envs/3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/m1l03053/.conda/envs/3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/m1l03053/.conda/envs/3.10/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1519, in forward
    else self._run_ddp_forward(*inputs, **kwargs)
  File "/home/m1l03053/.conda/envs/3.10/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1355, in _run_ddp_forward
    return self.module(*inputs, **kwargs)  # type: ignore[index]
  File "/home/m1l03053/.conda/envs/3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/m1l03053/.conda/envs/3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/m1l03053/.local/lib/python3.10/site-packages/accelerate/utils/operations.py", line 659, in forward
    return model_forward(*args, **kwargs)
  File "/home/m1l03053/.local/lib/python3.10/site-packages/accelerate/utils/operations.py", line 647, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/home/m1l03053/.conda/envs/3.10/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 16, in decorate_autocast
    return func(*args, **kwargs)
  File "/home/m1l03053/.local/lib/python3.10/site-packages/peft/peft_model.py", line 918, in forward
    return self.base_model(
  File "/home/m1l03053/.conda/envs/3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/m1l03053/.conda/envs/3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/m1l03053/.local/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 94, in forward
    return self.model.forward(*args, **kwargs)
  File "/home/m1l03053/.cache/huggingface/modules/transformers_modules/modeling_chatglm.py", line 937, in forward
    transformer_outputs = self.transformer(
  File "/home/m1l03053/.conda/envs/3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/m1l03053/.conda/envs/3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/m1l03053/.cache/huggingface/modules/transformers_modules/modeling_chatglm.py", line 830, in forward
    hidden_states, presents, all_hidden_states, all_self_attentions = self.encoder(
  File "/home/m1l03053/.conda/envs/3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/m1l03053/.conda/envs/3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/m1l03053/.cache/huggingface/modules/transformers_modules/modeling_chatglm.py", line 631, in forward
    layer_ret = torch.utils.checkpoint.checkpoint(
  File "/home/m1l03053/.conda/envs/3.10/lib/python3.10/site-packages/torch/_compile.py", line 24, in inner
    return torch._dynamo.disable(fn, recursive)(*args, **kwargs)
  File "/home/m1l03053/.conda/envs/3.10/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 328, in _fn
    return fn(*args, **kwargs)
  File "/home/m1l03053/.conda/envs/3.10/lib/python3.10/site-packages/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
  File "/home/m1l03053/.conda/envs/3.10/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 451, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/home/m1l03053/.conda/envs/3.10/lib/python3.10/site-packages/torch/autograd/function.py", line 539, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/m1l03053/.conda/envs/3.10/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 230, in forward
    outputs = run_function(*args)
  File "/home/m1l03053/.conda/envs/3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/m1l03053/.conda/envs/3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/m1l03053/.cache/huggingface/modules/transformers_modules/modeling_chatglm.py", line 544, in forward
    attention_output, kv_cache = self.self_attention(
  File "/home/m1l03053/.conda/envs/3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/m1l03053/.conda/envs/3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/m1l03053/.cache/huggingface/modules/transformers_modules/modeling_chatglm.py", line 376, in forward
    mixed_x_layer = self.query_key_value(hidden_states)
  File "/home/m1l03053/.conda/envs/3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/m1l03053/.conda/envs/3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/m1l03053/.local/lib/python3.10/site-packages/peft/tuners/lora.py", line 902, in forward
    result = F.linear(x, transpose(self.weight, self.fan_in_fan_out), bias=self.bias)
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`
  0%|                                                                                                                                               | 0/1000 [00:00<?, ?it/s]
[2023-11-01 14:03:14,166] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 130050) of binary: /home/m1l03053/.conda/envs/3.10/bin/python
Traceback (most recent call la

```

**Comment by BenjaminBossan** [comment]
So it looks like memory is much tighter in your second example, which could indicate that this is indeed caused by missing memory. Could you please check if the error vanishes if you reduce memory requirements, e.g. by lowering the batch size?

**Comment by diaojunxian** [comment]
@BenjaminBossan 

First of all, thank you very much for your reply.

I tried setting batch size to 1, but it still throws an error. My point is, when I run it on a single card, the same configuration works without any issue. However, when I use the "accelebrate launch" library to concurrently execute on 4 cards, it throws an error.

The main concern is the concurrent execution on multiple cards, but the executed command is the same. I have provided the execution command in detail above.

**Comment by BenjaminBossan** [comment]
> I tried setting batch size to 1, but it still throws an error.

So is it still the same error? And could you observe that there was a sufficient amount of free memory on the GPUs after switching to batch size 1?

> My point is, when I run it on a single card, the same configuration works without any issue.

I do understand your point. The reason for my questions was that I wanted to first figure out if the issue is caused by some memory overhead in the distributed setting, or if it's something else, because the error message is not very helpful in identifying the underlying cause.

**Comment by ll0ruc** [comment]
I have encountered the same issue as well. Have you resolved it?

**Comment by diaojunxian** [comment]
> I have encountered the same issue as well. Have you resolved it?

can not solve.

**Comment by XFR1998** [comment]
can not solve +1

**Comment by XFR1998** [comment]
您好！请问现在解决了吗？

**Comment by muellerzr** [comment]
Solution is there and posted, you're running out of memory. See this torch discussion: https://discuss.pytorch.org/t/cuda-error-cublas-status-not-initialized-when-calling-cublascreate-handle/125450/3

**Comment by XFR1998** [comment]
No, I think this issue is the bug of Accelerate. May be because Accelerate only support Nvlink, but rtx3090 belongs to PIX.
You can check your card with this type: nvidia-smi topo-m

**Comment by XFR1998** [comment]
> No, I think this issue is the bug of Accelerate. May be because Accelerate only support Nvlink, but rtx3090 belongs to PIX. You can check your card with this type: `nvidia-smi topo-m`

**Comment by muellerzr** [comment]
> No, I think this issue is the bug of Accelerate. May be because Accelerate only support Nvlink

Nope, not a thing. That’s now PyTorch we’re talking about, accelerate doesn’t have this limitation. Nvidia put it there. You do need to disable P2P communication manually however (for now). 

Try installing accelerate via main and try again using accelerate launch. We disable this automatically on consumer cards

**Comment by muellerzr** [comment]
I don’t think P2P is the issue, but do let me know if that fixes it. Trying to understand all these issues on the new consumer cards after NVIDIA removed NVLink support from them has been tricky to navigate
