### ISSUE TITLE
`model.gradient_checkpointing_enable()` will result in crash when used with `accelerate launch --use_fsdp`

### ISSUE THREAD

**Issue by xhluca** [huggingface/accelerate#2178]
### System Info

```Shell
- `Accelerate` version: 0.24.1
- Platform: Linux-5.15.0-84-generic-x86_64-with-glibc2.34
- Python version: 3.8.18
- Numpy version: 1.24.4
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 503.72 GB
- GPU type: NVIDIA RTX A6000
- `Accelerate` default config:
        Not found
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

Let's say we have the following python file `train_multi.py` (taken from [here](https://huggingface.co/docs/trl/sft_trainer)):

```python
# Train using accelerate across 2 gpus
from transformers import AutoModelForCausalLM
from datasets import load_dataset
from trl import SFTTrainer

dataset = load_dataset("imdb", split="train")

model = AutoModelForCausalLM.from_pretrained("facebook/opt-350m")

# model.gradient_checkpointing_enable()

trainer = SFTTrainer(
    model,
    train_dataset=dataset,
    dataset_text_field="text",
    max_seq_length=512,
)

trainer.train()
```

Note that, when `model.gradient_checkpointing_enable` is commented out, the model will train fine on 2 gpus:
```bash
$ accelerate launch --use_fsdp -m train_multi
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_processes` was set to a value of `2`
                More than one GPU was found, enabling multi-GPU training.
                If this was unintended please pass in `--num_processes=1`.
        `--num_machines` was set to a value of `1`
        `--mixed_precision` was set to a value of `'no'`
        `--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
You're using a GPT2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
  0%|                                                                                                                         | 0/4689 [00:00<?, ?it/s]You're using a GPT2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
  1%|█▋                                                                                                              | 70/4689 [00:48<48:51,  1.58it/s]
```

Here's the Nvidia-smi:
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.12             Driver Version: 535.104.12   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA RTX A6000               On  | 00000000:01:00.0 Off |                  Off |
| 45%   75C    P2             290W / 300W |  20147MiB / 49140MiB |    100%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA RTX A6000               On  | 00000000:23:00.0 Off |                  Off |
| 38%   69C    P2             291W / 300W |  20147MiB / 49140MiB |    100%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
```

However, when we uncomment `model.gradient_checkpointing_enable()`, we get this error:

```bash
(venv) username@server:~/project$ accelerate launch --use_fsdp -m train_multi
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_processes` was set to a value of `2`
                More than one GPU was found, enabling multi-GPU training.
                If this was unintended please pass in `--num_processes=1`.
        `--num_machines` was set to a value of `1`
        `--mixed_precision` was set to a value of `'no'`
        `--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
You're using a GPT2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
  0%|                                                                                                                         | 0/4689 [00:00<?, ?it/s]You're using a GPT2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
Traceback (most recent call last):
  File "/home/username/.pyenv/versions/3.8.18/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/username/.pyenv/versions/3.8.18/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/username/project/train_multi.py", line 19, in <module>
    trainer.train()
  File "/home/username/project/venv/lib/python3.8/site-packages/transformers/trainer.py", line 1555, in train
    return inner_training_loop(
  File "/home/username/project/venv/lib/python3.8/site-packages/transformers/trainer.py", line 1860, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/username/project/venv/lib/python3.8/site-packages/transformers/trainer.py", line 2734, in training_step
    self.accelerator.backward(loss)
  File "/home/username/project/venv/lib/python3.8/site-packages/accelerate/accelerator.py", line 1989, in backward
    loss.backward(**kwargs)
  File "/home/username/project/venv/lib/python3.8/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home/username/project/venv/lib/python3.8/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/username/project/venv/lib/python3.8/site-packages/torch/autograd/function.py", line 274, in apply
    return user_fn(self, *args)
  File "/home/username/project/venv/lib/python3.8/site-packages/torch/utils/checkpoint.py", line 141, in backward
    outputs = ctx.run_function(*detached_inputs)
  File "/home/username/project/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/username/project/venv/lib/python3.8/site-packages/transformers/models/opt/modeling_opt.py", line 299, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/username/project/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/username/project/venv/lib/python3.8/site-packages/transformers/models/opt/modeling_opt.py", line 142, in forward
    query_states = self.q_proj(hidden_states) * self.scaling
  File "/home/username/project/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/username/project/venv/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: setStorage: sizes [1024, 1024], strides [1, 1024], storage offset 308103168, and itemsize 4 requiring a storage size of 1236606976 are out of bounds for storage of size 0
Traceback (most recent call last):
  File "/home/username/.pyenv/versions/3.8.18/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/username/.pyenv/versions/3.8.18/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/username/project/train_multi.py", line 19, in <module>
    trainer.train()
  File "/home/username/project/venv/lib/python3.8/site-packages/transformers/trainer.py", line 1555, in train
    return inner_training_loop(
  File "/home/username/project/venv/lib/python3.8/site-packages/transformers/trainer.py", line 1860, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/username/project/venv/lib/python3.8/site-packages/transformers/trainer.py", line 2734, in training_step
    self.accelerator.backward(loss)
  File "/home/username/project/venv/lib/python3.8/site-packages/accelerate/accelerator.py", line 1989, in backward
    loss.backward(**kwargs)
  File "/home/username/project/venv/lib/python3.8/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home/username/project/venv/lib/python3.8/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/username/project/venv/lib/python3.8/site-packages/torch/autograd/function.py", line 274, in apply
    return user_fn(self, *args)
  File "/home/username/project/venv/lib/python3.8/site-packages/torch/utils/checkpoint.py", line 141, in backward
    outputs = ctx.run_function(*detached_inputs)
  File "/home/username/project/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/username/project/venv/lib/python3.8/site-packages/transformers/models/opt/modeling_opt.py", line 299, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/username/project/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/username/project/venv/lib/python3.8/site-packages/transformers/models/opt/modeling_opt.py", line 142, in forward
    query_states = self.q_proj(hidden_states) * self.scaling
  File "/home/username/project/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/username/project/venv/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: setStorage: sizes [1024, 1024], strides [1, 1024], storage offset 308103168, and itemsize 4 requiring a storage size of 1236606976 are out of bounds for storage of size 0
  0%|          | 0/4689 [00:00<?, ?it/s]                                                                                                               
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2766734) of binary: /home/username/project/venv/bin/python3
Traceback (most recent call last):
  File "/home/username/project/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/username/project/venv/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/home/username/project/venv/lib/python3.8/site-packages/accelerate/commands/launch.py", line 981, in launch_command
    multi_gpu_launcher(args)
  File "/home/username/project/venv/lib/python3.8/site-packages/accelerate/commands/launch.py", line 654, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/username/project/venv/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/username/project/venv/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/username/project/venv/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_multi FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-11-21_18:37:38
  host      : server.com
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 2766735)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-11-21_18:37:38
  host      : server.com
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2766734)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================```
```

### Expected behavior

It should work when we use gradient checkpointing

**Comment by xhluca** [comment]
@muellerzr Thanks for [encouraging me](https://x.com/TheZachMueller/status/1718035854705168502?s=20) to open this issue. Hope this will get resolved!

**Comment by xhluca** [comment]
Note the issue is specifically with FSDP, with DDP it works but my model won't fit on 1 gpu.

**Comment by pacman100** [comment]
Hello, please pass `gradient_checkpointing=True` to `SFTTrainer` like below:
```
trainer = SFTTrainer(
    model,
    train_dataset=dataset,
    dataset_text_field="text",
    max_seq_length=512,
    gradient_checkpointing=True,
)

trainer.train()
```

Let us know if that solves the issue. You need to enable gradient checkpoint post the model being wrapped in FSDP.

**Comment by xhluca** [comment]
I am using sfttrainer for convenience here, but I am not necessarily using it in my code. Does the regular trainer and seq2seqtrainer also have this flag?

**Comment by muellerzr** [comment]
@xhluca yes it does https://github.com/huggingface/transformers/blob/main/src/transformers/training_args.py#L575

**Comment by xhluca** [comment]
@muellerzr @pacman100 I tried with the following code:
```python
# Train using accelerate across 2 gpus
from transformers import AutoModelForCausalLM, TrainingArguments
from datasets import load_dataset
from trl import SFTTrainer

model_save_dir = "temp/models"
dataset = load_dataset("imdb", split="train")

model = AutoModelForCausalLM.from_pretrained("facebook/opt-350m")

# model.gradient_checkpointing_enable()

training_args = TrainingArguments(
    gradient_checkpointing=True,
    output_dir=model_save_dir,
)

trainer = SFTTrainer(
    model,
    args=training_args,
    train_dataset=dataset,
    dataset_text_field="text",
    max_seq_length=512,
)

trainer.train()
```

There's still an error:
```
$ accelerate launch --use_fsdp -m train_multi
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_processes` was set to a value of `2`
                More than one GPU was found, enabling multi-GPU training.
                If this was unintended please pass in `--num_processes=1`.
        `--num_machines` was set to a value of `1`
        `--mixed_precision` was set to a value of `'no'`
        `--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
You're using a GPT2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
  0%|                                                                                                                         | 0/4689 [00:00<?, ?it/s]You're using a GPT2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
Traceback (most recent call last):
  File "/home/username/.pyenv/versions/3.8.18/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/username/.pyenv/versions/3.8.18/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/username/project/train_multi.py", line 26, in <module>
    trainer.train()
  File "/home/username/project/venv/lib/python3.8/site-packages/transformers/trainer.py", line 1555, in train
    return inner_training_loop(
  File "/home/username/project/venv/lib/python3.8/site-packages/transformers/trainer.py", line 1860, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/username/project/venv/lib/python3.8/site-packages/transformers/trainer.py", line 2734, in training_step
    self.accelerator.backward(loss)
  File "/home/username/project/venv/lib/python3.8/site-packages/accelerate/accelerator.py", line 1989, in backward
    loss.backward(**kwargs)
  File "/home/username/project/venv/lib/python3.8/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home/username/project/venv/lib/python3.8/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/username/project/venv/lib/python3.8/site-packages/torch/autograd/function.py", line 274, in apply
    return user_fn(self, *args)
  File "/home/username/project/venv/lib/python3.8/site-packages/torch/utils/checkpoint.py", line 141, in backward
    outputs = ctx.run_function(*detached_inputs)
  File "/home/username/project/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/username/project/venv/lib/python3.8/site-packages/transformers/models/opt/modeling_opt.py", line 299, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/username/project/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/username/project/venv/lib/python3.8/site-packages/transformers/models/opt/modeling_opt.py", line 142, in forward
    query_states = self.q_proj(hidden_states) * self.scaling
  File "/home/username/project/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/username/project/venv/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: setStorage: sizes [1024, 1024], strides [1, 1024], storage offset 308103168, and itemsize 4 requiring a storage size of 1236606976 are out of bounds for storage of size 0
Traceback (most recent call last):
  File "/home/username/.pyenv/versions/3.8.18/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/username/.pyenv/versions/3.8.18/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/username/project/train_multi.py", line 26, in <module>
    trainer.train()
  File "/home/username/project/venv/lib/python3.8/site-packages/transformers/trainer.py", line 1555, in train
    return inner_training_loop(
  File "/home/username/project/venv/lib/python3.8/site-packages/transformers/trainer.py", line 1860, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/username/project/venv/lib/python3.8/site-packages/transformers/trainer.py", line 2734, in training_step
    self.accelerator.backward(loss)
  File "/home/username/project/venv/lib/python3.8/site-packages/accelerate/accelerator.py", line 1989, in backward
    loss.backward(**kwargs)
  File "/home/username/project/venv/lib/python3.8/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home/username/project/venv/lib/python3.8/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/username/project/venv/lib/python3.8/site-packages/torch/autograd/function.py", line 274, in apply
    return user_fn(self, *args)
  File "/home/username/project/venv/lib/python3.8/site-packages/torch/utils/checkpoint.py", line 141, in backward
    outputs = ctx.run_function(*detached_inputs)
  File "/home/username/project/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/username/project/venv/lib/python3.8/site-packages/transformers/models/opt/modeling_opt.py", line 299, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/username/project/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/username/project/venv/lib/python3.8/site-packages/transformers/models/opt/modeling_opt.py", line 142, in forward
    query_states = self.q_proj(hidden_states) * self.scaling
  File "/home/username/project/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/username/project/venv/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: setStorage: sizes [1024, 1024], strides [1, 1024], storage offset 308103168, and itemsize 4 requiring a storage size of 1236606976 are out of bounds for storage of size 0
  0%|          | 0/4689 [00:00<?, ?it/s]                                                                                                               
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2793868) of binary: /home/username/project/venv/bin/python3
Traceback (most recent call last):
  File "/home/username/project/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/username/project/venv/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/home/username/project/venv/lib/python3.8/site-packages/accelerate/commands/launch.py", line 981, in launch_command
    multi_gpu_launcher(args)
  File "/home/username/project/venv/lib/python3.8/site-packages/accelerate/commands/launch.py", line 654, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/username/project/venv/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/username/project/venv/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/username/project/venv/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_multi FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-11-22_12:49:13
  host      : server.com
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 2793869)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-11-22_12:49:13
  host      : server.com
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2793868)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

**Comment by xhluca** [comment]
I had to configure the accelerate yaml file to get it working (I think it's because I needed to explicitly enable automatic module wrapping). This should work now.

**Comment by jinghuayao** [comment]
> I had to configure the accelerate yaml file to get it working (I think it's because I needed to explicitly enable automatic module wrapping). This should work now.

HI @xhluca could you please share your configured accelerate yaml file?

**Comment by xhluca** [comment]
unfortunately the yaml file might not work for later versions of huggingface (running out of memory). i will need to look further into it. for now feel free to check out: https://github.com/McGill-NLP/weblinx/blob/main/modeling/llama/accelerate/fsdp_7b.yaml
