### ISSUE TITLE
launch error for multi-node training

### ISSUE THREAD

**Issue by kangxin** [huggingface/accelerate#218]
My working environment is as follows:

torch: 1.10.0
transformers: 4.16.0.dev0
accelerate: 0.6.0.dev0
GPU on computer one: NVIDIA TITAN RTX
GPU on computer two: NVIDIA TITAN X

I was trying to use accelerate launch on these two computers.
The test program is as follows:
```
from datasets import load_dataset
from transformers import AutoTokenizer, DataCollatorWithPadding
from tqdm.auto import tqdm

raw_datasets = load_dataset("glue", "mrpc")
checkpoint = "bert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)


def tokenize_function(example):
    return tokenizer(example["sentence1"], example["sentence2"], truncation=True)


tokenized_datasets = raw_datasets.map(tokenize_function, batched=True)
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)


tokenized_datasets = tokenized_datasets.remove_columns(["sentence1", "sentence2", "idx"])
tokenized_datasets = tokenized_datasets.rename_column("label", "labels")
tokenized_datasets.set_format("torch")


from torch.utils.data import DataLoader

train_dataloader = DataLoader(
    tokenized_datasets["train"], shuffle=True, batch_size=8, collate_fn=data_collator
)
eval_dataloader = DataLoader(
    tokenized_datasets["validation"], batch_size=8, collate_fn=data_collator
)


from accelerate import Accelerator
from transformers import AdamW, AutoModelForSequenceClassification, get_scheduler

accelerator = Accelerator()

model = AutoModelForSequenceClassification.from_pretrained(checkpoint, num_labels=2)
optimizer = AdamW(model.parameters(), lr=3e-5)

train_dl, eval_dl, model, optimizer = accelerator.prepare(
    train_dataloader, eval_dataloader, model, optimizer
)

num_epochs = 3
num_training_steps = num_epochs * len(train_dl)
lr_scheduler = get_scheduler(
    "linear",
    optimizer=optimizer,
    num_warmup_steps=0,
    num_training_steps=num_training_steps,
)

progress_bar = tqdm(range(num_training_steps))

model.train()
for epoch in range(num_epochs):
    for batch in train_dl:
        outputs = model(**batch)
        loss = outputs.loss
        accelerator.backward(loss)

        optimizer.step()
        lr_scheduler.step()
        optimizer.zero_grad()
        progress_bar.update(1)
```

I set the accelerate config as follows

On computer one:

(main) xkang@user-desktop:~/workspace/test$ accelerate config
In which compute environment are you running? ([0] This machine, [1] AWS (Amazon SageMaker)): 0
Which type of machine are you using? ([0] No distributed training, [1] multi-CPU, [2] multi-GPU, [3] TPU): 2
How many different machines will you use (use more than 1 for multi-node training)? [1]: 2
What is the rank of this machine (from 0 to the number of machines - 1 )? [0]: 0
What is the IP address of the machine that will host the main process? 192.168.0.242
What is the port you will use to communicate with the main process? 9000
Do you want to use DeepSpeed? [yes/NO]:
How many processes in total will you use? [1]:
Do you wish to use FP16 (mixed precision)? [yes/NO]: yes

On computer two:

(main) xkang@s235:test$ accelerate config
In which compute environment are you running? ([0] This machine, [1] AWS (Amazon SageMaker)): 0
Which type of machine are you using? ([0] No distributed training, [1] multi-CPU, [2] multi-GPU, [3] TPU): 2
How many different machines will you use (use more than 1 for multi-node training)? [1]: 2
What is the rank of this machine (from 0 to the number of machines - 1 )? [0]: 1
What is the IP address of the machine that will host the main process? 192.168.0.242
What is the port you will use to communicate with the main process? 9000
Do you want to use DeepSpeed? [yes/NO]:
How many processes in total will you use? [1]:
Do you wish to use FP16 (mixed precision)? [yes/NO]: yes

Then I run the command on computer one:

```
(main) xkang@user-desktop:~/workspace/test$ accelerate launch test.py
/home/xkang/anaconda3/envs/main/lib/python3.9/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See
https://pytorch.org/docs/stable/distributed.html#launch-utility for
further instructions

  warnings.warn(
Traceback (most recent call last):
  File "/home/xkang/anaconda3/envs/main/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/xkang/anaconda3/envs/main/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/xkang/anaconda3/envs/main/lib/python3.9/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/xkang/anaconda3/envs/main/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/xkang/anaconda3/envs/main/lib/python3.9/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/xkang/anaconda3/envs/main/lib/python3.9/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/home/xkang/anaconda3/envs/main/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/xkang/anaconda3/envs/main/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 231, in launch_agent
    spec = WorkerSpec(
  File "<string>", line 15, in __init__
  File "/home/xkang/anaconda3/envs/main/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 87, in __post_init__
    assert self.local_world_size > 0
AssertionError
Traceback (most recent call last):
  File "/home/xkang/anaconda3/envs/main/bin/accelerate", line 33, in <module>
    sys.exit(load_entry_point('accelerate', 'console_scripts', 'accelerate')())
  File "/home/xkang/Github/accelerate/src/accelerate/commands/accelerate_cli.py", line 41, in main
    args.func(args)
  File "/home/xkang/Github/accelerate/src/accelerate/commands/launch.py", line 378, in launch_command
    multi_gpu_launcher(args)
  File "/home/xkang/Github/accelerate/src/accelerate/commands/launch.py", line 176, in multi_gpu_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/xkang/anaconda3/envs/main/bin/python', '-m', 'torch.distributed.launch', '--use_env', '--nproc_per_node', '0', '--nnodes', '2', '--node_rank', '0', '--master_addr', '192.168.0.242', '--master_port', '9000', 'test.py']' returned non-zero exit status 1.
```

and on computer two:

```
(main) xkang@s235:test$ accelerate launch test.py
/home/xkang/anaconda3/envs/main/lib/python3.9/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See
https://pytorch.org/docs/stable/distributed.html#launch-utility for
further instructions

  warnings.warn(
Traceback (most recent call last):
  File "/home/xkang/anaconda3/envs/main/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/xkang/anaconda3/envs/main/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/xkang/anaconda3/envs/main/lib/python3.9/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/xkang/anaconda3/envs/main/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/xkang/anaconda3/envs/main/lib/python3.9/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/xkang/anaconda3/envs/main/lib/python3.9/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/home/xkang/anaconda3/envs/main/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/xkang/anaconda3/envs/main/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 231, in launch_agent
    spec = WorkerSpec(
  File "<string>", line 15, in __init__
  File "/home/xkang/anaconda3/envs/main/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 87, in __post_init__
    assert self.local_world_size > 0
AssertionError
Traceback (most recent call last):
  File "/home/xkang/anaconda3/envs/main/bin/accelerate", line 33, in <module>
    sys.exit(load_entry_point('accelerate', 'console_scripts', 'accelerate')())
  File "/home/xkang/Github/accelerate/src/accelerate/commands/accelerate_cli.py", line 41, in main
    args.func(args)
  File "/home/xkang/Github/accelerate/src/accelerate/commands/launch.py", line 378, in launch_command
    multi_gpu_launcher(args)
  File "/home/xkang/Github/accelerate/src/accelerate/commands/launch.py", line 176, in multi_gpu_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/xkang/anaconda3/envs/main/bin/python', '-m', 'torch.distributed.launch', '--use_env', '--nproc_per_node', '0', '--nnodes', '2', '--node_rank', '1', '--master_addr', '192.168.0.242', '--master_port', '9000', 'test.py']' returned non-zero exit status 1.
```

Looking forward for your reply.

**Comment by sgugger** [comment]
It looks like you did not specify the total number of processes when filling the two questionnaires. It should be the total number of GPUs you want to use, not 1.

**Comment by kangxin** [comment]
Thank you for the kind suggestion. I changed the answer to "How many processes in total will you use? [1]:" to 2, but the program throws another error on computer one:

```
(main) xkang@user-desktop:~/workspace/test$ accelerate launch test.py
/home/xkang/anaconda3/envs/main/lib/python3.9/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See
https://pytorch.org/docs/stable/distributed.html#launch-utility for
further instructions

  warnings.warn(
Reusing dataset glue (/home/xkang/.cache/huggingface/datasets/glue/mrpc/1.0.0/dacbe3125aa31d7f70367a07a8a9e72a5a0bfeb5fc42e75c9db75b96da6053ad)
100%|█████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 1630.54it/s]
Loading cached processed dataset at /home/xkang/.cache/huggingface/datasets/glue/mrpc/1.0.0/dacbe3125aa31d7f70367a07a8a9e72a5a0bfeb5fc42e75c9db75b96da6053ad/cache-3aeeb8181c85cfdd.arrow
Loading cached processed dataset at /home/xkang/.cache/huggingface/datasets/glue/mrpc/1.0.0/dacbe3125aa31d7f70367a07a8a9e72a5a0bfeb5fc42e75c9db75b96da6053ad/cache-1be6aedcee1dbe53.arrow
Loading cached processed dataset at /home/xkang/.cache/huggingface/datasets/glue/mrpc/1.0.0/dacbe3125aa31d7f70367a07a8a9e72a5a0bfeb5fc42e75c9db75b96da6053ad/cache-8913afcc8ff50f49.arrow
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "/home/xkang/workspace/test/test.py", line 41, in <module>
    train_dl, eval_dl, model, optimizer = accelerator.prepare(
  File "/home/xkang/Github/accelerate/src/accelerate/accelerator.py", line 276, in prepare
    result = tuple(self._prepare_one(obj) for obj in args)
  File "/home/xkang/Github/accelerate/src/accelerate/accelerator.py", line 276, in <genexpr>
    result = tuple(self._prepare_one(obj) for obj in args)
  File "/home/xkang/Github/accelerate/src/accelerate/accelerator.py", line 234, in _prepare_one
    return self.prepare_model(obj)
  File "/home/xkang/Github/accelerate/src/accelerate/accelerator.py", line 295, in prepare_model
    model = torch.nn.parallel.DistributedDataParallel(
  File "/home/xkang/anaconda3/envs/main/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 578, in __init__
    dist._verify_model_across_ranks(self.process_group, parameters)
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1634272204863/work/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:957, unhandled system error, NCCL version 21.0.3
ncclSystemError: System call (socket, malloc, munmap, etc) failed.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1143697) of binary: /home/xkang/anaconda3/envs/main/bin/python
```

And the computer two hangs with the following output:

```
(main) xkang@s235:test$ accelerate launch test.py
/home/xkang/anaconda3/envs/main/lib/python3.9/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See
https://pytorch.org/docs/stable/distributed.html#launch-utility for
further instructions

  warnings.warn(
Reusing dataset glue (/home/xkang/.cache/huggingface/datasets/glue/mrpc/1.0.0/dacbe3125aa31d7f70367a07a8a9e72a5a0bfeb5fc42e75c9db75b96da6053ad)
100%|██████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 536.81it/s]
Loading cached processed dataset at /home/xkang/.cache/huggingface/datasets/glue/mrpc/1.0.0/dacbe3125aa31d7f70367a07a8a9e72a5a0bfeb5fc42e75c9db75b96da6053ad/cache-3aeeb8181c85cfdd.arrow
100%|███████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.84ba/s]
Loading cached processed dataset at /home/xkang/.cache/huggingface/datasets/glue/mrpc/1.0.0/dacbe3125aa31d7f70367a07a8a9e72a5a0bfeb5fc42e75c9db75b96da6053ad/cache-fb93715b431c18b2.arrow
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.decoder.weight']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
^CWARNING:torch.distributed.elastic.agent.server.api:Received 2 death signal, shutting down workers
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 21931 closing signal SIGINT
Traceback (most recent call last):
  File "/home/xkang/anaconda3/envs/main/bin/accelerate", line 33, in <module>
    sys.exit(load_entry_point('accelerate', 'console_scripts', 'accelerate')())
  File "/home/xkang/Github/accelerate/src/accelerate/commands/accelerate_cli.py", line 41, in main
    args.func(args)
  File "/home/xkang/Github/accelerate/src/accelerate/commands/launch.py", line 378, in launch_command
    multi_gpu_launcher(args)
  File "/home/xkang/Github/accelerate/src/accelerate/commands/launch.py", line 174, in multi_gpu_launcher
    process.wait()
  File "/home/xkang/anaconda3/envs/main/lib/python3.9/subprocess.py", line 1189, in wait
    return self._wait(timeout=timeout)
  File "/home/xkang/anaconda3/envs/main/lib/python3.9/subprocess.py", line 1917, in _wait
    (pid, sts) = self._try_wait(0)
  File "/home/xkang/anaconda3/envs/main/lib/python3.9/subprocess.py", line 1875, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
```

Is there anything wrong with my environment setting?

**Comment by sgugger** [comment]
Mmm, this NCCL error is weird and might be linked to your setup indeed (maybe a driver issue). Are you using 1 GPU on each machine only?

**Comment by kangxin** [comment]
Thank you for the quick response. Each computer has only 1 GPU. I tried to launch the test on different machines, both of which has single NVIDIA TITAN X. The error was similar:

```
(main) xkang@root:~/workspace/test$ accelerate launch test.py
/home/xkang/anaconda3/envs/main/lib/python3.9/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See
https://pytorch.org/docs/stable/distributed.html#launch-utility for
further instructions

  warnings.warn(
Downloading: 28.8kB [00:00, 13.0MB/s]
Downloading: 28.7kB [00:00, 14.3MB/s]
Downloading and preparing dataset glue/mrpc (download: 1.43 MiB, generated: 1.43 MiB, post-processed: Unknown size, total: 2.85 MiB) to /home/xkang/.cache/huggingface/datasets/glue/mrpc/1.0.0/dacbe3125aa31d7f70367a07a8a9e72a5a0bfeb5fc42e75c9db75b96da6053ad...
Downloading: 6.22kB [00:00, 4.40MB/s]                                                           | 0/3 [00:00<?, ?it/s]
Downloading: 1.05MB [00:00, 1.52MB/s]                                                   | 1/3 [00:01<00:03,  1.51s/it]
Downloading: 441kB [00:00, 845kB/s]█████████████████████████▎                           | 2/3 [00:03<00:01,  1.87s/it]
100%|███████████████████████████████████████████████████████████████████████████████████| 3/3 [00:05<00:00,  1.81s/it]
Dataset glue downloaded and prepared to /home/xkang/.cache/huggingface/datasets/glue/mrpc/1.0.0/dacbe3125aa31d7f70367a07a8a9e72a5a0bfeb5fc42e75c9db75b96da6053ad. Subsequent calls will reuse this data.
100%|██████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 767.25it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████| 28.0/28.0 [00:00<00:00, 22.6kB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████████| 570/570 [00:00<00:00, 459kB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████| 226k/226k [00:00<00:00, 342kB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████| 455k/455k [00:00<00:00, 525kB/s]
100%|███████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 27.51ba/s]
100%|███████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 55.23ba/s]
100%|███████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 29.77ba/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████| 420M/420M [00:38<00:00, 11.6MB/s]
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.bias']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "/home/xkang/workspace/test/test.py", line 41, in <module>
    train_dl, eval_dl, model, optimizer = accelerator.prepare(
  File "/home/xkang/Github/accelerate/src/accelerate/accelerator.py", line 276, in prepare
    result = tuple(self._prepare_one(obj) for obj in args)
  File "/home/xkang/Github/accelerate/src/accelerate/accelerator.py", line 276, in <genexpr>
    result = tuple(self._prepare_one(obj) for obj in args)
  File "/home/xkang/Github/accelerate/src/accelerate/accelerator.py", line 234, in _prepare_one
    return self.prepare_model(obj)
  File "/home/xkang/Github/accelerate/src/accelerate/accelerator.py", line 295, in prepare_model
    model = torch.nn.parallel.DistributedDataParallel(
  File "/home/xkang/anaconda3/envs/main/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 578, in __init__
    dist._verify_model_across_ranks(self.process_group, parameters)
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1634272204863/work/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:957, unhandled system error, NCCL version 21.0.3
ncclSystemError: System call (socket, malloc, munmap, etc) failed.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 19600) of binary: /home/xkang/anaconda3/envs/main/bin/python
```
