### ISSUE TITLE
device_map not work on huawei NPU device  

### ISSUE THREAD

**Issue by lichangW** [huggingface/accelerate#2191]
### System Info

hi， I was trying to run llama2 over several huawei NPU device which has already been supported by transformers and accelerator;  it worked ok when I run with {"":"npu"} or {"":"npu:1"}, and will load model on device 0 or device 1. But I would like to use all available device, and it would load on cpu when use  device_map="auto" which is not what I wanted, any help is appreciated!
`
model = LlamaForCausalLM.from_pretrained(model_path,device_map={"":"npu"})
tokenizer = AutoTokenizer.from_pretrained(model_path)
`

the accelerator can detect npu device:
`
accelerator = Accelerator()
print('Accelerator device: ', accelerator.device)

output:
Accelerator device: npu
`

another case when set custom device_amp:

llama_dev_map2={
"lm_head":"npu:1",
"model.embed_tokens":"npu:1",
"model.layers.0":"npu:1",
"model.layers.1":"npu:1",
"model.layers.2":"npu:1",
"model.layers.3":"npu:1",
"model.layers.4":"npu:1",
"model.layers.5":"npu:1",
"model.layers.6":"npu:1",
"model.layers.7":"npu:1",
"model.layers.8":"npu:1",
"model.layers.9":"npu:1",
"model.layers.10":"npu:1",
"model.layers.11":"npu:1",
"model.layers.12":"npu:1",
"model.layers.13":"npu:1",
"model.layers.14":"npu:1",
"model.layers.15":"npu:1",
"model.layers.16":"npu:1",
"model.layers.17":"npu:1",
"model.layers.18":"npu:1",
"model.layers.19":"npu:1",
"model.layers.20":"npu:1",
"model.layers.21":"npu:1",
"model.layers.22":"npu:1",
"model.layers.23":"npu:1",
"model.layers.24":"npu:1",
"model.layers.25":"npu:1",
"model.layers.26":"npu:1",
"model.layers.27":"npu:1",
"model.layers.28":"npu:1",
"model.layers.29":"npu:1",
"model.layers.30":"npu:1",
"model.layers.31":"npu:1",
"model.norm":"npu:2"
}
`
model = LlamaForCausalLM.from_pretrained(model_path,device_map=llama_dev_map2)
tokenizer = AutoTokenizer.from_pretrained(model_path)
`

errors: 
![image](https://github.com/huggingface/transformers/assets/9452272/459697b5-3d31-424c-a56f-c3705d577549)

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

details above

### Expected behavior

I would like to use all available no GPU device with device_map

**Comment by statelesshz** [comment]
@lichangW @NingJinzhong Thanks for your feedback. Currently, torch_npu lacks certain features that prevent it from supporting device_map="auto". However, we are actively working to resolve this issue. If all goes according to plan, we should have support for NPUs using device_map="auto" within the next two weeks

**Comment by lichangW** [comment]
> @lichangW @NingJinzhong Thanks for your feedback! Currently, torch_npu lacks certain features that prevent it from supporting device_map="auto". However, we are actively working to resolve this issue. If all goes according to plan, we should have support for NPUs using device_map="auto" within the next two weeks 😄

that's great news, thanks for reply!

**Comment by junior-zsy** [comment]
@statelesshz Hello, I have also encountered this problem. Has it been resolved now? Thank you

**Comment by junior-zsy** [comment]
@statelesshz  Branch code error 

File "/home/jovyan/fast-data/mini/envs/huawei/lib/python3.8/site-packages/accelerate/utils/modeling.py", line 678, in get_max_memory
   max_memory = {i: torch.npu.mem_get_ifo(i)[0] for i in range(torch.npu.device_count())}
  File "/home/jovyan/fast-data/mini/envs/huawei/lib/python3.8/site-packages/accelerate/utils/modeling.py", line 678, in <dictcomp>
    max_memory = {i: torch.npu.mem_get_ifo(i)[0] for i in range(torch.npu.device_count())}
AttributeError: module 'torch_npu.npu' has no attribute 'mem_get_ifo'

**Comment by junior-zsy** [comment]
@statelesshz  i change mem_get_ifo to. torch.npu.max_memory_allocated,it works ,But there are other errors

Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████| 7/7 [00:07<00:00,  1.06s/it]
Traceback (most recent call last):
  File "server_fb.py", line 21, in <module>
    response, history = model.chat(tokenizer, "你是谁开发的", history=[])
  File "/home/jovyan/fast-data/mini/envs/huawei/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/jovyan/.cache/huggingface/modules/transformers_modules/chatglm3-6b-32k/modeling_chatglm.py", line 1038, in chat
    outputs = self.generate(**inputs, **gen_kwargs, eos_token_id=eos_token_id)
  File "/home/jovyan/fast-data/mini/envs/huawei/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/jovyan/fast-data/mini/envs/huawei/lib/python3.8/site-packages/transformers/generation/utils.py", line 1572, in generate
    return self.sample(
  File "/home/jovyan/fast-data/mini/envs/huawei/lib/python3.8/site-packages/transformers/generation/utils.py", line 2619, in sample
    outputs = self(
  File "/home/jovyan/fast-data/mini/envs/huawei/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jovyan/fast-data/mini/envs/huawei/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jovyan/.cache/huggingface/modules/transformers_modules/chatglm3-6b-32k/modeling_chatglm.py", line 940, in forward
    transformer_outputs = self.transformer(
  File "/home/jovyan/fast-data/mini/envs/huawei/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jovyan/fast-data/mini/envs/huawei/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jovyan/.cache/huggingface/modules/transformers_modules/chatglm3-6b-32k/modeling_chatglm.py", line 833, in forward
    hidden_states, presents, all_hidden_states, all_self_attentions = self.encoder(
  File "/home/jovyan/fast-data/mini/envs/huawei/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jovyan/fast-data/mini/envs/huawei/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jovyan/.cache/huggingface/modules/transformers_modules/chatglm3-6b-32k/modeling_chatglm.py", line 643, in forward
    layer_ret = layer(
  File "/home/jovyan/fast-data/mini/envs/huawei/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jovyan/fast-data/mini/envs/huawei/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jovyan/.cache/huggingface/modules/transformers_modules/chatglm3-6b-32k/modeling_chatglm.py", line 547, in forward
    attention_output, kv_cache = self.self_attention(
  File "/home/jovyan/fast-data/mini/envs/huawei/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jovyan/fast-data/mini/envs/huawei/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jovyan/.cache/huggingface/modules/transformers_modules/chatglm3-6b-32k/modeling_chatglm.py", line 379, in forward
    mixed_x_layer = self.query_key_value(hidden_states)
  File "/home/jovyan/fast-data/mini/envs/huawei/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jovyan/fast-data/mini/envs/huawei/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jovyan/fast-data/mini/envs/huawei/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'

**Comment by muellerzr** [comment]
@junior-zsy please either provide feedback here or in the PR, please not both to avoid spam :)

**Comment by junior-zsy** [comment]
> @junior-zsy please either provide feedback here or in the PR, please not both to avoid spam :)

ok

**Comment by junior-zsy** [comment]
@muellerzr  Can this be resolved first? We are Chinese users and Nvidia graphics cards are prohibited from being sold to Chinese users, so we can only use Huawei's NPU. Please help us resolve this first. Thank you

**Comment by muellerzr** [comment]
We are awaiting on the open PR, there is nothing on our end we can do. We are well aware of this problem and appreciate your patience as @statelesshz works on this integration in full to ensure that users can maintain the stable API and working code that accelerate provides.
