### ISSUE TITLE
Trouble training in fp16 when modifying the optimizer mid-training 

### ISSUE THREAD

**Issue by linoytsaban** [huggingface/accelerate#2193]
I'm building a training script and we are having an issue with `accelerate` and modifying the optimizer mid-training: 

- we have an operation to stop training the text-encoder midway through the steps but keep training the unet, meaning we _drop the text_encoder parameters halfway_, and re-initialize the optimizer only with the unet parameters. 

- Specifically, it’s failing when training in `fp16` . The same operation/code works fine when training in `bf16` or `fp32`

- This is the error we get when trying to do this operation in `fp16`
 `RuntimeError: unscale_() has already been called on this optimizer since the last update().`

The code where the optimizer update takes place: [https://github.com/linoytsaban/diffusers/blob/0af8f44755f0ca6e9e835f85f285a2d7133c[…]anced_diffusion_training/train_dreambooth_lora_sdxl_advanced.py](https://github.com/linoytsaban/diffusers/blob/0af8f44755f0ca6e9e835f85f285a2d7133cf579/examples/advanced_diffusion_training/train_dreambooth_lora_sdxl_advanced.py#L1632)

**Comment by pacman100** [comment]
Hello, could you please share the launch command and the versions of the Accelerate, Diffusers and Transformers?

**Comment by linoytsaban** [comment]
Edited to include these, thanks!

**Comment by pacman100** [comment]
When you create a new optimizer mid-way, it breaks the scheduler which was using the previous optimizer, the Accelerator object has no idea about this new optimizer as it wasn't prepared via `accelerator. prepare`. This leaves the optimizer and scheduler in a broken state. Instead of creating a new optimizer, please set the learning rate of these param groups to 0 as is done in https://github.com/cloneofsimo/lora/blob/bdd51b04c49fa90a88919a19850ec3b4cf3c5ecd/training_scripts/train_lora_w_ti.py#L987-L994. 

Hope this helps.

**Comment by pacman100** [comment]
Also, as a side note, this script breakdown when using tensorboard because the config now has lists as values which breaks the tensorboard logging. Notice, `'token_abstraction': ['TOK']`. 

```
{'pretrained_model_name_or_path': 'stabilityai/stable-diffusion-xl-base-1.0', 'pretrained_vae_model_name_or_path': 'madebyollin/sdxl-vae-fp16-fix', 'revision': None, 'dataset_name': 'LinoyTsaban/3d_icon', 'dataset_config_name': None, 'instance_data_dir': None, 'cache_dir': None, 'image_column': 'image', 'caption_column': None, 'repeats': 1, 'class_data_dir': None, 'instance_prompt': 'a <s0><s1> icon', 'token_abstraction': ['TOK'], 'num_new_tokens_per_abstraction': 2, 'class_prompt': None, 'validation_prompt': None, 'num_validation_images': 4, 'validation_epochs': 50, 'with_prior_preservation': False, 'prior_loss_weight': 1.0, 'num_class_images': 100, 'output_dir': '3d_icon_SDXL_LoRA', 'seed': 0, 'resolution': 1024, 'crops_coords_top_left_h': 0, 'crops_coords_top_left_w': 0, 'center_crop': False, 'train_text_encoder': False, 'train_batch_size': 1, 'sample_batch_size': 4, 'num_train_epochs': 5, 'max_train_steps': 100, 'checkpointing_steps': 2000, 'checkpoints_total_limit': None, 'resume_from_checkpoint': None, 'gradient_accumulation_steps': 1, 'gradient_checkpointing': True, 'learning_rate': 0.0001, 'text_encoder_lr': 5e-06, 'scale_lr': False, 'lr_scheduler': 'constant', 'snr_gamma': None, 'lr_warmup_steps': 0, 'lr_num_cycles': 1, 'lr_power': 1.0, 'dataloader_num_workers': 0, 'train_text_encoder_ti': True, 'train_text_encoder_ti_frac': 0.5, 'train_text_encoder_frac': 1.0, 'optimizer': 'adamW', 'use_8bit_adam': False, 'adam_beta1': 0.9, 'adam_beta2': 0.999, 'prodigy_beta3': None, 'prodigy_decouple': True, 'adam_weight_decay': 0.0001, 'adam_weight_decay_text_encoder': None, 'adam_epsilon': 1e-08, 'prodigy_use_bias_correction': True, 'prodigy_safeguard_warmup': True, 'max_grad_norm': 1.0, 'push_to_hub': False, 'hub_token': None, 'hub_model_id': None, 'logging_dir': 'logs', 'allow_tf32': False, 'report_to': 'tensorboard', 'mixed_precision': 'fp16', 'prior_generation_precision': None, 'local_rank': -1, 'enable_xformers_memory_efficient_attention': False, 'rank': 4}
Traceback (most recent call last):
  File "/raid/sourab/temp/issues/accelerate/train_dreambooth_lora_sdxl_advanced.py", line 1987, in <module>
    main(args)
  File "/raid/sourab/temp/issues/accelerate/train_dreambooth_lora_sdxl_advanced.py", line 1570, in main
    accelerator.init_trackers("dreambooth-lora-sd-xl", config=vars(args))
  File "/raid/sourab/accelerate/src/accelerate/accelerator.py", line 617, in _inner
    return PartialState().on_main_process(function)(*args, **kwargs)
  File "/raid/sourab/accelerate/src/accelerate/accelerator.py", line 2335, in init_trackers
    tracker.store_init_configuration(config)
  File "/raid/sourab/accelerate/src/accelerate/tracking.py", line 75, in execute_on_main_process
    return PartialState().on_main_process(function)(self, *args, **kwargs)
  File "/raid/sourab/accelerate/src/accelerate/tracking.py", line 207, in store_init_configuration
    self.writer.add_hparams(values, metric_dict={})
  File "/raid/sourab/miniconda3/envs/hf/lib/python3.10/site-packages/torch/utils/tensorboard/writer.py", line 332, in add_hparams
    exp, ssi, sei = hparams(hparam_dict, metric_dict, hparam_domain_discrete)
  File "/raid/sourab/miniconda3/envs/hf/lib/python3.10/site-packages/torch/utils/tensorboard/summary.py", line 281, in hparams
    raise ValueError(
ValueError: value should be one of int, float, str, bool, or torch.Tensor
```
