### ISSUE TITLE
model saved after wait_for_everyone could not be loaded

### ISSUE THREAD

**Issue by RylonW** [huggingface/accelerate#2209]
### System Info

```Shell
- `Accelerate` version: 0.24.1
- Platform: Linux-5.4.0-167-generic-x86_64-with-glibc2.31
- Python version: 3.10.9
- Numpy version: 1.23.5
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 251.55 GB
- GPU type: NVIDIA GeForce RTX 4090
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: MULTI_GPU
        - mixed_precision: bf16
        - use_cpu: False
        - debug: True
        - num_processes: 2
        - machine_rank: 0
        - num_machines: 1
        - gpu_ids: all
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

I came up with the error below when I use torch.load(args.wc_model_path, map_location='cpu'):
```bash
Traceback (most recent call last):
  File "/home/wrl/DewarpNet-master/infer.py", line 148, in <module>
    read(args)
  File "/home/wrl/DewarpNet-master/infer.py", line 26, in read
    para = torch.load(args.wc_model_path, map_location='cpu')
  File "/home/wrl/anaconda3/lib/python3.10/site-packages/torch/serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/wrl/anaconda3/lib/python3.10/site-packages/torch/serialization.py", line 1172, in _load
    result = unpickler.load()
  File "/home/wrl/anaconda3/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 881, in __setstate__
    self.process_group = _get_default_group()
  File "/home/wrl/anaconda3/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 707, in _get_default_group
    raise RuntimeError(
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
```
I save model after wait_for_everyone:
```python
accelerator.wait_for_everyone()
accelerator.save(model, args.logdir+"{}_{}_{}_{}_{}_best_model.pkl".format(args.arch, epoch+1,val_mse,train_mse,experiment_name))
```

### Expected behavior

the state dict be loaded successfully

**Comment by muellerzr** [comment]
When saving your model please use `accelerator.save_model`, as we generally need to remove and unwrap all of the parts used during DDP (and hence your issue)

**Comment by RylonW** [comment]
Thank you very much! I have changed the function to "save_model" and load the trained .pth file successfully, but I still wonder if there are any methods to unwarp the state_dict from the .pth file I saved by "save" function.

**Comment by RylonW** [comment]
Thank you for your reply!
