### ISSUE TITLE
Multi node training exited with socket timeout

### ISSUE THREAD

**Issue by summerisc** [huggingface/accelerate#2229]
I am using Accelerate for multi-node training. Within docker, env uses the host network.
Main node reports:
```
`Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/elastic/agent/server/api.py", line 904, in _exit_barrier
    barrier_timeout=self._exit_barrier_timeout,
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/elastic/utils/store.py", line 67, in barrier
    synchronize(store, data, rank, world_size, key_prefix, barrier_timeout)
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/elastic/utils/store.py", line 53, in synchronize
    agent_data = get_all(store, key_prefix, world_size)
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/elastic/utils/store.py", line 31, in get_all
    data = store.get(f"{prefix}{idx}")
RuntimeError: Socket Timeout`
```
after hangs a while.
Enable NCCL=INFO and found it reports:
```
`ps-8:796:796 [1] NCCL INFO Bootstrap : Using enp67s0:192.168.1.8<0>
ps-8:796:796 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
ps-8:796:796 [1] NCCL INFO NET/IB : No device found.
ps-8:796:796 [1] NCCL INFO NET/Socket : Using [0]enp67s0:192.168.1.8<0>
ps-8:796:796 [1] NCCL INFO Using network Socket

ps-8:795:822 [0] include/socket.h:409 NCCL WARN Net : Connect to 192.168.1.9<54263> failed : No route to host
ps-8:795:822 [0] NCCL INFO bootstrap.cc:148 -> 2

ps-8:797:824 [2] include/socket.h:409 NCCL WARN Net : Connect to 192.168.1.9<48607> failed : No route to host
`
```
I can ping IP(192.168.1.9) from this server but why does it show no route to host here? Also, I am using the right NIC, I explicitly set NIC.

**Comment by muellerzr** [comment]
Can you ping from inside the docker image?
