### ISSUE TITLE
when a tensor is generated from some_func(A.shape) (where A is a tensor), the generated tensor locates in cpu, not A's device

### ISSUE THREAD

**Issue by weizhenhuan** [huggingface/accelerate#2251]
how to solve it ? I have tried tensor.to(A.device) and tensor.to(accelerator.device), but it seems not to work.

**Comment by BenjaminBossan** [comment]
We need more context to answer the question. Could you please show the code that causes the error, as well as the full error message?

**Comment by weizhenhuan** [comment]
I am currently working on this code, which is part of the diffusion model:
```python
        t, weights = self.schedule_sampler.sample(batch.shape[0])
```
where sample() is implemented as follows:
```python
    def sample(self, batch_size, device):
        w = self.weights()
        p = w / np.sum(w)
        indices_np = np.random.choice(len(p), size=(batch_size,), p=p)
        indices = th.from_numpy(indices_np).long().to(device)
        weights_np = 1 / (len(p) * p[indices_np])
        weights = th.from_numpy(weights_np).float().to(device)
        return indices, weights
```
By debugging, the batch has been in gpu, but after running sample(), both t and weights are all in cpu. I have tried t.to(batch.device), t.to(accelerator.device), but it all fails.

**Comment by BenjaminBossan** [comment]
> I have tried t.to(batch.device), t.to(accelerator.device), but it all fails.

Normally it should work. What is the value of `batch.device` and `accelerator.device`? What is the error you're getting (please copy and paste the whole error message).

**Comment by muellerzr** [comment]
And please give us the output of `accelerate env` as well

**Comment by weizhenhuan** [comment]
Both `batch.device` and `accelerate.device` is `cuda:x`, but `t.device` is `cpu` 

Below is the error message.
```  
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cpu!
  0%|                                                                                                    | 0/6171 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/home/weizhenhuan/code/AGRoL_acce/train.py", line 178, in <module>
    main()
  File "/home/weizhenhuan/code/AGRoL_acce/train.py", line 172, in main
    train_diffusion_model(args, dataloader)
  File "/home/weizhenhuan/code/AGRoL_acce/train.py", line 44, in train_diffusion_model
    TrainLoop(args, model, diffusion, dataloader, accelerator).run_loop()
  File "/home/weizhenhuan/code/AGRoL_acce/runner/training_loop.py", line 113, in run_loop
    self.run_step(motion, cond)
  File "/home/weizhenhuan/code/AGRoL_acce/runner/training_loop.py", line 129, in run_step
    self.forward_backward(batch, cond)
  File "/home/weizhenhuan/code/AGRoL_acce/runner/training_loop.py", line 148, in forward_backward
    losses = compute_losses()
  File "/home/weizhenhuan/code/AGRoL_acce/diffusion/respace.py", line 106, in training_losses
    return super().training_losses(self._wrap_model(model), *args, **kwargs)
  File "/home/weizhenhuan/code/AGRoL_acce/diffusion/diffusion_model.py", line 54, in training_losses
    x_t = self.q_sample(x_start, t, noise=noise)
  File "/home/weizhenhuan/code/AGRoL_acce/diffusion/gaussian_diffusion.py", line 260, in q_sample
    _extract_into_tensor(self.sqrt_alphas_cumprod, t, x_start.shape) * x_start
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
[2023-12-14 21:15:56,411] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 1149974) of binary: /home/weizhenhuan/miniconda3/envs/torch/bin/python
Traceback (most recent call last):
  File "/home/weizhenhuan/miniconda3/envs/torch/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/weizhenhuan/miniconda3/envs/torch/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/home/weizhenhuan/miniconda3/envs/torch/lib/python3.9/site-packages/accelerate/commands/launch.py", line 1008, in launch_command
    multi_gpu_launcher(args)
  File "/home/weizhenhuan/miniconda3/envs/torch/lib/python3.9/site-packages/accelerate/commands/launch.py", line 666, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/weizhenhuan/miniconda3/envs/torch/lib/python3.9/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/weizhenhuan/miniconda3/envs/torch/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/weizhenhuan/miniconda3/envs/torch/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-12-14_21:15:56
  host      : 1070
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 1149975)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-12-14_21:15:56
  host      : 1070
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1149974)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

The accelerate env is:
```

Copy-and-paste the text below in your GitHub issue

- `Accelerate` version: 0.25.0
- Platform: Linux-5.15.0-78-generic-x86_64-with-glibc2.31
- Python version: 3.9.18
- Numpy version: 1.24.1
- PyTorch version (GPU?): 2.1.1+cu121 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 376.56 GB
- GPU type: NVIDIA GeForce RTX 3090
- `Accelerate` default config:
        Not found
```

**Comment by weizhenhuan** [comment]
Resolved. I modify the code as follows:
```python
        t, weights = self.schedule_sampler.sample(batch.shape[0], batch.device)
```
```python
    def sample(self, batch_size, device):
        w = self.weights()
        p = w / np.sum(w)
        indices_np = np.random.choice(len(p), size=(batch_size,), p=p)
        indices = th.from_numpy(indices_np).long().to(device)
        weights_np = 1 / (len(p) * p[indices_np])
        weights = th.from_numpy(weights_np).float().to(device)
        return indices, weights
```

It's really strange. Why above code works?? Why below code not works?
```python
t, weights = self.schedule_sampler.sample(batch.shape[0])
t.to(batch.device)
weights.to(batch.device)
```
Are there any differences between the two?

**Comment by BenjaminBossan** [comment]
> Are there any differences between the two?

Yes, in the first example, you assign the new variables, in the 2nd you don't. You'd have to change it to `t = t.to(batch.device)`. `.to` is not in-place.

Anyway, this should be the solution, feel free to re-open the issue if something else comes up.
