### ISSUE TITLE
when i have nn.module have another nn.module inside it that causes nans in fp16 precision

### ISSUE THREAD

**Issue by stunlocked1** [huggingface/accelerate#2252]
### System Info

```Shell
accelerate                0.25.0             pyhd8ed1ab_0    conda-forge
windows 11
python 3.11
numpy                     1.26.0          py311hdab7c0b_0    anaconda
numpy-base                1.26.0          py311hd01c5d8_0    anaconda
pytorch                   2.1.1           py3.11_cuda11.8_cudnn8_0    pytorch
pytorch-cuda              11.8                 h24eeafa_5    pytorch
pytorch-lightning         2.1.1              pyhd8ed1ab_0    conda-forge
pytorch-mutex             1.0                        cuda    pytorch
torchaudio                2.1.1                    pypi_0    pypi
torchmetrics              1.2.0              pyhd8ed1ab_0    conda-forge
torchvision               0.16.1                   pypi_0    pypi

(pytorch311) C:\Users\nkshv>accelerate env
Traceback (most recent call last):
  File "D:\miniconda3\envs\pytorch311\Scripts\accelerate-script.py", line 5, in <module>
    from accelerate.commands.accelerate_cli import main
  File "D:\miniconda3\envs\pytorch311\Lib\site-packages\accelerate\commands\accelerate_cli.py", line 21, in <module>
    from accelerate.commands.estimate import estimate_command_parser
  File "D:\miniconda3\envs\pytorch311\Lib\site-packages\accelerate\commands\estimate.py", line 18, in <module>
    from huggingface_hub import model_info
ModuleNotFoundError: No module named 'huggingface_hub'


also idk what scripts mean
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

```
class Autoencoder(nn.Module):
  def __init__(self, encoder, decoder):
    super().__init__()
    self.encoder = encoder
    self.decoder = decoder

  def forward(self, x):
    x = self.encoder(x)
    x = self.decoder(x)
    return x
```
you get what i mean
inside encoder nans start appearing after second conv2d forward.

And if I just copy everything from encoder and decoder into one thing it works fine

### Expected behavior

Also pls tell me if I am doing something extremely stupid there. if I am not I can actually use my time to do reproduction steps

**Comment by stunlocked1** [comment]
nevermind im just an idiot its a bug with my stupid nvidia 1650

**Comment by stunlocked1** [comment]
i mean this one 
https://github.com/pytorch/pytorch/issues/77955
btw
