### ISSUE TITLE
I run an llm train script in docker container wiith anaconda3 env but it shows error 

### ISSUE THREAD

**Issue by bewithme** [huggingface/accelerate#2277]
### System Info

```Shell
- `Accelerate` version: 0.24.1
- Platform: Linux-3.10.0-1160.76.1.el7.x86_64-x86_64-with-glibc2.27
- Python version: 3.10.13
- Numpy version: 1.26.2
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 376.40 GB
- GPU type: Tesla V100-PCIE-32GB
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: MULTI_GPU
        - mixed_precision: fp16
        - use_cpu: False
        - debug: False
        - num_processes: 2
        - machine_rank: 0
        - num_machines: 1
        - gpu_ids: all
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

here is my accelerate launch script

`accelerate launch python src/train_bash.py --stage sft --do_train --model_name_or_path /data/chatglm3-6b-base --dataset self_cognition --template chatglm3 --finetuning_type lora --lora_target query_key_value --output_dir sft_checkpoint --overwrite_cache --per_device_train_batch_size 4 --gradient_a ccumulation_steps 4 --lr_scheduler_type cosine --logging_steps 10 --save_steps 1000 --learning_rate 5e-5 --num_train_epochs 10.0 --plot_loss --fp16
`

and error info

```
root/anaconda3/envs/llama_factory/bin/python: can't open file '/app/LLaMA-Factory/python': [Errno 2] No such file or directory
/root/anaconda3/envs/llama_factory/bin/python: can't open file '/app/LLaMA-Factory/python': [Errno 2] No such file or directory
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 2) local_rank: 0 (pid: 9124) of binary: /root/anaconda3/envs/llama_factory/bin/python
Traceback (most recent call last):
  File "/root/anaconda3/envs/llama_factory/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/root/anaconda3/envs/llama_factory/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/root/anaconda3/envs/llama_factory/lib/python3.10/site-packages/accelerate/commands/launch.py", line 985, in launch_command
    multi_gpu_launcher(args)
  File "/root/anaconda3/envs/llama_factory/lib/python3.10/site-packages/accelerate/commands/launch.py", line 654, in multi_gpu_launcher
    distrib_run.run(args)
  File "/root/anaconda3/envs/llama_factory/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/root/anaconda3/envs/llama_factory/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/anaconda3/envs/llama_factory/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
python FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-12-22_07:20:25
  host      : gpu003
  rank      : 1 (local_rank: 1)
  exitcode  : 2 (pid: 9125)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-12-22_07:20:25
  host      : gpu003
  rank      : 0 (local_rank: 0)
  exitcode  : 2 (pid: 9124)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

```

### Expected behavior

can run it correctly

**Comment by muellerzr** [comment]
Don't use `python` when using `accelerate launch`, that's incompatible.

In your command:

```diff
-accelerate launch python 
+accelerate launch 
```

**Comment by bewithme** [comment]
> Don't use `python` when using `accelerate launch`, that's incompatible.
> 
> In your command:
> 
> ```diff
> -accelerate launch python 
> +accelerate launch 
> ```

thank you so much , its working now.
