### ISSUE TITLE
SIGKILL(Signal 9) when attempting to save state SDXL fine-tune LoRA

### ISSUE THREAD

**Issue by sr5434** [huggingface/accelerate#2281]
I am finetuning SDXL on a small dataset(~800 samples), and when the script attempts to checkpoint, it is always killed by the system, leading to all training progress being lost. I am using Google Colab with a T4
Logs:
```
...
12/23/2023 17:24:30 - INFO - __main__ - ***** Running training *****
12/23/2023 17:24:30 - INFO - __main__ -   Num examples = 803
12/23/2023 17:24:30 - INFO - __main__ -   Num Epochs = 6
12/23/2023 17:24:30 - INFO - __main__ -   Instantaneous batch size per device = 1
12/23/2023 17:24:30 - INFO - __main__ -   Total train batch size (w. parallel, distributed & accumulation) = 6
12/23/2023 17:24:30 - INFO - __main__ -   Gradient Accumulation steps = 6
12/23/2023 17:24:30 - INFO - __main__ -   Total optimization steps = 803
Steps:   0% 0/803 [01:23<?, ?it/s, lr=0, step_loss=0.0412][2023-12-23 17:25:57,281] [INFO] [loss_scaler.py:183:update_scale] [deepspeed] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 4294967296, reducing to 2147483648
Steps:   0% 1/803 [01:27<19:26:03, 87.24s/it, lr=0, step_loss=0.0412]12/23/2023 17:25:57 - INFO - accelerate.accelerator - Saving current state to /content/sddata/finetune/logos/checkpoint-1
12/23/2023 17:25:57 - INFO - accelerate.accelerator - Saving DeepSpeed Model and Optimizer
[2023-12-23 17:25:57,462] [INFO] [logging.py:96:log_dist] [Rank 0] [Torch] Checkpoint pytorch_model is about to be saved!
/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py:1879: UserWarning: Positional args are being deprecated, use kwargs instead. Refer to https://pytorch.org/docs/master/generated/torch.nn.Module.html#torch.nn.Module.state_dict for details.
  warnings.warn(
[2023-12-23 17:26:05,790] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: -9) local_rank: 0 (pid: 7368) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 1002, in launch_command
    deepspeed_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 718, in deepspeed_launcher
    distrib_run.run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/content/diffusers/examples/text_to_image/train_text_to_image_lora_sdxl.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-12-23_17:26:05
  host      : 2218c553da6b
  rank      : 0 (local_rank: 0)
  exitcode  : -9 (pid: 7368)
  error_file: <N/A>
  traceback : Signal 9 (SIGKILL) received by PID 7368
============================================================
```
The RAM and VRAM both had 9.5 GBs utilized.

**Comment by pacman100** [comment]
Hello, what is the launch command, library versions and the script being run?

**Comment by sr5434** [comment]
I was using the fine tune SDXL with LoRA script in diffusers. I forced the problem by running it with python instead of accelerate launch
