### ISSUE TITLE
roberta-base pretraining using trainer and accelerate on TPU help

### ISSUE THREAD

**Issue by gurveervirk** [huggingface/accelerate#2293]
I am trying to pretrain roberta-base on a number of DNA sequences. The data files have one sequence per line. I have the tokenizer trained for my purpose. This is the main code (pretrain.py) I am trying to run:
```
import sys
sys.path.append('/kaggle/working/florabert')
import torch
import os
from module.florabert import config, utils, training, dataio
from module.florabert import transformers as tr

# Import torch_xla for TPU support
import torch_xla.core.xla_model as xm

DATA_DIR = config.data_final / "transformer" / "seq"
TOKENIZER_DIR = config.models / "byte-level-bpe-tokenizer"

OUTPUT_DIR = config.models / "transformer" / "language-model"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

args = utils.get_args(
    data_dir=DATA_DIR,
    train_data="all_seqs_train.txt",
    test_data="all_seqs_test.txt",
    output_dir=OUTPUT_DIR,
    model_name="roberta-lm",
)

settings = utils.get_model_settings(config.settings, args, args.model_name)

config_obj, tokenizer, model = tr.load_model(
    args.model_name,
    TOKENIZER_DIR,
    pretrained_model=args.pretrained_model,
    **settings,
)

num_params = utils.count_model_parameters(model, trainable_only=True)
print(f"Loaded {args.model_name} model with {num_params:,} trainable parameters")

datasets = dataio.load_datasets(
    tokenizer,
    args.train_data,
    test_data=args.test_data,
    file_type="text",
    seq_key="text",
)

def main():
    config_obj, tokenizer, model = tr.load_model(
        args.model_name,
        TOKENIZER_DIR,
        pretrained_model=args.pretrained_model,
        **settings,
    )
    device = xm.xla_device()
    model = model.to(device)
    dataset_train = datasets["train"]
    dataset_test = datasets["test"]
    print(f"Loaded training data with {len(dataset_train):,} examples")
    data_collator = dataio.load_data_collator(
        "language-model",
        tokenizer=tokenizer,
    )

    training_settings = config.settings["training"]["pretrain"]

    trainer = training.make_trainer(
        model,
        data_collator,
        dataset_train,
        dataset_test,
        args.output_dir,
        **training_settings,
    )

    print(f"Starting training on TPU")
    training.do_training(trainer, args, args.output_dir)

    print("Saving model")

    trainer.save_model(str(args.output_dir))

def _mp_fn(index):
    # For xla_spawn (TPUs)
    main()

if __name__ == "__main__":
    main()
```

The corresponding kaggle notebook and dataset are as follows:
1) [Kaggle Notebook (Version 105)](https://www.kaggle.com/code/gurveersinghvirk/florabert-2?scriptVersionId=156747317)
2) [Kaggle Dataset (Version 62)](https://www.kaggle.com/datasets/gurveersinghvirk/florabert-base/versions/62)

I am launching this script in my notebook using the command:
```
!accelerate launch --tpu --main_training_function main /kaggle/working/florabert/scripts/1-modeling/pretrain.py 
```

This is the (main part of the) output log (also available in the Notebook):
```
Starting training on TPU
Starting training on TPU
Starting training on TPU
Starting training on TPU
Starting training on TPU
Starting training on TPU
Starting training on TPU
Starting training on TPU
wandb: Currently logged in as: gurveervirk-15517. Use `wandb login --relogin` to force relogin
You're using a RobertaTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
You're using a RobertaTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
You're using a RobertaTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
wandb: Tracking run with wandb version 0.16.1
wandb: Run data is saved locally in /kaggle/working/florabert/wandb/run-20231227_185309-mjx6thua
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run autumn-bee-119
wandb: ⭐️ View project at https://wandb.ai/gurveervirk-15517/huggingface
wandb: 🚀 View run at https://wandb.ai/gurveervirk-15517/huggingface/runs/mjx6thua
  0%|                                                 | 0/56178 [00:00<?, ?it/s]You're using a RobertaTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
You're using a RobertaTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
You're using a RobertaTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
You're using a RobertaTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
You're using a RobertaTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
https://symbolize.stripped_domain/r/?trace=7ff61fdf067d,7ff776543fcf,7ff61fdf0754,7ff61fdf0a6c,7ff61fa4605a,7ff61fa60d6f,7ff61fce4862,7ff739b9b361&map=2bdca697f10000c651e27dbf91628d1bb3a7aa8d:7ff61b1cb000-7ff629a0e3a0 
*** SIGSEGV (@0x1), see go/stacktraces#s15 received by PID 1231 (TID 2819) on cpu 6; stack trace: ***
PC: @     0x7ff61fdf067d  (unknown)  std::_Hashtable<>::_M_find_before_node()
    @     0x7ff53e7aa53a       1152  (unknown)
    @     0x7ff776543fd0       3376  (unknown)
    @     0x7ff61fdf0755         80  std::__detail::_Map_base<>::operator[]()
https://symbolize.stripped_domain/r/?trace=7ec77ebf068d,7ec8d5228fcf,7ec77ebf0754,7ec77ebf0a6c,7ec77e84605a,7ec77e860d6f,7ec77eae4862,7ec89899b361&map=2bdca697f10000c651e27dbf91628d1bb3a7aa8d:7ec779fcb000-7ec78880e3a0 
*** SIGSEGV (@0x18), see go/stacktraces#s15 received by PID 1230 (TID 2820) on cpu 75; stack trace: ***
    @     0x7ff61fdf0a6d        496  torch_xla::xla_cpu_fallback()
PC: @     0x7ec77ebf068d  (unknown)  std::_Hashtable<>::_M_find_before_node()
    @     0x7ec69e7aa53a       1152  (unknown)
    @     0x7ec8d5228fd0       3376  (unknown)
    @     0x7ff61fa4605b        112  at::native::_call_fallback_fn<>::call()
    @     0x7ec77ebf0755         80  std::__detail::_Map_base<>::operator[]()
    @     0x7ff61fa60d70        112  torch_xla::XLANativeFunctions::_local_scalar_dense()
    @     0x7ec77ebf0a6d        496  torch_xla::xla_cpu_fallback()
    @     0x7ff61fce4863         96  c10::impl::make_boxed_from_unboxed_functor<>::call()
    @     0x7ff739b9b362  (unknown)  c10::Dispatcher::callBoxed()
https://symbolize.stripped_domain/r/?trace=7ff61fdf067d,7ff53e7aa539,7ff776543fcf,7ff61fdf0754,7ff61fdf0a6c,7ff61fa4605a,7ff61fa60d6f,7ff61fce4862,7ff739b9b361&map=2bdca697f10000c651e27dbf91628d1bb3a7aa8d:7ff61b1cb000-7ff629a0e3a0,abbd016d9542b8098892badc0b19ea68:7ff531600000-7ff53e9becf0 
E1227 18:53:11.056009    2819 coredump_hook.cc:447] RAW: Remote crash data gathering hook invoked.
E1227 18:53:11.056021    2819 client.cc:272] RAW: Coroner client retries enabled (b/136286901), will retry for up to 30 sec.
E1227 18:53:11.056025    2819 coredump_hook.cc:542] RAW: Sending fingerprint to remote end.
E1227 18:53:11.056068    2819 coredump_hook.cc:551] RAW: Cannot send fingerprint to Coroner: [NOT_FOUND] stat failed on crash reporting socket /var/google/services/logmanagerd/remote_coredump.socket (Is the listener running?): No such file or directory
E1227 18:53:11.056075    2819 coredump_hook.cc:603] RAW: Dumping core locally.
    @     0x7ec77e84605b        112  at::native::_call_fallback_fn<>::call()
    @     0x7ec77e860d70        112  torch_xla::XLANativeFunctions::_local_scalar_dense()
    @     0x7ec77eae4863         96  c10::impl::make_boxed_from_unboxed_functor<>::call()
    @     0x7ec89899b362  (unknown)  c10::Dispatcher::callBoxed()
https://symbolize.stripped_domain/r/?trace=7ec77ebf068d,7ec69e7aa539,7ec8d5228fcf,7ec77ebf0754,7ec77ebf0a6c,7ec77e84605a,7ec77e860d6f,7ec77eae4862,7ec89899b361&map=2bdca697f10000c651e27dbf91628d1bb3a7aa8d:7ec779fcb000-7ec78880e3a0,abbd016d9542b8098892badc0b19ea68:7ec691600000-7ec69e9becf0 
E1227 18:53:11.152067    2820 coredump_hook.cc:447] RAW: Remote crash data gathering hook invoked.
E1227 18:53:11.152081    2820 client.cc:272] RAW: Coroner client retries enabled (b/136286901), will retry for up to 30 sec.
E1227 18:53:11.152086    2820 coredump_hook.cc:542] RAW: Sending fingerprint to remote end.
E1227 18:53:11.152146    2820 coredump_hook.cc:551] RAW: Cannot send fingerprint to Coroner: [NOT_FOUND] stat failed on crash reporting socket /var/google/services/logmanagerd/remote_coredump.socket (Is the listener running?): No such file or directory
E1227 18:53:11.152156    2820 coredump_hook.cc:603] RAW: Dumping core locally.
E1227 19:01:13.847483    2484 coredump_hook.cc:447] RAW: Remote crash data gathering hook invoked.
E1227 19:01:13.847530    2484 coredump_hook.cc:486] RAW: Called via ReportEvent and disabled coredump
E1227 19:01:13.847541    2484 client.cc:272] RAW: Coroner client retries enabled (b/136286901), will retry for up to 30 sec.
E1227 19:01:13.847548    2484 coredump_hook.cc:542] RAW: Sending fingerprint to remote end.
E1227 19:01:13.847603    2484 coredump_hook.cc:551] RAW: Cannot send fingerprint to Coroner: [NOT_FOUND] stat failed on crash reporting socket /var/google/services/logmanagerd/remote_coredump.socket (Is the listener running?): No such file or directory
E1227 19:01:13.847617    2484 coredump_hook.cc:603] RAW: Dumping core locally.
https://symbolize.stripped_domain/r/?trace=786f34017da6,786f33fcdfcf&map= 
*** SIGTERM received by PID 1226 (TID 1226) on cpu 0 from PID 296; stack trace: ***
https://symbolize.stripped_domain/r/?trace=7a2077870da6,7a2077826fcf&map= 
*** SIGTERM received by PID 1229 (TID 1229) on cpu 23 from PID 296; stack trace: ***
PC: @     0x786f34017da6  (unknown)  (unknown)
PC: @     0x7a2077870da6  (unknown)  (unknown)
    @     0x7a1e427aa53a       1152  (unknown)
    @     0x786cfe7aa53a       1152  (unknown)
    @     0x7a2077826fd0  (unknown)  (unknown)
https://symbolize.stripped_domain/r/?trace=7a2077870da6,    @     0x786f33fcdfd0  (unknown)  (unknown)
7a1e427aa539,https://symbolize.stripped_domain/r/?trace=7a2077826fcf&map=786f34017da6,786cfe7aa539,786f33fcdfcf&map=abbd016d9542b8098892badc0b19ea68:7a1e35600000-7a1e429becf0 
abbd016d9542b8098892badc0b19ea68:786cf1600000-786cfe9becf0 
E1227 19:01:14.510789    1229 coredump_hook.cc:393] RAW: Remote crash gathering disabled for SIGTERM.
E1227 19:01:14.510792    1226 coredump_hook.cc:393] RAW: Remote crash gathering disabled for SIGTERM.
E1227 19:01:14.999856    1226 process_state.cc:783] RAW: Raising signal 15 with default behavior
E1227 19:01:15.029555    1229 process_state.cc:783] RAW: Raising signal 15 with default behavior
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/usr/local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1019, in launch_command
    tpu_launcher(args)
  File "/usr/local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 762, in tpu_launcher
    xmp.spawn(PrepareForLaunch(main_function), args=(), nprocs=args.num_processes)
  File "/usr/local/lib/python3.10/site-packages/torch_xla/runtime.py", line 82, in wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 38, in spawn
    return pjrt.spawn(fn, nprocs, start_method, args)
  File "/usr/local/lib/python3.10/site-packages/torch_xla/_internal/pjrt.py", line 202, in spawn
    run_multiprocess(spawn_fn, start_method=start_method)
  File "/usr/local/lib/python3.10/site-packages/torch_xla/runtime.py", line 82, in wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch_xla/_internal/pjrt.py", line 159, in run_multiprocess
    replica_results = list(
  File "/usr/local/lib/python3.10/site-packages/torch_xla/_internal/pjrt.py", line 160, in <genexpr>
    itertools.chain.from_iterable(
  File "/usr/local/lib/python3.10/concurrent/futures/process.py", line 575, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```

Why is it failing? What changes do I make in my code and approach to resolve this issue? Is this the appropriate way to launch the script with trainer for TPU usage?

**Comment by muellerzr** [comment]
It's the appropriate way, however there's not enough code here to see what's going on. Does running the `nlp_example.py` script work fine?

**Comment by gurveervirk** [comment]
Will try and let you know. Is it supposed to be launching the main function on all the cores? Can it lead to RAM running out?
