### ISSUE TITLE
AssertionError: Invalid optimizer offloading device specified: NONE.

### ISSUE THREAD

**Issue by Biaocsu** [huggingface/accelerate#232]
Hi, there, I have a single machine with 4 GPUs, when I use this method, here is the error comes:

torch == 1.10.1
deepspeed == 0.5.9

```
(base) [root@kna-nlp-mg-k8s data]# nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89
(base) [root@kna-nlp-mg-k8s data]# nvidia-smi
Mon Jan 17 14:23:10 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.118.02   Driver Version: 440.118.02   CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:21:01.0 Off |                    0 |
| N/A   40C    P0    27W /  70W |      0MiB / 15109MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla T4            Off  | 00000000:21:02.0 Off |                    0 |
| N/A   37C    P0    26W /  70W |      0MiB / 15109MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla T4            Off  | 00000000:21:03.0 Off |                    0 |
| N/A   38C    P0    26W /  70W |      0MiB / 15109MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla T4            Off  | 00000000:21:04.0 Off |                    0 |
| N/A   38C    P0    27W /  70W |      0MiB / 15109MiB |      5%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

(liubiao) [root@kna-nlp-mg-k8s CPM]# accelerate config
In which compute environment are you running? ([0] This machine, [1] AWS (Amazon SageMaker)): 0
Which type of machine are you using? ([0] No distributed training, [1] multi-CPU, [2] multi-GPU, [3] TPU): 2
How many different machines will you use (use more than 1 for multi-node training)? [1]: 1
Do you want to use DeepSpeed? [yes/NO]: yes
What should be your DeepSpeed's ZeRO optimization stage (0, 1, 2, 3)? [2]: 3
Where to offload optimizer states? [NONE/cpu/nvme]: NONE
How many gradient accumulation steps you're passing in your script? [1]: 6
How many processes in total will you use? [1]: 4
Do you wish to use FP16 (mixed precision)? [yes/NO]: NO

```

```
(liubiao) [root@kna-nlp-mg-k8s CPM]# accelerate launch train.py
[2022-01-17 15:31:35,241] [WARNING] [runner.py:132:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2022-01-17 15:31:35,271] [INFO] [runner.py:398:main] cmd = /data/software/conda_install/envs/liubiao/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMCwgMSwgMiwgM119 --master_addr=127.0.0.1 --master_port=29500 train.py
[2022-01-17 15:31:36,251] [INFO] [launch.py:80:main] WORLD INFO DICT: {'localhost': [0, 1, 2, 3]}
[2022-01-17 15:31:36,251] [INFO] [launch.py:87:main] nnodes=1, num_local_procs=4, node_rank=0
[2022-01-17 15:31:36,251] [INFO] [launch.py:99:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0, 1, 2, 3]})
[2022-01-17 15:31:36,251] [INFO] [launch.py:100:main] dist_world_size=4
[2022-01-17 15:31:36,251] [INFO] [launch.py:102:main] Setting CUDA_VISIBLE_DEVICES=0,1,2,3
2022-01-17 15:31:38,967 - INFO - using device:cuda:0
2022-01-17 15:31:38,979 - INFO - using device:cuda:3
2022-01-17 15:31:38,981 - INFO - using device:cuda:2
2022-01-17 15:31:38,982 - INFO - using device:cuda:1
2022-01-17 15:31:47,497 - INFO - model config:
{
  "activation_function": "gelu_new",
  "architectures": [
    "GPT2LMHeadModel"
  ],
  "attn_pdrop": 0.1,
  "bos_token_id": 50256,
  "embd_pdrop": 0.1,
  "eos_token_id": 50256,
  "initializer_range": 0.02,
  "layer_norm_epsilon": 1e-05,
  "model_type": "gpt2",
  "n_ctx": 1024,
  "n_embd": 768,
  "n_head": 12,
  "n_inner": null,
  "n_layer": 12,
  "n_positions": 1024,
  "reorder_and_upcast_attn": false,
  "resid_pdrop": 0.1,
  "scale_attn_by_inverse_layer_idx": false,
  "scale_attn_weights": true,
  "summary_activation": null,
  "summary_first_dropout": 0.1,
  "summary_proj_to_labels": true,
  "summary_type": "cls_index",
  "summary_use_proj": true,
  "task_specific_params": {
    "text-generation": {
      "do_sample": true,
      "max_length": 50
    }
  },
  "transformers_version": "4.15.0",
  "use_cache": true,
  "vocab_size": 30000
}

2022-01-17 15:31:47,498 - INFO - number of model parameters: 108882432
2022-01-17 15:31:47,498 - INFO - args:Namespace(batch_size=8, cuda=True, device='0,1,2,3', eod_id=7, epochs=30, eps=1e-09, gpu0_bsz=16, gradient_accumulation_steps=6, ignore_index=-100, local_rank=0, log_path='log/train.log', log_step=1, lr=0.00015, max_grad_norm=1.0, max_len=200, model_config='config/cpm-small.json', no_cuda=False, num_workers=0, pad_id=5, pretrained_model='', save_model_path='model', seed=1234, train_path='data/train.pkl', vocab_path='vocab/chinese_vocab.model', warmup_steps=4000)
2022-01-17 15:31:47,498 - INFO - loading training dataset
2022-01-17 15:31:53,871 - INFO - model config:
{
  "activation_function": "gelu_new",
  "architectures": [
    "GPT2LMHeadModel"
  ],
  "attn_pdrop": 0.1,
  "bos_token_id": 50256,
  "embd_pdrop": 0.1,
  "eos_token_id": 50256,
  "initializer_range": 0.02,
  "layer_norm_epsilon": 1e-05,
  "model_type": "gpt2",
  "n_ctx": 1024,
  "n_embd": 768,
  "n_head": 12,
  "n_inner": null,
  "n_layer": 12,
  "n_positions": 1024,
  "reorder_and_upcast_attn": false,
  "resid_pdrop": 0.1,
  "scale_attn_by_inverse_layer_idx": false,
  "scale_attn_weights": true,
  "summary_activation": null,
  "summary_first_dropout": 0.1,
  "summary_proj_to_labels": true,
  "summary_type": "cls_index",
  "summary_use_proj": true,
  "task_specific_params": {
    "text-generation": {
      "do_sample": true,
      "max_length": 50
    }
  },
  "transformers_version": "4.15.0",
  "use_cache": true,
  "vocab_size": 30000
}

2022-01-17 15:31:53,872 - INFO - number of model parameters: 108882432
2022-01-17 15:31:53,872 - INFO - args:Namespace(batch_size=8, cuda=True, device='0,1,2,3', eod_id=7, epochs=30, eps=1e-09, gpu0_bsz=16, gradient_accumulation_steps=6, ignore_index=-100, local_rank=2, log_path='log/train.log', log_step=1, lr=0.00015, max_grad_norm=1.0, max_len=200, model_config='config/cpm-small.json', no_cuda=False, num_workers=0, pad_id=5, pretrained_model='', save_model_path='model', seed=1234, train_path='data/train.pkl', vocab_path='vocab/chinese_vocab.model', warmup_steps=4000)
2022-01-17 15:31:53,872 - INFO - loading training dataset
2022-01-17 15:31:54,122 - INFO - model config:
{
  "activation_function": "gelu_new",
  "architectures": [
    "GPT2LMHeadModel"
  ],
  "attn_pdrop": 0.1,
  "bos_token_id": 50256,
  "embd_pdrop": 0.1,
  "eos_token_id": 50256,
  "initializer_range": 0.02,
  "layer_norm_epsilon": 1e-05,
  "model_type": "gpt2",
  "n_ctx": 1024,
  "n_embd": 768,
  "n_head": 12,
  "n_inner": null,
  "n_layer": 12,
  "n_positions": 1024,
  "reorder_and_upcast_attn": false,
  "resid_pdrop": 0.1,
  "scale_attn_by_inverse_layer_idx": false,
  "scale_attn_weights": true,
  "summary_activation": null,
  "summary_first_dropout": 0.1,
  "summary_proj_to_labels": true,
  "summary_type": "cls_index",
  "summary_use_proj": true,
  "task_specific_params": {
    "text-generation": {
      "do_sample": true,
      "max_length": 50
    }
  },
  "transformers_version": "4.15.0",
  "use_cache": true,
  "vocab_size": 30000
}

2022-01-17 15:31:54,123 - INFO - number of model parameters: 108882432
2022-01-17 15:31:54,124 - INFO - args:Namespace(batch_size=8, cuda=True, device='0,1,2,3', eod_id=7, epochs=30, eps=1e-09, gpu0_bsz=16, gradient_accumulation_steps=6, ignore_index=-100, local_rank=1, log_path='log/train.log', log_step=1, lr=0.00015, max_grad_norm=1.0, max_len=200, model_config='config/cpm-small.json', no_cuda=False, num_workers=0, pad_id=5, pretrained_model='', save_model_path='model', seed=1234, train_path='data/train.pkl', vocab_path='vocab/chinese_vocab.model', warmup_steps=4000)
2022-01-17 15:31:54,124 - INFO - loading training dataset
2022-01-17 15:31:54,193 - INFO - model config:
{
  "activation_function": "gelu_new",
  "architectures": [
    "GPT2LMHeadModel"
  ],
  "attn_pdrop": 0.1,
  "bos_token_id": 50256,
  "embd_pdrop": 0.1,
  "eos_token_id": 50256,
  "initializer_range": 0.02,
  "layer_norm_epsilon": 1e-05,
  "model_type": "gpt2",
  "n_ctx": 1024,
  "n_embd": 768,
  "n_head": 12,
  "n_inner": null,
  "n_layer": 12,
  "n_positions": 1024,
  "reorder_and_upcast_attn": false,
  "resid_pdrop": 0.1,
  "scale_attn_by_inverse_layer_idx": false,
  "scale_attn_weights": true,
  "summary_activation": null,
  "summary_first_dropout": 0.1,
  "summary_proj_to_labels": true,
  "summary_type": "cls_index",
  "summary_use_proj": true,
  "task_specific_params": {
    "text-generation": {
      "do_sample": true,
      "max_length": 50
    }
  },
  "transformers_version": "4.15.0",
  "use_cache": true,
  "vocab_size": 30000
}

2022-01-17 15:31:54,194 - INFO - number of model parameters: 108882432
2022-01-17 15:31:54,194 - INFO - args:Namespace(batch_size=8, cuda=True, device='0,1,2,3', eod_id=7, epochs=30, eps=1e-09, gpu0_bsz=16, gradient_accumulation_steps=6, ignore_index=-100, local_rank=3, log_path='log/train.log', log_step=1, lr=0.00015, max_grad_norm=1.0, max_len=200, model_config='config/cpm-small.json', no_cuda=False, num_workers=0, pad_id=5, pretrained_model='', save_model_path='model', seed=1234, train_path='data/train.pkl', vocab_path='vocab/chinese_vocab.model', warmup_steps=4000)
2022-01-17 15:31:54,194 - INFO - loading training dataset
Traceback (most recent call last):
  File "train.py", line 343, in <module>
    main()
  File "train.py", line 339, in main
    train(model, logger, train_dataset, args)
  File "train.py", line 189, in train
    model, optimizer, train_dataloader = accelerator.prepare(model, optimizer, train_dataloader)
  File "/data/software/conda_install/envs/liubiao/lib/python3.6/site-packages/accelerate/accelerator.py", line 273, in prepare
    result = self._prepare_deepspeed(*args)
  File "/data/software/conda_install/envs/liubiao/lib/python3.6/site-packages/accelerate/accelerator.py", line 363, in _prepare_deepspeed
    dist_init_required=False,
  File "/data/software/conda_install/envs/liubiao/lib/python3.6/site-packages/accelerate/deepspeed_utils.py", line 32, in __init__
    super().__init__(*args, **kwargs)
  File "/data/software/conda_install/envs/liubiao/lib/python3.6/site-packages/deepspeed/runtime/engine.py", line 238, in __init__
    self._configure_with_arguments(args, mpu)
  File "/data/software/conda_install/envs/liubiao/lib/python3.6/site-packages/deepspeed/runtime/engine.py", line 884, in _configure_with_arguments
    self._config = DeepSpeedConfig(self.config, mpu)
  File "/data/software/conda_install/envs/liubiao/lib/python3.6/site-packages/deepspeed/runtime/config.py", line 872, in __init__
    self._initialize_params(self._param_dict)
  File "/data/software/conda_install/envs/liubiao/lib/python3.6/site-packages/deepspeed/runtime/config.py", line 891, in _initialize_params
    self.zero_config = DeepSpeedZeroConfig(param_dict)
  File "/data/software/conda_install/envs/liubiao/lib/python3.6/site-packages/deepspeed/runtime/zero/config.py", line 51, in __init__
    self._initialize(zero_config_dict)
  File "/data/software/conda_install/envs/liubiao/lib/python3.6/site-packages/deepspeed/runtime/zero/config.py", line 138, in _initialize
    self.offload_optimizer = get_offload_optimizer_config(zero_config_dict)
  File "/data/software/conda_install/envs/liubiao/lib/python3.6/site-packages/deepspeed/runtime/zero/offload_config.py", line 62, in get_offload_optimizer_config
    assert device in VALID_OFFLOAD_DEVICES, f'Invalid optimizer offloading device specified: {device}.'
AssertionError: Invalid optimizer offloading device specified: NONE.
[2022-01-17 15:32:07,299] [INFO] [launch.py:131:sigkill_handler] Killing subprocess 8723
[2022-01-17 15:32:07,299] [INFO] [launch.py:131:sigkill_handler] Killing subprocess 8724
[2022-01-17 15:32:07,300] [INFO] [launch.py:131:sigkill_handler] Killing subprocess 8725
[2022-01-17 15:32:07,300] [INFO] [launch.py:131:sigkill_handler] Killing subprocess 8726
[2022-01-17 15:32:07,300] [ERROR] [launch.py:137:sigkill_handler] ['/data/software/conda_install/envs/liubiao/bin/python', '-u', 'train.py', '--local_rank=3'] exits with return code = 1
Traceback (most recent call last):
  File "/data/software/conda_install/envs/liubiao/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/data/software/conda_install/envs/liubiao/lib/python3.6/site-packages/accelerate/commands/accelerate_cli.py", line 41, in main
    args.func(args)
  File "/data/software/conda_install/envs/liubiao/lib/python3.6/site-packages/accelerate/commands/launch.py", line 376, in launch_command
    deepspeed_launcher(args)
  File "/data/software/conda_install/envs/liubiao/lib/python3.6/site-packages/accelerate/commands/launch.py", line 213, in deepspeed_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['deepspeed', '--num_gpus', '4', 'train.py']' returned non-zero exit status 1.
```

However, when I use accelerate as the readme in the script, and launch like `python train.py`, there will be no erorr, but `only use one GPU`

**Comment by Biaocsu** [comment]
it seems the problem caused by some unknown reason of the hardware, I have solved it by using `Dokcer`
