### ISSUE TITLE
Unexpected behavior of prepare for IterableDataset

### ISSUE THREAD

**Issue by thesby** [huggingface/accelerate#2334]
### System Info

```Shell
accelerate: 0.25.0
pytorch: 1.12.1+cu113
OS: ubuntu 20.04
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

```python
import torch
from torch.utils.data import DataLoader, Dataset, IterableDataset
import random
import os

from accelerate import Accelerator

class ClassificationDataset(Dataset):
    def __init__(self):
        self.samples = list(zip('abcdefghijklmnopqrstuvwxyz', range(26)))
    
    def __len__(self):
        return len(self.samples)
    
    def __getitem__(self, index):
        return self.samples[index]

    def __iter__(self):
        return iter(self.samples)


if __name__ == '__main__':
    accelerator = Accelerator()
    rank = accelerator.process_index
    num_processes = accelerator.num_processes

    batch_size = 4
    dataset = ClassificationDataset()

    train_dataloader = DataLoader(dataset, num_workers=3, batch_size=batch_size)
    train_dataloader = accelerator.prepare(
        train_dataloader
    )

    for epoch in range(1):
        for bidx, batch in enumerate(train_dataloader):
            if bidx < 3:
                print(batch)
```
The code works well when launch with `accelerate launch --main_process_port 29000 test_dataloader.py`.
But when I replace `class ClassificationDataset(Dataset):` with `class ClassificationDataset(IterableDataset):`, an error occurs:
```
Traceback (most recent call last):
  File "test_dataloader.py", line 36, in <module>
    for bidx, batch in enumerate(train_dataloader):
  File "/home/pai/lib/python3.9/site-packages/accelerate/data_loader.py", line 654, in __iter__
    next_batch, next_batch_info = self._fetch_batches(main_iterator)
  File "/home/pai/lib/python3.9/site-packages/accelerate/data_loader.py", line 633, in _fetch_batches
    batch = concatenate(batches, dim=0)
  File "/home/pai/lib/python3.9/site-packages/accelerate/utils/operations.py", line 529, in concatenate
    return honor_type(data[0], (concatenate([d[i] for d in data], dim=dim) for i in range(len(data[0]))))
  File "/home/pai/lib/python3.9/site-packages/accelerate/utils/operations.py", line 84, in honor_type
    return type(obj)(generator)
  File "/home/pai/lib/python3.9/site-packages/accelerate/utils/operations.py", line 529, in <genexpr>
    return honor_type(data[0], (concatenate([d[i] for d in data], dim=dim) for i in range(len(data[0]))))
  File "/home/pai/lib/python3.9/site-packages/accelerate/utils/operations.py", line 529, in concatenate
    return honor_type(data[0], (concatenate([d[i] for d in data], dim=dim) for i in range(len(data[0]))))
  File "/home/pai/lib/python3.9/site-packages/accelerate/utils/operations.py", line 84, in honor_type
    return type(obj)(generator)
  File "/home/pai/lib/python3.9/site-packages/accelerate/utils/operations.py", line 529, in <genexpr>
    return honor_type(data[0], (concatenate([d[i] for d in data], dim=dim) for i in range(len(data[0]))))
  File "/home/pai/lib/python3.9/site-packages/accelerate/utils/operations.py", line 533, in concatenate
    raise TypeError(f"Can only concatenate tensors but got {type(data[0])}")
TypeError: Can only concatenate tensors but got <class 'str'>
```

### Expected behavior

Dataset and IterableDataset should be the same behavior.

**Comment by thesby** [comment]
Help, please.

**Comment by Danielement321** [comment]
Hi, you can refer to this https://github.com/huggingface/transformers/issues/26548#issuecomment-1885798533
