### ISSUE TITLE
Using Accelerate on llava 1.5 13b on dual V100 error

### ISSUE THREAD

**Issue by chungdz** [huggingface/accelerate#2336]
### System Info

```Shell
- `Accelerate` version: 0.26.1
- Platform: Linux-4.18.0-240.el8.ppc64le-ppc64le-with-glibc2.28
- Python version: 3.9.18
- Numpy version: 1.23.5
- PyTorch version (GPU?): 2.0.1 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 1144.75 GB
- GPU type: Tesla V100-SXM2-32GB
- `Accelerate` default config:
        Not found

transformers version 4.36.2
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.86.10              Driver Version: 535.86.10    CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla V100-SXM2-32GB           On  | 00000004:04:00.0 Off |                    0 |
| N/A   44C    P0              56W / 300W |  25302MiB / 32768MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2-32GB           On  | 00000004:05:00.0 Off |                    0 |
| N/A   48C    P0              57W / 300W |  26448MiB / 32768MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A   2770761      C   python                                    25300MiB |
|    1   N/A  N/A   2770761      C   python                                    26446MiB |
+---------------------------------------------------------------------------------------+
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

When I ran code
```
from PIL import Image
from transformers import AutoProcessor, LlavaForConditionalGeneration
import requests

model = LlavaForConditionalGeneration.from_pretrained("llava-hf/llava-1.5-13b-hf", device_map="auto")
print(model.hf_device_map)
processor = AutoProcessor.from_pretrained("llava-hf/llava-1.5-13b-hf")

inputs = processor(text=prompt, images=image, return_tensors="pt").to(0)
generate_ids = model.generate(**inputs, max_length=512, temperature=0.1, top_p=0.7, do_sample=True)
print(processor.batch_decode(generate_ids, skip_special_tokens=True, clean_up_token0104zation_spaces=False)[0])
```

I got Device Map:
```
OrderedDict([('vision_tower', 0), ('multi_modal_projector', 0), ('language_model.model.embed_tokens', 0), ('language_model.model.layers.0', 0), ('language_model.model.layers.1', 0), ('language_model.model.layers.2', 0), ('language_model.model.layers.3', 0), ('language_model.model.layers.4', 0), ('language_m
odel.model.layers.5', 0), ('language_model.model.layers.6', 0), ('language_model.model.layers.7', 0), ('language_model.model.layers.8', 0), ('language_model.model.layers.9', 0), ('language_model.model.layers.10', 0), ('language_model.model.layers.11', 0), ('language_model.model.layers.12', 0), ('language_mo
del.model.layers.13', 0), ('language_model.model.layers.14', 0), ('language_model.model.layers.15', 0), ('language_model.model.layers.16', 0), ('language_model.model.layers.17', 0), ('language_model.model.layers.18', 0), ('language_model.model.layers.19', 1), ('language_model.model.layers.20', 1), ('languag
e_model.model.layers.21', 1), ('language_model.model.layers.22', 1), ('language_model.model.layers.23', 1), ('language_model.model.layers.24', 1), ('language_model.model.layers.25', 1), ('language_model.model.layers.26', 1), ('language_model.model.layers.27', 1), ('language_model.model.layers.28', 1), ('lan
guage_model.model.layers.29', 1), ('language_model.model.layers.30', 1), ('language_model.model.layers.31', 1), ('language_model.model.layers.32', 1), ('language_model.model.layers.33', 1), ('language_model.model.layers.34', 1), ('language_model.model.layers.35', 1), ('language_model.model.layers.36', 1), (
'language_model.model.layers.37', 1), ('language_model.model.layers.38', 1), ('language_model.model.layers.39', 1), ('language_model.model.norm', 1), ('language_model.lm_head', 1)])
```

But when generating results using model.generate, it gave this error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "../anaconda3/envs/llm/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "../anaconda3/envs/llm/lib/python3.9/site-packages/transformers/generation/utils.py", line 1764, in generate
    return self.sample(
  File "../anaconda3/envs/llm/lib/python3.9/site-packages/transformers/generation/utils.py", line 2861, in sample
    outputs = self(
  File "../anaconda3/envs/llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "../anaconda3/envs/llm/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "../anaconda3/envs/llm/lib/python3.9/site-packages/transformers/models/llava/modeling_llava.py", line 433, in forward
    outputs = self.language_model(
  File "../anaconda3/envs/llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "../anaconda3/envs/llm/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 1181, in forward
    outputs = self.model(
  File "../anaconda3/envs/llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "../anaconda3/envs/llm/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 1068, in forward
    layer_outputs = decoder_layer(
  File "../anaconda3/envs/llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "../anaconda3/envs/llm/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "../anaconda3/envs/llm/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 796, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "../anaconda3/envs/llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "../anaconda3/envs/llm/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "../anaconda3/envs/llm/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 408, in forward
    key_states, value_states = past_key_value.update(key_states, value_states, self.layer_idx, cache_kwargs)
  File "../anaconda3/envs/llm/lib/python3.9/site-packages/transformers/cache_utils.py", line 127, in update
    self.key_cache[layer_idx] = torch.cat([self.key_cache[layer_idx], key_states], dim=-2)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument tensors in method wrapper_CUDA_cat)
```

### Expected behavior

Model could generate results as expected instead of giving CUDA error.

**Comment by davidluciolu** [comment]
I met this problem and I believe the author of llava have fixed it. You can update llava to the latest version and try again

**Comment by chungdz** [comment]
> I met this problem and I believe the author of llava have fixed it. You can update llava to the latest version and try again

Do you mean to use new model card？My code is using newest transformer package.

**Comment by davidluciolu** [comment]
> > I met this problem and I believe the author of llava have fixed it. You can update llava to the latest version and try again
> 
> Do you mean to use new model card？My code is using newest transformer package.

No, but update LLaVA code base.
```
git pull
pip install -e .
```

**Comment by chungdz** [comment]
Thanks for helping. Will try.
