### ISSUE TITLE
socket connection failed, because it selects another IP on the main_node

### ISSUE THREAD

**Issue by JasonWang1125** [huggingface/accelerate#2362]
### System Info

```Shell
1. main_node env
- `Accelerate` version: 0.25.0
- Platform: Linux-5.15.0-91-generic-x86_64-with-glibc2.29
- Python version: 3.8.10
- Numpy version: 1.24.3
- PyTorch version (GPU?): 2.1.1+cu121 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 62.66 GB
- GPU type: NVIDIA GeForce RTX 3060
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: MULTI_GPU
        - mixed_precision: no
        - use_cpu: False
        - debug: False
        - num_processes: 2
        - machine_rank: 0
        - num_machines: 2
        - gpu_ids: all
        - main_process_ip: 100.82.170.1
        - main_process_port: 10082
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []

2. common_node env
- `Accelerate` version: 0.26.1
- Platform: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
- Python version: 3.8.10
- Numpy version: 1.24.4
- PyTorch version (GPU?): 2.1.2+cu118 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 31.32 GB
- GPU type: NVIDIA GeForce RTX 3060
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: MULTI_GPU
        - mixed_precision: no
        - use_cpu: False
        - debug: False
        - num_processes: 2
        - machine_rank: 0
        - num_machines: 2
        - gpu_ids: all
        - main_process_ip: 100.82.170.1
        - main_process_port: 10082
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

I am testing multi-node training with examples/nlp_example.py on two node, which are connected throw a `tailscale VPN`.

**NIC info**
```bash
# main node
enp3s0: 192.168.1.25/24
tailscale0: 100.82.170.1/32

# common node
eth0: 172.26.83.32/20
tailscale0: 100.125.104.113/32
```

The network communication between nodes are **OK** and **PASS** testing with the `ping` command.

But after the launch, I get a `socketStartConnect` error from the `common_node` as following:
```bash
(nlp) jason@DESKTOP-EQ1SPAJ:~/master_code$ accelerate launch --config_file=accelerate_config.yaml --debug train_geo_relate_filter.py
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "train_geo_relate_filter.py", line 53, in <module>
    trainer.train()
  File "/home/jason/program_env/python/venv/nlp/lib/python3.8/site-packages/transformers/trainer.py", line 1537, in train
    return inner_training_loop(
  File "/home/jason/program_env/python/venv/nlp/lib/python3.8/site-packages/transformers/trainer.py", line 1672, in _inner_training_loop
    model, self.optimizer = self.accelerator.prepare(self.model, self.optimizer)
  File "/home/jason/program_env/python/venv/nlp/lib/python3.8/site-packages/accelerate/accelerator.py", line 1227, in prepare
    result = tuple(
  File "/home/jason/program_env/python/venv/nlp/lib/python3.8/site-packages/accelerate/accelerator.py", line 1228, in <genexpr>
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
  File "/home/jason/program_env/python/venv/nlp/lib/python3.8/site-packages/accelerate/accelerator.py", line 1104, in _prepare_one
    return self.prepare_model(obj, device_placement=device_placement)
  File "/home/jason/program_env/python/venv/nlp/lib/python3.8/site-packages/accelerate/accelerator.py", line 1355, in prepare_model
    model = torch.nn.parallel.DistributedDataParallel(
  File "/home/jason/program_env/python/venv/nlp/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 795, in __init__
    _verify_param_shape_across_processes(self.process_group, parameters)
  File "/home/jason/program_env/python/venv/nlp/lib/python3.8/site-packages/torch/distributed/utils.py", line 265, in _verify_param_shape_across_processes
    return dist._verify_params_across_processes(process_group, tensors, logger)
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1333, unhandled system error (run with NCCL_DEBUG=INFO for details), NCCL version 2.18.6
ncclSystemError: System call (e.g. socket, malloc) or external library call failed or device error. 
Last error:
socketStartConnect: Connect to **192.168.1.25**<54471> failed : Software caused connection abort
[2024-01-21 17:56:06,745] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 116556) of binary: /home/jason/program_env/python/venv/nlp/bin/python3.8
Traceback (most recent call last):
  File "/home/jason/program_env/python/venv/nlp/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/jason/program_env/python/venv/nlp/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/home/jason/program_env/python/venv/nlp/lib/python3.8/site-packages/accelerate/commands/launch.py", line 1014, in launch_command
    multi_gpu_launcher(args)
  File "/home/jason/program_env/python/venv/nlp/lib/python3.8/site-packages/accelerate/commands/launch.py", line 672, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/jason/program_env/python/venv/nlp/lib/python3.8/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/jason/program_env/python/venv/nlp/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/jason/program_env/python/venv/nlp/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_geo_relate_filter.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-01-21_17:56:06
  host      : DESKTOP-EQ1SPAJ.
  rank      : 1 (local_rank: 0)
  exitcode  : 1 (pid: 116556)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

### Expected behavior

I find that the target of socket connection is `192.168.1.25` which is another ip on the `main_node`.
But I do **NOT** mention that ip in accelerate config, the ip I config is `100.82.170.1`.

I wish how can I config default ip for that socket connection.

**Comment by muellerzr** [comment]
Both nodes are set as machine_rank==0. Set the main one only to 0, and the other 1

**Comment by JasonWang1125** [comment]
@muellerzr  
sorry, forget to describe about launch cmd that I use. I launch with the `--config_file` parameter, in the config file I set `main-node` rank 0, and `common-node` rank 1

```bash
# main-node
accelerate launch \ 
    --config_file=./config/accelerate_config_1.yaml \
    ./train.py

# accelerate_config_1.yaml
  1 compute_environment: LOCAL_MACHINE                                          
  2 debug: false
  3 distributed_type: MULTI_GPU
  4 downcast_bf16: 'no'
  5 gpu_ids: all
  6 machine_rank: 0
  7 main_process_ip: 100.82.170.1
  8 main_process_port: 10080
  9 main_training_function: main
 10 mixed_precision: 'no'
 11 num_machines: 2
 12 num_processes: 2
 13 rdzv_backend: static
 14 same_network: true
 15 tpu_env: []
 16 tpu_use_cluster: false
 17 tpu_use_sudo: false
 18 use_cpu: false         

# common-node
accelerate launch \ 
    --config_file=./config/accelerate_config_2.yaml \
    ./train.py

# accelerate_config_2.yaml
  1 compute_environment: LOCAL_MACHINE                                          
  2 debug: false
  3 distributed_type: MULTI_GPU
  4 downcast_bf16: 'no'
  5 gpu_ids: all
  6 machine_rank: 1
  7 main_process_ip: 100.82.170.1
  8 main_process_port: 10080
  9 main_training_function: main
 10 mixed_precision: 'no'
 11 num_machines: 2
 12 num_processes: 2
 13 rdzv_backend: static
 14 same_network: true
 15 tpu_env: []
 16 tpu_use_cluster: false
 17 tpu_use_sudo: false
 18 use_cpu: false         
```

**Comment by JasonWang1125** [comment]
I find this work

https://github.com/NVIDIA/nccl/issues/929#issuecomment-1650422352
