### ISSUE TITLE
RuntimeError: Expected to have finished reduction in the prior iteration.

### ISSUE THREAD

**Issue by VINUK0** [huggingface/accelerate#2389]
### System Info

```Shell
- `Accelerate` version: 0.26.1
- Platform: Linux-5.15.133+-x86_64-with-glibc2.35
- Python version: 3.10.12
- Numpy version: 1.23.5
- PyTorch version (GPU?): 2.3.0.dev20240128+cu118 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 31.36 GB
- GPU type: Tesla T4
- `Accelerate` default config:
	Not found
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

Try to train a hugging face Llama model with sdpa in DDP. It works in single GPU but in multi GPU environment it exit with `RuntimeError: Expected to have finished reduction in the prior iteration.`

### Expected behavior

```[rank1]:   File "/kaggle/working/Train_Raw.py", line 77, in <module>
[rank1]:     output = model(input_ids, labels=labels)
[rank1]:   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:   File "/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1519, in forward
[rank1]:     inputs, kwargs = self._pre_forward(*inputs, **kwargs)
[rank1]:   File "/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1413, in _pre_forward
[rank1]:     if torch.is_grad_enabled() and self.reducer._rebuild_buckets():
[rank1]: RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by 
[rank1]: making sure all `forward` function outputs participate in calculating loss. 
[rank1]: If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
[rank1]: Parameter indices which did not receive grad for rank 1: 88 89 90 123 124 125 139 140 141 158 159 160 186 187 188 196 197 198 215 216 217
[rank1]:  In addition, you can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print out information about which particular parameters did not receive gradient on this rank as part of this error
[rank0]: Traceback (most recent call last):
[rank0]:   File "/kaggle/working/Train_Raw.py", line 77, in <module>
[rank0]:     output = model(input_ids, labels=labels)
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1519, in forward
[rank0]:     inputs, kwargs = self._pre_forward(*inputs, **kwargs)
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1413, in _pre_forward
[rank0]:     if torch.is_grad_enabled() and self.reducer._rebuild_buckets():
[rank0]: RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by 
[rank0]: making sure all `forward` function outputs participate in calculating loss. 
[rank0]: If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
[rank0]: Parameter indices which did not receive grad for rank 0: 88 89 90 123 124 125 139 140 141 158 159 160 215 216 217
[rank0]:  In addition, you can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print out information about which particular parameters did not receive gradient on this rank as part of this error
Epoch's:   0%|                                            | 0/5 [00:01<?, ?it/s]
Batch's:   0%|                                 | 2/3251 [00:01<40:05,  1.35it/s]
[2024-01-29 12:07:17,227] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 318) of binary: /opt/conda/bin/python3.10
Traceback (most recent call last):
  File "/opt/conda/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1014, in launch_command
    multi_gpu_launcher(args)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/launch.py", line 672, in multi_gpu_launcher
    distrib_run.run(args)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
```

**Comment by muellerzr** [comment]
We need your code to know anything

**Comment by VINUK0** [comment]
> We need your code to know anything

Ah good sir pardon my oversight, I was a little pissed off at the time I posted it. Here is the code I used.

```
from accelerate import Accelerator
from transformers import AutoConfig, AutoTokenizer, MixtralForCausalLM, MixtralConfig, LlamaTokenizer
from transformers.optimization import Adafactor
from torch.utils.data import DataLoader
import torch.nn as nn
from tqdm import tqdm
import time
from Dataset import CustomDataset
from torch.optim.lr_scheduler import MultiStepLR
import torch
import numpy as np

accelerator = Accelerator(gradient_accumulation_steps=1)
device = accelerator.device
# print(f'Currently using {device}')


tokenizer = LlamaTokenizer.from_pretrained("/kaggle/working/tokenizer_utils/", legacy=False)
config = MixtralConfig(vocab_size=tokenizer.vocab_size,
                       hidden_size=768,
                       intermediate_size=2048,
                       num_hidden_layers=12,
                       num_attention_heads=12, num_key_value_heads=4, hidden_act="silu", max_position_embeddings=2048, num_experts_per_tok=1, num_local_experts=4, rms_norm_eps=1e-05, rope_theta=10000.0, router_aux_loss_coef=0.02, sliding_window=None, tie_word_embeddings=False, use_cache=True, initializer_range=0.02, attention_dropout=0.0g)
model =  MixtralForCausalLM(config)
model.to(torch.float16)

model.train()

# tokenizer = AutoTokenizer.from_pretrained("facebook/opt-350m")
# Config = AutoConfig.from_pretrained("facebook/opt-350m")
# model = OPTForCausalLM._from_config(Config)
# state_dict = torch.load('pytorch_model.bin')
#model._load_pretrained_model(model=model, state_dict=state_dict, pretrained_model_name_or_path="facebook/opt-350m", loaded_keys=None, resolved_archive_file=None)
#model.load_state_dict(torch.load('pytorch_model_2.bin'))

tokenizer.pad_token = tokenizer.eos_token
#model.half()
#model.gradient_checkpointing_enable()

Train_DataLoader = DataLoader(CustomDataset('/kaggle/input/test-dataset/instrut.db', tokenizer=tokenizer, dataset_line_max_length=256), batch_size=8, shuffle=True)

optimizer = Adafactor(model.parameters(),
                      lr=8e-5,
                      clip_threshold=1.0,
                      decay_rate=-1.0,
                      weight_decay=0.05,
                      scale_parameter=False,
                      relative_step=False,
                      warmup_init=False)


scheduler = MultiStepLR(optimizer=optimizer, milestones=[2, 4], gamma=0.7)

model, optimizer, scheduler, Train_DataLoader = accelerator.prepare(model, optimizer, scheduler, Train_DataLoader)




#accelerator.load_state('/kaggle/working/pytorch_model.bin')


epochs = 5

if accelerator.is_main_process:
    Epoch_Bar = tqdm(position=0, desc="Epoch's", total=epochs)
    Batch_Bar = tqdm(position=1, desc="Batch's", total=len(Train_DataLoader))
    
best_loss = float("inf")
best_accuracy = float("inf")
for i in range(epochs):
    for batch_idx, batch in enumerate(Train_DataLoader):
        epoch_accuracy = []
        epoch_loss = []
        with accelerator.autocast():
            optimizer.zero_grad()
            input_ids, labels = batch
            output = model(input_ids, labels=labels)
            loss = output[0]
            accelerator.wait_for_everyone()
            accelerator.backward(loss)
            optimizer.step()
            if accelerator.is_main_process:
                Batch_Bar.update()
    
    batch_acc = torch.exp(loss.detach())
    epoch_accuracy.append(batch_acc)
    epoch_loss.append(loss.detach())
    
    perplexity = [batch_acc.cpu().item() if not np.isinf(batch_acc.cpu().item()) else 1e+8 for batch_acc in epoch_accuracy]
    perplexity = np.mean(perplexity)
    average_loss = np.mean([loss.cpu().item() for loss in epoch_loss])
    
    if accelerator.is_main_process:
        Batch_Bar.reset()
        Batch_Bar.set_description(f"Avg loss: {average_loss} | Avg PPL: {perplexity}")
        Epoch_Bar.update() 
    scheduler.step()
    
    
    
    
    if accelerator.is_main_process:
        time.sleep(2)
    else:
        print("I'm waiting for the main process to finish its sleep...")
    
    
    
    if (i + 1) % 1 == 0:
        if average_loss < best_loss:
            best_loss = average_loss
            unwrapped_model = accelerator.unwrap_model(model)
            unwrapped_model.save_pretrained(
                "./models/",
                is_main_process=accelerator.is_main_process,
                save_function=accelerator.save,
                safe_serialization=False,
                )
        print('saving model.')
```

**Comment by adossantos21** [comment]
I have a similar problem:
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by 
making sure all `forward` function outputs participate in calculating loss. 
If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Parameters which did not receive grad for rank 0: encoder.block.0.layer.0.TransientGlobalSelfAttention.global_relative_attention_bias.weight
Parameter indices which did not receive grad for rank 0: 6

RuntimeError: Rank 1 successfully reached monitoredBarrier, but received errors while waiting for send/recv from rank 0. Please check rank 0 logs for faulty rank.
