### ISSUE TITLE
dataloader is unable to process data that only on cpu

### ISSUE THREAD

**Issue by ZhiyuanChen** [huggingface/accelerate#239]
I have a `str` object (id of the input) passes in dataset to log the exact output of each input. But since the `send_to_device()` has set `error_on_other_type=True`, it would raises a `TypeError`.

```python
Traceback (most recent call last):
  File "main.py", line 723, in <module>
    results = runner.run()
  File "main.py", line 126, in run
    result['train'] = self.train()
  File "main.py", line 197, in train
    for iteration, data in enumerate(self.dataloaders['train']):
  File "/opt/conda/lib/python3.8/site-packages/accelerate/data_loader.py", line 306, in __iter__
    yield batch if self.device is None else send_to_device(batch, self.device)
  File "/opt/conda/lib/python3.8/site-packages/accelerate/utils.py", line 204, in send_to_device
    return recursively_apply(_send_to_device, tensor, device, test_type=_has_to_method, error_on_other_type=True)
  File "/opt/conda/lib/python3.8/site-packages/accelerate/utils.py", line 156, in recursively_apply
    return honor_type(
  File "/opt/conda/lib/python3.8/site-packages/accelerate/utils.py", line 121, in honor_type
    return type(obj)(generator)
  File "/opt/conda/lib/python3.8/site-packages/accelerate/utils.py", line 159, in <genexpr>
    recursively_apply(
  File "/opt/conda/lib/python3.8/site-packages/accelerate/utils.py", line 156, in recursively_apply
    return honor_type(
  File "/opt/conda/lib/python3.8/site-packages/accelerate/utils.py", line 121, in honor_type
    return type(obj)(generator)
  File "/opt/conda/lib/python3.8/site-packages/accelerate/utils.py", line 159, in <genexpr>
    recursively_apply(
  File "/opt/conda/lib/python3.8/site-packages/accelerate/utils.py", line 177, in recursively_apply
    raise TypeError(
TypeError: Can't apply _send_to_device on object of type <class 'str'>, only of nested list/tuple/dicts of objects that satisfy _has_to_method.
```

**Comment by sgugger** [comment]
This has been fixed on master already.

**Comment by ZhiyuanChen** [comment]
Ahhh, thank you!!
