### ISSUE TITLE
SpanMarker support

### ISSUE THREAD

**Issue by advand** [huggingface/accelerate#2401]
As per accelerate output:

`ValueError: Library `span-marker` is not supported yet, please open an issue on GitHub for us to add support.`

https://github.com/tomaarsen/SpanMarkerNER

**Comment by muellerzr** [comment]
Can you give us a full trace please? What were you trying to do? What was the code you were running?

**Comment by advand** [comment]
I ran the following command from the shell:
`accelerate estimate-memory stefan-it/span-marker-gelectra-large-germeval14 --dtypes float32`

Full trace:
```/Users/user/anaconda3/envs/ner2/lib/python3.11/site-packages/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/Users/user/anaconda3/envs/ner2/lib/python3.11/site-packages/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
Traceback (most recent call last):
  File "/Users/user/anaconda3/envs/ner2/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/user/anaconda3/envs/ner2/lib/python3.11/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/Users/user/anaconda3/envs/ner2/lib/python3.11/site-packages/accelerate/commands/estimate.py", line 250, in estimate_command
    data = gather_data(args)
           ^^^^^^^^^^^^^^^^^
  File "/Users/user/anaconda3/envs/ner2/lib/python3.11/site-packages/accelerate/commands/estimate.py", line 217, in gather_data
    model = create_empty_model(
            ^^^^^^^^^^^^^^^^^^^
  File "/Users/user/anaconda3/envs/ner2/lib/python3.11/site-packages/accelerate/commands/estimate.py", line 133, in create_empty_model
    raise ValueError(
ValueError: Library `span-marker` is not supported yet, please open an issue on GitHub for us to add support.```

**Comment by muellerzr** [comment]
If a contributor would like to implement this that is most welcome, however we only guarantee support for libraries inside the Hugging Face suite

**Comment by SunMarc** [comment]
Not planned as there is no more demand from the community since this issue was created.
