### ISSUE TITLE
Dispatch model throws error with 4 GPUs 

### ISSUE THREAD

**Issue by KKNakkav2** [huggingface/accelerate#2416]
### System Info

```Shell
- `Accelerate` version: 0.26.1
- Platform: Linux-5.4.0-169-generic-x86_64-with-glibc2.31
- Python version: 3.9.18
- Numpy version: 1.26.2
- PyTorch version (GPU?): 2.0.0 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 93.07 GB
- GPU type: Quadro RTX 6000
- `Accelerate` default config:
        Not found


- 4 Quadro RTX 6000 GPUS of each 24GB RAM.
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

Command:

```sh
 accelerate launch --config_file accelerate_configs/multi_gpu.yaml  --multi_gpu --mixed_precision=fp16 --num_processes=4 --gpu_ids=0,1,2,3  peft_model_training_with_accelerate.py
```

multi_gpu.yaml
```yaml
compute_environment: LOCAL_MACHINE
debug: false
distributed_type: MULTI_GPU
downcast_bf16: 'no'
gpu_ids: all
machine_rank: 0
main_training_function: main
mixed_precision: fp16 # bf16
num_machines: 1
num_processes: 8  # num of gpus inside the node
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

```py
import logging
from trl import SFTTrainer
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    TrainingArguments,
    LlamaForCausalLM
)
import peft
from peft import LoraConfig, PeftModel, prepare_model_for_kbit_training
from huggingface_hub import notebook_login
import json
import re
from pprint import pprint
from peft import PeftModel

import pandas as pd
import torch
from datasets import Dataset, load_dataset
import accelerate
from accelerate import load_checkpoint_and_dispatch


MODEL_NAME = 'baffo32/decapoda-research-llama-7B-hf'


def create_model_and_tokenizer():
   
    bnb_config = None

    model = AutoModelForCausalLM.from_pretrained(
        MODEL_NAME,
        cache_dir="/home/krishna/2024/HFModels",
        # use_safetensors=True,
        quantization_config=bnb_config,
        trust_remote_code=True,
        # device_map="auto",
        torch_dtype=torch.float16,

        # load_in_4bit=True
    )

    print(f"Model:  {MODEL_NAME} is loaded now!")

    tokenizer = AutoTokenizer.from_pretrained(
        MODEL_NAME,
        cache_dir="/home/krishna/2024/HFModels",
    )

    print(f"Tokeniser for model {MODEL_NAME} loaded now!")
    tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "right"

    return model, tokenizer


model, tokenizer = create_model_and_tokenizer()
model.config.use_cache = False


print_model(model)


# dispatch models across GPUs
if 1:
    no_split_module_classes = LlamaForCausalLM._no_split_modules

    device_map = accelerate.infer_auto_device_map(
        model, verbose=True,
    )
    print(device_map)
    model = accelerate.dispatch_model(model=model, device_map=device_map)
```

Output:
```sh
Treating module model.
Putting model (size=13248249856) on 0 (available=19887751168).

Treating module lm_head.
Putting lm_head (size=262144000) on 0 (available=6901645312).
Device map: OrderedDict([('', 0)])

Treating module model.
Putting model (size=13248249856) on 0 (available=19887751168).

Treating module lm_head.
Putting lm_head (size=262144000) on 0 (available=6901645312).

Device map: OrderedDict([('', 0)])
Traceback (most recent call last):
  File "/home/krishna/2024/LLMHelpers/peft_model_training_with_accelerate.py", line 195, in <module>
    model = accelerate.dispatch_model(model=model, device_map=device_map)
  File "/home/krishna/miniconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/big_modeling.py", line 445, in dispatch_model
    model.to(device)
  File "/home/krishna/miniconda3/envs/fs-llm/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2597, in to
    return super().to(*args, **kwargs)
  File "/home/krishna/miniconda3/envs/fs-llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/home/krishna/miniconda3/envs/fs-llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/krishna/miniconda3/envs/fs-llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/krishna/miniconda3/envs/fs-llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "/home/krishna/miniconda3/envs/fs-llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/home/krishna/miniconda3/envs/fs-llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 86.00 MiB (GPU 0; 23.64 GiB total capacity; 5.28 GiB already allocated; 32.44 MiB free; 5.29 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "/home/krishna/2024/LLMHelpers/peft_model_training_with_accelerate.py", line 195, in <module>
    model = accelerate.dispatch_model(model=model, device_map=device_map)
  File "/home/krishna/miniconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/big_modeling.py", line 445, in dispatch_model
    model.to(device)
  File "/home/krishna/miniconda3/envs/fs-llm/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2597, in to
Traceback (most recent call last):
  File "/home/krishna/2024/LLMHelpers/peft_model_training_with_accelerate.py", line 195, in <module>
Traceback (most recent call last):
  File "/home/krishna/2024/LLMHelpers/peft_model_training_with_accelerate.py", line 195, in <module>
    model = accelerate.dispatch_model(model=model, device_map=device_map)
  File "/home/krishna/miniconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/big_modeling.py", line 445, in dispatch_model
    return super().to(*args, **kwargs)
  File "/home/krishna/miniconda3/envs/fs-llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1145, in to
    model.to(device)
  File "/home/krishna/miniconda3/envs/fs-llm/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2597, in to
    model = accelerate.dispatch_model(model=model, device_map=device_map)
  File "/home/krishna/miniconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/big_modeling.py", line 445, in dispatch_model
    model.to(device)
      File "/home/krishna/miniconda3/envs/fs-llm/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2597, in to
return self._apply(convert)
  File "/home/krishna/miniconda3/envs/fs-llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/krishna/miniconda3/envs/fs-llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    return super().to(*args, **kwargs)
  File "/home/krishna/miniconda3/envs/fs-llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1145, in to
    module._apply(fn)
  File "/home/krishna/miniconda3/envs/fs-llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "/home/krishna/miniconda3/envs/fs-llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 820, in _apply
    return super().to(*args, **kwargs)
  File "/home/krishna/miniconda3/envs/fs-llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/home/krishna/miniconda3/envs/fs-llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    param_applied = fn(param)
  File "/home/krishna/miniconda3/envs/fs-llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1143, in convert
    module._apply(fn)
  File "/home/krishna/miniconda3/envs/fs-llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    return self._apply(convert)
  File "/home/krishna/miniconda3/envs/fs-llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/krishna/miniconda3/envs/fs-llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 32.00 MiB (GPU 0; 23.64 GiB total capacity; 5.57 GiB already allocated; 32.44 MiB free; 5.57 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
    module._apply(fn)
  File "/home/krishna/miniconda3/envs/fs-llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "/home/krishna/miniconda3/envs/fs-llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 820, in _apply
    module._apply(fn)
  File "/home/krishna/miniconda3/envs/fs-llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    param_applied = fn(param)
  File "/home/krishna/miniconda3/envs/fs-llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1143, in convert
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "/home/krishna/miniconda3/envs/fs-llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 820, in _apply
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 86.00 MiB (GPU 0; 23.64 GiB total capacity; 5.75 GiB already allocated; 32.44 MiB free; 5.75 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
    param_applied = fn(param)
  File "/home/krishna/miniconda3/envs/fs-llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 86.00 MiB (GPU 0; 23.64 GiB total capacity; 6.12 GiB already allocated; 32.44 MiB free; 6.12 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 3471841) of binary: /home/krishna/miniconda3/envs/fs-llm/bin/python
Traceback (most recent call last):
  File "/home/krishna/miniconda3/envs/fs-llm/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/krishna/miniconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/home/krishna/miniconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/commands/launch.py", line 1014, in launch_command
    multi_gpu_launcher(args)
  File "/home/krishna/miniconda3/envs/fs-llm/lib/python3.9/site-packages/accelerate/commands/launch.py", line 672, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/krishna/miniconda3/envs/fs-llm/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/krishna/miniconda3/envs/fs-llm/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/krishna/miniconda3/envs/fs-llm/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
peft_model_training_with_accelerate.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-02-05_13:09:06
  host      : pteamgpu
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 3471848)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-02-05_13:09:06
  host      : pteamgpu
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 3471855)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-02-05_13:09:06
  host      : pteamgpu
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 3471862)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-02-05_13:09:06
  host      : pteamgpu
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 3471841)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

```

### Expected behavior

Dispatch model should load model across the  GPUs

**Comment by muellerzr** [comment]
Run it with `python` instead and it should work

**Comment by KKNakkav2** [comment]
Thank you @muellerzr  for prompt response. 

I have tried launching  with the following command  (using `python`). Please correct if this is not what you are suggesting.

```sh
python -m accelerate.commands.launch  --config_file accelerate_configs/multi_gpu.yaml  --multi_gpu --mixed_precision=fp16 --num_processes=4 --gpu_ids=0,1,2,3  peft_model_training_with_accelerate.py
```

It throws the same error

```sh
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 86.00 MiB (GPU 0; 23.64 GiB total capacity; 5.45 GiB already allocated; 20.44 MiB free; 5.45 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by sssszh** [comment]
@KKNakkav2 

Hi, did you solve this problem? I am having the same problem. I would be very grateful if you could give me a little suggestion.

Thanks！
