### ISSUE TITLE
OOM when finetuning GPTJ

### ISSUE THREAD

**Issue by PurvangL** [huggingface/accelerate#2417]
### System Info

```Shell
H100X8 (80GB)
docker : nvcr.io/nvidia/pytorch:23.12-py3
python packages:
  datasets 
  evaluate
  accelerate==0.25.0
  transformers==4.37.0
  deepspeed==0.13.1
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction
```
docker run --gpus all --rm -it  -v ~/.cache:/root/.cache --ipc=host nvcr.io/nvidia/pytorch:23.12-py3
pip install datasets evaluate accelerate==0.25.0 transformers==4.37.0 deepspeed==0.13.1
accelerate launch --multi_gpu --num_processes 8 script.py
```
script.py
```
import argparse
import os
import torch
import transformers
from accelerate import Accelerator, FullyShardedDataParallelPlugin
from accelerate import init_empty_weights, load_checkpoint_and_dispatch
from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForCausalLM, GPTJForCausalLM, LlamaForCausalLM
import pandas as pd
import numpy as np

accelerator = Accelerator()

model_name = "EleutherAI/gpt-j-6B"
output_dir = "tmp"
max_length = 128
max_steps = 2000
learning_rate = 2.5e-5

print("Loading tiny_shakespeare dataset")
current_dataset = load_dataset("tiny_shakespeare",streaming=True)
train_dataset = current_dataset["train"]
eval_dataset = current_dataset["validation"]

tokenizer = AutoTokenizer.from_pretrained(
    model_name,
    padding_side="left",
    add_eos_token=True,
    add_bos_token=True,
)
tokenizer.pad_token = tokenizer.eos_token


def split_text(batch):
    text = list(batch["text"])
    flat_text = "".join(text)
    split_text = [
        x.strip()
        for x in flat_text.split("\n")
        if x.strip() and not x.strip()[-1] == ":"
    ]
    return split_text

def tokenize(batch):
    ret = tokenizer(
        split_text(batch),
        truncation=True,
        max_length=max_length,
        padding="max_length",
        return_tensors="np",
    )
    ret["labels"] = ret["input_ids"].copy()
    return dict(ret)

tokenized_train_dataset = train_dataset.map(tokenize)
tokenized_val_dataset = eval_dataset.map(tokenize)

deepspeed = {
    "fp16": {
        "enabled": "auto",
        "initial_scale_power": 8,
    },
    "bf16": {"enabled": "auto"},
    "optimizer": {
        "type": "AdamW",
        "params": {
            "lr": "auto",
            "betas": "auto",
            "eps": "auto",
        },
    },
    "scheduler": {
        "type": "WarmupLR",
        "params": {
            "warmup_min_lr": learning_rate,
            "warmup_max_lr": learning_rate,
            "warmup_num_steps": 0
        },
    },
    "zero_optimization": {
        "stage": 3,
        "offload_optimizer": {
            "device": "cpu",
            "pin_memory": True,
        },
        "offload_param": {
            "device": "cpu",
            "pin_memory": True,
        },
        "overlap_comm": True,
        "contiguous_gradients": True,
        "reduce_bucket_size": "auto",
        "stage3_prefetch_bucket_size": "auto",
        "stage3_param_persistence_threshold": "auto",
        "gather_16bit_weights_on_model_save": True,
        "round_robin_gradients": True,
    },
    "gradient_accumulation_steps": "auto",
    "gradient_clipping": "auto",
    "steps_per_print": 10,
    "train_batch_size": "auto",
    "train_micro_batch_size_per_gpu": "auto",
    "wall_clock_breakdown": False,
}


print("Loading model")

model = GPTJForCausalLM.from_pretrained(model_name)

model.resize_token_embeddings(len(tokenizer))

print("Model loaded")

batch_size = 16
steps_per_epoch = 2
epochs = 10

print("Preparing training arguments")
training_args = transformers.TrainingArguments(
    output_dir,
    logging_steps=1,
    save_strategy="no", 
    save_steps=steps_per_epoch * epochs,
    max_steps=steps_per_epoch * epochs,
    learning_rate=learning_rate,
    weight_decay=0.01,
    warmup_steps=0,
    label_names=["input_ids", "attention_mask"],
    push_to_hub=False,
    report_to="none",
    disable_tqdm=True, 
    bf16=True,
    gradient_checkpointing=True,
    deepspeed=deepspeed,
    per_device_train_batch_size=batch_size,
    per_device_eval_batch_size=batch_size,
)

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return metric.compute(predictions=predictions, references=labels)

trainer =transformers.Trainer(
        model=model,
        args=training_args,
        train_dataset=tokenized_train_dataset,
        eval_dataset=tokenized_val_dataset,
        compute_metrics=compute_metrics,
        tokenizer=tokenizer,
        data_collator=transformers.default_data_collator,
    )

trainer.train()
```

### Expected behavior

accelerate launch --multi_gpu --num_processes 8 script.py

Is there any issue with my code or am I missing something?

**Comment by pacman100** [comment]
Hello @PurvangL, 

In the above code, you shouldn't prepare the trainer object. Other than that, you should be easily able to run GPT-J on 8 H100 GPUs. Please refer https://huggingface.co/docs/transformers/trainer?config=DistributedDataParallel#accelerate-and-trainer for the correct way to use Accelerate launcher when using DeepSpeed with Trainer.

**Comment by PurvangL** [comment]
@pacman100 I removed accelerator.prepare and not using accelerate.prepare at all and letting accelerate and trainer figure out distributed training. but now I get following error

```
Time to load cpu_adam op: 26.679558277130127 seconds
Loading extension module cpu_adam...
Time to load cpu_adam op: 26.72487235069275 seconds
Parameter Offload: Total persistent parameters: 811008 in 114 params
Traceback (most recent call last):
  File "/workspace/sc.py", line 160, in <module>
    trainer.train()
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1539, in train
Traceback (most recent call last):
  File "/workspace/sc.py", line 160, in <module>
    trainer.train()
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1869, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 2768, in training_step
    return inner_training_loop(
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1869, in _inner_training_loop
Traceback (most recent call last):
  File "/workspace/sc.py", line 160, in <module>
    trainer.train()
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1539, in train
    tr_loss_step = self.training_step(model, inputs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 2768, in training_step
    loss = self.compute_loss(model, inputs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 2791, in compute_loss
    return inner_training_loop(
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1869, in _inner_training_loop
    loss = self.compute_loss(model, inputs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 2791, in compute_loss
    outputs = model(**inputs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1510, in _wrapped_call_impl
    tr_loss_step = self.training_step(model, inputs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 2768, in training_step
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1519, in _call_impl
    outputs = model(**inputs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1510, in _wrapped_call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    loss = self.compute_loss(model, inputs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 2791, in compute_loss
    ret_val = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/engine.py", line 1842, in forward
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1519, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    loss = self.module(*inputs, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1510, in _wrapped_call_impl
    ret_val = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/engine.py", line 1842, in forward
    outputs = model(**inputs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1510, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1560, in _call_impl
        loss = self.module(*inputs, **kwargs)return self._call_impl(*args, **kwargs)

  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1510, in _wrapped_call_impl
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1519, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/gptj/modeling_gptj.py", line 853, in forward
    return forward_call(*args, **kwargs)
      File "/usr/local/lib/python3.10/dist-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1560, in _call_impl
    ret_val = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/engine.py", line 1842, in forward
    transformer_outputs = self.transformer(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1510, in _wrapped_call_impl
    result = forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/gptj/modeling_gptj.py", line 853, in forward
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1560, in _call_impl
    loss = self.module(*inputs, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1510, in _wrapped_call_impl
    transformer_outputs = self.transformer(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1510, in _wrapped_call_impl
    result = forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/gptj/modeling_gptj.py", line 606, in forward
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1560, in _call_impl
    raise ValueError("batch_size has to be defined and > 0")
    return self._call_impl(*args, **kwargs)ValueError
:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1560, in _call_impl
batch_size has to be defined and > 0
    result = forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/gptj/modeling_gptj.py", line 853, in forward
    result = forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/gptj/modeling_gptj.py", line 606, in forward
    transformer_outputs = self.transformer(Traceback (most recent call last):

  File "/workspace/sc.py", line 160, in <module>
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1510, in _wrapped_call_impl
    raise ValueError("batch_size has to be defined and > 0")
ValueError: batch_size has to be defined and > 0
```
