### ISSUE TITLE
NCCL operations have failed or timed out during tokenization for pretraining

### ISSUE THREAD

**Issue by Jason-Kim** [huggingface/accelerate#2528]
When I was pretraining with accelerate CLI like below, some NCCL operations have failed or timed out.
I found this solution https://github.com/huggingface/accelerate/issues/314#issuecomment-1096626216
But I don't know how to set timeout configure in accelerate CLI.

### command: 
```
CUDA_VISIBLE_DEVICES="0,1" accelerate launch --config_file config.yaml run_mlm_no_trainer.py \
    --model_type bert \
    --tokenizer_name ./tokenizer/wordpiece/ \
    --train_file ./train_data_for_pretrain/ \
    --validation_split_percentage 10 \
    --max_seq_length 512 \
    --per_device_train_batch_size 32 \
    --per_device_eval_batch_size 32 \
    --output_dir ./pretrained_lm_notrainer/ \
    --preprocessing_num_workers 32 \
    --seed 42 \
    --num_train_epochs 2
```

### error messages:
```
[E ProcessGroupNCCL.cpp:489] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:495] To avoid data inconsistency, we are taking the entire process down.
[E ProcessGroupNCCL.cpp:916] [Rank 1] NCCL watchdog thread terminated with exception: [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=2, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=1800000) ran for 1800437 milliseconds before timing out.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 1] NCCL watchdog thread terminated with exception: [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=2, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=1800000) ran for 1800437 milliseconds before timing out.
Running tokenizer on every text in dataset (num_proc=24):  33%|██████████████████████▍                                              | 384421000/1179100964 [30:16<57:49, 229032.98 examples/s][2024-03-06 14:34:20,764] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 4946 closing signal SIGTERM
[2024-03-06 14:34:22,885] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: -6) local_rank: 1 (pid: 4947) of binary: /home/nips/.conda/envs/pyenv38/bin/python
Traceback (most recent call last):
  File "/home/nips/.conda/envs/pyenv38/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/nips/.conda/envs/pyenv38/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/home/nips/.conda/envs/pyenv38/lib/python3.8/site-packages/accelerate/commands/launch.py", line 1004, in launch_command
    multi_gpu_launcher(args)
  File "/home/nips/.conda/envs/pyenv38/lib/python3.8/site-packages/accelerate/commands/launch.py", line 666, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/nips/.conda/envs/pyenv38/lib/python3.8/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/nips/.conda/envs/pyenv38/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/nips/.conda/envs/pyenv38/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
```

**Comment by muellerzr** [comment]
It needs to be done in the code, as with Sylvain's solution. Most of all we need your code to help at all

**Comment by Jason-Kim** [comment]
Thanks @muellerzr. I used the run_mlm_no_trainer.py script from the [transformers examples](https://github.com/huggingface/transformers/blob/v4.36.2/examples/pytorch/language-modeling/run_mlm_no_trainer.py).
I just changed the code to allow processing from a single file to multiple files for --train_file parameter.
The rest of the code is the same as the original.
