### ISSUE TITLE
loss become None after model forward

### ISSUE THREAD

**Issue by matthewdm0816** [huggingface/accelerate#2550]
After some frustrations, I tried to make a reproducer, validated on either `accelerate==0.24.0` or `accelerate==0.28.0`.
---
### The reproducer

```python
# reprod.py
import transformers
import accelerate
from accelerate import Accelerator, DistributedDataParallelKwargs
from accelerate.state import AcceleratorState
import torch

class DummyDataset(torch.utils.data.Dataset):
    def __init__(self, length, max_length):
        self.length = length
        self.max_length = max_length
    def __len__(self):
        return self.length
    def __getitem__(self, idx):
        return {
            "input_ids": torch.randint(0, 100, (self.max_length,)),
            "attention_mask": torch.ones(self.max_length),
            "labels": torch.randint(0, 100, (self.max_length,)),
        }
    
class DummyModel(transformers.GPT2LMHeadModel):
    def __init__(self, config):
        super().__init__(config)
        self.cached_inputs = None
        self.linear = torch.nn.Linear(10, 20)

    def forward(self, **kwargs):
        labels = kwargs.get("labels")
        del kwargs["labels"]
        with torch.cuda.amp.autocast(enabled=False):
            outputs = super().forward(**kwargs)

        if self.cached_inputs is None: # some dummy computation
            self.cached_inputs = kwargs["input_ids"].detach().clone()
        else:
            # print(self.cached_inputs)
            pass

        print(outputs.loss)
        loss = None
        lm_logits = outputs.logits
        # labels = kwargs.get("labels")
        if labels is not None:
            # move labels to correct device to enable model parallelism
            labels = labels.to(lm_logits.device)
            # Shift so that tokens < n predict n
            shift_logits = lm_logits[..., :-1, :].contiguous()
            shift_labels = labels[..., 1:].contiguous()
            loss_fct = torch.nn.CrossEntropyLoss()
            shift_logits = shift_logits.view(-1, self.config.vocab_size)
            shift_labels = shift_labels.view(-1)
            shift_labels = shift_labels.to(shift_logits.device)
            # Flatten the tokens
            loss = loss_fct(shift_logits, shift_labels)
        outputs.loss = loss # here it is still a tensor

        return outputs


def main():
    # model: transformers.GPT2LMHeadModel = transformers.GPT2LMHeadModel(transformers.GPT2Config())
    model = DummyModel(transformers.GPT2Config())
    # to bfloat16
    # for param in model.parameters():
        # param.data = param.data.to(torch.bfloat16)

    optimizer = torch.optim.AdamW(model.parameters(), lr=1e-4)
    batch_size = 16

    ddp_kwargs = DistributedDataParallelKwargs(find_unused_parameters=True)
    accelerator = Accelerator(gradient_accumulation_steps=32, kwargs_handlers=[ddp_kwargs])

    print(accelerator.state.distributed_type)

    dataset = DummyDataset(100, 30)
    dataloader = torch.utils.data.DataLoader(dataset, batch_size=batch_size)
    history_losses = []


    model, optimizer, dataloader = accelerator.prepare(model, optimizer, dataloader)

    model.train()
    for batch in dataloader:
        with accelerator.accumulate(model):
            outputs = model(**batch)
            loss = outputs.loss # here it will become None!!!
            accelerator.backward(loss)

            with torch.no_grad():
                loss_mean = accelerator.gather(loss.unsqueeze(0)).mean()
                history_losses.append(loss_mean.item())
                if accelerator.is_local_main_process:
                    print(loss_mean.item())

            print(loss.item())
            optimizer.step()
            optimizer.zero_grad()


if __name__ == "__main__":
    main()
 ```

just run it with simple DDP config
```yaml
compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
downcast_bf16: 'no'
gpu_ids: all
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 6
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```
with command line
`accelerate launch reprod.py`
### The error
```
Traceback (most recent call last):
  File "/scratch/generalvision/xxx/ScanQA/reprod-deepspeed.py", line 115, in <module>
    main()
  File "/scratch/generalvision/xxx/ScanQA/reprod-deepspeed.py", line 91, in main
    accelerator.backward(loss)
  File "/scratch/xxx/.conda/envs/llama/lib/python3.10/site-packages/accelerate/accelerator.py", line 1981, in backward
    loss = loss / self.gradient_accumulation_steps
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
```
### The (possible) reason
The only code change that cause the problem is that, the loss computation is moved out from inner GPT2 model (or any other model with `transformers` formatted output).  
remove that computation code and add back the labels for inner GPT2 forward works fine, but a custom loss would inevitably require such computation code without hacking the code in the `transformers` package.

The deeper root might be related to the `accelerator.prepare_model` method [here](https://github.com/huggingface/accelerate/blob/ee163b66fb7848892519e804688cb4ae981aacbe/src/accelerate/accelerator.py#L1334), that wraps the forward with a `convert_outputs_to_fp32` method, which somehow let the loss becomes None.

_Originally posted by @matthewdm0816 in https://github.com/huggingface/accelerate/issues/1366#issuecomment-1993100000_

**Comment by matthewdm0816** [comment]
it is due to https://github.com/huggingface/accelerate/issues/1366#issuecomment-1993199033
