### ISSUE TITLE
Accelerate's tqdm doesn't support IterableDatasets / streaming datasets from HF datasets

### ISSUE THREAD

**Issue by irowberryFS** [huggingface/accelerate#2555]
### System Info

```Shell
- `Accelerate` version: 0.28.0
- Platform: Linux-5.15.0-89-generic-x86_64-with-glibc2.31
- Python version: 3.12.2
- Numpy version: 1.26.4
- PyTorch version (GPU?): 2.2.1 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 125.64 GB
- GPU type: NVIDIA GeForce RTX 3090
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: DEEPSPEED
        - mixed_precision: fp16
        - use_cpu: False
        - debug: True
        - num_processes: 3
        - machine_rank: 0
        - num_machines: 1
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - deepspeed_config: {'gradient_accumulation_steps': 1, 'gradient_clipping': 1.0, 'offload_optimizer_device': 'none', 'offload_param_device': 'none', 'zero3_init_flag': False, 'zero_stage': 2}
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

```python
from accelerate.utils import tqdm
from datasets import load_dataset
from torch.utils.data import DataLoader

dataset = load_dataset('fka/awesome-chatgpt-prompts', 'en', split='train', streaming='true')
dl = DataLoader(dataset, 5)
epochs = 1

for epoch in range(epochs):
    with tqdm(dl, total=1000, unit='batch') as tepoch:
        tepoch.set_description(f"Epoch: {epoch}")
        for batch in tepoch:
            print(batch)
            loss = 0.1
            tepoch.set_postfix(loss=loss)
```
Here's the traceback using the given example.
```
Traceback (most recent call last):
  File "/home/irowberry/projects/experiments.py", line 10, in <module>
    with tqdm(dl, total=1000, unit='batch') as tepoch:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/irowberry/projects/venv/lib/python3.11/site-packages/accelerate/utils/tqdm.py", line 35, in tqdm
    if main_process_only:
  File "/home/irowberry/projects/venv/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 474, in __len__
    length = self._IterableDataset_len_called = len(self.dataset)  # type: ignore[assignment, arg-type]
                                                ^^^^^^^^^^^^^^^^^
TypeError: object of type 'IterableDataset' has no len()
```

### Expected behavior

It should show a progress bar as normal, since I passed in `total` keyword.

**Comment by muellerzr** [comment]
This doesn't seem to stem from `tqdm` from what I can see.

Does the epoch iterate normally without it?

**Comment by irowberryFS** [comment]
If you swap out `from accelerate.utils import tqdm` with `from tqdm import tqdm` it works as intended.

**Comment by muellerzr** [comment]
As the type-hint for the `tqdm` wrapper states, the first argument is whether it should go on the main process or not. 

```python
def tqdm(main_process_only: bool = True, *args, **kwargs):
    """
    Wrapper around `tqdm.tqdm` that optionally displays only on the main process.

    Args:
        main_process_only (`bool`, *optional*):
            Whether to display the progress bar only on the main process
    """
```

So, just do this:

```python
with tqdm(main_process_only=True, dl, total=1000, unit='batch') as tepoch:
```

**Comment by irowberryFS** [comment]
Ahh I see that. You also need to do `iterable=dataloader` to properly pass in the dataloader. Thanks for the help!
