### ISSUE TITLE
Single GPU [1080ti] Training - Meta Tensor Issues

### ISSUE THREAD

**Issue by AnshKetchum** [huggingface/accelerate#2556]
### System Info

```Shell
- `Accelerate` version: 0.28.0
- Platform: Linux-6.2.0-39-generic-x86_64-with-glibc2.37
- Python version: 3.10.13
- Numpy version: 1.26.4
- PyTorch version (GPU?): 2.2.1+cu121 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 31.30 GB
- GPU type: NVIDIA GeForce GTX 1080
- `Accelerate` default config:
	- compute_environment: LOCAL_MACHINE
	- distributed_type: DEEPSPEED
	- mixed_precision: fp8
	- use_cpu: True
	- debug: False
	- num_processes: 1
	- machine_rank: 0
	- num_machines: 1
	- rdzv_backend: static
	- same_network: True
	- main_training_function: main
	- deepspeed_config: {'gradient_accumulation_steps': 1, 'gradient_clipping': 1.0, 'zero3_init_flag': True, 'zero_stage': 0}
	- ipex_config: {'ipex': True}
	- downcast_bf16: no
	- tpu_use_cluster: False
	- tpu_use_sudo: False
	- tpu_env: []
	- dynamo_config: {'dynamo_backend': 'ONNXRT', 'dynamo_mode': 'max-autotune', 'dynamo_use_dynamic': True, 'dynamo_use_fullgraph': True}
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

Implementing the original DDPM paper here: [https://arxiv.org/pdf/2006.11239.pdf](https://arxiv.org/pdf/2006.11239.pdf) , and attempting to use functionality from accelerate to optimize for out-of-memory errors - particularly any features that can offload to the disk / CPU to reduce GPU tensor usage.

```python
Somewhere in __init__ above in a Diffusion class ... 
    self.model = UNet(
        dim=8, 
        dim_mults=(1, 1, 1, 1),
        channels=num_channels,
        resnet_block_groups=1
    )

# Actual training code
def train(self, dataloader: DataLoader, num_epochs=100, timesteps=1000):

        optimizer = torch.optim.Adam(self.model.parameters())

        # Port the model to the desired device
        accelerator = Accelerator()
        self.model, optimizer, dataloader = accelerator.prepare(
            self.model, optimizer, dataloader)

        self.model.train()
        for i in range(num_epochs):

            for k, img in enumerate(dataloader):
                optimizer.zero_grad()

                noisy_images = torch.randn(
                    (img.shape[0], self.channels, self.image_shape, self.image_shape))

                timesteps = [random.randint(0, timesteps)
                             for i in range(img.shape[0])]

                # Sample the noise at timestep t
                samples_generated = self.reverse_diffusion(
                    noisy_images, timesteps)

                # Compute the loss
                loss = self.compute_loss(samples_generated, img, timesteps)
                accelerator.backward(loss)

                optimizer.step()
```

### Expected behavior

This code would throw the following error: 

```
Traceback (most recent call last):
  File "/home/pchaurasia/CodingWorkspace/personal/archipelago/ml/diffusion/main2.py", line 41, in <module>
    data.train(dataloader, 10, 100)
  File "/home/pchaurasia/CodingWorkspace/personal/archipelago/ml/diffusion/diffusion.py", line 116, in train
    self.model, optimizer, dataloader = accelerator.prepare(
  File "/home/pchaurasia/miniconda3/envs/sdenv/lib/python3.10/site-packages/accelerate/accelerator.py", line 1263, in prepare
    result = tuple(
  File "/home/pchaurasia/miniconda3/envs/sdenv/lib/python3.10/site-packages/accelerate/accelerator.py", line 1264, in <genexpr>
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
  File "/home/pchaurasia/miniconda3/envs/sdenv/lib/python3.10/site-packages/accelerate/accelerator.py", line 1140, in _prepare_one
    return self.prepare_model(obj, device_placement=device_placement)
  File "/home/pchaurasia/miniconda3/envs/sdenv/lib/python3.10/site-packages/accelerate/accelerator.py", line 1376, in prepare_model
    model = model.to(self.device)
  File "/home/pchaurasia/miniconda3/envs/sdenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1152, in to
    return self._apply(convert)
  File "/home/pchaurasia/miniconda3/envs/sdenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 802, in _apply
    module._apply(fn)
  File "/home/pchaurasia/miniconda3/envs/sdenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 825, in _apply
    param_applied = fn(param)
  File "/home/pchaurasia/miniconda3/envs/sdenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1150, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
NotImplementedError: Cannot copy out of meta tensor; no data!
```

**Comment by muellerzr** [comment]
```
self.model = UNet(
        dim=8, 
        dim_mults=(1, 1, 1, 1),
        channels=num_channels,
        resnet_block_groups=1
    )
```
Is that fully how you are init'ng your model? Are you using `init_empty_weights` or anything else? This logic shows that some part of the model has been offloaded **before** `accelerator.prepare`, so how you are constructing it and any modifications you are doing is critically important

**Comment by AnshKetchum** [comment]
Yes, that is how I am calling it. I tried replacing it with the following: 

```python
with init_empty_weights():
                  self.model = UNet(
                dim=8,  # Throws an error when the image dimension is under 6
                dim_mults=(1, 2, 4, 8),
                channels=num_channels,
                resnet_block_groups=1
            )
```

To get the exact same error. I do use the `init_empty_weights` method somewhere else, when I'm calling the top class (which is just a Python object, not PyTorch Module).

```
with init_empty_weights():
    random_sampler = RandomSampler(dataset, num_samples=sample_size)
    dataloader = DataLoader(
        dataset, batch_size=batch_size, sampler=random_sampler)

    data = Diffusion(image_shape=64)
    data.train(dataloader, 10, 100)

    image = data.sample_images(1)
    image[0].save("out.jpg")
```
Above is how the call would look
