### ISSUE TITLE
`accelerate test` starts to fail on both TPU v4 and TPU v2/v3

### ISSUE THREAD

**Issue by vanbasten23** [huggingface/accelerate#2610]
### System Info

```Shell
- `Accelerate` version: 0.29.0.dev0
- Platform: Linux-5.19.0-1022-gcp-x86_64-with-glibc2.35
- Python version: 3.10.6
- Numpy version: 1.26.4
- PyTorch version (GPU?): 2.4.0.dev20240401+cpu (False)
- PyTorch XPU available: False
- PyTorch NPU available: False
- PyTorch MLU available: False
- System RAM: 400.47 GB
- `Accelerate` default config:
	- compute_environment: LOCAL_MACHINE
	- distributed_type: XLA
	- mixed_precision: no
	- use_cpu: False
	- debug: False
	- num_processes: 4
	- machine_rank: 0
	- num_machines: 1
	- rdzv_backend: static
	- same_network: True
	- main_training_function: main
	- enable_cpu_affinity: False
	- downcast_bf16: no
	- tpu_use_cluster: False
	- tpu_use_sudo: False
	- tpu_env: []
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

Hi. We observed the `accelerate test` starts failing on TPU's 04/02 nightly run.

```
accelerate test

stderr: """
stderr: Traceback (most recent call last):
stderr:   File "/usr/lib/python3.10/concurrent/futures/process.py", line 246, in _process_worker
stderr:     r = call_item.fn(*call_item.args, **call_item.kwargs)
stderr:   File "/usr/lib/python3.10/concurrent/futures/process.py", line 205, in _process_chunk
stderr:     return [fn(*args) for args in chunk]
stderr:   File "/usr/lib/python3.10/concurrent/futures/process.py", line 205, in <listcomp>
stderr:     return [fn(*args) for args in chunk]
stderr:   File "/home/ml-auto-solutions/.local/lib/python3.10/site-packages/torch_xla/runtime.py", line 95, in wrapper
stderr:     return fn(*args, **kwargs)
stderr:   File "/home/ml-auto-solutions/.local/lib/python3.10/site-packages/torch_xla/_internal/pjrt.py", line 78, in _run_thread_per_device
stderr:     replica_results = list(
[2024-04-02, 07:16:36 PDT] {logging_mixin.py:150} WARNING - stderr:   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
stderr:     yield _result_or_cancel(fs.pop())
stderr:   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
stderr:     return fut.result(timeout)
stderr:   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
stderr:     return self.__get_result()
stderr:   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
stderr:     raise self._exception
stderr:   File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
stderr:     result = self.fn(*self.args, **self.kwargs)
stderr:   File "/home/ml-auto-solutions/.local/lib/python3.10/site-packages/torch_xla/_internal/pjrt.py", line 71, in _thread_fn
stderr:     return fn()
stderr:   File "/home/ml-auto-solutions/.local/lib/python3.10/site-packages/torch_xla/_internal/pjrt.py", line 190, in __call__
stderr:     self.fn(runtime.global_ordinal(), *self.
[2024-04-02, 07:16:36 PDT] {logging_mixin.py:150} WARNING - args, **self.kwargs)
stderr:   File "/home/ml-auto-solutions/.local/lib/python3.10/site-packages/accelerate/utils/launch.py", line 624, in __call__
stderr:     self.launcher(*args)
stderr:   File "/home/ml-auto-solutions/.local/lib/python3.10/site-packages/accelerate/test_utils/scripts/test_script.py", line 788, in main
stderr:     training_check(use_seedable_sampler=False)
stderr:   File "/home/ml-auto-solutions/.local/lib/python3.10/site-packages/accelerate/test_utils/scripts/test_script.py", line 447, in training_check
stderr:     assert torch.allclose(old_model.a, model.a), "Did not obtain the same model on CPU or distributed training."
stderr: AssertionError: Did not obtain the same model on CPU or distributed training.
stderr: """
stderr: 
stderr: The above exception was the direct cause of the following exception:
stderr: 
stderr: Traceback (most recent call last):
stderr:   File "/home/ml-auto-solutions/.local/bin/accelerate-launch", line 8, in <module>
stderr:     sys.exit(mai
[2024-04-02, 07:16:36 PDT] {logging_mixin.py:150} WARNING - n())
stderr:   File "/home/ml-auto-solutions/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1081, in main
[2024-04-02, 07:16:36 PDT] {logging_mixin.py:150} WARNING - stderr:     launch_command(args)
stderr:   File "/home/ml-auto-solutions/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1071, in launch_command
stderr:     tpu_launcher(args)
stderr:   File "/home/ml-auto-solutions/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 802, in tpu_launcher
stderr:     xmp.spawn(PrepareForLaunch(main_function), args=(), nprocs=args.num_processes)
[2024-04-02, 07:16:36 PDT] {logging_mixin.py:150} WARNING - stderr:   File "/home/ml-auto-solutions/.local/lib/python3.10/site-packages/torch_xla/runtime.py", line 95, in wrapper
stderr:     return fn(*args, **kwargs)
stderr:   File "/home/ml-auto-solutions/.local/lib/python3.10/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 38, in spawn
stderr:     return pjrt.spawn(fn, nprocs, start_method, args)
stderr:   File "/home/ml-auto-solutions/.local/lib/python3.10/site-packages/torch_xla/_internal/pjrt.py", line 214, in spawn
stderr:     run_multiprocess(spawn_fn, start_method=start_method)
[2024-04-02, 07:16:36 PDT] {logging_mixin.py:150} WARNING - stderr:   File "/home/ml-auto-solutions/.local/lib/python3.10/site-packages/torch_xla/runtime.py", line 95, in wrapper
stderr:     return fn(*args, **kwargs)
stderr:   File "/home/ml-auto-solutions/.local/lib/python3.10/site-packages/torch_xla/_internal/pjrt.py", line 174, in run_multiprocess
[2024-04-02, 07:16:36 PDT] {logging_mixin.py:150} WARNING - stderr:     replica_results = list(
[2024-04-02, 07:16:36 PDT] {logging_mixin.py:150} WARNING - stderr:   File "/home/ml-auto-solutions/.local/lib/python3.10/site-packages/torch_xla/_internal/pjrt.py", line 175, in <genexpr>
stderr:     itertools.chain.from_iterable(
[2024-04-02, 07:16:36 PDT] {logging_mixin.py:150} WARNING - stderr:   File "/usr/lib/python3.10/concurrent/futures/process.py", line 570, in _chain_from_iterable_of_lists
stderr:     for element in iterable:
stderr:   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
stderr:     yield _result_or_cancel(fs.pop())
[2024-04-02, 07:16:36 PDT] {logging_mixin.py:150} WARNING - stderr:   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
[2024-04-02, 07:16:36 PDT] {logging_mixin.py:150} WARNING - stderr:     return fut.result(timeout)
stderr:   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
stderr:     return self.__get_result()
stderr:   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
stderr:     raise self._exception
stderr: AssertionError: Did not obtain the same model on CPU or distributed training.
```
full output: https://gist.github.com/vanbasten23/61b0fd5a5264fcfa00b28e82fd3c97f2

### Expected behavior

The test should succeed.

cc @muellerzr @will-cromar

**Comment by vanbasten23** [comment]
Hi @muellerzr , I was able to find out the error first occurs in the commit https://github.com/huggingface/accelerate/commit/11568e562c4389291bd0c71c8a6b5d99c7705e7b. Do you have any idea on which change could result in the failure?

**Comment by muellerzr** [comment]
I think I have a guess, let me check on our latest refactor to see something

**Comment by muellerzr** [comment]
@vanbasten23 can you try on v0.29.2? (The latest pypi)

**Comment by muellerzr** [comment]
I think I put a fix in there for XLA

**Comment by vanbasten23** [comment]
I sync'd to v0.29.2 as well as HEAD, both work. Thanks a lot @muellerzr !
