### ISSUE TITLE
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cuda:1)

### ISSUE THREAD

**Issue by ChuanhongLi** [huggingface/accelerate#2656]
Hi, two GPUs are used for the Qwen1.5-7B-Chat deployment. The codes: 
```
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

import subprocess


def get_gpu_memory_usage(info):
    # 使用nvidia-smi命令获取显卡信息
    cmd = "nvidia-smi --query-gpu=memory.used --format=csv,nounits,noheader"
    result = subprocess.run(cmd, stdout=subprocess.PIPE, shell=True, encoding='utf-8')
    memory_used = result.stdout.strip().split('\n')
    print("[%s Memory Usage: %s]" % (info, ','.join(memory_used)))


def generate_text(model, input_text):
    # 编码输入文本
    input_ids = tokenizer.encode(input_text, return_tensors="pt").to(model.device)
    # 生成文本
    outputs = model.generate(input_ids, max_length=50)
    # 解码生成的文本
    generated_text = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return generated_text


if __name__ == '__main__':
    model_path = "/mnt/afs/data/model/open_source_data/Qwen/Qwen1.5-7B-Chat"
    bc_model = AutoModelForCausalLM.from_pretrained(
        model_path,
        # config=config,
        torch_dtype=torch.float16,
        low_cpu_mem_usage=True,
        trust_remote_code=True,
        # revision='main',
        device_map='auto'
    )

    if torch.cuda.device_count() > 1:
        from accelerate import dispatch_model
        from accelerate.utils import infer_auto_device_map, get_balanced_memory

        device_map = infer_auto_device_map(bc_model, max_memory=get_balanced_memory(bc_model))
        bc_model = dispatch_model(bc_model, device_map)
        print('multi GPU predict => {}'.format(device_map))
    else:
        bc_model = bc_model.cuda()
        print("single GPU predict")

    bc_model.eval()
    tokenizer = AutoTokenizer.from_pretrained(model_path)
    torch.set_grad_enabled(False)

    input_ids = '你是谁'
    # ids = tokenizer(sents, max_length=1800, padding=True, truncation=True, return_tensors="pt")
    # ids = ids.to(bc_model.device)
    # outputs = bc_model.generate(**ids, do_sample=False)
    outputs = generate_text(bc_model, input_ids)
    print("outputs: ", outputs)
```
I got some errors:
```
Traceback (most recent call last):
  File "load.py", line 60, in <module>
    outputs = generate_text(bc_model, input_ids)
  File "load.py", line 22, in generate_text
    outputs = model.generate(input_ids, max_length=50)
  File "/usr/local/lib/miniconda3/envs/rope/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/miniconda3/envs/rope/lib/python3.8/site-packages/transformers/generation/utils.py", line 1575, in generate
    result = self._sample(
  File "/usr/local/lib/miniconda3/envs/rope/lib/python3.8/site-packages/transformers/generation/utils.py", line 2697, in _sample
    outputs = self(
  File "/usr/local/lib/miniconda3/envs/rope/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/miniconda3/envs/rope/lib/python3.8/site-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/usr/local/lib/miniconda3/envs/rope/lib/python3.8/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 1173, in forward
    outputs = self.model(
  File "/usr/local/lib/miniconda3/envs/rope/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/miniconda3/envs/rope/lib/python3.8/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 1058, in forward
    layer_outputs = decoder_layer(
  File "/usr/local/lib/miniconda3/envs/rope/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/miniconda3/envs/rope/lib/python3.8/site-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/usr/local/lib/miniconda3/envs/rope/lib/python3.8/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 773, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/usr/local/lib/miniconda3/envs/rope/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/miniconda3/envs/rope/lib/python3.8/site-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/usr/local/lib/miniconda3/envs/rope/lib/python3.8/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 278, in forward
    query_states, key_states = apply_rotary_pos_emb(query_states, key_states, cos, sin, position_ids)
  File "/usr/local/lib/miniconda3/envs/rope/lib/python3.8/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 165, in apply_rotary_pos_emb
    cos = cos[position_ids].unsqueeze(unsqueeze_dim)
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cuda:1)
```
The accelerate version is 0.28.0.  Thanks for your help!!!

**Comment by SunMarc** [comment]
Hi @ChuanhongLi, you don't need to call `infer_auto_device_map` and `dispatch_model` since the model is already dispatched on multi gpu when you call `from_pretrained` with device_map='auto'. 
```python 
bc_model = AutoModelForCausalLM.from_pretrained(
        model_path,
        # config=config,
        torch_dtype=torch.float16,
        low_cpu_mem_usage=True,
        trust_remote_code=True,
        # revision='main',
        device_map='auto'
    )
```

**Comment by ChuanhongLi** [comment]
> multi gpu when you call `from_pretrained` with device_map='auto'.
> 
> ```python
> bc_model = AutoModelForCausalLM.from_pretrained(
> ```

Thanks！
