### ISSUE TITLE
Module 'glue' doesn't exist on the Hugging Face Hub either.

### ISSUE THREAD

**Issue by enori** [huggingface/accelerate#2668]
I am a beginner at Hugging Face.

I am trying to run "accelerate/examples/nlp_example.py", and this error happened.
What should I do to solve this error?

Thanks for your help and kindness!!

### System Info

```Shell
Traceback (most recent call last):
  File "/home/ubuntu/huggingface-accelerate/examples/nlp_example.py", line 229, in <module>
    main()
  File "/home/ubuntu/huggingface-accelerate/examples/nlp_example.py", line 225, in main
    training_function(config, args)
  File "/home/ubuntu/huggingface-accelerate/examples/nlp_example.py", line 142, in training_function
    metric = evaluate.load("glue", "mrpc")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/ray_tutorial/lib/python3.11/site-packages/evaluate/loading.py", line 748, in load
    evaluation_module = evaluation_module_factory(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/ray_tutorial/lib/python3.11/site-packages/evaluate/loading.py", line 681, in evaluation_module_factory
    raise FileNotFoundError(
FileNotFoundError: Couldn't find a module script at /home/ubuntu/huggingface-accelerate/glue/glue.py. Module 'glue' doesn't exist on the Hugging Face Hub either.
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/ray_tutorial/bin/accelerate", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ubuntu/miniconda3/envs/ray_tutorial/lib/python3.11/site-packages/accelerate/commands/accelerate_cli.py", line 46, in main
    args.func(args)
  File "/home/ubuntu/miniconda3/envs/ray_tutorial/lib/python3.11/site-packages/accelerate/commands/launch.py", line 1075, in launch_command
    simple_launcher(args)
  File "/home/ubuntu/miniconda3/envs/ray_tutorial/lib/python3.11/site-packages/accelerate/commands/launch.py", line 681, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/ubuntu/miniconda3/envs/ray_tutorial/bin/python3.11', 'examples/nlp_example.py']' returned non-zero exit status 1.
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

accelerate launch accelerate/examples/nlp_example.py

### Expected behavior

success to run program.

**Comment by muellerzr** [comment]
Most likely you have a folder named `glue` somewhere in the same directory as what you're launching out of, which is confusing the `evaluate.load`. (BTW this is an evaluate issue more than an accelerate issue: https://github.com/huggingface/evaluate)

**Comment by enori** [comment]
Thank you!
There are no folder named `glue`. 

```sh
$ tree | grep glue
```

I will ask the issue to https://github.com/huggingface/evaluate.
