### ISSUE TITLE
Fail to pass the accelerate test with mps as the device

### ISSUE THREAD

**Issue by JINNMnm** [huggingface/accelerate#2693]
### System Info

```Shell
- `Accelerate` version: 0.29.3
- Platform: macOS-14.1.1-arm64-arm-64bit
- `accelerate` bash location: /Users/jin/anaconda3/envs/openlrm/bin/accelerate
- Python version: 3.11.9
- Numpy version: 1.26.4
- PyTorch version (GPU?): 2.2.2 (False)
- PyTorch XPU available: False
- PyTorch NPU available: False
- PyTorch MLU available: False
- System RAM: 36.00 GB
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: NO
        - mixed_precision: no
        - use_cpu: False
        - debug: False
        - num_processes: 1
        - machine_rank: 0
        - num_machines: 1
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - enable_cpu_affinity: False
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

1. First i use 
```
accelerate config
```
with the choice below to generate the config file:
```
In which compute environment are you running?
This machine                                                                                                                                                                                       
Which type of machine are you using?                                                                                                                                                               
No distributed training                                                                                                                                                                            
Do you want to run your training on CPU only (even if a GPU / Apple Silicon / Ascend NPU device is available)? [yes/NO]:no                                                                         
Do you wish to optimize your script with torch dynamo?[yes/NO]:no                                                                                                                                  
Do you wish to use FP16 or BF16 (mixed precision)? 
no                                                                                                                                                                                                 
accelerate configuration saved at /Users/jin/.cache/huggingface/accelerate/default_config.yaml     
```
2. Then i try:
```
accelerate test
```
to test the environment but i got the error like this:
```
Running:  accelerate-launch /Users/jin/anaconda3/envs/openlrm/lib/python3.11/site-packages/accelerate/test_utils/scripts/test_script.py
stdout: **Initialization**
stdout: Testing, testing. 1, 2, 3.
stdout: Distributed environment: DistributedType.NO
stdout: Num processes: 1
stdout: Process index: 0
stdout: Local process index: 0
stdout: Device: mps
stdout: 
stdout: Mixed precision type: no
stdout: 
stdout: 
stdout: **Test process execution**
stdout: 
stdout: **Test split between processes as a list**
stdout: 
stdout: **Test split between processes as a dict**
stdout: 
stdout: **Test split between processes as a tensor**
stdout: 
stdout: **Test split between processes as a datasets.Dataset**
stdout: Skipped because Hugging Face datasets is not available
stdout: 
stdout: **Test random number generator synchronization**
stdout: All rng are properly synched.
stdout: 
stdout: **DataLoader integration test**
stdout: 0 tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
stdout:         18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31],
stdout:        device='mps:0') <class 'accelerate.data_loader.DataLoaderShard'>
stdout: Non-shuffled dataloader passing.
stdout: Shuffled dataloader passing.
stdout: Non-shuffled central dataloader passing.
stdout: Shuffled central dataloader passing.
stdout: 
stdout: **Training integration test**
stdout: Model dtype: torch.float32, torch.float32. Input dtype: torch.float32
stdout: Model dtype: torch.float32, torch.float32. Input dtype: torch.float32
stdout: Training yielded the same results on one CPU or distributed setup with no batch split.
stdout: Model dtype: torch.float32, torch.float32. Input dtype: torch.float32
stdout: Training yielded the same results on one CPU or distributes setup with batch split.
stdout: BF16 training check.
stderr: Traceback (most recent call last):
stderr:   File "/Users/jin/anaconda3/envs/openlrm/lib/python3.11/site-packages/accelerate/test_utils/scripts/test_script.py", line 802, in <module>
stderr:     main()
stderr:   File "/Users/jin/anaconda3/envs/openlrm/lib/python3.11/site-packages/accelerate/test_utils/scripts/test_script.py", line 789, in main
stderr:     training_check(use_seedable_sampler=False)
stderr:   File "/Users/jin/anaconda3/envs/openlrm/lib/python3.11/site-packages/accelerate/test_utils/scripts/test_script.py", line 527, in training_check
stderr:     train_dl, model, optimizer = accelerator.prepare(train_dl, model, optimizer)
stderr:                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
stderr:   File "/Users/jin/anaconda3/envs/openlrm/lib/python3.11/site-packages/accelerate/accelerator.py", line 1274, in prepare
stderr:     result = tuple(
stderr:              ^^^^^^
stderr:   File "/Users/jin/anaconda3/envs/openlrm/lib/python3.11/site-packages/accelerate/accelerator.py", line 1275, in <genexpr>
stderr:     self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
stderr:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
stderr:   File "/Users/jin/anaconda3/envs/openlrm/lib/python3.11/site-packages/accelerate/accelerator.py", line 1151, in _prepare_one
stderr:     return self.prepare_model(obj, device_placement=device_placement)
stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
stderr:   File "/Users/jin/anaconda3/envs/openlrm/lib/python3.11/site-packages/accelerate/accelerator.py", line 1341, in prepare_model
stderr:     autocast_context = get_mixed_precision_context_manager(self.native_amp, self.autocast_handler)
stderr:                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
stderr:   File "/Users/jin/anaconda3/envs/openlrm/lib/python3.11/site-packages/accelerate/utils/modeling.py", line 1796, in get_mixed_precision_context_manager
stderr:     return torch.autocast(device_type=device_type, dtype=torch.bfloat16, **autocast_kwargs)
stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
stderr:   File "/Users/jin/anaconda3/envs/openlrm/lib/python3.11/site-packages/torch/amp/autocast_mode.py", line 241, in __init__
stderr:     raise RuntimeError(
stderr: RuntimeError: User specified an unsupported autocast device_type 'mps'
stderr: Traceback (most recent call last):
stderr:   File "/Users/jin/anaconda3/envs/openlrm/bin/accelerate-launch", line 8, in <module>
stderr:     sys.exit(main())
stderr:              ^^^^^^
stderr:   File "/Users/jin/anaconda3/envs/openlrm/lib/python3.11/site-packages/accelerate/commands/launch.py", line 1081, in main
stderr:     launch_command(args)
stderr:   File "/Users/jin/anaconda3/envs/openlrm/lib/python3.11/site-packages/accelerate/commands/launch.py", line 1075, in launch_command
stderr:     simple_launcher(args)
stderr:   File "/Users/jin/anaconda3/envs/openlrm/lib/python3.11/site-packages/accelerate/commands/launch.py", line 681, in simple_launcher
stderr:     raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
stderr: subprocess.CalledProcessError: Command '['/Users/jin/anaconda3/envs/openlrm/bin/python3.11', '/Users/jin/anaconda3/envs/openlrm/lib/python3.11/site-packages/accelerate/test_utils/scripts/test_script.py']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/Users/jin/anaconda3/envs/openlrm/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/jin/anaconda3/envs/openlrm/lib/python3.11/site-packages/accelerate/commands/accelerate_cli.py", line 46, in main
    args.func(args)
  File "/Users/jin/anaconda3/envs/openlrm/lib/python3.11/site-packages/accelerate/commands/test.py", line 53, in test_command
    result = execute_subprocess_async(cmd)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jin/anaconda3/envs/openlrm/lib/python3.11/site-packages/accelerate/test_utils/testing.py", line 539, in execute_subprocess_async
    raise RuntimeError(
RuntimeError: 'accelerate-launch /Users/jin/anaconda3/envs/openlrm/lib/python3.11/site-packages/accelerate/test_utils/scripts/test_script.py' failed with returncode 1

The combined stderr from workers follows:
Traceback (most recent call last):
  File "/Users/jin/anaconda3/envs/openlrm/lib/python3.11/site-packages/accelerate/test_utils/scripts/test_script.py", line 802, in <module>
    main()
  File "/Users/jin/anaconda3/envs/openlrm/lib/python3.11/site-packages/accelerate/test_utils/scripts/test_script.py", line 789, in main
    training_check(use_seedable_sampler=False)
  File "/Users/jin/anaconda3/envs/openlrm/lib/python3.11/site-packages/accelerate/test_utils/scripts/test_script.py", line 527, in training_check
    train_dl, model, optimizer = accelerator.prepare(train_dl, model, optimizer)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jin/anaconda3/envs/openlrm/lib/python3.11/site-packages/accelerate/accelerator.py", line 1274, in prepare
    result = tuple(
             ^^^^^^
  File "/Users/jin/anaconda3/envs/openlrm/lib/python3.11/site-packages/accelerate/accelerator.py", line 1275, in <genexpr>
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jin/anaconda3/envs/openlrm/lib/python3.11/site-packages/accelerate/accelerator.py", line 1151, in _prepare_one
    return self.prepare_model(obj, device_placement=device_placement)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jin/anaconda3/envs/openlrm/lib/python3.11/site-packages/accelerate/accelerator.py", line 1341, in prepare_model
    autocast_context = get_mixed_precision_context_manager(self.native_amp, self.autocast_handler)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jin/anaconda3/envs/openlrm/lib/python3.11/site-packages/accelerate/utils/modeling.py", line 1796, in get_mixed_precision_context_manager
    return torch.autocast(device_type=device_type, dtype=torch.bfloat16, **autocast_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jin/anaconda3/envs/openlrm/lib/python3.11/site-packages/torch/amp/autocast_mode.py", line 241, in __init__
    raise RuntimeError(
RuntimeError: User specified an unsupported autocast device_type 'mps'
Traceback (most recent call last):
  File "/Users/jin/anaconda3/envs/openlrm/bin/accelerate-launch", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/jin/anaconda3/envs/openlrm/lib/python3.11/site-packages/accelerate/commands/launch.py", line 1081, in main
    launch_command(args)
  File "/Users/jin/anaconda3/envs/openlrm/lib/python3.11/site-packages/accelerate/commands/launch.py", line 1075, in launch_command
    simple_launcher(args)
  File "/Users/jin/anaconda3/envs/openlrm/lib/python3.11/site-packages/accelerate/commands/launch.py", line 681, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/Users/jin/anaconda3/envs/openlrm/bin/python3.11', '/Users/jin/anaconda3/envs/openlrm/lib/python3.11/site-packages/accelerate/test_utils/scripts/test_script.py']' returned non-zero exit status 1.
```

### Expected behavior

Why i can't use the mps as the device. It is noted that when i try
```
from accelerate import Accelerator
a = Accelerator()
a.device
```
and it output correctly.
```
device(type='mps')
```

**Comment by SunMarc** [comment]
Hi @JINNMnm, thanks for the report. This will be fixed once this [PR](https://github.com/huggingface/accelerate/pull/2699) is merged.

**Comment by JINNMnm** [comment]
Thanks for your amazing work!
