### ISSUE TITLE
accelerate launch increases allocated memory on all GPUs, not just GPU:0, by amount proportional to total number of available GPUs

### ISSUE THREAD

**Issue by jubueche** [huggingface/accelerate#2709]
### System Info

```Shell
- `Accelerate` version: 0.30.0.dev0
- Platform: Linux-3.10.0-1160.76.1.el7.x86_64-x86_64-with-glibc2.17
- Python version: 3.10.14
- Numpy version: 1.26.4
- PyTorch version (GPU?): 2.4.0.dev20240322 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- PyTorch MLU available: False
- System RAM: 755.37 GB
- GPU type: Tesla V100-SXM2-32GB
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

This code prints the used memory on every GPU after I initialise the `Accelerator` class, and after I synchronise the processes.
```
from pynvml import nvmlInit, nvmlDeviceGetHandleByIndex, nvmlDeviceGetMemoryInfo
from accelerate import Accelerator

def print_gpu_mem():
    nvmlInit()
    for i in range(8):
        h = nvmlDeviceGetHandleByIndex(i)
        info = nvmlDeviceGetMemoryInfo(h)
        print(
            f"GPU: {i} total:{info.total/1e9:.4f}GB | used:{info.used/1e9:.4f}GB | free:{info.free/1e9:.4f}GB"
        )

accelerator = Accelerator()
accelerator.wait_for_everyone()
print_gpu_mem()
```
Launching this with 
```
MKL_SERVICE_FORCE_INTEL=1 accelerate launch --multi_gpu --dynamo_backend no --mixed_precision fp16 --num_processes 8 --gpu_ids all --num_machines 1 test_mem.py
```
Shows me around 1.3GB of used data on each GPU. If I run it with only, say, 4 GPUs, I see a proportionally lower value.
Also, removing `accelerator.wait_for_everyone()` "solves" the problem, but I can't imagine this to be related to the torch barrier.

Since we are really maxing out the DRAM of our V100, we are getting an OOM down the road because of this small difference of extra used memory.

### Expected behavior

I would expect only GPU:0 to have allocated more memory proportional to the amount of GPUs we have.

**Comment by muellerzr** [comment]
*Some* amount is expected because torch will allocate this when initializing the distributed processes, and with CUDA, so they should be about the same on each device. It being proportional to each GPU is interesting however

**Comment by jubueche** [comment]
Can you also observe this? I am asking because my cluster has a pretty old Limux kernel (don't know if it could be related to that...). I am using CUDA 12.1

**Comment by jubueche** [comment]
Maybe somewhat unrelated: When I continue my training, it just crashes with batch size 1. Before, it was working with batch size 16 and I have no idea what changed inbetween.
I am running the script with 
```
ACCELERATE_LOG_LEVEL=DEBUG TORCH_CPP_LOG_LEVEL=INFO TORCH_DISTRIBUTED_DEBUG=DETAIL MKL_SERVICE_FORCE_INTEL=1 accelerate launch ...
```
But still, the error is not informative at all:

```
0%|          | 0/31083 [00:00<?, ?it/s]E0425 09:31:39.103000 140677603280768 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: -7) local_rank: 0 (pid: 46098) of binary: /gpfs/u/home/ANFM/ANFMbchl/scratch/miniconda3/envs/torch-nightly/bin/python
Traceback (most recent call last):
  File "/gpfs/u/home/ANFM/ANFMbchl/scratch/miniconda3/envs/torch-nightly/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/gpfs/u/home/ANFM/ANFMbchl/scratch/miniconda3/envs/torch-nightly/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 46, in main
    args.func(args)
  File "/gpfs/u/home/ANFM/ANFMbchl/scratch/miniconda3/envs/torch-nightly/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1073, in launch_command
    multi_gpu_launcher(args)
  File "/gpfs/u/home/ANFM/ANFMbchl/scratch/miniconda3/envs/torch-nightly/lib/python3.10/site-packages/accelerate/commands/launch.py", line 718, in multi_gpu_launcher
    distrib_run.run(args)
  File "/gpfs/u/home/ANFM/ANFMbchl/scratch/miniconda3/envs/torch-nightly/lib/python3.10/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/gpfs/u/home/ANFM/ANFMbchl/scratch/miniconda3/envs/torch-nightly/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/gpfs/u/home/ANFM/ANFMbchl/scratch/miniconda3/envs/torch-nightly/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
=====================================================
train.py FAILED
-----------------------------------------------------
Failures:
[1]:
  time      : 2024-04-25_09:31:39
  host      : npl13.ccni.rpi.edu
  rank      : 1 (local_rank: 1)
  exitcode  : -7 (pid: 46099)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 46099
...
...
```

**Comment by jubueche** [comment]
Ok, the above was most likely an OOM error due to [this](https://github.com/huggingface/transformers/issues/30500) issue.
