### ISSUE TITLE
checkpointing error when using IterableDataset and dispatch_batches=False

### ISSUE THREAD

**Issue by Fadelis98** [huggingface/accelerate#2718]
### System Info

```Shell
- `Accelerate` version: 0.29.1
- Platform: Linux-5.10.134-13.1.al8.x86_64-x86_64-with-glibc2.35
- `accelerate` bash location: /mnt/data/ai4phys/hugengyuan/miniconda3/envs/qec/bin/accelerate
- Python version: 3.11.8
- Numpy version: 1.26.4
- PyTorch version (GPU?): 2.2.2 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- PyTorch MLU available: False
- System RAM: 739.74 GB
- GPU type: NVIDIA GeForce RTX 3090
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: MULTI_GPU
        - mixed_precision: no
        - use_cpu: False
        - debug: True
        - num_processes: 4
        - machine_rank: 0
        - num_machines: 1
        - gpu_ids: all
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - enable_cpu_affinity: False
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

NOTE: The bug only happens for num_processes > 1
```python
from typing import Iterator
import torch
from torch.utils.data import IterableDataset,DataLoader

class FooSet(IterableDataset):
    def __iter__(self) -> Iterator:
        for i in range(100):
            yield i

from accelerate import Accelerator

def main():
    dset = FooSet()
    dloader = DataLoader(dset,batch_size=1)

    ac = Accelerator(
        dispatch_batches=False,
        split_batches=False,
    )

    dloader = ac.prepare(dloader)
    for data in dloader:
        ac.print(data)
        # anything else in a typical training script here
        ac.save_state('test_checkpoint')
        break
        
from accelerate import notebook_launcher

notebook_launcher(main,num_processes=2,)
```

It will raise the following error:
```
-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/mnt/data/ai4phys/hugengyuan/miniconda3/envs/qec/lib/python3.11/site-packages/torch/multiprocessing/spawn.py", line 68, in _wrap
    fn(i, *args)
  File "/mnt/data/ai4phys/hugengyuan/miniconda3/envs/qec/lib/python3.11/site-packages/accelerate/utils/launch.py", line 624, in __call__
    self.launcher(*args)
  File "/tmp/ipykernel_5768/3570394569.py", line 16, in main
    ac.save_state('test_checkpoint')
  File "/mnt/data/ai4phys/hugengyuan/miniconda3/envs/qec/lib/python3.11/site-packages/accelerate/accelerator.py", line 2825, in save_state
    save_location = save_accelerator_state(
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/ai4phys/hugengyuan/miniconda3/envs/qec/lib/python3.11/site-packages/accelerate/checkpointing.py", line 123, in save_accelerator_state
    sampler = dataloader.sampler.sampler
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: '_InfiniteConstantSampler' object has no attribute 'sampler'
```

### Expected behavior

checkpointing without any error

**Comment by SunMarc** [comment]
Hi @Fadelis98, this should be solved in the above PR !
