### ISSUE TITLE
replacing torch.utils.checkpoint with deepspeed.runtime.activation_checkpointing.checkpointing does not work

### ISSUE THREAD

**Issue by vkaul11** [huggingface/accelerate#2792]
### System Info

```Shell
- `Accelerate` version: 0.30.1
- Platform: Linux-6.5.0-1018-gcp-x86_64-with-glibc2.35
- `accelerate` bash location: /usr/local/bin/accelerate
- Python version: 3.10.12
- Numpy version: 1.26.4
- PyTorch version (GPU?): 2.3.0+cu121 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- PyTorch MLU available: False
- System RAM: 1338.60 GB
- GPU type: NVIDIA A100-SXM4-80GB
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: DEEPSPEED
        - use_cpu: False
        - debug: True
        - num_processes: 8
        - machine_rank: 0
        - num_machines: 1
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - enable_cpu_affinity: False
               - enable_cpu_affinity: False
        - deepspeed_config: {'deepspeed_config_file': 'zero_stage3_config.json', 
           'zero3_init_flag': True}
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []

and zero_stage3_config.json
{
     "zero_optimization": {
       "stage": 3,
       "stage3_gather_16bit_weights_on_model_save": true,
       "offload_optimizer": {
         "device": "none"
       },
       "offload_param": {
         "device": "none"
       }
     },
     "activation_checkpointing": {
       "partition_activations": true,
       "contiguous_memory_optimization": true,
       "cpu_checkpointing": true
     },
     "gradient_accumulation_steps": "auto",
     "train_batch_size": "auto",
     "train_micro_batch_size_per_gpu": "auto" 
 }
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

I wanted to use deepspeed activation checkpointing parameters
 ```
"activation_checkpointing": {
       "partition_activations": true,
       "contiguous_memory_optimization": true,
       "cpu_checkpointing": true
     },
```
in my accelerate job but I couldn't see those being used and in fact whether I used gradient_checkpointing parameter in my model config to be true or false I still use up same memory. That is why I wanted to try activation checkpointing from deepseed to avoid OOM errors. I followed the idea here https://github.com/huggingface/accelerate/issues/2160 and made the change https://github.com/huggingface/transformers/pull/30915
```
gradient_checkpointing: True
load_in_4bit: True
torch_dtype: bfloat16
bf16: True
```

### Expected behavior

I expected that this will run the accelerate job described after I made the change https://github.com/huggingface/transformers/pull/30915 to the checkpoint and pick up activation checking parameters so that I will not run into OOM issues when I train with bigger model and longer context. 
However instead I got this error based on the checkpoint change. Can you please help with this?
```
Traceback (most recent call last):
  File "/workspace/cookbook-internal/recipes/tune/instruct_lora/finetune.py", line 223, in _app
    trainer = train(
  File "/workspace/cookbook-internal/recipes/tune/common/trainer.py", line 156, in train
    trainer.train(resume_from_checkpoint=False)
  File "/workspace/cookbook-internal/transformers/src/transformers/trainer.py", line 1885, in train
    return inner_training_loop(
  File "/workspace/cookbook-internal/transformers/src/transformers/trainer.py", line 2216, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/workspace/cookbook-internal/transformers/src/transformers/trainer.py", line 3238, in training_step
    loss = self.compute_loss(model, inputs)
  File "/workspace/cookbook-internal/transformers/src/transformers/trainer.py", line 3264, in compute_loss
    outputs = model(**inputs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/engine.py", line 1855, in forward
    loss = self.module(*inputs, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1582, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/peft/peft_model.py", line 1083, in forward
    return self.base_model(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1582, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/peft/tuners/tuners_utils.py", line 161, in forward
    return self.model.forward(*args, **kwargs)
  File "/workspace/cookbook-internal/transformers/src/transformers/models/llama/modeling_llama.py", line 1164, in forward
    outputs = self.model(  
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1582, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/workspace/cookbook-internal/transformers/src/transformers/models/llama/modeling_llama.py", line 957, in forward
    layer_outputs = self._gradient_checkpointing_func(
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 995, in
 checkpoint
    CheckpointFunction.apply(function, all_outputs, *args)
  File "/usr/local/lib/python3.10/dist-packages/torch/autograd/function.py", line 598, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 566, in
 forward
    outputs = run_function(*inputs_cuda)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1582, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/workspace/cookbook-internal/transformers/src/transformers/models/llama/modeling_llama.py", line 713, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1582, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/workspace/cookbook-internal/transformers/src/transformers/models/llama/modeling_llama.py", line 414, in forward
    bsz, q_len, _ = hidden_states.size()
ValueError: not enough values to unpack (expected 3, got 2)
```

**Comment by muellerzr** [comment]
This is an issue with deepspeed, it seems it changes how the model returns things when checkpointing is activated somehow

**Comment by vkaul11** [comment]
@muellerzr do you recommend using reentrant = False or reentrant = True and how do you set it? I don't know if not setting it to False causes such issues?
