### ISSUE TITLE
RuntimeError: Expected is_sm80 || is_sm90 to be true, but got false.

### ISSUE THREAD

**Issue by mostafamdy** [huggingface/accelerate#2799]
### System Info

```Shell
Hi
I got this error when trying to run '!accelerate launch file.py' in kaggle GPU T4x2
RuntimeError: Expected is_sm80 || is_sm90 to be true, but got false.

full logs
Traceback (most recent call last):
  File "/kaggle/working/file.py", line 151, in <module>
Traceback (most recent call last):
  File "/kaggle/working/file.py", line 151, in <module>
    trainer.train()
  File "/opt/conda/lib/python3.10/site-packages/trl/trainer/sft_trainer.py", line 323, in train
    trainer.train()
  File "/opt/conda/lib/python3.10/site-packages/trl/trainer/sft_trainer.py", line 323, in train
    output = super().train(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 1537, in train
    output = super().train(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 1537, in train
    return inner_training_loop(    
return inner_training_loop(
  File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 1854, in _inner_training_loop
  File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 1854, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 2744, in training_step
    tr_loss_step = self.training_step(model, inputs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 2744, in training_step
    self.accelerator.backward(loss)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/accelerator.py", line 1962, in backward
    self.accelerator.backward(loss)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/accelerator.py", line 1962, in backward
    self.scaler.scale(loss).backward(**kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_tensor.py", line 492, in backward
    self.scaler.scale(loss).backward(**kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_tensor.py", line 492, in backward
        torch.autograd.backward(torch.autograd.backward(

  File "/opt/conda/lib/python3.10/site-packages/torch/autograd/__init__.py", line 251, in backward
  File "/opt/conda/lib/python3.10/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Expected is_sm80 || is_sm90 to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Expected is_sm80 || is_sm90 to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

.

### Expected behavior

.

**Comment by muellerzr** [comment]
Can you please share your code? I've never seen an error like this before. 

Also can you make sure your code works on a single GPU?

**Comment by mostafamdy** [comment]
Here is the code. it's working on single GPU

the error raise when run `accelerate launch file.py`
```
import numpy as np
import pandas as pd
import os
from tqdm import tqdm
import bitsandbytes as bnb
import torch
import torch.nn as nn
import transformers
from datasets import Dataset
from peft import LoraConfig, PeftConfig
from trl import SFTTrainer
from trl import setup_chat_format
from transformers import (AutoModelForCausalLM, 
                          AutoTokenizer, 
                          BitsAndBytesConfig, 
                          TrainingArguments, 
                          pipeline, 
                          logging)
from sklearn.metrics import (accuracy_score, 
                             classification_report, 
                             confusion_matrix)
from sklearn.model_selection import train_test_split

print(f"pytorch version {torch.__version__}")
import os

from accelerate import PartialState
device_string = PartialState().process_index
print(f"working on {device_string}")

model_name = "deepseek-ai/deepseek-math-7b-base"

compute_dtype = getattr(torch, "float16")

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True, 
    bnb_4bit_quant_type="nf4", 
    bnb_4bit_compute_dtype=compute_dtype,
    bnb_4bit_use_double_quant=True,
)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    device_map={'':device_string},
    torch_dtype=compute_dtype,
    quantization_config=bnb_config, 
)

model.config.use_cache = False
model.config.pretraining_tp = 1

tokenizer = AutoTokenizer.from_pretrained(model_name, 
                                          trust_remote_code=True,
                                         )

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

model, tokenizer = setup_chat_format(model, tokenizer)

output_dir="trained_weigths"

peft_config = LoraConfig(
        lora_alpha=16, 
        lora_dropout=0.1,
        r=64,
        bias="none",
        target_modules="all-linear",
        task_type="CAUSAL_LM",
)

training_arguments = TrainingArguments(
    output_dir=output_dir,                    # directory to save and repository id
    num_train_epochs=3,                       # number of training epochs
    per_device_train_batch_size=1,            # batch size per device during training
    gradient_accumulation_steps=4,            # number of steps before performing a backward/update pass
    gradient_checkpointing=True,              # use gradient checkpointing to save memory
    gradient_checkpointing_kwargs={'use_reentrant':False},
    save_steps=50,
    logging_steps=30,                         # log every 10 steps
    learning_rate=2e-4,                       # learning rate, based on QLoRA paper
    weight_decay=0.001,
    fp16=True,
    bf16=False,
    max_grad_norm=0.3,                        # max gradient norm based on QLoRA paper
    max_steps=500,
    warmup_ratio=0.03,                        # warmup ratio based on QLoRA paper
    group_by_length=True,
    lr_scheduler_type="cosine",               # use cosine learning rate scheduler
    report_to="tensorboard",                  # report metrics to tensorboard
    evaluation_strategy="steps",#"epoch",              # save checkpoint every epoch
    eval_steps=50,
    save_total_limit=1,
    load_best_model_at_end=True,
    per_device_eval_batch_size=1,
)

trainer = SFTTrainer(
    model=model,
    args=training_arguments,
    train_dataset=train_data,
    eval_dataset=valid_data,
    peft_config=peft_config,
    dataset_text_field="text",
    tokenizer=tokenizer,
    max_seq_length=1024,
    packing=True,
    neftune_noise_alpha=5,
)
import gc
for _ in range(100):
    torch.cuda.empty_cache()
    gc.collect()
def print_trainable_parameters(model):
    trainable_params = 0
    all_param = 0
    for _, param in model.named_parameters():
        all_param += param.numel()
        if param.requires_grad:
            trainable_params += param.numel()
    print(
        f"trainable params: {trainable_params} || all params: {all_param} || trainable%: {100 * trainable_params / all_param}"
    )
    
print_trainable_parameters(trainer.model)
# Train model
trainer.train()
```

**Comment by muellerzr** [comment]
What is the output of `accelerate env`?

**Comment by mostafamdy** [comment]
- `Accelerate` version: 0.26.1
- Platform: Linux-5.15.133+-x86_64-with-glibc2.35
- Python version: 3.10.12
- Numpy version: 1.23.5
- PyTorch version (GPU?): 2.1.2+cu121 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 31.36 GB
- GPU type: Tesla T4
- `Accelerate` default config:
	Not found

**Comment by mostafamdy** [comment]
> Looks like you should try disabling flash attention: [pytorch/pytorch#98140](https://github.com/pytorch/pytorch/issues/98140)

Thanks but do you know how we can do this? in transformer

**Comment by ArthurinRUC** [comment]
> Thanks but do you know how we can do this? in transformer

Check `model.config._attn_implementation` to find the attention method. By default SDPA will be used for torch>=2.1.1, so if you get "sdpa", that may cause your problem.

Try setting like this to disable flash attention:

```diff
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    device_map={'':device_string},
    torch_dtype=compute_dtype,
    quantization_config=bnb_config,
+   attn_implementation="eager",
)
```
