### ISSUE TITLE
Crash with fp16 in pytorch 1.11

### ISSUE THREAD

**Issue by miquelmarti** [huggingface/accelerate#281]
Crash due to new signature of `autocast.__exit__()` in pytorch 1.11

See below, now args are required:
https://github.com/pytorch/pytorch/compare/v1.10.0...v1.11.0#diff-688be417042a389cd06bdaa4f45d527c522ea010ced0b08282d0b5e55332497fL179

Error:
```
Traceback (most recent call last):
 File "/Midgard/home/mrabadan/anaconda3/envs/multitask/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/Midgard/home/mrabadan/anaconda3/envs/multitask/lib/python3.8/site-packages/accelerate/accelerator.py", line 573, in autocast
    autocast_context.__exit__()
TypeError: __exit__() missing 3 required positional arguments: 'exc_type', 'exc_val', and 'exc_tb'
```

**Comment by sgugger** [comment]
Could you explain how you got this error? Executing a few examples with mixed precision with PyTorch 1.11 and I didn't get it.

**Comment by miquelmarti** [comment]
I run as `pytorch -m torch.distributed.run myscript` and I set the `fp16` argument in the Accelerator to true. Using master.

**Comment by sgugger** [comment]
Like I said, I have no problem with this, so I need a clear reproducer to be able to help.

**Comment by miquelmarti** [comment]
There you go. Tried on three different machines with fresh installs.

Minimal conda env:
```
name: test
channels:
  - pytorch
dependencies:
  - cudatoolkit=11.3
  - pip
  - pytorch
  - pip:
    - accelerate
    - packaging
```

Example script to reproduce:
```python
import torch
import accelerate

accelerator = accelerate.Accelerator(fp16=True)

a = torch.ones((2,10)).cuda()
criterion = torch.nn.CrossEntropyLoss()

with accelerator.autocast():
    out = criterion(a,a)
```

Result:
```
Traceback (most recent call last):
  File "/home/miquelmr/multitask/test2.py", line 10, in <module>
    out = criterion(a,a)
  File "/home/miquelmr/miniconda3/envs/test/lib/python3.9/contextlib.py", line 126, in __exit__
    next(self.gen)
  File "/home/miquelmr/miniconda3/envs/test/lib/python3.9/site-packages/accelerate/accelerator.py", line 573, in autocast
    autocast_context.__exit__()
TypeError: __exit__() missing 3 required positional arguments: 'exc_type', 'exc_val', and 'exc_tb'
```

**Comment by sgugger** [comment]
Thanks a lot, I understand the problem now! Will fix this today.
