### ISSUE TITLE
accelerate 0.33 can crash when initializing Accelerator object on torch 2.1

### ISSUE THREAD

**Issue by iXce** [huggingface/accelerate#2954]
### System Info

```Shell
When using a CPU device, this line of this change: https://github.com/huggingface/accelerate/commit/c6da9f869390e5ae09f25c7ed6cbc937f75eda99#diff-e54d1f9cdd342420827fcabd4280eceb68da266c9ca6df120d0432c6f6f2e10aR795
assumes that `torch.cpu.set_device` is defined, which is only true starting torch 2.2. This breaks on torch 2.1
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

- Install torch 2.1 and accelerate 0.33
- Run:
```
MASTER_ADDR=127.0.0.1 MASTER_PORT=41994 LOCAL_RANK=0 python -c "import accelerate; accelerate.Accelerator()"
```

Witness:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/world/envs/cf/lib/python3.10/site-packages/accelerate/accelerator.py", line 383, in __init__
    self.state = AcceleratorState(
  File "/world/envs/cf/lib/python3.10/site-packages/accelerate/state.py", line 846, in __init__
    PartialState(cpu, **kwargs)
  File "/world/envs/cf/lib/python3.10/site-packages/accelerate/state.py", line 275, in __init__
    self.set_device()
  File "/world/envs/cf/lib/python3.10/site-packages/accelerate/state.py", line 786, in set_device
    device_module.set_device(self.device)
AttributeError: module 'torch.cpu' has no attribute 'set_device'. Did you mean: '_device'?
```

This passes gracefully with accelerate 0.32

### Expected behavior

Not crashing on torch 2.1 (behavior of accelerate 0.32)

**Comment by fuyb1992** [comment]
this works for me accelerate 0.32
