### ISSUE TITLE
How to run Vision Model(Like llava) based on pippy?

### ISSUE THREAD

**Issue by JerryLu991223** [huggingface/accelerate#2956]
Currently I tried to apply model parallelism based on pippy and I refer to the given example,

```
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from accelerate import PartialState, prepare_pippy

model = AutoModelForCausalLM.from_pretrained(
    "meta-llama/Llama-2-7b-chat-hf", low_cpu_mem_usage=True, attn_implementation="sdpa"
)
model.eval()

tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-2-7b-chat-hf")
prompts = ("I would like to", "I really like to", "The weather is pretty")  # bs = 3
tokenizer.pad_token = tokenizer.eos_token
inputs = tokenizer(prompts, return_tensors="pt", padding=True)

model = prepare_pippy(model, split_points="auto", example_kwargs=inputs)

inputs = inputs.to(0)
with torch.no_grad():
    output = model(**inputs)

if PartialState().is_last_process:
    next_token_logits = output[0][:, -1, :]
    next_token = torch.argmax(next_token_logits, dim=-1)
    print(tokenizer.batch_decode(next_token))
```
    
  But I don't know how to convert it to the vision-model sample. Currently, my code is:

```
import requests
from PIL import Image
from accelerate import Accelerator, load_checkpoint_and_dispatch, init_empty_weights
import torch
import torch.distributed as dist
from transformers import AutoProcessor, LlavaForConditionalGeneration, LlavaNextForConditionalGeneration, LlavaNextProcessor
from accelerate import PartialState, prepare_pippy
from transformers.models.auto.tokenization_auto import AutoTokenizer

if __name__ == "__main__":

    model_id = "llava-hf/llava-v1.6-mistral-7b-hf"
    prompt = "USER: <image>\nWhat are these?\nASSISTANT:"
    image_file = "http://images.cocodataset.org/val2017/000000039769.jpg"
    raw_image = Image.open(requests.get(image_file, stream=True).raw)

    model = LlavaNextForConditionalGeneration.from_pretrained(
        model_id, 
        torch_dtype=torch.float16, 
        low_cpu_mem_usage=True
    )
    model.eval()

    processor = LlavaNextProcessor.from_pretrained(model_id)
    inputs = processor(prompt, raw_image, return_tensors='pt')

    model = prepare_pippy(model, split_points="auto", example_kwargs=inputs)
    inputs = inputs.to(0)

    with torch.no_grad():
        output = model(**inputs)
    if PartialState().is_last_process:
        print(processor.decode(output[0][2:], skip_special_tokens=True))
```
and I get the error below:

accelerate launch --num_processes 2 llava/accelerate/pipeline_inference.py 

```
The following values were not passed to `accelerate launch` and had defaults used instead:
                More than one GPU was found, enabling multi-GPU training.
                If this was unintended please pass in `--num_processes=1`.
        `--num_machines` was set to a value of `1`
        `--mixed_precision` was set to a value of `'no'`
        `--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00,  9.15it/s]
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00,  6.01it/s]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...

[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1764, in run_node
[rank0]:     return node.target(*args, **kwargs)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/__init__.py", line 470, in sym_int
[rank0]:     return math.floor(a) if a >= 0 else math.ceil(a)  # type: ignore[arg-type, call-overload]
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/__init__.py", line 376, in __bool__
[rank0]:     return self.node.bool_()
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/fx/experimental/sym_node.py", line 432, in bool_
[rank0]:     return self.guard_bool("", 0)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/fx/experimental/sym_node.py", line 374, in guard_bool
[rank0]:     r = self.shape_env.evaluate_expr(self.expr, self.hint, fx_node=self.fx_node)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/fx/experimental/recording.py", line 231, in wrapper
[rank0]:     return fn(*args, **kwargs)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/fx/experimental/symbolic_shapes.py", line 4138, in evaluate_expr
[rank0]:     raise self._make_data_dependent_error(
[rank0]: torch.fx.experimental.symbolic_shapes.GuardOnDataDependentSymNode: Could not guard on data-dependent expression u1*Min(336/u0, 672/u1) >= 0 (unhinted: u1*Min(336/u0, 672/u1) >= 0).  (Size-like symbols: none)

[rank0]: Potential framework code culprit (scroll up for full backtrace):
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1764, in run_node
[rank0]:     return node.target(*args, **kwargs)

[rank0]: For more information, run with TORCH_LOGS="dynamic"
[rank0]: For extended logs when we create symbols, also add TORCHDYNAMO_EXTENDED_DEBUG_CREATE_SYMBOL="u1,u0"
[rank0]: If you suspect the guard was triggered from C++, add TORCHDYNAMO_EXTENDED_DEBUG_CPP=1
[rank0]: For more debugging help, see https://docs.google.com/document/d/1HSuTTVvYH1pTew89Rtpeu84Ht3nQEFTYhAX3Ypa_xJs/edit?usp=sharing

[rank0]: User Stack (most recent call last):
[rank0]:   (snipped, see stack below for prefix)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/transformers/models/llava_next/modeling_llava_next.py", line 766, in forward
[rank0]:     image_num_patches = [
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/transformers/models/llava_next/modeling_llava_next.py", line 767, in <listcomp>
[rank0]:     image_size_to_num_patches(
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/transformers/models/llava_next/modeling_llava_next.py", line 102, in image_size_to_num_patches
[rank0]:     best_resolution = select_best_resolution(image_size, grid_pinpoints)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/transformers/image_processing_utils.py", line 276, in select_best_resolution
[rank0]:     downscaled_width, downscaled_height = int(original_width * scale), int(original_height * scale)


[rank0]: The above exception was the direct cause of the following exception:

[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1656, in get_fake_value
[rank0]:     ret_val = wrap_fake_exception(
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1190, in wrap_fake_exception
[rank0]:     return fn()
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1657, in <lambda>
[rank0]:     lambda: run_node(tx.output, node, args, kwargs, nnmodule)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1782, in run_node
[rank0]:     raise RuntimeError(make_error_message(e)).with_traceback(
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1764, in run_node
[rank0]:     return node.target(*args, **kwargs)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/__init__.py", line 470, in sym_int
[rank0]:     return math.floor(a) if a >= 0 else math.ceil(a)  # type: ignore[arg-type, call-overload]
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/__init__.py", line 376, in __bool__
[rank0]:     return self.node.bool_()
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/fx/experimental/sym_node.py", line 432, in bool_
[rank0]:     return self.guard_bool("", 0)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/fx/experimental/sym_node.py", line 374, in guard_bool
[rank0]:     r = self.shape_env.evaluate_expr(self.expr, self.hint, fx_node=self.fx_node)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/fx/experimental/recording.py", line 231, in wrapper
[rank0]:     return fn(*args, **kwargs)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/fx/experimental/symbolic_shapes.py", line 4138, in evaluate_expr
[rank0]:     raise self._make_data_dependent_error(
[rank0]: RuntimeError: Failed running call_function <function sym_int at 0x7f05816af250>(*(u1*Min(336/u0, 672/u1),), **{}):
[rank0]: Could not guard on data-dependent expression u1*Min(336/u0, 672/u1) >= 0 (unhinted: u1*Min(336/u0, 672/u1) >= 0).  (Size-like symbols: none)

[rank0]: Potential framework code culprit (scroll up for full backtrace):
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1764, in run_node
[rank0]:     return node.target(*args, **kwargs)

[rank0]: For more information, run with TORCH_LOGS="dynamic"
[rank0]: For extended logs when we create symbols, also add TORCHDYNAMO_EXTENDED_DEBUG_CREATE_SYMBOL="u1,u0"
[rank0]: If you suspect the guard was triggered from C++, add TORCHDYNAMO_EXTENDED_DEBUG_CPP=1
[rank0]: For more debugging help, see https://docs.google.com/document/d/1HSuTTVvYH1pTew89Rtpeu84Ht3nQEFTYhAX3Ypa_xJs/edit?usp=sharing

[rank0]: User Stack (most recent call last):
[rank0]:   (snipped, see stack below for prefix)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/transformers/models/llava_next/modeling_llava_next.py", line 766, in forward
[rank0]:     image_num_patches = [
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/transformers/models/llava_next/modeling_llava_next.py", line 767, in <listcomp>
[rank0]:     image_size_to_num_patches(
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/transformers/models/llava_next/modeling_llava_next.py", line 102, in image_size_to_num_patches
[rank0]:     best_resolution = select_best_resolution(image_size, grid_pinpoints)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/transformers/image_processing_utils.py", line 276, in select_best_resolution
[rank0]:     downscaled_width, downscaled_height = int(original_width * scale), int(original_height * scale)


[rank0]: During handling of the above exception, another exception occurred:

[rank0]: Traceback (most recent call last):
[rank0]:   File "/mnt/data/workspace/LLM/llava/accelerate/pipeline_inference.py", line 32, in <module>
[rank0]:     model = prepare_pippy(model, split_points="auto", example_kwargs=inputs)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/accelerate/inference.py", line 173, in prepare_pippy
[rank0]:     stage = build_pipeline(model, split_points, example_args, example_kwargs, num_chunks)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/accelerate/inference.py", line 94, in build_pipeline
[rank0]:     pipe = Pipe.from_tracing(model, num_chunks=num_chunks, example_args=args, example_kwargs=kwargs)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/pippy/IR.py", line 1067, in from_tracing
[rank0]:     traced = Pipe._trace_with_export(
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/pippy/IR.py", line 1015, in _trace_with_export
[rank0]:     traced: torch.fx.GraphModule = _export_to_torch_ir(
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/export/_trace.py", line 347, in _export_to_torch_ir
[rank0]:     gm_torch_level, _ = torch._dynamo.export(
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 1311, in inner
[rank0]:     result_traced = opt_f(*args, **kwargs)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 451, in _fn
[rank0]:     return fn(*args, **kwargs)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 921, in catch_errors
[rank0]:     return callback(frame, cache_entry, hooks, frame_state, skip=1)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 400, in _convert_frame_assert
[rank0]:     return _compile(
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/contextlib.py", line 79, in inner
[rank0]:     return func(*args, **kwds)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 676, in _compile
[rank0]:     guarded_code = compile_inner(code, one_graph, hooks, transform)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 262, in time_wrapper
[rank0]:     r = func(*args, **kwargs)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 535, in compile_inner
[rank0]:     out_code = transform_code_object(code, transform)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 1036, in transform_code_object
[rank0]:     transformations(instructions, code_options)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 165, in _fn
[rank0]:     return fn(*args, **kwargs)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 500, in transform
[rank0]:     tracer.run()
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2149, in run
[rank0]:     super().run()
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 810, in run
[rank0]:     and self.step()
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 773, in step
[rank0]:     getattr(self, inst.opname)(inst)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 489, in wrapper
[rank0]:     return inner_fn(self, inst)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1219, in CALL_FUNCTION
[rank0]:     self.call_function(fn, args, {})
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 674, in call_function
[rank0]:     self.push(fn.call_function(self, args, kwargs))
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 90, in call_function
[rank0]:     return tx.inline_user_function_return(
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 680, in inline_user_function_return
[rank0]:     return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2285, in inline_call
[rank0]:     return cls.inline_call_(parent, func, args, kwargs)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2399, in inline_call_
[rank0]:     tracer.run()
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 810, in run
[rank0]:     and self.step()
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 773, in step
[rank0]:     getattr(self, inst.opname)(inst)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 489, in wrapper
[rank0]:     return inner_fn(self, inst)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1272, in CALL_FUNCTION_KW
[rank0]:     self.call_function(fn, args, kwargs)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 674, in call_function
[rank0]:     self.push(fn.call_function(self, args, kwargs))
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 289, in call_function
[rank0]:     return super().call_function(tx, args, kwargs)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 90, in call_function
[rank0]:     return tx.inline_user_function_return(
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 680, in inline_user_function_return
[rank0]:     return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2285, in inline_call
[rank0]:     return cls.inline_call_(parent, func, args, kwargs)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2399, in inline_call_
[rank0]:     tracer.run()
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 810, in run
[rank0]:     and self.step()
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 773, in step
[rank0]:     getattr(self, inst.opname)(inst)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 489, in wrapper
[rank0]:     return inner_fn(self, inst)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1219, in CALL_FUNCTION
[rank0]:     self.call_function(fn, args, {})
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 674, in call_function
[rank0]:     self.push(fn.call_function(self, args, kwargs))
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 289, in call_function
[rank0]:     return super().call_function(tx, args, kwargs)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 90, in call_function
[rank0]:     return tx.inline_user_function_return(
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 680, in inline_user_function_return
[rank0]:     return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2285, in inline_call
[rank0]:     return cls.inline_call_(parent, func, args, kwargs)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2399, in inline_call_
[rank0]:     tracer.run()
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 810, in run
[rank0]:     and self.step()
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 773, in step
[rank0]:     getattr(self, inst.opname)(inst)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 489, in wrapper
[rank0]:     return inner_fn(self, inst)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1219, in CALL_FUNCTION
[rank0]:     self.call_function(fn, args, {})
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 674, in call_function
[rank0]:     self.push(fn.call_function(self, args, kwargs))
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/variables/builtin.py", line 656, in call_function
[rank0]:     out = wrap_fx_proxy(
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/variables/builder.py", line 1330, in wrap_fx_proxy
[rank0]:     return wrap_fx_proxy_cls(target_cls=TensorVariable, **kwargs)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/variables/builder.py", line 1415, in wrap_fx_proxy_cls
[rank0]:     example_value = get_fake_value(proxy.node, tx, allow_non_graph_fake=True)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1704, in get_fake_value
[rank0]:     raise UserError(  # noqa: TRY200
[rank0]: torch._dynamo.exc.UserError: Tried to use data-dependent value in the subsequent computation. This can happen when we encounter unbounded dynamic value that is unknown during tracing time.  You will need to explicitly give hint to the compiler. Please take a look at constrain_as_value OR constrain_as_size APIs.  Could not guard on data-dependent expression u1*Min(336/u0, 672/u1) >= 0 (unhinted: u1*Min(336/u0, 672/u1) >= 0).  (Size-like symbols: none)

[rank0]: Potential framework code culprit (scroll up for full backtrace):
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1764, in run_node
[rank0]:     return node.target(*args, **kwargs)

[rank0]: For more information, run with TORCH_LOGS="dynamic"
[rank0]: For extended logs when we create symbols, also add TORCHDYNAMO_EXTENDED_DEBUG_CREATE_SYMBOL="u1,u0"
[rank0]: If you suspect the guard was triggered from C++, add TORCHDYNAMO_EXTENDED_DEBUG_CPP=1
[rank0]: For more debugging help, see https://docs.google.com/document/d/1HSuTTVvYH1pTew89Rtpeu84Ht3nQEFTYhAX3Ypa_xJs/edit?usp=sharing

[rank0]: User Stack (most recent call last):
[rank0]:   (snipped, see stack below for prefix)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/transformers/models/llava_next/modeling_llava_next.py", line 766, in forward
[rank0]:     image_num_patches = [
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/transformers/models/llava_next/modeling_llava_next.py", line 767, in <listcomp>
[rank0]:     image_size_to_num_patches(
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/transformers/models/llava_next/modeling_llava_next.py", line 102, in image_size_to_num_patches
[rank0]:     best_resolution = select_best_resolution(image_size, grid_pinpoints)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/transformers/image_processing_utils.py", line 276, in select_best_resolution
[rank0]:     downscaled_width, downscaled_height = int(original_width * scale), int(original_height * scale)

[rank0]: For more information about this error, see: https://pytorch.org/docs/main/generated/exportdb/index.html#constrain-as-size-example

[rank0]: from user code:
[rank0]:    File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/transformers/models/llava_next/modeling_llava_next.py", line 766, in forward
[rank0]:     image_num_patches = [
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/transformers/models/llava_next/modeling_llava_next.py", line 767, in <listcomp>
[rank0]:     image_size_to_num_patches(
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/transformers/models/llava_next/modeling_llava_next.py", line 102, in image_size_to_num_patches
[rank0]:     best_resolution = select_best_resolution(image_size, grid_pinpoints)
[rank0]:   File "/home/zhenghao-lu/anaconda3/envs/vllm/lib/python3.10/site-packages/transformers/image_processing_utils.py", line 276, in select_best_resolution
[rank0]:     downscaled_width, downscaled_height = int(original_width * scale), int(original_height * scale)

[rank0]: Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
```

May you please provide me a complete example for that? Thanks a lot!

**Comment by BenjaminBossan** [comment]
I have no experience with PiPPy but from the error, it looks like the compilation step is failing for this model architecture. Therefore, I don't think this can be fixed from the accelerate side of things. It appears that [this open issue](https://github.com/huggingface/transformers/issues/29891) is about compiling Llava.
