### ISSUE TITLE
Pippy example error: torch._dynamo.exc.Unsupported: call_method UserDefinedObjectVariable(Logger) warning_once [ConstantVariable()] {}

### ISSUE THREAD

**Issue by hchings** [huggingface/accelerate#2987]
### System Info

```Shell
torch: 2.4.0
python: 3.10.12
accelerate: 0.33.0
accelerate config:
- Platform: Linux-5.15.0-88-generic-x86_64-with-glibc2.35
- `accelerate` bash location: /usr/local/bin/accelerate
- Python version: 3.10.12
- Numpy version: 1.24.4
- PyTorch XPU available: False
- PyTorch NPU available: False
- PyTorch MLU available: False
- PyTorch MUSA available: False
- System RAM: 1007.68 GB
- GPU type: NVIDIA A100 80GB PCIe
- `Accelerate` default config:
	Not found
GPU: 4 X A100 80GB
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Clone and setup this `pippy/llama` example: https://github.com/huggingface/accelerate/blob/288accc0ec3321932a494f3a2aea262c58c55e44/examples/inference/pippy/llama.py
2. `accelerate launch --num_processes 4 ./llama.py`
3. Error occurs after checkpoints are loaded. It seems that there's a custom logger function `warn_once` that's not compatible with dynamo:

```
[rank2]: Traceback (most recent call last):
....
[rank2]:     model = prepare_pippy(model, split_points="auto", example_kwargs=inputs)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/accelerate/inference.py", line 173, in prepare_pippy
[rank2]:     stage = build_pipeline(model, split_points, example_args, example_kwargs, num_chunks)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/accelerate/inference.py", line 94, in build_pipeline
[rank2]:     pipe = Pipe.from_tracing(model, num_chunks=num_chunks, example_args=args, example_kwargs=kwargs)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/pippy/IR.py", line 1067, in from_tracing
[rank2]:     traced = Pipe._trace_with_export(
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/pippy/IR.py", line 1015, in _trace_with_export
[rank2]:     traced: torch.fx.GraphModule = _export_to_torch_ir(
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/export/_trace.py", line 430, in _export_to_torch_ir
[rank2]:     gm_torch_level, _ = torch._dynamo.export(
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/eval_frame.py", line 1237, in inner
[rank2]:     result_traced = opt_f(*args, **kwargs)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank2]:     return self._call_impl(*args, **kwargs)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank2]:     return forward_call(*args, **kwargs)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/eval_frame.py", line 410, in _fn
[rank2]:     return fn(*args, **kwargs)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank2]:     return self._call_impl(*args, **kwargs)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank2]:     return forward_call(*args, **kwargs)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 942, in catch_errors
[rank2]:     return callback(frame, cache_entry, hooks, frame_state, skip=1)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 402, in _convert_frame_assert
[rank2]:     return _compile(
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/_utils_internal.py", line 70, in wrapper_function
[rank2]:     return function(*args, **kwargs)
[rank2]:   File "/usr/lib/python3.10/contextlib.py", line 79, in inner
[rank2]:     return func(*args, **kwds)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 689, in _compile
[rank2]:     guarded_code = compile_inner(code, one_graph, hooks, transform)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/utils.py", line 265, in time_wrapper
[rank2]:     r = func(*args, **kwargs)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 544, in compile_inner
[rank2]:     out_code = transform_code_object(code, transform)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/bytecode_transformation.py", line 1103, in transform_code_object
[rank2]:     transformations(instructions, code_options)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 166, in _fn
[rank2]:     return fn(*args, **kwargs)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 506, in transform
[rank2]:     tracer.run()
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 2197, in run
[rank2]:     super().run()
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 847, in run
[rank2]:     while self.step():
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 757, in step
[rank2]:     self.dispatch_table[inst.opcode](self, inst)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 481, in wrapper
[rank2]:     return inner_fn(self, inst)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 1281, in CALL_FUNCTION_KW
[rank2]:     self.call_function(fn, args, kwargs)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 697, in call_function
[rank2]:     self.push(fn.call_function(self, args, kwargs))
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/variables/nn_module.py", line 351, in call_function
[rank2]:     return tx.inline_user_function_return(
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 703, in inline_user_function_return
[rank2]:     return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 2357, in inline_call
[rank2]:     return cls.inline_call_(parent, func, args, kwargs)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 2473, in inline_call_
[rank2]:     tracer.run()
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 847, in run
[rank2]:     while self.step():
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 757, in step
[rank2]:     self.dispatch_table[inst.opcode](self, inst)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 481, in wrapper
[rank2]:     return inner_fn(self, inst)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 1269, in CALL_FUNCTION_EX
[rank2]:     self.call_function(fn, argsvars.items, kwargsvars)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 697, in call_function
[rank2]:     self.push(fn.call_function(self, args, kwargs))
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/variables/functions.py", line 339, in call_function
[rank2]:     return super().call_function(tx, args, kwargs)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/variables/functions.py", line 293, in call_function
[rank2]:     return super().call_function(tx, args, kwargs)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/variables/functions.py", line 90, in call_function
[rank2]:     return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 703, in inline_user_function_return
[rank2]:     return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 2357, in inline_call
[rank2]:     return cls.inline_call_(parent, func, args, kwargs)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 2473, in inline_call_
[rank2]:     tracer.run()
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 847, in run
[rank2]:     while self.step():
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 757, in step
[rank2]:     self.dispatch_table[inst.opcode](self, inst)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 481, in wrapper
[rank2]:     return inner_fn(self, inst)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 1228, in CALL_FUNCTION
[rank2]:     self.call_function(fn, args, {})
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 697, in call_function
[rank2]:     self.push(fn.call_function(self, args, kwargs))
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/variables/misc.py", line 592, in call_function
[rank2]:     return self.obj.call_method(tx, self.name, args, kwargs)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/variables/user_defined.py", line 618, in call_method
[rank2]:     return super().call_method(tx, name, args, kwargs)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/variables/base.py", line 313, in call_method
[rank2]:     unimplemented(f"call_method {self} {name} {args} {kwargs}")
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/exc.py", line 204, in unimplemented
[rank2]:     raise Unsupported(msg)
[rank2]: torch._dynamo.exc.Unsupported: call_method UserDefinedObjectVariable(Logger) warning_once [ConstantVariable()] {}
```

### Expected behavior

Run through the example without error and get inference results.

**Comment by moumeneb98** [comment]
Hello did you manage to fix it @hchings ?

**Comment by hchings** [comment]
No, I've used other framework instead. Thank you though!
