### ISSUE TITLE
accelerate test TPU Error: Unsupported nprocs (2)

### ISSUE THREAD

**Issue by radna0** [huggingface/accelerate#2999]
### System Info

```Shell
- `Accelerate` version: 0.33.0
- Platform: Linux-5.4.0-1043-gcp-x86_64-with-glibc2.31
- `accelerate` bash location: /home/kojoe/.local/bin/accelerate
- Python version: 3.10.14
- Numpy version: 1.26.4
- PyTorch version (GPU?): 2.4.0+cu121 (False)
- PyTorch XPU available: False
- PyTorch NPU available: False
- PyTorch MLU available: False
- PyTorch MUSA available: False
- System RAM: 334.58 GB
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: XLA
        - mixed_precision: no
        - use_cpu: False
        - debug: False
        - num_processes: 2
        - machine_rank: 0
        - num_machines: 1
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - enable_cpu_affinity: False
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

kojoe@t1v-n-c3d71aed-w-0:/$ accelerate test
WARNING:root:libtpu.so and TPU device found. Setting PJRT_DEVICE=TPU.

Running:  accelerate-launch /home/kojoe/.local/lib/python3.10/site-packages/accelerate/test_utils/scripts/test_script.py
stderr: WARNING:root:Unsupported nprocs (2), ignoring...
stderr: concurrent.futures.process._RemoteTraceback:
stderr: """
stderr: Traceback (most recent call last):
stderr:   File "/usr/lib/python3.10/concurrent/futures/process.py", line 246, in _process_worker
stderr:     r = call_item.fn(*call_item.args, **call_item.kwargs)
stderr:   File "/usr/lib/python3.10/concurrent/futures/process.py", line 205, in _process_chunk
stderr:     return [fn(*args) for args in chunk]
stderr:   File "/usr/lib/python3.10/concurrent/futures/process.py", line 205, in <listcomp>
stderr:     return [fn(*args) for args in chunk]
stderr:   File "/home/kojoe/.local/lib/python3.10/site-packages/torch_xla/_internal/pjrt.py", line 58, in _run_thread_per_device
stderr:     initializer_fn(local_rank, local_world_size)
stderr:   File "/home/kojoe/.local/lib/python3.10/site-packages/torch_xla/_internal/pjrt.py", line 121, in initialize_multiprocess
stderr:     devices = xm.get_xla_supported_devices()
stderr:   File "/home/kojoe/.local/lib/python3.10/site-packages/torch_xla/core/xla_model.py", line 88, in get_xla_supported_devices
stderr:     devices = torch_xla._XLAC._xla_get_devices()
stderr: RuntimeError: Bad StatusOr access: UNKNOWN: TPU initialization failed: open(/dev/accel0): Operation not permitted: Operation not permitted; Couldn't open device: /dev/accel0; Unable to create Node RegisterInterface for node 0, config: go/nodeserialize    device_path: "/dev/accel0" mode: KERNEL debug_data_directory: "" dump_anomalies_only: true crash_in_debug_dump: false allow_core_dump: true; could not create driver instance
stderr: """
stderr:
stderr: The above exception was the direct cause of the following exception:
stderr:
stderr: Traceback (most recent call last):
stderr:   File "/home/kojoe/.local/bin/accelerate-launch", line 8, in <module>
stderr:     sys.exit(main())
stderr:   File "/home/kojoe/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1112, in main
stderr:     launch_command(args)
stderr:   File "/home/kojoe/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1102, in launch_command
stderr:     tpu_launcher(args)
stderr:   File "/home/kojoe/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 825, in tpu_launcher
stderr:     xmp.spawn(PrepareForLaunch(main_function), args=(), nprocs=args.num_processes)
stderr:   File "/home/kojoe/.local/lib/python3.10/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 37, in spawn
stderr:     return pjrt.spawn(fn, nprocs, start_method, args)
stderr:   File "/home/kojoe/.local/lib/python3.10/site-packages/torch_xla/_internal/pjrt.py", line 209, in spawn
stderr:     run_multiprocess(spawn_fn, start_method=start_method)
stderr:   File "/home/kojoe/.local/lib/python3.10/site-packages/torch_xla/_internal/pjrt.py", line 169, in run_multiprocess
stderr:     replica_results = list(
stderr:   File "/home/kojoe/.local/lib/python3.10/site-packages/torch_xla/_internal/pjrt.py", line 170, in <genexpr>
stderr:     itertools.chain.from_iterable(
stderr:   File "/usr/lib/python3.10/concurrent/futures/process.py", line 575, in _chain_from_iterable_of_lists
stderr:     for element in iterable:
stderr:   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
stderr:     yield _result_or_cancel(fs.pop())
stderr:   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
stderr:     return fut.result(timeout)
stderr:   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
stderr:     return self.__get_result()
stderr:   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
stderr:     raise self._exception
stderr: RuntimeError: Bad StatusOr access: UNKNOWN: TPU initialization failed: open(/dev/accel0): Operation not permitted: Operation not permitted; Couldn't open device: /dev/accel0; Unable to create Node RegisterInterface for node 0, config: go/nodeserialize    device_path: "/dev/accel0" mode: KERNEL debug_data_directory: "" dump_anomalies_only: true crash_in_debug_dump: false allow_core_dump: true; could not create driver instance
Traceback (most recent call last):
  File "/home/kojoe/.local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/kojoe/.local/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/home/kojoe/.local/lib/python3.10/site-packages/accelerate/commands/test.py", line 53, in test_command
    result = execute_subprocess_async(cmd)
  File "/home/kojoe/.local/lib/python3.10/site-packages/accelerate/test_utils/testing.py", line 584, in execute_subprocess_async
    raise RuntimeError(
RuntimeError: 'accelerate-launch /home/kojoe/.local/lib/python3.10/site-packages/accelerate/test_utils/scripts/test_script.py' failed with returncode 1

The combined stderr from workers follows:
WARNING:root:Unsupported nprocs (2), ignoring...
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.10/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/lib/python3.10/concurrent/futures/process.py", line 205, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/usr/lib/python3.10/concurrent/futures/process.py", line 205, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/home/kojoe/.local/lib/python3.10/site-packages/torch_xla/_internal/pjrt.py", line 58, in _run_thread_per_device
    initializer_fn(local_rank, local_world_size)
  File "/home/kojoe/.local/lib/python3.10/site-packages/torch_xla/_internal/pjrt.py", line 121, in initialize_multiprocess
    devices = xm.get_xla_supported_devices()
  File "/home/kojoe/.local/lib/python3.10/site-packages/torch_xla/core/xla_model.py", line 88, in get_xla_supported_devices
    devices = torch_xla._XLAC._xla_get_devices()
RuntimeError: Bad StatusOr access: UNKNOWN: TPU initialization failed: open(/dev/accel0): Operation not permitted: Operation not permitted; Couldn't open device: /dev/accel0; Unable to create Node RegisterInterface for node 0, config: go/nodeserialize    device_path: "/dev/accel0" mode: KERNEL debug_data_directory: "" dump_anomalies_only: true crash_in_debug_dump: false allow_core_dump: true; could not create driver instance
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kojoe/.local/bin/accelerate-launch", line 8, in <module>
    sys.exit(main())
  File "/home/kojoe/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1112, in main
    launch_command(args)
  File "/home/kojoe/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1102, in launch_command
    tpu_launcher(args)
  File "/home/kojoe/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 825, in tpu_launcher
    xmp.spawn(PrepareForLaunch(main_function), args=(), nprocs=args.num_processes)
  File "/home/kojoe/.local/lib/python3.10/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 37, in spawn
    return pjrt.spawn(fn, nprocs, start_method, args)
  File "/home/kojoe/.local/lib/python3.10/site-packages/torch_xla/_internal/pjrt.py", line 209, in spawn
    run_multiprocess(spawn_fn, start_method=start_method)
  File "/home/kojoe/.local/lib/python3.10/site-packages/torch_xla/_internal/pjrt.py", line 169, in run_multiprocess
    replica_results = list(
  File "/home/kojoe/.local/lib/python3.10/site-packages/torch_xla/_internal/pjrt.py", line 170, in <genexpr>
    itertools.chain.from_iterable(
  File "/usr/lib/python3.10/concurrent/futures/process.py", line 575, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
RuntimeError: Bad StatusOr access: UNKNOWN: TPU initialization failed: open(/dev/accel0): Operation not permitted: Operation not permitted; Couldn't open device: /dev/accel0; Unable to create Node RegisterInterface for node 0, config: go/nodeserialize    device_path: "/dev/accel0" mode: KERNEL debug_data_directory: "" dump_anomalies_only: true crash_in_debug_dump: false allow_core_dump: true; could not create driver instance

### Expected behavior

Should test successfully.

**Comment by muellerzr** [comment]
To be clear: did it work for 8 processes? It seems torch_xla doesn't support just using 2, based on what the error states

**Comment by radna0** [comment]
No for 8 as well @muellerzr

**Comment by ghsanti** [comment]
Same error here, any ideas what's wrong?  @muellerzr 

It seems that something is missing judging from the traceback error, why is it assuming that colab runs on GPU?


```
[/usr/local/lib/python3.10/dist-packages/accelerate/launchers.py](https://localhost:8080/#) in notebook_launcher(function, args, num_processes, mixed_precision, use_port, master_addr, node_rank, num_nodes, rdzv_backend, rdzv_endpoint, rdzv_conf, rdzv_id, max_restarts, monitor_interval, log_line_prefix_template)
    149         print(f"Launching a training on {num_processes} TPU cores.")
    150         xmp.spawn(launcher, args=args, nprocs=num_processes, start_method="fork")
--> 151     elif in_colab and get_gpu_info()[1] < 2:
    152         # No need for a distributed launch otherwise as it's either CPU or one GPU.
    153         if torch.cuda.is_available():
```

**Comment by ghsanti** [comment]
I see that the code checks:

```python
    if (in_colab or in_kaggle) and (os.environ.get("TPU_NAME", None) is not None):
```
But here (using TPU)
```python
print(os.environ.get("TPU_NAME"))
```

Is indeed `None`.

**Comment by radna0** [comment]
For anyone working with TPUs and can not use all tpu devices, nprocs only works with either 1 or all devices.

To utilize all tpu devices with accelerate. Follow this
```
site_pkg_path=$(python3.10 -c 'import site; print(site.getsitepackages()[0])')

# TPU all gather implementation
cd $site_pkg_path/accelerate/utils/
sudo rm -rf operations.py
sudo wget -O operations.py https://raw.githubusercontent.com/radna0/EasyAnimate/75206e17b95a48001d97fb870a53f81272c749b6/accelerate/operations.py


# Accelerate TPU config

accelerate config default
cd ~/.cache/huggingface/accelerate/
rm default_config.yaml
wget -O default_config.yaml https://raw.githubusercontent.com/radna0/EasyAnimate/75206e17b95a48001d97fb870a53f81272c749b6/accelerate/config.yaml
```
