### ISSUE TITLE
ROCm Navi 31 7900 Support

### ISSUE THREAD

**Issue by unclemusclez** [huggingface/accelerate#3043]
### System Info

WSL2 Ubuntu linux ROCm 6.1.2

My guess is that accelerate is looking for an MIX00 GPU? It's looking for a CUDA device but I am running an AMD 7900XT

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction
```Shell
Traceback (most recent call last):
  File "/home/musclez/ComfyUI/.venv/bin/autotrain", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/musclez/ComfyUI/.venv/lib/python3.11/site-packages/autotrain/cli/autotrain.py", line 68, in main
    command.run()
  File "/home/musclez/ComfyUI/.venv/lib/python3.11/site-packages/autotrain/cli/run_app.py", line 132, in run
    logger.warning("Attempting to terminate the process...")
  File "/home/musclez/ComfyUI/.venv/lib/python3.11/site-packages/loguru/_logger.py", line 2052, in warning
    __self._log("WARNING", False, __self._options, __message, args, kwargs)
  File "/home/musclez/ComfyUI/.venv/lib/python3.11/site-packages/loguru/_logger.py", line 2032, in _log
    handler.emit(log_record, level_id, from_decorator, raw, colored_message)
  File "/home/musclez/ComfyUI/.venv/lib/python3.11/site-packages/loguru/_handler.py", line 133, in emit
    if not self._filter(record):
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/musclez/ComfyUI/.venv/lib/python3.11/site-packages/autotrain/logging.py", line 28, in <lambda>
    filter=lambda x: self._should_log(x),
                     ^^^^^^^^^^^^^^^^^^^
  File "/home/musclez/ComfyUI/.venv/lib/python3.11/site-packages/autotrain/logging.py", line 21, in _should_log
    return PartialState().is_main_process
           ^^^^^^^^^^^^^^
  File "/home/musclez/ComfyUI/.venv/lib/python3.11/site-packages/accelerate/state.py", line 275, in __init__
    self.set_device()
  File "/home/musclez/ComfyUI/.venv/lib/python3.11/site-packages/accelerate/state.py", line 775, in set_device
    self.device = torch.device("cpu") if self._cpu else self.default_device
                                                        ^^^^^^^^^^^^^^^^^^^
  File "/home/musclez/ComfyUI/.venv/lib/python3.11/site-packages/accelerate/state.py", line 702, in default_device
    elif torch.cuda.is_available():
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/musclez/ComfyUI/.venv/lib/python3.11/site-packages/torch/cuda/__init__.py", line 128, in is_available
    return torch._C._cuda_getDeviceCount() > 0
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

```

I am using `autotrain`, trying to train a model. This works with CPU, to my surprise. 

### Expected behavior

it should be looking for HIP/ROCm devices, not CUDA.

This is the same environment i and using actively for other PyTorch applications, like ComfyUI.

**Comment by muellerzr** [comment]
Do you have the ROCm torch wheels installed? Per my understanding, they hook into calls with `torch.cuda` but I may be wrong

**Comment by unclemusclez** [comment]
> Do you have the ROCm torch wheels installed? Per my understanding, they hook into calls with `torch.cuda` but I may be wrong

because i am using WSL2 linux this limits me quite a bit, but i can try to create venv for python 3.10 with the pytorch 2.1.2 they provide. thats the only version of the whl that exists, and it's not particularly easy to integrate. i normally use the nightly from pytorch if possible

**Comment by unclemusclez** [comment]
```
$ autotrain --config HuggingFaceTBSmolLM-135M-Instruct-devinator-autotrain.yml
INFO     | 2024-08-27 11:29:16 | autotrain.cli.autotrain:main:60 - Using AutoTrain configuration: HuggingFaceTBSmolLM-135M-Instruct-devinator-autotrain.yml
INFO     | 2024-08-27 11:29:16 | autotrain.parser:__post_init__:147 - Running task: sentence_transformers
INFO     | 2024-08-27 11:29:16 | autotrain.parser:__post_init__:148 - Using backend: local
INFO     | 2024-08-27 11:29:16 | autotrain.parser:run:211 - {'data_path': 'skratos115/opendevin_DataDevinator', 'model': 'HuggingFaceTB/SmolLM-135M-Instruct', 'lr': 1e-05, 'epochs': 12, 'max_seq_length': 2048, 'batch_size': 128, 'warmup_ratio': 0.1, 'gradient_accumulation': 1, 'optimizer': 'adamw_torch', 'scheduler': 'linear', 'weight_decay': 0.0, 'max_grad_norm': 1.0, 'seed': 42, 'train_split': 'train', 'valid_split': None, 'logging_steps': -1, 'project_name': 'HuggingFaceTBSmolLM-135M-Instruct-autotrain', 'auto_find_batch_size': False, 'mixed_precision': 'fp16', 'save_total_limit': 1, 'token': '*****', 'push_to_hub': False, 'eval_strategy': 'epoch', 'username': 'unclemusclez', 'log': 'tensorboard', 'early_stopping_patience': 5, 'early_stopping_threshold': 0.01, 'trainer': 'pair_score', 'sentence1_column': 'prompt', 'sentence2_column': 'solution', 'sentence3_column': 'sentence3', 'target_column': 'grade'}
INFO     | 2024-08-27 11:29:16 | autotrain.backends.local:create:8 - Starting local training...
INFO     | 2024-08-27 11:29:16 | autotrain.commands:launch_command:489 - ['accelerate', 'launch', '--cpu', '-m', 'autotrain.trainers.sent_transformers', '--training_config', 'HuggingFaceTBSmolLM-135M-Instruct-autotrain/training_params.json']
INFO     | 2024-08-27 11:29:16 | autotrain.commands:launch_command:490 - {'data_path': 'skratos115/opendevin_DataDevinator', 'model': 'HuggingFaceTB/SmolLM-135M-Instruct', 'lr': 1e-05, 'epochs': 12, 'max_seq_length': 2048, 'batch_size': 128, 'warmup_ratio': 0.1, 'gradient_accumulation': 1, 'optimizer': 'adamw_torch', 'scheduler': 'linear', 'weight_decay': 0.0, 'max_grad_norm': 1.0, 'seed': 42, 'train_split': 'train', 'valid_split': None, 'logging_steps': -1, 'project_name': 'HuggingFaceTBSmolLM-135M-Instruct-autotrain', 'auto_find_batch_size': False, 'mixed_precision': 'fp16', 'save_total_limit': 1, 'token': '*****', 'push_to_hub': False, 'eval_strategy': 'epoch', 'username': 'unclemusclez', 'log': 'tensorboard', 'early_stopping_patience': 5, 'early_stopping_threshold': 0.01, 'trainer': 'pair_score', 'sentence1_column': 'prompt', 'sentence2_column': 'solution', 'sentence3_column': 'sentence3', 'target_column': 'grade'}
/home/musclez/autotrain/.venv/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'libc10_hip.so: cannot open shared object file: No such file or directory'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/home/musclez/autotrain/.venv/lib/python3.10/site-packages/torch/cuda/__init__.py:654: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_processes` was set to a value of `0`
        `--num_machines` was set to a value of `1`
        `--mixed_precision` was set to a value of `'no'`
        `--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
/home/musclez/autotrain/.venv/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'libc10_hip.so: cannot open shared object file: No such file or directory'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
INFO     | 2024-08-27 11:29:22 | __main__:train:111 - Logging steps: 7
INFO     | 2024-08-27 11:29:22 | __main__:train:114 - Train data: Dataset({
    features: ['instruction', 'sentence1', 'sentence2', 'category', 'score', 'Generated with', 'Made By'],
    num_rows: 4784
})
No sentence-transformers model found with name HuggingFaceTB/SmolLM-135M-Instruct. Creating a new one with mean pooling.
INFO     | 2024-08-27 11:29:29 | __main__:train:195 - Setting up training arguments...
/home/musclez/autotrain/.venv/lib/python3.10/site-packages/torch/cuda/__init__.py:654: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")
INFO     | 2024-08-27 11:29:29 | __main__:train:203 - Setting up trainer...
The dataset `id` 'skratos115/opendevin_data_devinator' does not exist on the Hub. Setting the `id` to None.
INFO     | 2024-08-27 11:29:32 | __main__:train:212 - Starting training...
INFO     | 2024-08-27 11:29:32 | autotrain.trainers.common:on_train_begin:230 - Starting to train...
  0%|                                                                                                                                                                                                                | 0/456 [00:00<?, ?it/s]
  ```
  
  pretty sure this is using my CPU
  
  
![image](https://github.com/user-attachments/assets/abeba99c-97dc-48a2-9bdc-45e0771b568c)

**Comment by unclemusclez** [comment]
> Do you have the ROCm torch wheels installed? Per my understanding, they hook into calls with `torch.cuda` but I may be wrong

```
INFO     | 2024-08-27 13:04:53 | autotrain.trainers.common:on_log:225 - {'loss': 0.0, 'grad_norm': 0.0, 'learning_rate': 7.402891482320154e-07, 'epoch': 0.08883779264214046}
{'loss': 0.0, 'grad_norm': 0.0, 'learning_rate': 7.402891482320154e-07, 'epoch': 0.09}
  1%|█▍                                                                                                                                                                                                | 435/57408 [02:00<4:28:25,  3.54it/s]
  ``` yes

**Comment by unclemusclez** [comment]
always try sudo usermod -a -G render,video $USER:$GROUP for each user
