### ISSUE TITLE
Accelerate job fails with a multi-gpu setup

### ISSUE THREAD

**Issue by shashankg7** [huggingface/accelerate#3125]
### System Info

```Shell
- `Accelerate` version: 0.34.2
- Platform: Linux-5.15.0-1068-aws-x86_64-with-glibc2.31
- `accelerate` bash location: /data/home/shashankgupta/miniconda3/envs/vqdiffuser/bin/accelerate
- Python version: 3.9.19
- Numpy version: 1.26.4
- PyTorch version (GPU?): 2.4.1+cu121 (False)
- PyTorch XPU available: False
- PyTorch NPU available: False
- PyTorch MLU available: False
- PyTorch MUSA available: False
- System RAM: 248.94 GB
- `Accelerate` default config:
        Not found
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

I am trying to run the HuggingFace TRL DDPO script: https://github.com/huggingface/trl/blob/main/examples/scripts/ddpo.py, on a slurm single node with 4 GPUs using the following job script:

```
#!/bin/bash

#SBATCH --job-name=multigpu
#SBATCH --output=O-%x.%j
#SBATCH --error=E-%x.%j
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1         # number of MP tasks
#SBATCH --gres=gpu:4                # number of GPUs per node
#SBATCH --cpus-per-task=64        # number of cores per tasks
#SBATCH --time=01:59:00             # maximum execution time (HH:MM:SS)

######################
### Set enviroment ###
######################
source /data/home/shashankgupta/miniconda3/etc/profile.d/conda.sh 
conda activate vqdiffuser
export GPUS_PER_NODE=4
######################

export ACCELERATE_DIR="${ACCELERATE_DIR:-/accelerate}"

accelerate launch --num_processes $GPUS_PER_NODE --multi_gpu ddpo.py --num_epochs=200 --train_gradient_accumulation_steps=1 --sample_num_steps=50 --sample_batch_size=6  --train_batch_size=3  --sample_num_batches_per_epoch=4 --train_learning_rate=3e-4 --per_prompt_stat_tracking=True  --mixed_precision=no --per_prompt_stat_tracking_buffer_size=64 --tracker_project_name="stable_diffusion_training" --log_with="wandb"
```

I am getting an error:

```
[rank3]:   File "/opt/hpcaas/.mounts/fs-074514506a8464fcb/home/shashankgupta/RLHF_Compositionality/ddpo.py", line 208, in <module>
[rank3]:     trainer.train()
[rank3]:   File "/data/home/shashankgupta/miniconda3/envs/vqdiffuser/lib/python3.9/site-packages/trl/trainer/ddpo_trainer.py", line 605, in train
[rank3]:     global_step = self.step(epoch, global_step)
[rank3]:   File "/data/home/shashankgupta/miniconda3/envs/vqdiffuser/lib/python3.9/site-packages/trl/trainer/ddpo_trainer.py", line 267, in step
[rank3]:     self.image_samples_callback(prompt_image_data, global_step, self.accelerator.trackers[0])
[rank3]: IndexError: list index out of range
[rank1]: Traceback (most recent call last):
[rank1]:   File "/opt/hpcaas/.mounts/fs-074514506a8464fcb/home/shashankgupta/RLHF_Compositionality/ddpo.py", line 208, in <module>
[rank1]:     trainer.train()
[rank1]:   File "/data/home/shashankgupta/miniconda3/envs/vqdiffuser/lib/python3.9/site-packages/trl/trainer/ddpo_trainer.py", line 605, in train
[rank1]:     global_step = self.step(epoch, global_step)
[rank1]:   File "/data/home/shashankgupta/miniconda3/envs/vqdiffuser/lib/python3.9/site-packages/trl/trainer/ddpo_trainer.py", line 267, in step
[rank1]:     self.image_samples_callback(prompt_image_data, global_step, self.accelerator.trackers[0])
[rank1]: IndexError: list index out of range
[rank2]: Traceback (most recent call last):
[rank2]:   File "/opt/hpcaas/.mounts/fs-074514506a8464fcb/home/shashankgupta/RLHF_Compositionality/ddpo.py", line 208, in <module>
[rank2]:     trainer.train()
[rank2]:   File "/data/home/shashankgupta/miniconda3/envs/vqdiffuser/lib/python3.9/site-packages/trl/trainer/ddpo_trainer.py", line 605, in train
[rank2]:     global_step = self.step(epoch, global_step)
[rank2]:   File "/data/home/shashankgupta/miniconda3/envs/vqdiffuser/lib/python3.9/site-packages/trl/trainer/ddpo_trainer.py", line 267, in step
[rank2]:     self.image_samples_callback(prompt_image_data, global_step, self.accelerator.trackers[0])
[rank2]: IndexError: list index out of range
```

### Expected behavior

I think `self.accelerator.trackers[0]` is not getting initialized in a multiGPU setup. The script works with a single GPU.

**Comment by shashankg7** [comment]
Removed the image_samples_callback and the code worked.
