### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device after running sample from `load_checkpoint_and_dispatch` function

### ISSUE THREAD

**Issue by jmcshane** [huggingface/accelerate#3135]
### System Info

```Shell
- `Accelerate` version: 0.34.2
- Platform: Linux-6.5.0-44-generic-x86_64-with-glibc2.35
- `accelerate` bash location: /home/student/hf/.venv/bin/accelerate
- Python version: 3.10.12
- Numpy version: 2.1.1
- PyTorch version (GPU?): 2.4.1+cu121 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- PyTorch MLU available: False
- PyTorch MUSA available: False
- System RAM: 42.12 GB
- GPU type: Quadro RTX 5000
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: MULTI_GPU
        - mixed_precision: fp16
        - use_cpu: False
        - debug: True
        - num_processes: 2
        - machine_rank: 0
        - num_machines: 1
        - gpu_ids: all
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - enable_cpu_affinity: True
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Write python script in line with https://github.com/huggingface/accelerate/blob/main/src/accelerate/big_modeling.py#L568-L589 (I'm using `EleutherAI/gpt-neo-125M` for faster iteration)
2. Add the following code:
```
device = torch.device("cuda")
model.eval()
tokenizer = AutoTokenizer.from_pretrained(checkpoint, token=token, config=model.config, device_map=collections.OrderedDict(model.hf_device_map))
eos = tokenizer.eos_token_id
input_ids = tokenizer.encode(
    "¡Hola! Encantado de conocerte. hoy voy a", return_tensors="pt"
).to(device)

with torch.no_grad():
    output = model.generate(
        input_ids, max_new_tokens=10, do_sample=False
    )

print(f"Output: {tokenizer.decode(output[0], skip_special_tokens=True)}")
```

I receive the error:

```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/student/hf/.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/student/hf/.venv/lib/python3.10/site-packages/transformers/generation/utils.py", line 2048, in generate
    result = self._sample(
  File "/home/student/hf/.venv/lib/python3.10/site-packages/transformers/generation/utils.py", line 3008, in _sample
    outputs = self(**model_inputs, return_dict=True)
  File "/home/student/hf/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/student/hf/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/student/hf/.venv/lib/python3.10/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/student/hf/.venv/lib/python3.10/site-packages/transformers/models/gpt_neo/modeling_gpt_neo.py", line 1043, in forward
    transformer_outputs = self.transformer(
  File "/home/student/hf/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/student/hf/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/student/hf/.venv/lib/python3.10/site-packages/transformers/models/gpt_neo/modeling_gpt_neo.py", line 743, in forward
    inputs_embeds = self.wte(input_ids)
  File "/home/student/hf/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/student/hf/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/student/hf/.venv/lib/python3.10/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/student/hf/.venv/lib/python3.10/site-packages/torch/nn/modules/sparse.py", line 164, in forward
    return F.embedding(
  File "/home/student/hf/.venv/lib/python3.10/site-packages/torch/nn/functional.py", line 2267, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)
```

### Expected behavior

The output works and provides the output from the model in line with how `from_pretrained` works when initializing the model from the huggingface repository.

**Comment by BenjaminBossan** [comment]
Thanks for reporting this. I think this should be a self-contained reproducer with the same error:

```python
import torch
from accelerate import init_empty_weights, load_checkpoint_and_dispatch
from huggingface_hub import hf_hub_download
from transformers import AutoConfig, AutoModelForCausalLM, AutoTokenizer

# Download the Weights
checkpoint = "facebook/opt-125m"
weights_location = hf_hub_download(checkpoint, "pytorch_model.bin")

device = torch.device("cuda")
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
input_ids = tokenizer.encode(
    "¡Hola! Encantado de conocerte. hoy voy a", return_tensors="pt"
).to(device)

# Create a model and initialize it with empty weights
config = AutoConfig.from_pretrained(checkpoint)
with init_empty_weights():
    model = AutoModelForCausalLM.from_config(config)

# Load the checkpoint and dispatch it to the right devices
model = load_checkpoint_and_dispatch(model, weights_location, device_map="auto")
print({p.device for p in model.parameters()})  # should be cuda:0 and cuda:1
model.eval()

with torch.no_grad():
    # error here
    output = model.generate(input_ids, max_new_tokens=10, do_sample=False)
```

As you correctly noted, when using `from_pretraiend(..., device_map="auto")`, we don't encounter this error. This probably means that some hooks responsible for device movement are not correctly set. Maybe @SunMarc can elucidate.

**Comment by jmcshane** [comment]
is there a generalized entrypoint in `transformers` where those hooks are invoked? I know `transformers` calls `dispatch_model` directly when `accelerate` is available: https://github.com/huggingface/transformers/blob/351873a145f52685ae611c0a15190fec5949e133/src/transformers/modeling_utils.py#L4108

Wondering if there's something that can be invoked directly from `modeling_utils` to get these hooks initialized

**Comment by SunMarc** [comment]
> model = load_checkpoint_and_dispatch(model, weights_location, device_map="auto")

For practically all models, you need to specify the `no_split_module_classes` arg in `load_checkpoint_and_dispatch`. 
See here for more [details](https://huggingface.co/docs/accelerate/en/concept_guides/big_model_inference#nosplitmoduleclasses). When using `device_map="auto"` in from_pretrained, each models have the `no_split_module_classes` set already, so that's why it works.

**Comment by jmcshane** [comment]
ah, i see `_get_no_split_modules` is available in `modeling_utils`. Let me try that

**Comment by jmcshane** [comment]
Confirmed that method does the trick. Here's a functional script:

```python
import torch
from accelerate import init_empty_weights, load_checkpoint_and_dispatch
from huggingface_hub import hf_hub_download
from transformers import AutoConfig, AutoModelForCausalLM, AutoTokenizer

# Download the Weights
checkpoint = "EleutherAI/gpt-neo-125M"
weights_location = hf_hub_download(checkpoint, "pytorch_model.bin")

device = torch.device("cuda")
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
input_ids = tokenizer.encode(
    "¡Hola! Encantado de conocerte. hoy voy a", return_tensors="pt"
).to(device)

# Create a model and initialize it with empty weights
config = AutoConfig.from_pretrained(checkpoint)
with init_empty_weights():
    model = AutoModelForCausalLM.from_config(config)

model.tie_weights()
# Load the checkpoint and dispatch it to the right devices
model = load_checkpoint_and_dispatch(model, weights_location, device_map="auto", no_split_module_classes=model._get_no_split_modules(device_map="auto"))
print({p.device for p in model.parameters()})  # should be cuda:0 and cuda:1
model.eval()

with torch.no_grad():
    # error here
    output = model.generate(input_ids, max_new_tokens=10, do_sample=False)
```
