### ISSUE TITLE
Multi-Node (2x8 H100) training progress bar not showing up! (Node Connection Issue)

### ISSUE THREAD

**Issue by KeshavSingh29** [huggingface/accelerate#3273]
### System Info

```Shell
- `Accelerate` version: 1.0.0
- Platform: Linux-5.15.0-1059-nvidia-x86_64-with-glibc2.35
- `accelerate` bash location: /usr/local/bin/accelerate
- Python version: 3.10.12
- Numpy version: 1.26.3
- PyTorch version (GPU?): 2.4.1+cu124 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- PyTorch MLU available: False
- PyTorch MUSA available: False
- System RAM: 2015.56 GB
- GPU type: NVIDIA H100 80GB HBM3
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: DEEPSPEED
        - use_cpu: False
        - debug: False
        - num_processes: 16
        - machine_rank: 0
        - num_machines: 2
        - main_process_ip: 10.0.1.6
        - main_process_port: 56789
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - enable_cpu_affinity: False
        - deepspeed_config: {'deepspeed_config_file': 'config/ds_config.json', 'deepspeed_hostfile': 'config/hostfile.txt', 'deepspeed_multinode_launcher': 'pdsh', 'zero3_init_flag': True}
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
        - dynamo_config: {'dynamo_backend': 'AOT_EAGER'}
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Background: 
- Using containerized env on two nodes (each with 8 h100 gpus)
- Training LLM (scratch) using accelerate + huggingface Trainer + Deepspeed
- Containers have no issue with connection (using docker swarm, passwordless ssh, hostfile.txt etc)
- Script has no issue with training 

### hostfile.txt
10.0.1.6 slots=8
10.0.1.8 slots=8

### Issue:
- At training time, cannot see progress bar
- The GPUs are being used on both nodes (`nvidia-smi` shows the occupancy)
- wandb is reporting only system graphs but nothing else 

### What I tried already:
- Single node run with same setup -> Working !
- Multi node run without wandb -> Not Working !! (I thought the issue is with wandb, but no)
- Multi node run with wandb + printing data collater (Batch samples are being iterated through as expected but no progress bar)
- Additionally I tried accelerate test, the connection seem to work except here: 

```text
### some other output here before ####
stdout: 10.0.1.8:
stdout: 10.0.1.8: Distributed environment: DEEPSPEED  Backend: nccl
stdout: 10.0.1.8: Num processes: 16
stdout: 10.0.1.8: Process index: 10
stdout: 10.0.1.8: Local process index: 2
stdout: 10.0.1.8: Device: cuda:2
stdout: 10.0.1.8:
stdout: 10.0.1.8: Mixed precision type: no
stdout: 10.0.1.8: ds_config: {'gradient_accumulation_steps': 4, 'train_micro_batch_size_per_gpu': 8, 'optimizer': {'type': 'AdamW', 'params': {'lr': 0.0003, 'betas': [0.9, 0.95], 'eps': 1e-08, 'weight_decay': 0.1}}, 'gradient_clipping': 1.0, 'zero_optimization': {'stage': 3, 'offload_optimizer': {'device': 'cpu', 'pin_memory': True}, 'offload_param': {'device': 'cpu', 'pin_memory': True}, 'overlap_comm': True, 'reduce_scatter': True, 'contiguous_gradients': True}, 'steps_per_print': inf, 'fp16': {'enabled': False}, 'bf16': {'enabled': False}}
stdout: 10.0.1.8:
stdout: 10.0.1.6:
stdout: 10.0.1.6: **Test process execution**
stderr: 10.0.1.6: [rank0]: Traceback (most recent call last):
stderr: 10.0.1.6: [rank0]:   File "/usr/local/lib/python3.10/dist-packages/accelerate/test_utils/scripts/test_script.py", line 829, in <module>
stderr: 10.0.1.6: [rank0]:     main()
stderr: 10.0.1.6: [rank0]:   File "/usr/local/lib/python3.10/dist-packages/accelerate/test_utils/scripts/test_script.py", line 765, in main
stderr: 10.0.1.6: [rank0]:     process_execution_check()
stderr: 10.0.1.6: [rank0]:   File "/usr/local/lib/python3.10/dist-packages/accelerate/test_utils/scripts/test_script.py", line 110, in process_execution_check
stderr: 10.0.1.6: [rank0]:     text.count("Now on another process\n") == accelerator.num_processes - 1
stderr: 10.0.1.6: [rank0]: AssertionError: Only wrote to file 8 times, not 16
stdout: 10.0.1.6: [2024-12-06 07:19:42,640] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 6717
stdout: 10.0.1.6: [2024-12-06 07:19:42,640] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 6718
stdout: 10.0.1.6: [2024-12-06 07:19:42,934] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 6719
stdout: 10.0.1.6: [2024-12-06 07:19:43,308] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 6720
stdout: 10.0.1.6: [2024-12-06 07:19:43,523] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 6721
stdout: 10.0.1.6: [2024-12-06 07:19:43,777] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 6722
stdout: 10.0.1.6: [2024-12-06 07:19:44,031] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 6723
stdout: 10.0.1.6: [2024-12-06 07:19:44,284] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 6724
stdout: 10.0.1.6: [2024-12-06 07:19:44,538] [ERROR] [launch.py:325:sigkill_handler] ['/usr/bin/python3', '-u', '/usr/local/lib/python3.10/dist-packages/accelerate/test_utils/scripts/test_script.py'] exits with return code = 1
stderr: pdsh@5f513b305ece: 10.0.1.6: ssh exited with exit code 1
```

When starting training with accelerate launch, everything seems to work except here:
![image](https://github.com/user-attachments/assets/d95e47a5-3199-4f70-aafc-969407ed6098)

Nothing after this... 

Here is my docker file (if needed): 
```dockerfile
#Base image
FROM nvidia/cuda:12.4.0-devel-ubuntu22.04

WORKDIR /home/keshav

COPY . .

# Install Python 3.9
RUN apt-get update && apt-get install -y \
    python3.9 \
    python3-pip \
    wget \
    pdsh \
    emacs \
    openssh-server && \
    mkdir /var/run/sshd && \
    echo "PermitRootLogin yes" >> /etc/ssh/sshd_config && \
    echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config && \
    apt-get clean

# Install dependencies
RUN pip install --upgrade pip && \
    pip install torch==2.4.1 torchvision==0.19.1 torchaudio==2.4.1 --index-url https://download.pytorch.org/whl/cu124 && \
    pip install -r requirements.txt

RUN mkdir -p /root/.triton/autotune

ENV PATH="/usr/local/cuda/bin:${PATH}"
ENV LD_LIBRARY_PATH="/usr/local/cuda/lib64:${LD_LIBRARY_PATH}"

ENV NCCL_SOCKET_IFNAME=eth0

EXPOSE 56789

CMD ["bash"]
```

### Is this a bug on accelerate side ? Any help would be appreciated. 

Additional Info: 
Inside each container when i run `hostname -I`, i get 
node2 -> 10.0.1.8 172.19.0.3 
node1 -> 10.0.1.6 

where i use 10.0.1.8 and 10.0.1.6 (docker swarm network) which is  overlay network for multi-node communication. 

Also I run accelerate launch only on the main process node while the container is up and running on other worker node. 

### Expected behavior

The training to perform as expected with progress bar showing up.

**Comment by KeshavSingh29** [comment]
Closing this issue. 
Update: 
- Containerization with nvidia toolkit and then setting up multinode is very difficult. 
- Default it uses eth0 (super slow) while using infiniband runs into network issues (possibly due to how my containers are setup or idk what might be the case, spent a month on it but cannot find a sol)

What worked for me: 
- No containerization
- On all nodes miniconda with same name of virtual env and setup files. 
- To use infiniband, make sure all nodes had ipv4 (if not, add a address)
- Passwordless ssh between main node to all other nodes + main node (yes from main to main is also imp)

Works like a charm! 
But still wandb progress bar not showing up. 

Note: 
If the nvidia-cuda toolkit has mismatch or you get nvcc error. 
Make sure to install the correct pytorch. 
Example: 
On one node i had `CUDA Version: 12.4` and other with `CUDA Version: 12.2`
Install on node with CUDA 12.2
`pip install torch==2.4.1 torchvision==0.19.1 torchaudio==2.4.1 --index-url https://download.pytorch.org/whl/cu121`
On node with CUDA 12.4
`pip install torch==2.4.1 torchvision==0.19.1 torchaudio==2.4.1 --index-url https://download.pytorch.org/whl/cu124`

Make sure pytorch versions are same but cuda compatibility is according to your driver. 

There are some other considerations like: 
NCCL_IB_DISABLE=0
NCCL_SOCKET_IFNAME=ibp24s0
But this depends on if you want to use infiniband. 
Cheers!
