### ISSUE TITLE
PaliGemma2 peft + accelerate evaluation during training fails with TypeError: Unsupported types (<class 'transformers.cache_utils.HybridCache'>) passed to `_pad_across_processes`

### ISSUE THREAD

**Issue by beniz** [huggingface/accelerate#3277]
### System Info

```Shell
Accelerate 1.2.0, peft 0.14.0, transformers 4.47.0
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

```
Traceback (most recent call last):
  File "/data1/beniz/code/llmbox/multimodal/ft_paligemma2.py", line 213, in <module>
    trainer.train(resume_from_checkpoint=(args.resume > 0))
  File "/home/beniz/.local/lib/python3.10/site-packages/transformers/trainer.py", line 2164, in train
    return inner_training_loop(
  File "/home/beniz/.local/lib/python3.10/site-packages/transformers/trainer.py", line 2589, in _inner_training_loop
    self._maybe_log_save_evaluate(
  File "/home/beniz/.local/lib/python3.10/site-packages/transformers/trainer.py", line 3047, in _maybe_log_save_evaluate
    metrics = self._evaluate(trial, ignore_keys_for_eval)
  File "/home/beniz/.local/lib/python3.10/site-packages/transformers/trainer.py", line 3001, in _evaluate
    metrics = self.evaluate(ignore_keys=ignore_keys_for_eval)
  File "/home/beniz/.local/lib/python3.10/site-packages/transformers/trainer.py", line 4051, in evaluate
    output = eval_loop(
  File "/home/beniz/.local/lib/python3.10/site-packages/transformers/trainer.py", line 4267, in evaluation_loop
    logits = self.accelerator.pad_across_processes(logits, dim=1, pad_index=-100)
  File "/home/beniz/.local/lib/python3.10/site-packages/accelerate/accelerator.py", line 2602, in pad_across_processes
    return pad_across_processes(tensor, dim=dim, pad_index=pad_index, pad_first=pad_first)
  File "/home/beniz/.local/lib/python3.10/site-packages/accelerate/utils/operations.py", line 412, in wrapper
    return function(*args, **kwargs)
  File "/home/beniz/.local/lib/python3.10/site-packages/accelerate/utils/operations.py", line 682, in pad_across_processes
    return recursively_apply(
  File "/home/beniz/.local/lib/python3.10/site-packages/accelerate/utils/operations.py", line 108, in recursively_apply
    return honor_type(
  File "/home/beniz/.local/lib/python3.10/site-packages/accelerate/utils/operations.py", line 82, in honor_type
    return type(obj)(generator)
  File "/home/beniz/.local/lib/python3.10/site-packages/accelerate/utils/operations.py", line 111, in <genexpr>
    recursively_apply(
  File "/home/beniz/.local/lib/python3.10/site-packages/accelerate/utils/operations.py", line 129, in recursively_apply
    raise TypeError(
TypeError: Unsupported types (<class 'transformers.cache_utils.HybridCache'>) passed to `_pad_across_processes`. Only nested list/tuple/dicts of objects that are valid for `is_torch_tensor` should be passed.
```

This is the full trace. I have yet to find how to give you code for easy reproduction. This is using https://github.com/beniz/llmbox/blob/main/multimodal/ft_paligemma.py.

Now, my goal here is to gather feedback on whether this could be a bug in accelerate. This because it seems to be occuring before my own code is called, in the `pad_across_processes` function.

Happy to help dig further.

### Expected behavior

With PaliGemma, the same script works fine: training steps are OK, evaluation steps are OK.
With PaliGemma2, training steps are OK, evaluation fails with the error above.

**Comment by scris** [comment]
I met similar issue on it migrating a Mistral code into Gemma 2, and it's also only during evaluation. 
Looking forward to any updates.

**Comment by BenjaminBossan** [comment]
@beniz It would be great if you could provide a complete reproducer. The script you linked seems to be rely on a local dataset. Can this be substituted with a publicly available dataset?

Otherwise, it may help if you could start a debugger and report back what the arguments are that are passed to `pad_across_processes` in this part of the code:

> `pad_across_processes(tensor, dim=dim, pad_index=pad_index, pad_first=pad_first)`

**Comment by beniz** [comment]
Hi @BenjaminBossan, thanks for your answer. 

Please find a script to easily reproduce the problem: https://github.com/beniz/llmbox/blob/debug_accelerate_paligemma2/multimodal/ft_paligemma2_debug.py

This is a very simple task that classifies images of dogs and cats by finetuning paligemma2.

To reproduce the issue:
```
python3 -W ignore ft_paligemma2_debug.py --model-id google/paligemma2-3b-pt-448 --batch-size 1 --iter-size 8 --save-steps 100 --eval-steps 2 --output-dir test_cats_dogs --nepochs 3 --min-img-size 448
```
The error is at evaluation.

Now, if you rollback to the v1 of paligemma, it does work fine with the same script: 
```
python3 -W ignore ft_paligemma2_debug.py --model-id google/paligemma-3b-pt-448 --batch-size 1 --iter-size 8 --save-steps 100 --eval-steps 2 --output-dir test_cats_dogs --nepochs 3 --min-img-size 448
```

Happy to help with this, I've looked for the HybridCache stuff and even within accelerate, but I could not really locate even a starting point from where to debug.

**Comment by mjschock** [comment]
I see a similar issue when trying to run evaluations with SFTTrainer but it shows DynamicCache instead of HybridCache for me:

```
.venv/lib/python3.12/site-packages/accelerate/utils/operations.py", line 129, in recursively_apply
    raise TypeError(
TypeError: Unsupported types (<class 'transformers.cache_utils.DynamicCache'>) passed to `_pad_across_processes`. Only nested list/tuple/dicts of objects that are valid for `is_torch_tensor` should be passed.
```

**Comment by mjschock** [comment]
> I see a similar issue when trying to run evaluations with SFTTrainer but it shows DynamicCache instead of HybridCache for me:
> 
> ```
> .venv/lib/python3.12/site-packages/accelerate/utils/operations.py", line 129, in recursively_apply
>     raise TypeError(
> TypeError: Unsupported types (<class 'transformers.cache_utils.DynamicCache'>) passed to `_pad_across_processes`. Only nested list/tuple/dicts of objects that are valid for `is_torch_tensor` should be passed.
> ```

I got it working by setting `model.config.use_cache=False` before training. I saw this fix for a slightly different situation here: https://github.com/huggingface/transformers/issues/30631#issuecomment-2092476406. YMMV.

**Comment by beniz** [comment]
Thanks @mjschock I tried with Trainer and SFTTrainer and don't see it fixing the issue. Also I don't see reference to `DynamicCache`, but to `HybridCache`. Would you be able to share relevant excerpts of your code, especially model loading, and training config, to see whether I can find a way to trace the Cache class difference at least ? Thanks.

**Comment by BenjaminBossan** [comment]
@beniz Could you try adding the following line after initializing the PaliGemma model:

`model.config.keys_to_ignore_at_inference = ["past_key_values"]`

For me, this fixed the issue.

**Comment by beniz** [comment]
@BenjaminBossan Thanks, this is black magic to me but it did work! Will this be fixed from within transformers then ? Thanks again.

**Comment by BenjaminBossan** [comment]
@beniz The reason why this works is that `forward` returns the tensors but also the cache instances. The latter can of course not be padded. By setting this flag (`past_key_values` == cache), we prevent the cache instances from being returned and the error disappears. Honestly, I don't know enough about why the cache is returned, so I'm not sure if this is a "bug or a feature".

**Comment by scris** [comment]
Will knowledges discovered in this issue be recorded elsewhere, e.g. in some docs, or merged in some code somewhere?
