### ISSUE TITLE
AssertionError: No inf checks were recorded for this optimizer.

### ISSUE THREAD

**Issue by ishandutta04** [huggingface/accelerate#328]
I am using Huggingface Accelerator for mixed precision training in my image classification pipeline. However I get an AssertionError. This is the full traceback - 

```
Traceback (most recent call last):
  File "main.py", line 87, in <module>
    accelerator=accelerator
  File "/content/metadome-hairColor-pytorch/training/train.py", line 80, in run_training
    accelerator=accelerator
  File "/content/metadome-hairColor-pytorch/training/engine.py", line 72, in train_one_epoch
    optimizer.step()
  File "/usr/local/lib/python3.7/dist-packages/accelerate/optimizer.py", line 129, in step
    self.scaler.step(self.optimizer, closure)
  File "/usr/local/lib/python3.7/dist-packages/torch/cuda/amp/grad_scaler.py", line 336, in step
    assert len(optimizer_state["found_inf_per_device"]) > 0, "No inf checks were recorded for this optimizer."
AssertionError: No inf checks were recorded for this optimizer.
```

The code works correctly when I use it on a GPU without accelerator but if I use accelerator I get this error.
The task is to build a color classifier. The colors are provided in RGB format as targets.
  
Following is the relevant code - 

## engine.py
```
import gc 
import torch
import numpy as np
from tqdm.auto import tqdm

import training.loss_fn as loss_fn
import utilities.utils as utils

def train_one_epoch(args, cfg, model, optimizer, scheduler, dataloader, device, epoch, accelerator = None):
    """
    Function to train one epoch on the data
    Args:
        cfg (dict): Configuration File 
        model: Model definition
        optimizer: Optimizer for the network
        scheduler: Learning Rate Scheduler
        dataloader: PyTorch DataLoader
        device: GPU or CPU device for training
        epoch (int): Number of epochs
        scaler: Scaler for AMP
    Returns:
        epoch_loss (float): Loss for the epoch
    """
    
    # Initialize model train mode
    model.train()
    
    # Initial parameters
    dataset_size = 0
    running_loss = 0.0
    size_sampler = len(dataloader.sampler)
    
    # Progress bar
    bar = tqdm(enumerate(dataloader), total=len(dataloader))

    # Iterate over batches
    for step, data in bar:
        
        # Get data
        if args.fp16 == True:
            images = data['image'].to(torch.float)
            target_r = data['target_r'].to(torch.float)
            target_g = data['target_g'].to(torch.float)
            target_b = data['target_b'].to(torch.float)

        else:
            images = data['image'].to(device, dtype=torch.float)
            target_r = data['target_r'].to(device, dtype=torch.float)
            target_g = data['target_g'].to(device, dtype=torch.float)
            target_b = data['target_b'].to(device, dtype=torch.float)
            
        batch_size = images.size(0)

        # Generate predictions
        outputs = model(images)
        # outputs = utils.bound_outputs(outputs)

        # Calculate loss
        loss = loss_fn.criterion(outputs, [target_r, target_g, target_b], device)

        # Accumulate loss
        loss = loss / cfg['TRAIN']['N_ACCUMULATE']

        # Backpropagation
        if args.fp16 == True:
            accelerator.backward(loss)
        
        else:
            loss.backward()
        
        if (step + 1) % cfg['TRAIN']['N_ACCUMULATE'] == 0:
            optimizer.step()

            # zero the parameter gradients
            optimizer.zero_grad()

        if scheduler is not None:
            scheduler.step()
                
        running_loss += (loss.item() * batch_size)
        dataset_size += batch_size
        
        epoch_loss = running_loss / dataset_size
        
        # Progress bar details
        bar.set_postfix(
            Epoch=epoch, 
            Train_Loss=epoch_loss,
            LR=optimizer.param_groups[0]['lr'],
            )

    gc.collect()

    return epoch_loss

def valid_one_epoch(args, cfg, model, optimizer, dataloader, device, epoch):
    """
    Function to validate on one epoch on the data
    Args:
        cfg (dict): Configuration File 
        model: Model definition
        optimizer: Optimizer for the network
        dataloader: PyTorch DataLoader
        device: GPU or CPU device for training
        epoch (int): Number of epochs

    Returns:
        epoch_loss (float): Loss for the epoch
        final_targets (list): List of Targets
        final_outputs (list): List of Model Predictions
    """
    model.eval()

    final_targets_r = []
    final_targets_g = []
    final_targets_b = []

    final_outputs_r = []
    final_outputs_g = []
    final_outputs_b = []
    
    dataset_size = 0
    running_loss = 0.0
    size_sampler = len(dataloader.sampler)
    
    bar = tqdm(enumerate(dataloader), total=len(dataloader))
    for step, data in bar:   

        # Get data
        if args.fp16 == True:
            images = data['image'].to(torch.float)
            target_r = data['target_r'].to(torch.float)
            target_g = data['target_g'].to(torch.float)
            target_b = data['target_b'].to(torch.float)

        else:
            images = data['image'].to(device, dtype=torch.float)
            target_r = data['target_r'].to(device, dtype=torch.float)
            target_g = data['target_g'].to(device, dtype=torch.float)
            target_b = data['target_b'].to(device, dtype=torch.float)
        
        batch_size = images.size(0)

        # Generate predictions
        outputs = model(images)
        # outputs = utils.bound_outputs(outputs)

        # Calculate loss
        loss = loss_fn.criterion(outputs, [target_r, target_g, target_b], device)
        
        running_loss += (loss.item() * batch_size)
        dataset_size += batch_size
        
        epoch_loss = running_loss / dataset_size
        
        # Progress bar details
        bar.set_postfix(
            Epoch=epoch, 
            Valid_Loss=epoch_loss,
            LR=optimizer.param_groups[0]['lr']
            )   

        # Move targets and outputs to cpu 
        target_r = (target_r.detach().clone().cpu().numpy()).tolist()
        target_g = (target_g.detach().clone().cpu().numpy()).tolist()
        target_b = (target_b.detach().clone().cpu().numpy()).tolist()

        output_r = (outputs[0].detach().clone().cpu().numpy()).tolist()
        output_g = (outputs[1].detach().clone().cpu().numpy()).tolist()
        output_b = (outputs[2].detach().clone().cpu().numpy()).tolist()

        final_targets_r.extend(target_r)
        final_targets_g.extend(target_g)
        final_targets_b.extend(target_b)

        final_outputs_r.extend(output_r)
        final_outputs_g.extend(output_g)
        final_outputs_b.extend(output_b)
    
    gc.collect()
    
    return epoch_loss, \
           [final_targets_r, final_targets_g, final_targets_b], \
           [final_outputs_r, final_outputs_g, final_outputs_b]
```

## optimizer_fn.py
```
import torch

def get_optimizer(cfg, model, optimizer = "Adam"):
    """
    Function to obtain the optimizer for the network.
    Args:
        cfg (dict): Configuration File
        model: Model class
        optimizer (str): "SGD" or "Adam"
    Returns:
        optimizer
    """
    if optimizer == "SGD":
        return torch.optim.SGD(
            model.parameters(), 
            lr=cfg['TRAIN']['LEARNING_RATE'], 
            momentum=cfg['TRAIN']['MOMENTUM'], 
            weight_decay=cfg['TRAIN']['WEIGHT_DECAY']
            )

    if optimizer == "Adam":
        return torch.optim.Adam(
            model.parameters(), 
            lr=cfg['TRAIN']['LEARNING_RATE'], 
            weight_decay=cfg['TRAIN']['WEIGHT_DECAY']
            )
```

## loss_fn.py
This is a custom loss function which is used to calculate the difference between the RGB values of the outputs and targets. 
```
# Custom Loss for Colors
import numpy as np
import torch 
from skimage import  color
from colormath.color_objects import LabColor, sRGBColor
from colormath.color_conversions import convert_color
from colormath.color_diff import delta_e_cie2000

def rgb_to_lab(rgb_color):
    rgb_color = sRGBColor(rgb_color[0], rgb_color[1], rgb_color[2])
    lab_color = convert_color(rgb_color, LabColor)
    return lab_color

def criterion(outputs, targets, device):
    """
    Custom Loss function for the model.
    # Ref: https://dev.to/tejeshreddy/color-difference-between-2-colours-using-python-182b
    """
    
    # Convert to CIE Lab Space
    lab_outputs = []
    lab_targets = []

    for output in outputs:
        lab_outputs.append(rgb_to_lab(output))

    for target in targets:
        lab_targets.append(rgb_to_lab(target))

    # Calculate the difference in Lab space
    diff = []
    for i in range(len(lab_outputs)):
        diff.append(delta_e_cie2000(lab_outputs[i], lab_targets[i]))

    # Calculate the mean of the difference
    loss = torch.mean(torch.tensor(diff))

    return torch.tensor(loss, requires_grad = True).to(device)
```

How to resolve this?

**Comment by sgugger** [comment]
It looks like your the optimizer stepped through is disconnected from the scaler somehow. It's hard to know why without seeing the code of your training loop.

**Comment by clam004** [comment]
I get the same error

```python
model.train()
for step, batch in enumerate(tqdm(train_dataloader), start=1):
    
    inputs = torch.tensor(batch['input_ids'])
    inputs = inputs.to(model.device)
    
    outputs = model(inputs, return_dict=True)
    
    logits = outputs.logits
    
    shift_labels = inputs[..., 1:].contiguous()
    shift_logits = logits[..., :-1, :].contiguous()
    
    loss_func = torch.nn.CrossEntropyLoss()
    loss = loss_func(shift_logits.view(-1, shift_logits.size(-1)), shift_labels.view(-1))
    loss = loss / training_args.gradient_accumulation_steps
    
    accelerator.backward(loss)
    
    if step % training_args.gradient_accumulation_steps == 0:
        optimizer.step()
        optimizer.zero_grad()
```

```console
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Input In [47], in <cell line: 2>()
     20 if step % training_args.gradient_accumulation_steps == 0:
     21     print(loss.item())
---> 22     optimizer.step()
     23     optimizer.zero_grad()

File lib/python3.8/site-packages/accelerate/optimizer.py:128, in AcceleratedOptimizer.step(self, closure)
    126 elif self.scaler is not None:
    127     scale_before = self.scaler.get_scale()
--> 128     self.scaler.step(self.optimizer, closure)
    129     self.scaler.update()
    130     scale_after = self.scaler.get_scale()

File /lib/python3.8/site-packages/torch/cuda/amp/grad_scaler.py:336, in GradScaler.step(self, optimizer, *args, **kwargs)
    333 if optimizer_state["stage"] is OptState.READY:
    334     self.unscale_(optimizer)
--> 336 assert len(optimizer_state["found_inf_per_device"]) > 0, "No inf checks were recorded for this optimizer."
    338 retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
    340 optimizer_state["stage"] = OptState.STEPPED

AssertionError: No inf checks were recorded for this optimizer.

```

**Comment by Michael-H777** [comment]
@sgugger  any updates? i am also experiencing this problem with accelerate. 
since the release of pytorch 2.0, i wanted to try the compile feature of accelerate. i setup pytorch2.0+cu11.7 with python 3.10. 
when not compiling (just using fp16), the optimizer would work. but when trying to compile it breaks. (eager, inductor, nvfuser)

the codebase is very large, i can try to strip it down.

**Comment by rickywrq** [comment]
> @sgugger any updates? i am also experiencing this problem with accelerate. since the release of pytorch 2.0, i wanted to try the compile feature of accelerate. i setup pytorch2.0+cu11.7 with python 3.10. when not compiling (just using fp16), the optimizer would work. but when trying to compile it breaks. (eager, inductor, nvfuser)
> 
> the codebase is very large, i can try to strip it down.

Believe it or not. I end up arriving here after searching for the problem: `AssertionError: No inf checks were recorded for this optimizer`, although my code is not relevant to anything from hugging face. I am simply loading the weights and resuming the multi-gpu training with DistributedDataParallel + AMP/Mixed-Precision.

My finding is that the same code produces **different error messages with amp + PyTorch 1.x and 2.x.** In 1.x, the error message will be: `RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and CPU!` Surprisingly different, right?

So this leads me to the post: https://discuss.pytorch.org/t/loading-a-model-runtimeerror-expected-all-tensors-to-be-on-the-same-device-but-found-at-least-two-devices-cuda-0-and-cpu/143897/10 
which suggests moving the model to cuda before loading the weights. This can be easily neglected if anyone is using some examples snippets, i.e. [Link](https://github.com/pytorch/examples/blob/main/distributed/ddp-tutorial-series/multigpu.py), from official PyTorch docs.

**Comment by WXH-Olina** [comment]
Thanks @rickywrq Moving model to cuda before setting the optimizer solves my problem: `AssertionError: No inf checks were recorded for this optimizer`
