### ISSUE TITLE
UnboundLocalError: local variable 'fsdp_config' referenced before assignment

### ISSUE THREAD

**Issue by Nomiizz** [huggingface/accelerate#333]
There is an issue in the accelerate/commands/config/cluster.py file:

In which compute environment are you running? ([0] This machine, [1] AWS (Amazon SageMaker)): 0
Which type of machine are you using? ([0] No distributed training, [1] multi-CPU, [2] multi-GPU, [3] TPU): 0
Do you want to run your training on CPU only (even if a GPU is available)? [yes/NO]:yes
Do you want to use DeepSpeed? [yes/NO]: NO
How many processes in total will you use? [1]: 1
Do you wish to use FP16 or BF16 (mixed precision)? [NO/fp16/bf16]: NO
Traceback (most recent call last):
  File "/opt/conda/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/opt/conda/lib/python3.8/site-packages/accelerate/commands/config/__init__.py", line 64, in config_command
    config = get_user_input()
  File "/opt/conda/lib/python3.8/site-packages/accelerate/commands/config/__init__.py", line 37, in get_user_input
    config = get_cluster_input()
  File "/opt/conda/lib/python3.8/site-packages/accelerate/commands/config/cluster.py", line 165, in get_cluster_input
    fsdp_config=fsdp_config,
`UnboundLocalError: local variable 'fsdp_config' referenced before assignment`

**Comment by muellerzr** [comment]
Fixed with https://github.com/huggingface/accelerate/pull/331
