### ISSUE TITLE
ModuleNotFoundError: No module named 'packaging'

### ISSUE THREAD

**Issue by kakumarabhishek** [huggingface/accelerate#393]
Hi,

I tried installing Accelerate both using `pip` and from source, and in both the cases, importing `accelerate` led to a `ModuleNotFoundError`.

### **Installing with pip**

```
$ pip install accelerate
Collecting accelerate
  Downloading accelerate-0.9.0-py3-none-any.whl (106 kB)
     |████████████████████████████████| 106 kB 5.4 MB/s 
Requirement already satisfied: numpy>=1.17 in ./miniconda3/envs/hfaccl/lib/python3.10/site-packages (from accelerate) (1.22.3)
Collecting pyyaml
  Downloading PyYAML-6.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (682 kB)
     |████████████████████████████████| 682 kB 17.9 MB/s 
Requirement already satisfied: torch>=1.4.0 in ./miniconda3/envs/hfaccl/lib/python3.10/site-packages (from accelerate) (1.11.0)
Requirement already satisfied: typing_extensions in ./miniconda3/envs/hfaccl/lib/python3.10/site-packages (from torch>=1.4.0->accelerate) (4.1.1)
Installing collected packages: pyyaml, accelerate
Successfully installed accelerate-0.9.0 pyyaml-6.0

$ python 
Python 3.10.4 (main, Mar 31 2022, 08:41:55) [GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from accelerate import Accelerator
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/<PATH>/miniconda3/envs/hfaccl/lib/python3.10/site-packages/accelerate/__init__.py", line 7, in <module>
    from .accelerator import Accelerator
  File "/<PATH>/miniconda3/envs/hfaccl/lib/python3.10/site-packages/accelerate/accelerator.py", line 24, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'
```

### **Installing from source**

```
$ pip install git+https://github.com/huggingface/accelerate
Collecting git+https://github.com/huggingface/accelerate
  Cloning https://github.com/huggingface/accelerate to /tmp/pip-req-build-5_5o_ta0
  Running command git clone -q https://github.com/huggingface/accelerate /tmp/pip-req-build-5_5o_ta0
  Resolved https://github.com/huggingface/accelerate to commit 6be221f15e1278f67aca58be21d6c6e7ab695419
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: torch>=1.4.0 in ./miniconda3/envs/hfaccl/lib/python3.10/site-packages (from accelerate==0.10.0.dev0) (1.11.0)
Requirement already satisfied: pyyaml in ./miniconda3/envs/hfaccl/lib/python3.10/site-packages (from accelerate==0.10.0.dev0) (6.0)
Requirement already satisfied: numpy>=1.17 in ./miniconda3/envs/hfaccl/lib/python3.10/site-packages (from accelerate==0.10.0.dev0) (1.22.3)
Requirement already satisfied: typing_extensions in ./miniconda3/envs/hfaccl/lib/python3.10/site-packages (from torch>=1.4.0->accelerate==0.10.0.dev0) (4.1.1)
Building wheels for collected packages: accelerate
  Building wheel for accelerate (PEP 517) ... done
  Created wheel for accelerate: filename=accelerate-0.10.0.dev0-py3-none-any.whl size=106963 sha256=93c1dfc2f30c21979d8c2d625dc779e9f917298bb25c4e7d881921f6f9daa34f
  Stored in directory: /tmp/pip-ephem-wheel-cache-axmay_5w/wheels/f6/c7/9d/1b8a5ca8353d9307733bc719107acb67acdc95063bba749f26
Successfully built accelerate
Installing collected packages: accelerate
Successfully installed accelerate-0.10.0.dev0

$ python 
Python 3.10.4 (main, Mar 31 2022, 08:41:55) [GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from accelerate import Accelerator
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/<PATH>/miniconda3/envs/hfaccl/lib/python3.10/site-packages/accelerate/__init__.py", line 7, in <module>
    from .accelerator import Accelerator
  File "/<PATH>/miniconda3/envs/hfaccl/lib/python3.10/site-packages/accelerate/accelerator.py", line 24, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'
```

### **Fix**

Manually installing `packaging` seems to have fixed the issue.

```
$ pip install packaging
Collecting packaging
  Downloading packaging-21.3-py3-none-any.whl (40 kB)
     |████████████████████████████████| 40 kB 3.5 MB/s 
Collecting pyparsing!=3.0.5,>=2.0.2
  Downloading pyparsing-3.0.9-py3-none-any.whl (98 kB)
     |████████████████████████████████| 98 kB 3.6 MB/s 
Installing collected packages: pyparsing, packaging
Successfully installed packaging-21.3 pyparsing-3.0.9`

$ python 
Python 3.10.4 (main, Mar 31 2022, 08:41:55) [GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from accelerate import Accelerator
>>> accelerator = Accelerator(mixed_precision='bf16')
>>> accelerator
<accelerate.accelerator.Accelerator object at 0x7f35af75f4f0>
```

However, the installation check still throws an error:

```
$ python -c "TODO write"
  File "<string>", line 1
    TODO write
         ^^^^^
SyntaxError: invalid syntax
```

## **Environment details:**
- **OS:** Ubuntu 18.04.6 LTS
- **conda:** 4.12.0
- **Python:** 3.10.4
- **PyTorch:** 1.11.0
- **CUDA:**  11.3

**Comment by sgugger** [comment]
Oh, looks like it's missing from the setup indeed. Will add it this morning.
In the meantime, just do `pip install packaging` before trying to install Accelerate.
