### ISSUE TITLE
UnboundLocalError when running on Google Colab using TPU runtime

### ISSUE THREAD

**Issue by miguelvictor** [huggingface/accelerate#40]
**Steps to reproduce**

1. Open new Google Colab notebook and choose TPU runtime.
2. Install accelerate

   ```
   !pip install accelerate
   ```
3. Run `accelerate config`

   ```
   In which compute environment are you running? ([0] This machine, [1] AWS (Amazon SageMaker)): 0
   Which type of machine are you using? ([0] No distributed training, [1] multi-GPU, [2] TPU): 2
   What is the name of the function in your script that should be launched in all parallel scripts? [main]: 
   Traceback (most recent call last):
     File "/usr/local/bin/accelerate", line 8, in <module>
       sys.exit(main())
     File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/accelerate_cli.py", line 41, in main
       args.func(args)
     File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/config/__init__.py", line 64, in config_command
       config = get_user_input()
     File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/config/__init__.py", line 37, in get_user_input
       config = get_cluster_input()
     File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/config/cluster.py", line 81, in get_cluster_input
       num_processes=num_processes,
   UnboundLocalError: local variable 'num_processes' referenced before assignment
   ```

**Comment by philschmid** [comment]
Hello @miguelvictor 

Could you try `!pip install git+https://github.com/huggingface/accelerate` and installing from `master`.

**Comment by miguelvictor** [comment]
Hello!

I tried your suggestion and it worked. But i think there's another error:

```
WARNING:root:Waiting for TPU to be start up with version pytorch-1.8.1...
WARNING:root:Waiting for TPU to be start up with version pytorch-1.8.1...
WARNING:root:TPU has started up successfully with version pytorch-1.8.1

Running:  accelerate-launch /usr/local/lib/python3.7/dist-packages/accelerate/test_utils/test_script.py --config_file=/root/.cache/huggingface/accelerate/default_config.yaml
stderr: WARNING:root:TPU has started up successfully with version pytorch-1.8.1
stderr: Traceback (most recent call last):
stderr:   File "/usr/local/bin/accelerate-launch", line 8, in <module>
stderr:     sys.exit(main())
stderr:   File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 331, in main
stderr:     launch_command(args)
stderr:   File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 321, in launch_command
stderr:     tpu_launcher(args)
stderr:   File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 182, in tpu_launcher
stderr:     xmp.spawn(_AddOneArg(main_function), args=(), nprocs=args.num_processes)
stderr:   File "/usr/local/lib/python3.7/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 384, in spawn
stderr:     pf_cfg = _pre_fork_setup(nprocs)
stderr:   File "/usr/local/lib/python3.7/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 201, in _pre_fork_setup
stderr:     dev_count, num_devices))
stderr: ValueError: The number of devices must be either 1 or 8, got 4 instead
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/accelerate_cli.py", line 41, in main
    args.func(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/test.py", line 52, in test_command
    result = execute_subprocess_async(cmd, env=os.environ.copy())
  File "/usr/local/lib/python3.7/dist-packages/accelerate/test_utils/testing.py", line 135, in execute_subprocess_async
    f"'{cmd_str}' failed with returncode {result.returncode}\n\n"
RuntimeError: 'accelerate-launch /usr/local/lib/python3.7/dist-packages/accelerate/test_utils/test_script.py --config_file=/root/.cache/huggingface/accelerate/default_config.yaml' failed with returncode 1

The combined stderr from workers follows:
WARNING:root:TPU has started up successfully with version pytorch-1.8.1
Traceback (most recent call last):
  File "/usr/local/bin/accelerate-launch", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 331, in main
    launch_command(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 321, in launch_command
    tpu_launcher(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 182, in tpu_launcher
    xmp.spawn(_AddOneArg(main_function), args=(), nprocs=args.num_processes)
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 384, in spawn
    pf_cfg = _pre_fork_setup(nprocs)
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 201, in _pre_fork_setup
    dev_count, num_devices))
ValueError: The number of devices must be either 1 or 8, got 4 instead
```

My config file looks like this:

```
{
compute_environment: LOCAL_MACHINE, 
distributed_type: TPU, 
fp16: false, 
machine_rank: 0,
main_process_ip: null, 
main_process_port: null, 
main_training_function: main, 
num_machines: 1,
num_processes: 4
}
```

I installed xla and tpu libraries like this:

```
!pip install cloud-tpu-client https://storage.googleapis.com/tpu-pytorch/wheels/torch_xla-1.8.1-cp37-cp37m-linux_x86_64.whl
```

**Comment by philschmid** [comment]
> {
> compute_environment: LOCAL_MACHINE, 
> distributed_type: TPU, 
> fp16: false, 
> machine_rank: 0,
> main_process_ip: null, 
> main_process_port: null, 
> main_training_function: main, 
> num_machines: 1,
> num_processes: 4
> }

As the error says "The number of devices[`num_processes`] must be either 1 or 8, got 4 instead". If you adjust `num_processes` to `8` it works. I create a [small colab example](https://colab.research.google.com/drive/19iN7CMJD-8dA-qI59tejk_0Op5NHXDSQ?usp=sharing).
Or is there a specific reason why you defined `num_processes` as only 4?

**Comment by miguelvictor** [comment]
My apologies for misunderstanding that error message. I thought `devices` refer to the TPU core count and not the `num_process` in the config 😅. I just tried it and it works now. Thanks!
