### ISSUE TITLE
Adding accelerate to `transformer` mdoels

### ISSUE THREAD

**Issue by StellaAthena** [huggingface/accelerate#404]
Is there a guide to assign accelerate support to models that are already implemented in the `transformers` library?

**Comment by muellerzr** [comment]
We have many examples of this! Check out (most) any of the folders in transformers/examples/pytorch and look for scripts ending with no_trainer. They all use accelerate

Such as this QA example here: https://github.com/huggingface/transformers/blob/main/examples/pytorch/question-answering/run_qa_no_trainer.py

**Comment by StellaAthena** [comment]
Hmmm I think I miscommunicated. I would like to add support for accelerate to a model on the hub (specifically, GPT-NeoX and GPT-J) that doesn't currently have it. When I try to run the models with accelerate it says `GPTNeoXForCausalLM does not support `device_map='auto'`

**Comment by pacman100** [comment]
Hello, the error is due to `model._no_split_modules is None`. I think all you need to do is to have attribute  `_no_split_modules` in the corresponding model file. Please refer the PR [#17382](https://github.com/huggingface/transformers/pull/17382) which does this for OPT models.

**Comment by StellaAthena** [comment]
Thanks for the help! I'm now getting
```bash
05/29/2022 06:02:17 - INFO - __main__ - ***** Running training *****
05/29/2022 06:02:17 - INFO - __main__ -   Num examples = 73997
05/29/2022 06:02:17 - INFO - __main__ -   Num Epochs = 3
05/29/2022 06:02:17 - INFO - __main__ -   Instantaneous batch size per device = 1
05/29/2022 06:02:17 - INFO - __main__ -   Total train batch size (w. parallel, distributed & accumulation) = 8
05/29/2022 06:02:17 - INFO - __main__ -   Gradient Accumulation steps = 1
05/29/2022 06:02:17 - INFO - __main__ -   Total optimization steps = 27750
  0%|                                                                                                                                | 0/27750 [00:00<?, ?it/s]Traceback (most recent call last):
  File "examples/pytorch/language-modeling/run_clm_no_trainer.py", line 648, in <module>
Traceback (most recent call last):
  File "examples/pytorch/language-modeling/run_clm_no_trainer.py", line 648, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
  File "examples/pytorch/language-modeling/run_clm_no_trainer.py", line 648, in <module>
  File "examples/pytorch/language-modeling/run_clm_no_trainer.py", line 648, in <module>
Traceback (most recent call last):
  File "examples/pytorch/language-modeling/run_clm_no_trainer.py", line 648, in <module>
    main()
  File "examples/pytorch/language-modeling/run_clm_no_trainer.py", line 560, in main
    main()
  File "examples/pytorch/language-modeling/run_clm_no_trainer.py", line 560, in main
        main()main()

  File "examples/pytorch/language-modeling/run_clm_no_trainer.py", line 560, in main
  File "examples/pytorch/language-modeling/run_clm_no_trainer.py", line 560, in main
    outputs = model(**batch)
      File "/home/mchorse/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
main()
  File "examples/pytorch/language-modeling/run_clm_no_trainer.py", line 560, in main
    outputs = model(**batch)
  File "/home/mchorse/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
Traceback (most recent call last):
    outputs = model(**batch)
  File "examples/pytorch/language-modeling/run_clm_no_trainer.py", line 648, in <module>
  File "/home/mchorse/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    outputs = model(**batch)
  File "/home/mchorse/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    outputs = model(**batch)
  File "/home/mchorse/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/mchorse/.local/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    return forward_call(*input, **kwargs)
  File "/home/mchorse/.local/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
Traceback (most recent call last):
        return func(*args, **kwargs)  File "examples/pytorch/language-modeling/run_clm_no_trainer.py", line 648, in <module>

return forward_call(*input, **kwargs)  File "/home/mchorse/.local/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1616, in forward

  File "/home/mchorse/.local/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
Traceback (most recent call last):
    return forward_call(*input, **kwargs)      File "examples/pytorch/language-modeling/run_clm_no_trainer.py", line 648, in <module>
    
main()return func(*args, **kwargs)

  File "examples/pytorch/language-modeling/run_clm_no_trainer.py", line 560, in main
  File "/home/mchorse/.local/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
  File "/home/mchorse/.local/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1616, in forward
        return func(*args, **kwargs)return forward_call(*input, **kwargs)

  File "/home/mchorse/.local/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1616, in forward
  File "/home/mchorse/.local/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    return func(*args, **kwargs)
  File "/home/mchorse/.local/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1616, in forward
    return func(*args, **kwargs)
  File "/home/mchorse/.local/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1616, in forward
    outputs = model(**batch)
  File "/home/mchorse/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    loss = self.module(*inputs, **kwargs)
  File "/home/mchorse/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1071, in _call_impl
    main()
  File "examples/pytorch/language-modeling/run_clm_no_trainer.py", line 560, in main
    loss = self.module(*inputs, **kwargs)
  File "/home/mchorse/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1071, in _call_impl
    main()
  File "examples/pytorch/language-modeling/run_clm_no_trainer.py", line 560, in main
        return forward_call(*input, **kwargs)loss = self.module(*inputs, **kwargs)
    
    loss = self.module(*inputs, **kwargs)  File "/home/mchorse/.local/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
  File "/home/mchorse/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1071, in _call_impl
result = forward_call(*input, **kwargs)

  File "/home/mchorse/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1071, in _call_impl
  File "/home/mchorse/test/transformers/src/transformers/models/gpt_neox/modeling_gpt_neox.py", line 597, in forward
    outputs = model(**batch)
  File "/home/mchorse/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    loss = self.module(*inputs, **kwargs)
          File "/home/mchorse/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1071, in _call_impl
result = forward_call(*input, **kwargs)return func(*args, **kwargs)

  File "/home/mchorse/test/transformers/src/transformers/models/gpt_neox/modeling_gpt_neox.py", line 597, in forward
  File "/home/mchorse/.local/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1616, in forward
    outputs = model(**batch)
  File "/home/mchorse/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    outputs = self.gpt_neox(
  File "/home/mchorse/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1071, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/mchorse/test/transformers/src/transformers/models/gpt_neox/modeling_gpt_neox.py", line 597, in forward
    return forward_call(*input, **kwargs)    
outputs = self.gpt_neox(
  File "/home/mchorse/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1071, in _call_impl
  File "/home/mchorse/.local/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
        result = forward_call(*input, **kwargs)result = forward_call(*input, **kwargs)

  File "/home/mchorse/test/transformers/src/transformers/models/gpt_neox/modeling_gpt_neox.py", line 597, in forward
  File "/home/mchorse/test/transformers/src/transformers/models/gpt_neox/modeling_gpt_neox.py", line 597, in forward
    return func(*args, **kwargs)
  File "/home/mchorse/.local/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1616, in forward
    loss = self.module(*inputs, **kwargs)
  File "/home/mchorse/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1071, in _call_impl
    result = forward_call(*input, **kwargs)    
outputs = self.gpt_neox(  File "/home/mchorse/test/transformers/src/transformers/models/gpt_neox/modeling_gpt_neox.py", line 489, in forward

  File "/home/mchorse/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1071, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/mchorse/.local/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    result = forward_call(*input, **kwargs)
  File "/home/mchorse/test/transformers/src/transformers/models/gpt_neox/modeling_gpt_neox.py", line 489, in forward
    outputs = self.gpt_neox(
  File "/home/mchorse/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1071, in _call_impl
    outputs = layer(
      File "/home/mchorse/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1071, in _call_impl
    outputs = self.gpt_neox(return func(*args, **kwargs)

  File "/home/mchorse/.local/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1616, in forward
      File "/home/mchorse/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1071, in _call_impl
result = forward_call(*input, **kwargs)
  File "/home/mchorse/test/transformers/src/transformers/models/gpt_neox/modeling_gpt_neox.py", line 597, in forward
            outputs = layer(result = forward_call(*input, **kwargs)loss = self.module(*inputs, **kwargs)


  File "/home/mchorse/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1071, in _call_impl
  File "/home/mchorse/test/transformers/src/transformers/models/gpt_neox/modeling_gpt_neox.py", line 489, in forward
  File "/home/mchorse/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1071, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/mchorse/test/transformers/src/transformers/models/gpt_neox/modeling_gpt_neox.py", line 489, in forward
    outputs = self.gpt_neox(    
result = forward_call(*input, **kwargs)  File "/home/mchorse/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1071, in _call_impl

  File "/home/mchorse/test/transformers/src/transformers/models/gpt_neox/modeling_gpt_neox.py", line 297, in forward
    outputs = layer(
  File "/home/mchorse/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1071, in _call_impl
        result = forward_call(*input, **kwargs)result = forward_call(*input, **kwargs)

  File "/home/mchorse/test/transformers/src/transformers/models/gpt_neox/modeling_gpt_neox.py", line 597, in forward
          File "/home/mchorse/test/transformers/src/transformers/models/gpt_neox/modeling_gpt_neox.py", line 297, in forward
    result = forward_call(*input, **kwargs)attention_layer_outputs = self.attention(    outputs = layer(

loss = self.module(*inputs, **kwargs)
  File "/home/mchorse/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1071, in _call_impl

  File "/home/mchorse/test/transformers/src/transformers/models/gpt_neox/modeling_gpt_neox.py", line 489, in forward
  File "/home/mchorse/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1071, in _call_impl
  File "/home/mchorse/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1071, in _call_impl
    result = forward_call(*input, **kwargs)
      File "/home/mchorse/test/transformers/src/transformers/models/gpt_neox/modeling_gpt_neox.py", line 489, in forward
attention_layer_outputs = self.attention(
      File "/home/mchorse/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1071, in _call_impl
result = forward_call(*input, **kwargs)
  File "/home/mchorse/test/transformers/src/transformers/models/gpt_neox/modeling_gpt_neox.py", line 297, in forward
    outputs = self.gpt_neox(
  File "/home/mchorse/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1071, in _call_impl
    outputs = layer(
  File "/home/mchorse/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1071, in _call_impl
        attention_layer_outputs = self.attention(result = forward_call(*input, **kwargs)        

result = forward_call(*input, **kwargs)outputs = layer(  File "/home/mchorse/test/transformers/src/transformers/models/gpt_neox/modeling_gpt_neox.py", line 149, in forward

  File "/home/mchorse/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1071, in _call_impl

      File "/home/mchorse/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1071, in _call_impl
  File "/home/mchorse/test/transformers/src/transformers/models/gpt_neox/modeling_gpt_neox.py", line 297, in forward
result = forward_call(*input, **kwargs)
  File "/home/mchorse/test/transformers/src/transformers/models/gpt_neox/modeling_gpt_neox.py", line 597, in forward
    result = forward_call(*input, **kwargs)    
result = forward_call(*input, **kwargs)  File "/home/mchorse/test/transformers/src/transformers/models/gpt_neox/modeling_gpt_neox.py", line 149, in forward

  File "/home/mchorse/test/transformers/src/transformers/models/gpt_neox/modeling_gpt_neox.py", line 489, in forward
    attn_output, attn_weights = self._attn(query, key, value, attention_mask, head_mask)
  File "/home/mchorse/test/transformers/src/transformers/models/gpt_neox/modeling_gpt_neox.py", line 209, in _attn
    attention_layer_outputs = self.attention(
  File "/home/mchorse/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1071, in _call_impl
    attn_output, attn_weights = self._attn(query, key, value, attention_mask, head_mask)
  File "/home/mchorse/test/transformers/src/transformers/models/gpt_neox/modeling_gpt_neox.py", line 209, in _attn
            raise RuntimeError()outputs = layer(result = forward_call(*input, **kwargs)


      File "/home/mchorse/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1071, in _call_impl
outputs = self.gpt_neox(  File "/home/mchorse/test/transformers/src/transformers/models/gpt_neox/modeling_gpt_neox.py", line 297, in forward

      File "/home/mchorse/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1071, in _call_impl
RuntimeErrorresult = forward_call(*input, **kwargs)    

raise RuntimeError()  File "/home/mchorse/test/transformers/src/transformers/models/gpt_neox/modeling_gpt_neox.py", line 149, in forward

    result = forward_call(*input, **kwargs)RuntimeError

  File "/home/mchorse/test/transformers/src/transformers/models/gpt_neox/modeling_gpt_neox.py", line 297, in forward
    result = forward_call(*input, **kwargs)
  File "/home/mchorse/test/transformers/src/transformers/models/gpt_neox/modeling_gpt_neox.py", line 149, in forward
    attn_output, attn_weights = self._attn(query, key, value, attention_mask, head_mask)
  File "/home/mchorse/test/transformers/src/transformers/models/gpt_neox/modeling_gpt_neox.py", line 209, in _attn
            attention_layer_outputs = self.attention(attention_layer_outputs = self.attention(    
attn_output, attn_weights = self._attn(query, key, value, attention_mask, head_mask)

result = forward_call(*input, **kwargs)      File "/home/mchorse/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1071, in _call_impl
  File "/home/mchorse/test/transformers/src/transformers/models/gpt_neox/modeling_gpt_neox.py", line 209, in _attn
  File "/home/mchorse/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1071, in _call_impl

raise RuntimeError()
  File "/home/mchorse/test/transformers/src/transformers/models/gpt_neox/modeling_gpt_neox.py", line 297, in forward
RuntimeError
    raise RuntimeError()
    result = forward_call(*input, **kwargs)
RuntimeError      File "/home/mchorse/test/transformers/src/transformers/models/gpt_neox/modeling_gpt_neox.py", line 489, in forward
attention_layer_outputs = self.attention(

  File "/home/mchorse/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1071, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/mchorse/test/transformers/src/transformers/models/gpt_neox/modeling_gpt_neox.py", line 149, in forward
    attn_output, attn_weights = self._attn(query, key, value, attention_mask, head_mask)
  File "/home/mchorse/test/transformers/src/transformers/models/gpt_neox/modeling_gpt_neox.py", line 209, in _attn
    outputs = layer(    
result = forward_call(*input, **kwargs)      File "/home/mchorse/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1071, in _call_impl

result = forward_call(*input, **kwargs)
  File "/home/mchorse/test/transformers/src/transformers/models/gpt_neox/modeling_gpt_neox.py", line 149, in forward
  File "/home/mchorse/test/transformers/src/transformers/models/gpt_neox/modeling_gpt_neox.py", line 149, in forward
    raise RuntimeError()
RuntimeError
    attn_output, attn_weights = self._attn(query, key, value, attention_mask, head_mask)
  File "/home/mchorse/test/transformers/src/transformers/models/gpt_neox/modeling_gpt_neox.py", line 209, in _attn
    attn_output, attn_weights = self._attn(query, key, value, attention_mask, head_mask)
  File "/home/mchorse/test/transformers/src/transformers/models/gpt_neox/modeling_gpt_neox.py", line 209, in _attn
    raise RuntimeError()
    RuntimeErrorresult = forward_call(*input, **kwargs)

  File "/home/mchorse/test/transformers/src/transformers/models/gpt_neox/modeling_gpt_neox.py", line 297, in forward
    raise RuntimeError()
    attention_layer_outputs = self.attention(
  File "/home/mchorse/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1071, in _call_impl
RuntimeError
    result = forward_call(*input, **kwargs)
  File "/home/mchorse/test/transformers/src/transformers/models/gpt_neox/modeling_gpt_neox.py", line 149, in forward
    attn_output, attn_weights = self._attn(query, key, value, attention_mask, head_mask)
  File "/home/mchorse/test/transformers/src/transformers/models/gpt_neox/modeling_gpt_neox.py", line 209, in _attn
    raise RuntimeError()
RuntimeError
  0%|                                                                                                                                | 0/27750 [00:01<?, ?it/s]
[2022-05-29 06:02:23,480] [INFO] [launch.py:178:sigkill_handler] Killing subprocess 282026
[2022-05-29 06:02:23,480] [INFO] [launch.py:178:sigkill_handler] Killing subprocess 282027
[2022-05-29 06:02:23,480] [INFO] [launch.py:178:sigkill_handler] Killing subprocess 282028
[2022-05-29 06:02:23,480] [INFO] [launch.py:178:sigkill_handler] Killing subprocess 282029
[2022-05-29 06:02:23,480] [INFO] [launch.py:178:sigkill_handler] Killing subprocess 282030
[2022-05-29 06:02:23,480] [INFO] [launch.py:178:sigkill_handler] Killing subprocess 282031
[2022-05-29 06:02:23,480] [INFO] [launch.py:178:sigkill_handler] Killing subprocess 282032
[2022-05-29 06:02:23,480] [INFO] [launch.py:178:sigkill_handler] Killing subprocess 282077
[2022-05-29 06:02:23,480] [ERROR] [launch.py:184:sigkill_handler] ['/usr/bin/python3', '-u', 'examples/pytorch/language-modeling/run_clm_no_trainer.py', '--model_name_or_path', 'EleutherAI/gpt-neox-20b', '--dataset_name', 'wikitext_tl39'] exits with return code = 1
Traceback (most recent call last):
  File "/home/mchorse/.local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/mchorse/.local/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/home/mchorse/.local/lib/python3.8/site-packages/accelerate/commands/launch.py", line 524, in launch_command
    deepspeed_launcher(args)
  File "/home/mchorse/.local/lib/python3.8/site-packages/accelerate/commands/launch.py", line 332, in deepspeed_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['deepspeed', '--no_local_rank', '--num_gpus', '8', 'examples/pytorch/language-modeling/run_clm_no_trainer.py', '--model_name_or_path', 'EleutherAI/gpt-neox-20b', '--dataset_name', 'wikitext_tl39']' returned non-zero exit status 1.
```
But I don't think that has anything to do with Accelerate.

**Comment by sgugger** [comment]
Note that for the first issue, you just need to implement the `_no_split_modules` attribute for `GPTNeoXPreTrainedModel` as is done [here](https://github.com/huggingface/transformers/blob/main/src/transformers/models/gpt2/modeling_gpt2.py#L451) for GPT-2.

**Comment by ZeyiLiao** [comment]
@sgugger , Hi , I also encounter a same problem here though passing the `no_split_modules`. I wanna do training on "EleutherAI/gpt-neox-20b"

```
    if args.config_name:
        config = AutoConfig.from_pretrained(args.config_name)
    elif args.model_name_or_path:
        config = AutoConfig.from_pretrained(args.model_name_or_path)

    if '20b' in args.model_name_or_path:
        with init_empty_weights():
            model = AutoModelForCausalLM.from_config(config)
        model = load_checkpoint_and_dispatch(
            model, args.model_name_or_path, device_map="auto",no_split_module_classes  = ["GPTNeoXLayer"])

```
