### ISSUE TITLE
run finisied but subprocess not killed automatically

### ISSUE THREAD

**Issue by drinkingxi** [huggingface/accelerate#486]
### System Info

```Shell
- `Accelerate` version: 0.10.0
- Platform: Linux-5.13.0-27-generic-x86_64-with-debian-bullseye-sid
- Python version: 3.7.13
- Numpy version: 1.21.5
- PyTorch version (GPU?): 1.7.1+cu110 (True)
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: MULTI_GPU
        - mixed_precision: no
        - use_cpu: False
        - num_processes: 4
        - machine_rank: 0
        - num_machines: 1
        - main_process_ip: None
        - main_process_port: None
        - main_training_function: main
        - deepspeed_config: {}
        - fsdp_config: {}
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

Every time the task is finished, the main process closed normally. However the subprocesses keep running and I have to kill them manually with `kill pid`. 

Besides, in the output log I can found traceback below. 
```
Traceback (most recent call last):
  File "/anaconda3/envs/env-msmn/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/anaconda3/envs/env-msmn/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/anaconda3/envs/env-msmn/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/anaconda3/envs/env-msmn/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/anaconda3/envs/env-msmn/bin/python', '-u', 'main.py', '--batch_size', '64']' died with <Signals.SIGTERM: 15>.
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
```

And here is how I use Accelerate in my code
```
kwargs_handlers = [DistributedDataParallelKwargs(find_unused_parameters=True)]
accelerator = Accelerator(kwargs_handlers=kwargs_handlers, split_batches=True)  
model = generate_model(args, train_dataset).to(accelerator.device)
model, optimizer, train_dataloader = accelerator.prepare(model, optimizer, train_dataloader)
```

### Expected behavior

```Shell
Although the bug doesn't affect the performance, but once the run finishes, I have to hurry to kill the subprocesses left to avoid the occupation of gpu. It's quite annoying.
```

**Comment by sgugger** [comment]
This has been fixed directly in PyTorch, so I'd suggest upgrading your PyTorch installation (I think to 1.9 at least) :-)
