### ISSUE TITLE
bug when using R-Drop 

### ISSUE THREAD

**Issue by Lijiadong** [huggingface/accelerate#538]
### System Info

```Shell
- `Accelerate` version: 0.9.0
- Platform: Linux-3.10.0-1127.19.1.el7.x86_64-x86_64-with-centos-7.9.2009-Core
- Python version: 3.6.13
- Numpy version: 1.17.0
- PyTorch version (GPU?): 1.10.0+cu111 (True)
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: MULTI_GPU        - mixed_precision: no
        - use_cpu: False
        - num_processes: 8
        - machine_rank: 0
        - num_machines: 1
        - main_process_ip: None
        - main_process_port: None
        - main_training_function: main
        - deepspeed_config: {}
        - fsdp_config: {}
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

First,I can normally train my model without R-Drop,envery thing goes well;
Than,when use **R-Drop**,implementation(model was prepared by `accelerator.prepare`:
```python
def compute_kl_loss(p, q):
    p_loss = F.kl_div(F.log_softmax(p, dim=-1), F.softmax(q, dim=-1), reduction='none')
    q_loss = F.kl_div(F.log_softmax(q, dim=-1), F.softmax(p, dim=-1), reduction='none')

    # You can choose whether to use function "sum" and "mean" depending on your task
    q_loss = q_loss.mean()
    p_loss = p_loss.mean()

    loss = (p_loss + q_loss) / 2
    return loss
```
```python
for step, batch in enumerate(train_dataloader):
          if args.rdrop:
              outputs_1 = model(**batch)
              outputs_2 = model(**batch)
              loss_1 = outputs_1['loss']
              loss_2 = outputs_2['loss']
              ce_loss = 0.5*(loss_1 + loss_2)
              kl_loss = compute_kl_loss(outputs_1['logits'], outputs_2['logits'])
              loss = ce_loss + 4 * kl_loss
              logger.info(f'step: {step}')
          else:
              outputs = model(**batch)
              loss = outputs['loss']
```
**bug output**:
```bash
**Epoch: 0**:   0%|          | 0/11939 [00:00<?, ?it/s]07/20/2022 16:55:01 - INFO - __main__ - step: 0
Traceback (most recent call last):
  File "run_train.py", line 592, in <module>
    main()
  File "run_train.py", line 468, in main
    accelerator.backward(loss)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/accelerate/accelerator.py", line 620, in backward
    loss.backward(**kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 156, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.LongTensor [16, 256]] is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
```
**when i only use the ce_loss, output is same**.
```python
for step, batch in enumerate(train_dataloader):
          if args.rdrop:
              outputs_1 = model(**batch)
              outputs_2 = model(**batch)
              loss_1 = outputs_1['loss']
              loss_2 = outputs_2['loss']
              ce_loss = 0.5*(loss_1 + loss_2)
              # kl_loss = compute_kl_loss(outputs_1['logits'], outputs_2['logits'])
              loss = ce_loss # + 4 * kl_loss
              logger.info(f'step: {step}')
          else:
              outputs = model(**batch)
              loss = outputs['loss']
```
seems like something went wrong when i forward the model twice.

### Expected behavior

```Shell
normally training
```

**Comment by Lijiadong** [comment]
problem is model(**batch) twice
tried add `_ = model(**batch)` in none rdrop mode, get the same error.

**Comment by Lijiadong** [comment]
problem is model(**batch) twice
tried add _ = model(**batch) in none rdrop mode, get the same error.
