### ISSUE TITLE
OPT-66b Multi-GPU Inference Issue

### ISSUE THREAD

**Issue by jhou-23** [huggingface/accelerate#636]
Hi,

For my purposes, I'm trying to run inference on the OPT-66B model on a ~400 char string with a Multi-GPU machine (4x NVIDIA RTX A6000 48GB). The program is run in a docker container (1.12.0-cuda11.3-cudnn8-devel) and my library versions are
- transformers - 4.22.0.dev0 (i tried with pip version and yielded same result)
- accelerate -  0.13.0.dev0

My accelerate config is

```
In which compute environment are you running? ([0] This machine, [1] AWS (Amazon SageMaker)): 0
Which type of machine are you using? ([0] No distributed training, [1] multi-CPU, [2] multi-GPU, [3] TPU [4] MPS): 2
How many different machines will you use (use more than 1 for multi-node training)? [1]: 1
Do you want to use DeepSpeed? [yes/NO]: NO
Do you want to use FullyShardedDataParallel? [yes/NO]: NO
How many GPU(s) should be used for distributed training? [1]:4
Do you wish to use FP16 or BF16 (mixed precision)? [NO/fp16/bf16]: fp16
```

and the relevant code (looking through past issues I saw `init_empty_weights`, `load_checkpoint_and_dispatch` being used but `from_pretrained` seemed the most up to date) 

```
import transformers
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch
from accelerate import Accelerator

accelerator = Accelerator()

accelerator.print("--------------------1")
checkpoint = "facebook/opt-66b"
model = AutoModelForCausalLM.from_pretrained("facebook/opt-66b", torch_dtype=torch.float16, device_map="auto")
model = accelerate.prepare(model)
```

which when run yields

```
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    device_map="auto"
  File "/opt/conda/lib/python3.7/site-packages/transformers/models/auto/auto_factory.py", line 464, in from_pretrained
    pretrained_model_name_or_path, *model_args, config=config, **hub_kwargs, **kwargs
  File "/opt/conda/lib/python3.7/site-packages/transformers/modeling_utils.py", line 2236, in from_pretrained
    load_in_8bit=load_in_8bit,
  File "/opt/conda/lib/python3.7/site-packages/transformers/modeling_utils.py", line 2455, in _load_pretrained_model
    load_in_8bit=load_in_8bit,
  File "/opt/conda/lib/python3.7/site-packages/transformers/modeling_utils.py", line 574, in _load_state_dict_into_meta_model
    set_module_tensor_to_device(model, param_name, param_device, value=param)
  File "/opt/conda/lib/python3.7/site-packages/accelerate/utils/modeling.py", line 124, in set_module_tensor_to_device
    new_value = value.to(device)
RuntimeError: CUDA out of memory. Tried to allocate 648.00 MiB (GPU 0; 47.54 GiB total capacity; 9.76 GiB already allocated; 112.25 MiB free; 9.76 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    device_map="auto"
  File "/opt/conda/lib/python3.7/site-packages/transformers/models/auto/auto_factory.py", line 464, in from_pretrained
    pretrained_model_name_or_path, *model_args, config=config, **hub_kwargs, **kwargs
  File "/opt/conda/lib/python3.7/site-packages/transformers/modeling_utils.py", line 2236, in from_pretrained
    load_in_8bit=load_in_8bit,
  File "/opt/conda/lib/python3.7/site-packages/transformers/modeling_utils.py", line 2455, in _load_pretrained_model
    load_in_8bit=load_in_8bit,
  File "/opt/conda/lib/python3.7/site-packages/transformers/modeling_utils.py", line 574, in _load_state_dict_into_meta_model
    set_module_tensor_to_device(model, param_name, param_device, value=param)
  File "/opt/conda/lib/python3.7/site-packages/accelerate/utils/modeling.py", line 124, in set_module_tensor_to_device
    new_value = value.to(device)
RuntimeError: CUDA out of memory. Tried to allocate 162.00 MiB (GPU 0; 47.54 GiB total capacity; 10.55 GiB already allocated; 112.25 MiB free; 10.55 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    device_map="auto"
  File "/opt/conda/lib/python3.7/site-packages/transformers/models/auto/auto_factory.py", line 464, in from_pretrained
    pretrained_model_name_or_path, *model_args, config=config, **hub_kwargs, **kwargs
  File "/opt/conda/lib/python3.7/site-packages/transformers/modeling_utils.py", line 2236, in from_pretrained
    load_in_8bit=load_in_8bit,
  File "/opt/conda/lib/python3.7/site-packages/transformers/modeling_utils.py", line 2455, in _load_pretrained_model
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    device_map="auto"
  File "/opt/conda/lib/python3.7/site-packages/transformers/models/auto/auto_factory.py", line 464, in from_pretrained
    load_in_8bit=load_in_8bit,
  File "/opt/conda/lib/python3.7/site-packages/transformers/modeling_utils.py", line 574, in _load_state_dict_into_meta_model
    pretrained_model_name_or_path, *model_args, config=config, **hub_kwargs, **kwargs
  File "/opt/conda/lib/python3.7/site-packages/transformers/modeling_utils.py", line 2236, in from_pretrained
    set_module_tensor_to_device(model, param_name, param_device, value=param)
  File "/opt/conda/lib/python3.7/site-packages/accelerate/utils/modeling.py", line 124, in set_module_tensor_to_device
    new_value = value.to(device)
RuntimeError: CUDA out of memory. Tried to allocate 162.00 MiB (GPU 0; 47.54 GiB total capacity; 10.39 GiB already allocated; 112.25 MiB free; 10.39 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
    load_in_8bit=load_in_8bit,
  File "/opt/conda/lib/python3.7/site-packages/transformers/modeling_utils.py", line 2455, in _load_pretrained_model
    load_in_8bit=load_in_8bit,
  File "/opt/conda/lib/python3.7/site-packages/transformers/modeling_utils.py", line 574, in _load_state_dict_into_meta_model
    set_module_tensor_to_device(model, param_name, param_device, value=param)
  File "/opt/conda/lib/python3.7/site-packages/accelerate/utils/modeling.py", line 124, in set_module_tensor_to_device
    new_value = value.to(device)
RuntimeError: CUDA out of memory. Tried to allocate 162.00 MiB (GPU 0; 47.54 GiB total capacity; 10.39 GiB already allocated; 112.25 MiB free; 10.39 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 19384) of binary: /opt/conda/bin/python
Traceback (most recent call last):
  File "/opt/conda/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/opt/conda/lib/python3.7/site-packages/accelerate/commands/launch.py", line 842, in launch_command
    multi_gpu_launcher(args)
  File "/opt/conda/lib/python3.7/site-packages/accelerate/commands/launch.py", line 446, in multi_gpu_launcher
    distrib_run.run(distrib_args)
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/run.py", line 755, in run
    )(*cmd_args)
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 247, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
```

Looking at the RuntimeError message, it is strange that the total capacity is no where near fully utilized, which is also reflected in an nvidia-smi check

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.57       Driver Version: 515.57       CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA RTX A6000    Off  | 00000000:01:00.0 Off |                  Off |
| 30%   48C    P2    84W / 300W |  48571MiB / 49140MiB |     32%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA RTX A6000    Off  | 00000000:41:00.0 Off |                  Off |
| 30%   43C    P2    78W / 300W |   6487MiB / 49140MiB |      3%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA RTX A6000    Off  | 00000000:81:00.0 Off |                  Off |
| 30%   48C    P2    76W / 300W |   6487MiB / 49140MiB |      2%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA RTX A6000    Off  | 00000000:C1:00.0 Off |                  Off |
| 30%   44C    P2    83W / 300W |   6487MiB / 49140MiB |      2%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     18590      C   ray::ImplicitFunc.train()        1283MiB |
|    0   N/A  N/A     35474      C   ray::ImplicitFunc.train()        1283MiB |
|    0   N/A  N/A     36662      C   ray::ImplicitFunc.train()        1283MiB |
|    0   N/A  N/A     38610      C   /opt/conda/bin/python           10653MiB |
|    0   N/A  N/A     38611      C   /opt/conda/bin/python           11949MiB |
|    0   N/A  N/A     38612      C   /opt/conda/bin/python           11463MiB |
|    0   N/A  N/A     38613      C   /opt/conda/bin/python           10653MiB |
|    1   N/A  N/A     18632      C   ray::ImplicitFunc.train()        1283MiB |
|    1   N/A  N/A     28211      C   ray::ImplicitFunc.train()        1283MiB |
|    1   N/A  N/A     34844      C   ray::ImplicitFunc.train()        1283MiB |
|    1   N/A  N/A     38610      C   /opt/conda/bin/python             659MiB |
|    1   N/A  N/A     38611      C   /opt/conda/bin/python             659MiB |
|    1   N/A  N/A     38612      C   /opt/conda/bin/python             659MiB |
|    1   N/A  N/A     38613      C   /opt/conda/bin/python             659MiB |
|    2   N/A  N/A     18634      C   ray::ImplicitFunc.train()        1283MiB |
|    2   N/A  N/A     24441      C   ray::ImplicitFunc.train()        1283MiB |
|    2   N/A  N/A     34392      C   ray::ImplicitFunc.train()        1283MiB |
|    2   N/A  N/A     38610      C   /opt/conda/bin/python             659MiB |
|    2   N/A  N/A     38611      C   /opt/conda/bin/python             659MiB |
|    2   N/A  N/A     38612      C   /opt/conda/bin/python             659MiB |
|    2   N/A  N/A     38613      C   /opt/conda/bin/python             659MiB |
|    3   N/A  N/A     18636      C   ray::ImplicitFunc.train()        1283MiB |
|    3   N/A  N/A     20269      C   ray::ImplicitFunc.train()        1283MiB |
|    3   N/A  N/A     35129      C   ray::ImplicitFunc.train()        1283MiB |
|    3   N/A  N/A     38610      C   /opt/conda/bin/python             659MiB |
|    3   N/A  N/A     38611      C   /opt/conda/bin/python             659MiB |
|    3   N/A  N/A     38612      C   /opt/conda/bin/python             659MiB |
|    3   N/A  N/A     38613      C   /opt/conda/bin/python             659MiB |
+-----------------------------------------------------------------------------+
```

Any solution to this would be much appreciated. Thanks in advance!

**Comment by sgugger** [comment]
Hi there! The generation requires more space on GPU-0, especially for long sentences. One way around this is to use `device_map="balanced_low_0"` so that the weights of the models are balanced across GPUs, except GPU 0 (which is going to be kept free to do all generation work). It requires a source install on Transformers and the latest Accelerate.
