### ISSUE TITLE
Custom names for the runs in W&B logger

### ISSUE THREAD

**Issue by mrsalehi** [huggingface/accelerate#691]
Hi,

I want to log my runs with wandb using accelerator tracker. I realized that there is no way to set a custom name for a run in Wandb tracker and it just sets the project name. Therefore all of my runs will get random names that Wandb API assigns. 

The following is the code of constructor for WandBTracker:
```
class WandBTracker(GeneralTracker):
    """
    A `Tracker` class that supports `wandb`. Should be initialized at the start of your script.

    Args:
        run_name (`str`):
            The name of the experiment run.
    """

    requires_logging_directory = False

    def __init__(self, run_name: str):
        self.run_name = run_name
        self.run = wandb.init(project=self.run_name)
        logger.info(f"Initialized WandB project {self.run_name}")
        logger.info(
            "Make sure to log any initial configurations with `self.store_init_configuration` before training!"
        )
```

Only project argument is passed to the constructor of wandb and there is no way to pass run name. I was wondering if we can add this feature. I think the implementation is pretty straightforward.

**Comment by pacman100** [comment]
Hello @mrsalehi, this is already being supported by the latest 🤗 accelerate repo. Please follow the below code snippet on how to go about it:

```
from accelerate import Accelerator

accelerator = Accelerator(log_with="wandb")
accelerator.init_trackers("InterestingProject", config={}, init_kwargs={"wandb":{"name":"Idea10"}})
``` 
![Screenshot 2022-09-10 at 6 27 45 PM](https://user-images.githubusercontent.com/13534540/189484394-c1fbbf73-6074-401a-8cb1-18d8ccc5f2ae.png)

**Comment by mrsalehi** [comment]
Awesome thanks! I forgot to check the main branch. Then I will go ahead and close this.

**Comment by ZeyiLiao** [comment]
@pacman100 Hi, I can successfully save the model and log via wandb, however, the code can not exit successfully.

Error:
```
Configuration saved in ./gpt2-large-f0da480b-0113-4cb5-a7b2-4d4a0141bc89/config.json
Model weights saved in ./gpt2-large-f0da480b-0113-4cb5-a7b2-4d4a0141bc89/pytorch_model.bin
tokenizer config file saved in ./gpt2-large-f0da480b-0113-4cb5-a7b2-4d4a0141bc89/tokenizer_config.json
Special tokens file saved in ./gpt2-large-f0da480b-0113-4cb5-a7b2-4d4a0141bc89/special_tokens_map.json
100%|████████████████████████████████████████████████████████████████████████████| 88/88 [02:58<00:00,  2.03s/it]
Exception in thread SockSrvRdThr:
Traceback (most recent call last):
  File "/home/zeyi/miniconda3/envs/longtail/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/zeyi/miniconda3/envs/longtail/lib/python3.7/site-packages/wandb/sdk/service/server_sock.py", line 112, in run
    shandler(sreq)
  File "/home/zeyi/miniconda3/envs/longtail/lib/python3.7/site-packages/wandb/sdk/service/server_sock.py", line 173, in server_record_publish
    iface = self._mux.get_stream(stream_id).interface
  File "/home/zeyi/miniconda3/envs/longtail/lib/python3.7/site-packages/wandb/sdk/service/streams.py", line 199, in get_stream
    stream = self._streams[stream_id]
KeyError: '2xe5hau2'
```
