### ISSUE TITLE
Error in running multi GPU model

### ISSUE THREAD

**Issue by Tangzy7** [huggingface/accelerate#72]
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:761, internal error, NCCL version 2.7.8
ncclInternalError: Internal check failed. This is either a bug in NCCL or due to memory corruption

**Comment by sgugger** [comment]
It's a bit hard to help without knowing how you got that error. Could you tell us more?

**Comment by Tangzy7** [comment]
> It's a bit hard to help without knowing how you got that error. Could you tell us more?

I run in multi GPUs with Accelerate config and launcher:

my accelerate config like these:
```
In which compute environment are you running? ([0] This machine, [1] AWS (Amazon SageMaker)): 0
Which type of machine are you using? ([0] No distributed training, [1] multi-GPU, [2] TPU): 1
How many different machines will you use (use more than 1 for multi-node training)? [1]: 1
How many processes in total will you use? [1]: 2
Do you wish to use FP16 (mixed precision)? [yes/NO]: yes
```
I got one machine and two GPUs.  I enable NCCL_DEBUG=INFO and started training
`accelerate launch --cpu ./nlp_example.py`

Then I got error.

```
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:825, unhandled system error, NCCL version 2.7.8
ncclSystemError: System call (socket, malloc, munmap, etc) failed.
Killing subprocess 24973
Killing subprocess 24974
Traceback (most recent call last):
  File "/dockerdata/zhiyaotang/py36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/dockerdata/zhiyaotang/py36/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/dockerdata/zhiyaotang/py36/lib/python3.6/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/dockerdata/zhiyaotang/py36/lib/python3.6/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/dockerdata/zhiyaotang/py36/lib/python3.6/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/dockerdata/zhiyaotang/py36/bin/python3.6', '-u', './nlp_example.py']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/dockerdata/zhiyaotang/py36/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/dockerdata/zhiyaotang/py36/lib/python3.6/site-packages/accelerate/commands/accelerate_cli.py", line 41, in main
    args.func(args)
  File "/dockerdata/zhiyaotang/py36/lib/python3.6/site-packages/accelerate/commands/launch.py", line 307, in launch_command
    multi_gpu_launcher(args)
  File "/dockerdata/zhiyaotang/py36/lib/python3.6/site-packages/accelerate/commands/launch.py", line 151, in multi_gpu_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/dockerdata/zhiyaotang/py36/bin/python3.6', '-m', 'torch.distributed.launch', '--use_env', '--nproc_per_node', '2', './nlp_example.py']' returned non-zero exit status 1.
```

**Comment by sgugger** [comment]
Just to double-check:
```
python -m torch.distributed.launch --nproc_per_node 2 --use_env ./nlp_example.py
```
doesn't work either? If that's the case, if looks like something is wrong in your setup.

**Comment by Tangzy7** [comment]
It doesn't work either. My torch is 1.8.1+cu101. I think NCCL is installed with torch

**Comment by Tangzy7** [comment]
> Just to double-check:
> 
> ```
> python -m torch.distributed.launch --nproc_per_node 2 --use_env ./nlp_example.py
> ```
> 
> doesn't work either? If that's the case, if looks like something is wrong in your setup.

It doesn't work either. My torch is 1.8.1+cu101. I think NCCL is installed with torch

**Comment by pldlgb** [comment]
I think I met the same problem. How did you solve it in the end?

**Comment by sgugger** [comment]
If a reinstall does not fix it, I would look at the [PyTorch forums](https://discuss.pytorch.org/) for help.

**Comment by pldlgb** [comment]
I meet the same problem yesterday, perhaps you can check the process running in your machine by 'nvidia-smi'. And then kill some process. Hope It can  works.

**Comment by jaimeenahn** [comment]
If you are using docker, try adding `--ipc=host` while opening the container.
