### ISSUE TITLE
Not possible to launch distributed training with mixed_precision set to "bf16"

### ISSUE THREAD

**Issue by anshradh** [huggingface/accelerate#721]
### System Info

```Shell
Copy-and-paste the text below in your GitHub issue

- `Accelerate` version: 0.12.0
- Platform: Linux-5.4.0-105-generic-x86_64-with-debian-buster-sid
- Python version: 3.7.13
- Numpy version: 1.21.5
- PyTorch version (GPU?): 1.12.0 (True)
- `Accelerate` default config:
	- compute_environment: LOCAL_MACHINE
	- distributed_type: MULTI_GPU
	- mixed_precision: bf16
	- use_cpu: False
	- num_processes: 8
	- machine_rank: 0
	- num_machines: 1
	- main_process_ip: None
	- main_process_port: None
	- main_training_function: main
	- deepspeed_config: {}
	- fsdp_config: {}
	- downcast_bf16: False
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

```
def training_loop(mixed_precision="bf16", seed: int = 42, batch_size: int = 64):
  set_seed(seed)
  
  accelerator = Accelerator(mixed_precision=mixed_precision)
  
args = ("bf16", 42, 64)
notebook_launcher(training_loop, args, num_processes=8)
  
```

### Expected behavior

```Shell
I expect training to start with autocasting to bfloat16 - instead, I get the error: "RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method"

AFAICT, this is due to the "is_bf16_available" function in accelerate.utils, which calls "torch.cuda.is_available()" and "torch.cuda.is_bf16_supported()".
```

**Comment by muellerzr** [comment]
@anshradh can you please provide the full stack trace it gave you?

**Comment by muellerzr** [comment]
And just to confirm, we're trying to launch bf16 training on 8 GPUs and not TPUs right? :)

**Comment by anshradh** [comment]
Yup, 8 GPUs!

**Comment by muellerzr** [comment]
@anshradh I'm not noticing this on two A100's. Can you verify that the following minimal code works for you in a freshly reset jupyter notebook instance? I've broken it up by cells (which shouldn't matter)

```python
from accelerate import Accelerator, notebook_launcher
from accelerate.utils import set_seed
```
```python
def training_loop():
    set_seed(42)
    accelerator = Accelerator(mixed_precision="bf16")
    print("Hello There!")
```
```python
notebook_launcher(training_loop, (), num_processes=2)
```
(replace 2 with `n`, you can also try 2)

**Comment by muellerzr** [comment]
What GPU are you using in colab? IIRC out of the box they only have single GPU instances (Trying to make my test env match yours as best as humanly possible).

**Comment by anshradh** [comment]
It's actually connected to a local runtime which consists of 8 A100s.

**Comment by anshradh** [comment]
Sorry 8 A6000s, not A100s!

**Comment by muellerzr** [comment]
Hi @anshradh, working on trying to get resources to test this out, but I think I found the cause. Can we try one more time with the Accelerate installed in my bugfix branch?

```bash
pip install git+https://github.com/huggingface/accelerate@bf16-stas-method
```

Hopefully it works, thanks!

**Comment by anshradh** [comment]
Hmm it still seems to be failing on the minimal example - I get the following stack trace:

```
ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/opt/conda/lib/python3.7/site-packages/accelerate/utils/launch.py", line 89, in __call__
    self.launcher(*args)
  File "/tmp/ipykernel_2267126/3328339086.py", line 3, in training_loop
    accelerator = Accelerator(mixed_precision="bf16")
  File "/opt/conda/lib/python3.7/site-packages/accelerate/accelerator.py", line 251, in __init__
    **kwargs,
  File "/opt/conda/lib/python3.7/site-packages/accelerate/state.py", line 158, in __init__
    torch.cuda.set_device(self.device)
  File "/opt/conda/lib/python3.7/site-packages/torch/cuda/__init__.py", line 314, in set_device
    torch._C._cuda_setDevice(device)
  File "/opt/conda/lib/python3.7/site-packages/torch/cuda/__init__.py", line 208, in _lazy_init
    "Cannot re-initialize CUDA in forked subprocess. To use CUDA with "
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 
'spawn' start method
```

**Comment by muellerzr** [comment]
@anshradh actually this seems to be entirely unrelated to bf16. Does it work when setting the mixed precision to none (the default) or fp16?

**Comment by anshradh** [comment]
Nope, same stack trace for both of those cases.

**Comment by muellerzr** [comment]
I'll go ahead and change this as a feature request then and slightly modify the title, because really it's a Feature Request for running the `notebook_launcher` on the A6000 series. For now I'd recommend through the command line (not the best result I know, but that should work til we can get this!)

**Comment by anshradh** [comment]
Sounds good, thanks for your help!

**Comment by muellerzr** [comment]
No problem! Last question, what provider are you using for renting the 8 A6000 so I can look into it? :)

**Comment by anshradh** [comment]
https://www.runpod.io/

**Comment by muellerzr** [comment]
Just to make sure, does it break also if you don't use Colab? (Sometimes colab does some very weird things, so if we can test in native Jupyter that'd be nice :) )

**Comment by anshradh** [comment]
Nope, unfortunately no luck with Jupyter either.

**Comment by muellerzr** [comment]
This is indeed a torch backend issue, you can track it's progress here: https://github.com/pytorch/pytorch/issues/85841

**Comment by anshradh** [comment]
Oh interesting, thanks for diving into this!
