### ISSUE TITLE
use `accelerate` with `fastai` and `wandb`

### ISSUE THREAD

**Issue by deven-gqc** [huggingface/accelerate#729]
I know that `accelerate` has a mechanism which directly works with `wandb`, but upon having a callback with `fastai` inside a Learner object, `wandb` is unable to track any metrics.

**Comment by muellerzr** [comment]
@deven-gqc can you provide an example please? You should just be able to launch using fastai distributed and use their existing wandb callback

**Comment by deven-gqc** [comment]
This is the error I get,

```
Currently running fastai_distributed.py with bs = 1024, epochs = 50, and sample_00 image_csvs
The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_cpu_threads_per_process` was set to `32` to improve out-of-box performance
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
Traceback (most recent call last):
Traceback (most recent call last):
  File "/localscratch/vannary.45771063.0/sewer_ml/script_runner.py", line 61, in <module>
  File "/localscratch/vannary.45771063.0/sewer_ml/script_runner.py", line 61, in <module>
    main()
  File "/localscratch/vannary.45771063.0/sewer_ml/script_runner.py", line 49, in main
    main()    
f'{args["directory"]}.{args["script"]}')  File "/localscratch/vannary.45771063.0/sewer_ml/script_runner.py", line 49, in main

  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.7.9/lib/python3.7/importlib/__init__.py", line 127, in import_module
    f'{args["directory"]}.{args["script"]}')
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.7.9/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)    
return _bootstrap._gcd_import(name[level:], package, level)  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import

  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/localscratch/vannary.45771063.0/sewer_ml/script/fastai_distributed.py", line 17, in <module>
  File "/localscratch/vannary.45771063.0/sewer_ml/script/fastai_distributed.py", line 17, in <module>
        wandb.login(key=KEY)wandb.login(key=KEY)

  File "/project/6062137/vannary/CCTV/fastai/lib/python3.7/site-packages/wandb/sdk/wandb_login.py", line 74, in login
  File "/project/6062137/vannary/CCTV/fastai/lib/python3.7/site-packages/wandb/sdk/wandb_login.py", line 74, in login
Traceback (most recent call last):
  File "/localscratch/vannary.45771063.0/sewer_ml/script_runner.py", line 61, in <module>
    if wandb.setup()._settings._noop:
  File "/project/6062137/vannary/CCTV/fastai/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 312, in setup
    if wandb.setup()._settings._noop:
  File "/project/6062137/vannary/CCTV/fastai/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 312, in setup
    main()
  File "/localscratch/vannary.45771063.0/sewer_ml/script_runner.py", line 49, in main
    f'{args["directory"]}.{args["script"]}')
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.7.9/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/localscratch/vannary.45771063.0/sewer_ml/script/fastai_distributed.py", line 17, in <module>
    wandb.login(key=KEY)
  File "/project/6062137/vannary/CCTV/fastai/lib/python3.7/site-packages/wandb/sdk/wandb_login.py", line 74, in login
    ret = _setup(settings=settings)
  File "/project/6062137/vannary/CCTV/fastai/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 307, in _setup
    ret = _setup(settings=settings)
  File "/project/6062137/vannary/CCTV/fastai/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 307, in _setup
    wl = _WandbSetup(settings=settings)
      File "/project/6062137/vannary/CCTV/fastai/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 293, in __init__
if wandb.setup()._settings._noop:
  File "/project/6062137/vannary/CCTV/fastai/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 312, in setup
    wl = _WandbSetup(settings=settings)
  File "/project/6062137/vannary/CCTV/fastai/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 293, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "/project/6062137/vannary/CCTV/fastai/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 106, in __init__
    ret = _setup(settings=settings)    
_WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)  File "/project/6062137/vannary/CCTV/fastai/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 307, in _setup

  File "/project/6062137/vannary/CCTV/fastai/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 106, in __init__
    self._setup()
  File "/project/6062137/vannary/CCTV/fastai/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 234, in _setup
    wl = _WandbSetup(settings=settings)
  File "/project/6062137/vannary/CCTV/fastai/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 293, in __init__
    self._setup()    
self._setup_manager()  File "/project/6062137/vannary/CCTV/fastai/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 234, in _setup

  File "/project/6062137/vannary/CCTV/fastai/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 266, in _setup_manager
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "/project/6062137/vannary/CCTV/fastai/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 106, in __init__
    self._setup_manager()
  File "/project/6062137/vannary/CCTV/fastai/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 266, in _setup_manager
    _use_grpc=use_grpc, settings=self._settings
      File "/project/6062137/vannary/CCTV/fastai/lib/python3.7/site-packages/wandb/sdk/wandb_manager.py", line 108, in __init__
self._setup()
  File "/project/6062137/vannary/CCTV/fastai/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 234, in _setup
    _use_grpc=use_grpc, settings=self._settings
  File "/project/6062137/vannary/CCTV/fastai/lib/python3.7/site-packages/wandb/sdk/wandb_manager.py", line 108, in __init__
    self._setup_manager()
  File "/project/6062137/vannary/CCTV/fastai/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 266, in _setup_manager
    _use_grpc=use_grpc, settings=self._settings
  File "/project/6062137/vannary/CCTV/fastai/lib/python3.7/site-packages/wandb/sdk/wandb_manager.py", line 108, in __init__
        self._service.start()self._service.start()

  File "/project/6062137/vannary/CCTV/fastai/lib/python3.7/site-packages/wandb/sdk/service/service.py", line 112, in start
  File "/project/6062137/vannary/CCTV/fastai/lib/python3.7/site-packages/wandb/sdk/service/service.py", line 112, in start
    self._service.start()
  File "/project/6062137/vannary/CCTV/fastai/lib/python3.7/site-packages/wandb/sdk/service/service.py", line 112, in start
        self._launch_server()self._launch_server()

  File "/project/6062137/vannary/CCTV/fastai/lib/python3.7/site-packages/wandb/sdk/service/service.py", line 108, in _launch_server
  File "/project/6062137/vannary/CCTV/fastai/lib/python3.7/site-packages/wandb/sdk/service/service.py", line 108, in _launch_server
    self._launch_server()
  File "/project/6062137/vannary/CCTV/fastai/lib/python3.7/site-packages/wandb/sdk/service/service.py", line 108, in _launch_server
    assert ports_found    
assert ports_found
AssertionError
AssertionError
    assert ports_found
AssertionError
```

**Comment by muellerzr** [comment]
This looks unrelated to Accelerate, and has to do with wandb. Can you test this by running wandb by itself in a python script to see if you can use it to verify?

**Comment by deven-gqc** [comment]
Sure, I'll try and let you know.

**Comment by deven-gqc** [comment]
@muellerzr I think it was a `wandb` issue, its now resolved. Thanks Zach.
