### ISSUE TITLE
It seems this package coule not work on some pytorch version

### ISSUE THREAD

**Issue by KleinXin** [huggingface/accelerate#733]
### System Info

```Shell
accelerate  0.12.0
torch 1.12.0
torchvision 0.13.0
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

1. import accelerate

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/accelerate/__init__.py", line 7, in <module>
    from .accelerator import Accelerator
  File "/opt/conda/lib/python3.7/site-packages/accelerate/accelerator.py", line 27, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "/opt/conda/lib/python3.7/site-packages/accelerate/checkpointing.py", line 24, in <module>
    from .utils import (
  File "/opt/conda/lib/python3.7/site-packages/accelerate/utils/__init__.py", line 21, in <module>
    from .imports import (
  File "/opt/conda/lib/python3.7/site-packages/accelerate/utils/imports.py", line 20, in <module>
    from .versions import is_torch_version
  File "/opt/conda/lib/python3.7/site-packages/accelerate/utils/versions.py", line 24, in <module>
    import importlib_metadata
ModuleNotFoundError: No module named 'importlib_metadata'

### Expected behavior

```Shell
accelerate can be imported
```

**Comment by muellerzr** [comment]
Please do `pip install importlib_metadata` and it should solve this.

**Comment by KleinXin** [comment]
> Please do `pip install importlib_metadata` and it should solve this.

thx!
It works now. However, the training speed is not accelerated.
This package can only be used to implement the training on multi-gpus or fp16 training instead of speedup training?
