### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by shizhediao** [huggingface/accelerate#74]
When I am running two programs with the same python file, I encountered the following issue. I think it is because of the address/port, but I do not know how to change it.  

`Traceback (most recent call last):  File "run_clm_no_trainer.py", line 490, in <module>
    main()  File "run_clm_no_trainer.py", line 207, in main
    accelerator = Accelerator()
  File "/home/.conda/envs/transformers-sgd/lib/python3.7/site-packages/accelerate/accelerator.py", line 79, in __init__
    self.state = AcceleratorState(fp16=fp16, cpu=cpu, _from_accelerator=True)
  File "/home/.conda/envs/transformers-sgd/lib/python3.7/site-packages/accelerate/state.py", line 125, in __init__    torch.distributed.init_process_group(backend="nccl")
  File "/home/.local/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 436, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/home/.local/lib/python3.7/site-packages/torch/distributed/rendezvous.py", line 179, in _env_rendezvous_handler
    store = TCPStore(master_addr, master_port, world_size, start_daemon, timeout)
RuntimeError: Address already in use`

**Comment by sgugger** [comment]
You can specify a new port to use with `--main_process_port xxx` with the `accelerate launch` command.
You may also have hanging processes if this appears after launching a previous command that did not work (in PyTorch <= 1.7, the processes launched by the launcher are not properly killed when there is an error).

**Comment by shizhediao** [comment]
Thanks for your reply!
Is it ok with PyTorch==1.7.1?

**Comment by sgugger** [comment]
No, the fixed launcher is in PyTorch 1.8.

**Comment by shizhediao** [comment]
OK, thanks a lot!
