### ISSUE TITLE
Cannot configure Accelerate (AttributeError: module 'distutils' has no attribute 'version')

### ISSUE THREAD

**Issue by shcxlee** [huggingface/accelerate#793]
Hello,

I've successfully installed Accelerate but cannot configure it.
````
Successfully built accelerate
Installing collected packages: accelerate
  Attempting uninstall: accelerate
    Found existing installation: accelerate 0.13.2
    Uninstalling accelerate-0.13.2:
      Successfully uninstalled accelerate-0.13.2
Successfully installed accelerate-0.14.0.dev0
(speech2image)$ accelerate config
Traceback (most recent call last):
  File "/home/.conda/envs/speech2image/bin/accelerate", line 5, in <module>
    from accelerate.commands.accelerate_cli import main
  File "/home/speech2image/accelerate/src/accelerate/__init__.py", line 7, in <module>
    from .accelerator import Accelerator
  File "/home/speech2image/accelerate/src/accelerate/accelerator.py", line 33, in <module>
    from .tracking import LOGGER_TYPE_TO_CLASS, GeneralTracker, filter_trackers
  File "/home/speech2image/accelerate/src/accelerate/tracking.py", line 32, in <module>
    from torch.utils import tensorboard
  File "/home/.conda/envs/speech2image/lib/python3.9/site-packages/torch/utils/tensorboard/__init__.py", line 4, in <module>
    LooseVersion = distutils.version.LooseVersion
AttributeError: module 'distutils' has no attribute 'version'
````

**Comment by shcxlee** [comment]
Problem solved. I used `pip install setuptools==59.5.0`
