### ISSUE TITLE
[Bug] importlib.metadata.PackageNotFoundError: megatron-lm

### ISSUE THREAD

**Issue by comaniac** [huggingface/accelerate#809]
### System Info

```Shell
p.s. `accelerate env` crashes.

You only need the latest accelerate commit b816e258a95904736c8e3a5a2b14a18d5f407f4a.
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Clone `Megatron-LM`.
2. Add the path of `Megatron-LM` to `PYTHONPATH`.
3. `import accelerate`.

### Expected behavior

```Shell
`accelerate` should not crash.

With https://github.com/huggingface/accelerate/pull/755, accelerate checks whether `megatron` is available.
However, once it is available, accelerate loads `megatron-lm`.

Error message:

Traceback (most recent call last):
  File "/home/ubuntu/workspace_hf/transformers/src/transformers/utils/import_utils.py", line 1063, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/home/ubuntu/anaconda3/envs/hf-bench-env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/workspace_hf/transformers/src/transformers/modeling_utils.py", line 39, in <module>
    from .deepspeed import deepspeed_config, is_deepspeed_zero3_enabled
  File "/home/ubuntu/workspace_hf/transformers/src/transformers/deepspeed.py", line 38, in <module>
    from accelerate.utils.deepspeed import HfDeepSpeedConfig as DeepSpeedConfig
  File "/home/ubuntu/workspace_hf/accelerate/src/accelerate/__init__.py", line 7, in <module>
    from .accelerator import Accelerator
  File "/home/ubuntu/workspace_hf/accelerate/src/accelerate/accelerator.py", line 27, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "/home/ubuntu/workspace_hf/accelerate/src/accelerate/checkpointing.py", line 24, in <module>
    from .utils import (
  File "/home/ubuntu/workspace_hf/accelerate/src/accelerate/utils/__init__.py", line 100, in <module>
    from .megatron_lm import (
  File "/home/ubuntu/workspace_hf/accelerate/src/accelerate/utils/megatron_lm.py", line 38, in <module>
    if is_megatron_lm_available():
  File "/home/ubuntu/workspace_hf/accelerate/src/accelerate/utils/imports.py", line 96, in is_megatron_lm_available
    megatron_version = parse(importlib_metadata.version("megatron-lm"))
  File "/home/ubuntu/anaconda3/envs/hf-bench-env/lib/python3.8/importlib/metadata.py", line 530, in version
    return distribution(distribution_name).version
  File "/home/ubuntu/anaconda3/envs/hf-bench-env/lib/python3.8/importlib/metadata.py", line 503, in distribution
    return Distribution.from_name(distribution_name)
  File "/home/ubuntu/anaconda3/envs/hf-bench-env/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: megatron-lm
```
```

**Comment by sgugger** [comment]
cc @pacman100

**Comment by pacman100** [comment]
Hello @comaniac, could you please try the installing the Megatron-LM as explained in the pre-requisites section of the usage guide https://huggingface.co/docs/accelerate/main/en/usage_guides/megatron_lm#prerequisites. Let us know if that solves the issue.

**Comment by comaniac** [comment]
btw, I just found that the Megatron-LM installed with `pip install git+https://github.com/huggingface/Megatron-LM.git` failed to work with PyTorch nightly:

```
Python 3.8.13 (default, Mar 28 2022, 11:38:47)
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.14.0.dev20221102+cu117'
>>> import accelerate
Wandb import failed
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/workspace_hf/accelerate/src/accelerate/__init__.py", line 7, in <module>
    from .accelerator import Accelerator
  File "/home/ubuntu/workspace_hf/accelerate/src/accelerate/accelerator.py", line 27, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "/home/ubuntu/workspace_hf/accelerate/src/accelerate/checkpointing.py", line 24, in <module>
    from .utils import (
  File "/home/ubuntu/workspace_hf/accelerate/src/accelerate/utils/__init__.py", line 100, in <module>
    from .megatron_lm import (
  File "/home/ubuntu/workspace_hf/accelerate/src/accelerate/utils/megatron_lm.py", line 39, in <module>
    from megatron import (
  File "/home/ubuntu/anaconda3/envs/hf-bench-env/lib/python3.8/site-packages/megatron/__init__.py", line 27, in <module>
    from .initialize  import initialize_megatron
  File "/home/ubuntu/anaconda3/envs/hf-bench-env/lib/python3.8/site-packages/megatron/initialize.py", line 37, in <module>
    from megatron.checkpointing import load_args_from_checkpoint
  File "/home/ubuntu/anaconda3/envs/hf-bench-env/lib/python3.8/site-packages/megatron/checkpointing.py", line 28, in <module>
    from .utils import (unwrap_model,
  File "/home/ubuntu/anaconda3/envs/hf-bench-env/lib/python3.8/site-packages/megatron/utils.py", line 24, in <module>
    import amp_C
ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
```

**Comment by pacman100** [comment]
Hello, the above PR should resolve the issue of checking Megatron-LM when it is only put in `PYTHONPATH` without it being launched. By the way, feel free to try out Megatron-LM integration in Accelerate which makes it super easy to use with minimal code changes to existing scripts for BERT, GPT and T5 models. Also, the above error `ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory` might be because of -> Cuda extensions are being compiled with a version of Cuda that does not match the version used to compile Pytorch binaries. I was able to reproduce above error when the bare metal cuda was `11.0` and I installed PyTorch 1.13.0 compiled with CUDA `11.6`.

**Comment by comaniac** [comment]
@pacman100 thanks for the PR. The fix looks good to me.

I know that the import error was due to inconsistent CUDA versions and it happens to official Megatron too. However, the official Megatron doesn't provide wheels so everyone has to build from source, which eliminates this issue as it always builds the extension based on the current installed PyTorch. I would suggest not releasing pre-built .so library but directly building it from source at the moment of first initialization, just like what Megatron does.
