### ISSUE TITLE
Training after several epochs it throws cudaErrorLaunchFailure: unspecified launch failure

### ISSUE THREAD

**Issue by over-shine** [huggingface/accelerate#83]
When I use accelerate to my model, it often throws this problem after training several epochs. And my code as follows:
```python
    def train(self, train_step, compute_metric, eval_step, train_scratch=False):
        wandb.init(project=self.model._get_name(), resume=~train_scratch)
        self.logger.info("Start training model")
        wandb.watch(self.model, log="all")
        wandb.save("model.py")
        set_seed(self.config.seed)
        self.model.train()
        accelerator = Accelerator(fp16=True)
        start_epoch = 1
        data_loader = self.get_train_dataset_dataloader()
        optimizer = self.optimizer(self.model.parameters(), lr=self.config.lr)
        schedule = get_cosine_schedule_with_warmup(optimizer,
                                                   num_warmup_steps=1000,
                                                   num_training_steps=len(data_loader) * self.config.epochs)
        if train_scratch:
            model, optimizer, data_loader = accelerator.prepare(self.model, optimizer, data_loader)
            start_epoch = 1
            best_metric = 0.
        elif os.path.exists(self.output_dir) and os.listdir(self.output_dir):
            checkpoint = self.load_checkpoint()
            self.model.load_state_dict(checkpoint['net'])
            optimizer.load_state_dict(checkpoint["optimizer"])
            schedule.load_state_dict(checkpoint['scheduler'])
            start_epoch = checkpoint['epoch'] + 1 if checkpoint['epoch'] > 1 else 1
            best_metric = checkpoint["best_metric"]
            model, optimizer, data_loader = accelerator.prepare(self.model, optimizer, data_loader)

        last_step = len(data_loader) - 1
        train_loss, train_score, log_info = 0., {}, {}
        eval_loss, eval_score = 0., {}
        for epoch in range(start_epoch, self.config.epochs + 1):
            # do train
            model.train()
            for i, data in enumerate(tqdm(data_loader, desc=f"Epoch {epoch}/{self.config.epochs}"), start=1):
                torch.cuda.empty_cache()
                outputs = train_step(model=model, data=data)
                loss = outputs.loss / self.config.accumulate_step
                train_loss += loss.item()
                accelerator.backward(loss)
                if i % self.config.accumulate_step == 0 or i == last_step:
                    optimizer.step()
                    schedule.step()
                    optimizer.zero_grad()
                    wandb.log({"lr": schedule.get_last_lr()[-1]},
                              step=math.ceil(i / self.config.accumulate_step) + math.ceil(
                                  (epoch - 1) * len(data_loader) / self.config.accumulate_step))
                compute_metric(outputs.logits, data['labels'], self.metrics)
            train_loss = train_loss / len(data_loader)
            for metric in self.metrics:
                train_score.update(metric.compute())
            log_info.update({"train_acc": train_score["accuracy"], "train_loss": train_loss})
            self.logger.info("Epoch {}/{} train_loss={:.5f}\t train_accuracy={:.5f}".format(epoch, self.config.epochs,
                                                                                            loss,
                                                                                            train_score['accuracy']))
            # do eval
            if self.eval_dataset:
                model.eval()
                eval_loader = accelerator.prepare(self.get_val_dataset_dataloader())
                for i, data in enumerate(tqdm(eval_loader, desc=f"Eval Epoch {epoch}/{self.config.epochs}"), start=1):
                    outputs = eval_step(model, data)
                    eval_loss += outputs.loss.item()
                    compute_metric(outputs.logits, data['labels'], self.metrics)
                eval_loss = eval_loss / len(eval_loader)
                for metric in self.metrics:
                    eval_score.update(metric.compute())
                log_info.update({"eval_loss": eval_loss, "eval_acc": eval_score["accuracy"]})
                self.logger.info(
                    "Eval Epoch {}/{} eval_loss={:.5f}\t eval_accuracy={:.5f}".format(epoch, self.config.epochs,
                                                                                      eval_loss,
                                                                                      eval_score['accuracy']))
```
And the error as follows:
```python
`Traceback (most recent call last):
  File "D:/code/GNN_LM1/train.py", line 43, in <module>
    trainer.train(train_step, msm_compute_metric, eval_step, train_scratch=True)
  File "D:\code\GNN_LM1\trainer.py", line 138, in train
    train_loss += loss.item()
  File "C:\Anaconda3\lib\site-packages\accelerate\accelerator.py", line 249, in backward
    self.scaler.scale(loss).backward()
  File "C:\Anaconda3\lib\site-packages\torch\tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "C:\Anaconda3\lib\site-packages\torch\autograd\__init__.py", line 145, in backward
    Variable._execution_engine.run_backward(
RuntimeError: transform: failed to synchronize: cudaErrorLaunchFailure: unspecified launch failure
```
pytorch version: 1.8
I want to know what cause this problem and how to make it?

**Comment by sgugger** [comment]
I must say I have never seen that error. A quick search on the [PyTorch forums](https://discuss.pytorch.org/t/strange-cuda-error-on-specific-gpu-cuda-error-unspecified-launch-failure/33062/2) seems to say it may be related to a bad driver install?
