### ISSUE TITLE
Issues running `bigscience/bloom` inference on 3 * 40GB a100 cards 

### ISSUE THREAD

**Issue by darraghdog** [huggingface/accelerate#864]
### System Info

```Shell
Linux Distribution:		Ubuntu 20.04.5 LTS
Linux Kernel:			5.4.0-121-generic
Computer Model:			NVIDIA DGXA100 920-23687-2530-000 v1.0 (40GB per card)
Processor (CPU):		AMD EPYC 7742 64-Core Processor
CPU Sockets/Cores/Threads:	2/128/256
Architecture:			x86_64 (64-bit)
Total memory (RAM):		1031875 MiB (1008GiB) (1081999 MB (1.1TB))

- `Accelerate` version: 0.14.0
- Platform: Linux-5.4.0-121-generic-x86_64-with-glibc2.10
- Python version: 3.8.13
- Numpy version: 1.22.2
- PyTorch version (GPU?): 1.13.0a0+d0d6b1f (True)
- `Accelerate` default config:
	Not found


accelerate==0.14.0
bitsandbytes==0.35.4
deepspeed==0.7.5
transformers==4.24.0

Docker built from nvcr.io/nvidia/pytorch:22.10-py3

Python 3.8.13
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

To start the docker container,
```
cd ~
docker run -itd --name BLOOM3GPU -v $PWD:/mount -v /raid/darragh/:/raid1 --shm-size=1024G --gpus '"device=1,2,3"' --rm nvcr.io/nvidia/pytorch:22.10-py3
git clone https://github.com/huggingface/transformers-bloom-inference
cd transformers-bloom-inference
pip install --upgrade transformers accelerate bitsandbytes
docker attach BLOOM3GPU
export TRANSFORMERS_CACHE="/raid1/huggingface"
cd transformers-bloom-inference
```
To run the benchmark script,
```
CUDA_VISIBLE_DEVICES=0,1,2 python bloom-inference-scripts/bloom-accelerate-inference.py --name bigscience/bloom --dtype int8 --batch_size 1 --benchmark
```

When I run this, with 3 a100 GPU cards (40GB each) I get the below message. 

```
Traceback (most recent call last):
  File "bloom-inference-scripts/bloom-accelerate-inference.py", line 79, in <module>
    model = AutoModelForCausalLM.from_pretrained(model_name, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 463, in from_pretrained
    return model_class.from_pretrained(
  File "/opt/conda/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2280, in from_pretrained
    raise ValueError(
ValueError: 
                        Some modules are dispatched on the CPU or the disk. Make sure you have enough GPU RAM to fit
                        the quantized model. If you have set a value for `max_memory` you should increase that. To have
                        an idea of the modules that are set on the CPU or RAM you can print model.hf_device_map.
```

### Expected behavior

I have tried a few different ways to run the script and get the model loaded in memory (across CPU/GPU). I can try it on up to 7 GPU cards, but am starting with 3 cards.     
As in the script, 
```Shell
CUDA_VISIBLE_DEVICES=0,1,2 python bloom-inference-scripts/bloom-accelerate-inference.py --name bigscience/bloom --dtype int8 --batch_size 1 --benchmark
```
  
Without `int8`
```
CUDA_VISIBLE_DEVICES=0,1,2 python bloom-inference-scripts/bloom-accelerate-inference.py --name bigscience/bloom --batch_size 1 --benchmark
```
  
I have also tried manually adding a mapping as `kwargs` in the loading of the model. 
```
{'device_map': 'auto', 'load_in_8bit': True, 'max_memory': {0: '40GiB', 1: '40GiB', 2: '40GiB', 'cpu': '512GiB'}}
```
```

**Comment by sgugger** [comment]
Not sure what the issue is here. As the error clearly mentions, you cannot use `int8` with offloaded weights as it's not possible to offload modules in int8.

**Comment by darraghdog** [comment]
@sgugger FYI, I got it working using the below on 5 x 40GB A100 cards... I think what I missed in the (tutorial)[https://huggingface.co/blog/bloom-inference-pytorch-scripts] was explicitely setting `max_memory` per card and setting it a bit lower than the card memory, to allow for the forward pass. 

Its working like a charm now, thanks for all the work! 

```
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

MAX_NEW_TOKENS = 128
model_name = "bigscience/bloom"

text = """
Q: On average Joe throws 25 punches per minute. A fight lasts 5 rounds of 3 minutes. 
How many punches did he throw?\n
A: Let’s think step by step.\n"""

tokenizer = AutoTokenizer.from_pretrained(model_name)
input_ids = tokenizer(text, return_tensors="pt").input_ids

max_memory = '38GB'

n_gpus = torch.cuda.device_count()
max_memory = {i: max_memory for i in range(n_gpus)}

print(f'Max memory : {max_memory}')


model = AutoModelForCausalLM.from_pretrained(
  model_name,
  device_map='auto',
  load_in_8bit=True,
  max_memory=max_memory
)
generated_ids = model.generate(input_ids, max_length=MAX_NEW_TOKENS)
print(tokenizer.decode(generated_ids[0], skip_special_tokens=True))
```
