### ISSUE TITLE
Question: How to I use the kwargs handler to pass DDP params?

### ISSUE THREAD

**Issue by antopost** [huggingface/accelerate#870]
I would like to set broacast_buffers=False when wrapping DDP.
The [documentation](https://huggingface.co/docs/accelerate/v0.2.0/kwargs.html) suggests using a kwargs handler class, but I have no idea how to pass it to Accelerator.

This is how I imagined it:

```
import copy
from dataclasses import dataclass


class KwargsHandler:

    def to_dict(self):
        return copy.deepcopy(self.__dict__)

    def to_kwargs(self):
        default_dict = self.__class__().to_dict()
        this_dict = self.to_dict()
        return {k: v for k, v in this_dict.items() if default_dict[k] != v}

@dataclass
class DistributedDataParallelKwargs(KwargsHandler):

    broadcast_buffers: bool = False

# Here I create an instance of KwargsHandler
kw = DistributedDataParallelKwargs()

# But passing it like this throws an error
accelerator = Accelerator(kwargs_handlers=kw)
```

Any help would be much appreciated!

**Comment by sgugger** [comment]
You need to use the kwarg handles in the library:
```py
from accelerate import Accelerator
from accelerate.utils import DistributedDataParallelKwargs

accelerator = Accelerator(kwargs_handlers=[DistributedDataParallelKwargs(broadcast_buffers=False)])
```

**Comment by antopost** [comment]
Many thanks, @sgugger !

**Comment by muellerzr** [comment]
@antopost alright if I reopen this and flag docs so I can improve it? 😄

**Comment by antopost** [comment]
You're very welcome to do so ^^

**Comment by antopost** [comment]
@sgugger
Actually, when I try instantiate accelerator using more than one gpu, I get the following error:
```

  File "train.py", line 46, in __init__
    self.accelerator = Accelerator(gradient_accumulation_steps=self.gas,
  File "/opt/conda/lib/python3.8/site-packages/accelerate/accelerator.py", line 227, in __init__
    assert isinstance(handler, KwargsHandler), f"Unsupported kwargs handler passed: {handler}."
AssertionError: Unsupported kwargs handler passed: DistributedDataParallelKwargs(broadcast_buffers=False).
Traceback (most recent call last):
  File "train.py", line 645, in <module>
    main(config, output_dir, args)
  File "train.py", line 610, in main
    TA = TrainAgent(config, output_dir, args)
  File "train.py", line 46, in __init__
    self.accelerator = Accelerator(gradient_accumulation_steps=self.gas,
  File "/opt/conda/lib/python3.8/site-packages/accelerate/accelerator.py", line 227, in __init__
    assert isinstance(handler, KwargsHandler), f"Unsupported kwargs handler passed: {handler}."
AssertionError: Unsupported kwargs handler passed: DistributedDataParallelKwargs(broadcast_buffers=False).
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2190) of binary: /opt/conda/bin/python
```
Could it be due to using the nightly version of accelerate?
```
- `Accelerate` version: 0.14.0.dev0
- Platform: Linux-5.4.0-128-generic-x86_64-with-glibc2.17
- Python version: 3.8.12
- Numpy version: 1.21.5
- PyTorch version (GPU?): 1.12.1+cu113 (True)
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: MULTI_GPU
        - mixed_precision: no
        - use_cpu: False
        - num_processes: 2
        - machine_rank: 0
        - num_machines: 1
        - gpu_ids: all
        - main_process_ip: None
        - main_process_port: None
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - deepspeed_config: {}
        - fsdp_config: {}
        - downcast_bf16: no
```

**Comment by muellerzr** [comment]
Will look into this and improve the docs

**Comment by muellerzr** [comment]
@antopost are you sure you're using the Accelerate kwarg handler class? As that's very important. This works for me:

```python
from accelerate import Accelerator
from accelerate.utils import DistributedDataParallelKwargs

def main():
  kwarg_handler = DistributedDataParallelKwargs(broadcast_buffers=False)
  accelerator = Accelerator(kwargs_handlers=[kwarg_handler])

if __name__ == "__main__":
  main()
```

This was ran on two GPUs

**Comment by antopost** [comment]
@muellerzr Yes, it works for me now. My I forgot to delete some code that broke the kwarghandler class. I'll make my edit a bit clearer.

**Comment by JulesGM** [comment]
hello @muellerzr, is there a way to do this with accelerate config file directly
