### ISSUE TITLE
cv_example.py fail at final epoch, ValueError: Tried to step 281 times. The specified number of total steps is 279

### ISSUE THREAD

**Issue by r-matsuzaka** [huggingface/accelerate#874]
### System Info

- Ubuntu Desktop 22.04 LTS
- 2GPUs RTX2080, RTX2080 super
- Driver nvidia-driver-510

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

Please run followings:  

```
$ docker run --gpus all --shm-size 16G -it --rm nvidia/cuda:11.6.0-cudnn8-devel-ubuntu20.04 /bin/bash
# apt-get update && apt-get install -y python3 python3-pip git vim curl wget
# cd
# git clone https://github.com/huggingface/accelerate.git
# pip3 install torch torchvision numpy timm accelerate Pillow deepspeed
# cd accelerate/examples
# wget https://thor.robots.ox.ac.uk/~vgg/data/pets/images.tar.gz
# tar -xzf images.tar.gz
# python3 -m torch.distributed.launch --nproc_per_node 2 --use_env ./cv_example.py --data_dir images
/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py:180: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Downloading: "https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-weights/resnet50d_ra2-464e36ba.pth" to /root/.cache/torch/hub/checkpoints/resnet50d_ra2-464e36ba.pth
Downloading: "https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-weights/resnet50d_ra2-464e36ba.pth" to /root/.cache/torch/hub/checkpoints/resnet50d_ra2-464e36ba.pth
epoch 0: 85.99
epoch 1: 87.69
Traceback (most recent call last):
  File "./cv_example.py", line 211, in <module>
    main()
  File "./cv_example.py", line 207, in main
    training_function(config, args)
  File "./cv_example.py", line 163, in training_function
    lr_scheduler.step()
  File "/usr/local/lib/python3.8/dist-packages/accelerate/scheduler.py", line 75, in step
    self.scheduler.step(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/optim/lr_scheduler.py", line 161, in step
    values = self.get_lr()
  File "/usr/local/lib/python3.8/dist-packages/torch/optim/lr_scheduler.py", line 1686, in get_lr
    raise ValueError("Tried to step {} times. The specified number of total steps is {}"
ValueError: Tried to step 281 times. The specified number of total steps is 279
Traceback (most recent call last):
  File "./cv_example.py", line 211, in <module>
    main()
  File "./cv_example.py", line 207, in main
    training_function(config, args)
  File "./cv_example.py", line 163, in training_function
    lr_scheduler.step()
  File "/usr/local/lib/python3.8/dist-packages/accelerate/scheduler.py", line 75, in step
    self.scheduler.step(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/optim/lr_scheduler.py", line 161, in step
    values = self.get_lr()
  File "/usr/local/lib/python3.8/dist-packages/torch/optim/lr_scheduler.py", line 1686, in get_lr
    raise ValueError("Tried to step {} times. The specified number of total steps is {}"
ValueError: Tried to step 281 times. The specified number of total steps is 279
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1330) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
./cv_example.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2022-11-19_09:28:11
  host      : 4b4968aba1a3
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 1331)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-11-19_09:28:11
  host      : 4b4968aba1a3
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1330)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

```

### Expected behavior

`python3 -m torch.distributed.launch --nproc_per_node 2 --use_env ./cv_example.py --data_dir images` finish with no error.

P.S.  
BTW, the url in `wget https://www.robots.ox.ac.uk/~vgg/data/pets/data/images.tar.gz` is no longer available. So I used `wget https://thor.robots.ox.ac.uk/~vgg/data/pets/images.tar.gz` instead.

**Comment by muellerzr** [comment]
Hi @r-matsuzaka this looks to have been fixed in https://github.com/huggingface/accelerate/pull/849, and will be solved in the next release which will be in a few days. In the interim install accelerate from github with `pip install git+https://github.com/huggingface/accelerate`.

**Comment by r-matsuzaka** [comment]
Hi, @muellerzr . Thank you very much for your reply and workaround. I will tri it and share the result here:)

**Comment by r-matsuzaka** [comment]
@muellerzr 
Thank you very much. It worked! Is it okay to close the issue?

**Comment by muellerzr** [comment]
Fantastic! Yep feel free :)
