### ISSUE TITLE
Program stuck at 'pad_across_processes'

### ISSUE THREAD

**Issue by ZeyiLiao** [huggingface/accelerate#876]
### System Info

```Shell
Copy-and-paste the text below in your GitHub issue

- `Accelerate` version: 0.14.0
- Platform: Linux-4.15.0-194-generic-x86_64-with-debian-buster-sid
- Python version: 3.7.3
- Numpy version: 1.21.6
- PyTorch version (GPU?): 1.9.1+cu111 (True)
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: DEEPSPEED
        - mixed_precision: no
        - use_cpu: False
        - num_processes: 4
        - machine_rank: 0
        - num_machines: 1
        - gpu_ids: None
        - main_process_ip: None
        - main_process_port: None
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - deepspeed_config: {'gradient_accumulation_steps': 1, 'offload_optimizer_device': 'cpu', 'offload_param_device': 'cpu', 'zero3_init_flag': True, 'zero3_save_16bit_model': False, 'zero_stage': 3}
        - fsdp_config: {}
        - megatron_lm_config: {}
        - downcast_bf16: no
        - tpu_name: None
        - tpu_zone: None
        - command_file: None
        - commands: None
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

1. The code at [here](https://github.com/huggingface/transformers/blob/main/examples/pytorch/translation/run_translation_no_trainer.py)

2. Can replace the datasets with own small datasets for debugging.

3.Model just stuck at [line674 ](https://github.com/huggingface/transformers/blob/d316037ad71f8748aac9045ffd96970826456a04/examples/pytorch/translation/run_translation_no_trainer.py#L674)and finally said time limit error. 

### Expected behavior

```Shell
Can run successfully but program stuck at pad_across_devices
```

**Comment by pacman100** [comment]
Hello @ZeyiLiao, when using DeepSpeed Zero Stage-3, the `generate()` call in eval loop hangs because it is missing `synced_gpus=True` argument. Please refer  issue https://github.com/huggingface/transformers/issues/20130 which details what's happening and how to resolve it.

**Comment by ZeyiLiao** [comment]
@pacman100 Gotcha! Reaaly helps!!

And would you mind checking why the program can not exit correctly with --report_to wandb --with_tracking?

And I just simply modify the code like this:
```
    if args.with_tracking:
        if accelerator.is_main_process:
            experiment_config = vars(args)
            # TensorBoard cannot log Enums, need the raw value
            experiment_config["lr_scheduler_type"] = experiment_config["lr_scheduler_type"].value
            tmp = {"entity":"zeyiliao","name":str(args.output_dir).replace("./","")}
            accelerator.init_trackers("t5-finetune", experiment_config,init_kwargs={"wandb":tmp})
```

error looks like
```
Configuration saved in ./t5-large-79a06195-d1b9-4b5a-8b7f-b2c0181fced8/config.json
Model weights saved in ./t5-large-79a06195-d1b9-4b5a-8b7f-b2c0181fced8/pytorch_model.bin
tokenizer config file saved in ./t5-large-79a06195-d1b9-4b5a-8b7f-b2c0181fced8/tokenizer_config.json
Special tokens file saved in ./t5-large-79a06195-d1b9-4b5a-8b7f-b2c0181fced8/special_tokens_map.json
Copy vocab file to ./t5-large-79a06195-d1b9-4b5a-8b7f-b2c0181fced8/spiece.model
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11/11 [01:21<00:00,  7.44s/it]
Exception in thread SockSrvRdThr:
Traceback (most recent call last):
  File "/home/zeyi/miniconda3/envs/longtail/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/zeyi/miniconda3/envs/longtail/lib/python3.7/site-packages/wandb/sdk/service/server_sock.py", line 112, in run
    shandler(sreq)
  File "/home/zeyi/miniconda3/envs/longtail/lib/python3.7/site-packages/wandb/sdk/service/server_sock.py", line 173, in server_record_publish
    iface = self._mux.get_stream(stream_id).interface
  File "/home/zeyi/miniconda3/envs/longtail/lib/python3.7/site-packages/wandb/sdk/service/streams.py", line 199, in get_stream
    stream = self._streams[stream_id]
KeyError: 'cs1ulxr6'
```


All the checkpoints can save correctly and wandb can also log correctly, just the code can not exit correcly.

**Comment by pacman100** [comment]
Hello @ZeyiLiao, this is different issue, anyways, I don't know the root cause for this but to resolve it just remove the following lines 
```diff
- if args.with_tracking:
-        accelerator.end_training()
```

**Comment by pacman100** [comment]
If this is resolved, can you please go ahead and close the issue?

**Comment by ZeyiLiao** [comment]
Sure!
