### ISSUE TITLE
Type error when importing

### ISSUE THREAD

**Issue by EmreTaha** [huggingface/accelerate#886]
### System Info

```Shell
accelerate 0.14
torch 1.12.1+cu113
numpy 1.21.5
Python 3.8.13
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

`accelerate config`

```
Traceback (most recent call last):
  File "/home/optima/temre/anaconda3/envs/preproc_env/bin/accelerate", line 5, in <module>
    from accelerate.commands.accelerate_cli import main
  File "/home/optima/temre/anaconda3/envs/preproc_env/lib/python3.8/site-packages/accelerate/__init__.py", line 7, in <module>
    from .accelerator import Accelerator
  File "/home/optima/temre/anaconda3/envs/preproc_env/lib/python3.8/site-packages/accelerate/accelerator.py", line 27, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "/home/optima/temre/anaconda3/envs/preproc_env/lib/python3.8/site-packages/accelerate/checkpointing.py", line 24, in <module>
    from .utils import (
  File "/home/optima/temre/anaconda3/envs/preproc_env/lib/python3.8/site-packages/accelerate/utils/__init__.py", line 23, in <module>
    from .imports import (
  File "/home/optima/temre/anaconda3/envs/preproc_env/lib/python3.8/site-packages/accelerate/utils/imports.py", line 26, in <module>
    from .versions import compare_versions, is_torch_version
  File "/home/optima/temre/anaconda3/envs/preproc_env/lib/python3.8/site-packages/accelerate/utils/versions.py", line 28, in <module>
    torch_version = parse(importlib_metadata.version("torch"))
  File "/home/optima/temre/anaconda3/envs/preproc_env/lib/python3.8/site-packages/packaging/version.py", line 49, in parse
    return Version(version)
  File "/home/optima/temre/anaconda3/envs/preproc_env/lib/python3.8/site-packages/packaging/version.py", line 264, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
```

### Expected behavior

```Shell
Not to receive error when importing or just calling `accelerate env` , `accelerate config` or `import accelerate`
```

**Comment by muellerzr** [comment]
@EmreTaha which o.s. are you running on?

**Comment by EmreTaha** [comment]
> @EmreTaha which o.s. are you running on?

Hi, I am using CentOs 7
