### ISSUE TITLE
accelerator.end_training() is generating exception when wandb is being used as tracker

### ISSUE THREAD

**Issue by DuttaSamarpan** [huggingface/accelerate#944]
### System Info

```Shell
- `Accelerate` version: 0.15.0
- Platform: macOS-13.1-arm64-i386-64bit
- Python version: 3.9.15
- Numpy version: 1.24.0
- PyTorch version (GPU?): 1.13.1 (False)
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: MPS
        - mixed_precision: bf16
        - use_cpu: False
        - dynamo_backend: NO
        - num_processes: 1
        - machine_rank: 0
        - num_machines: 1
        - gpu_ids: None
        - main_process_ip: None
        - main_process_port: None
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - deepspeed_config: {}
        - fsdp_config: {}
        - megatron_lm_config: {}
        - downcast_bf16: no
        - tpu_name: None
        - tpu_zone: None
        - command_file: None
        - commands: None
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

I am initiating my accelerator tracker in this way
<img width="947" alt="Screenshot 2022-12-24 at 11 45 43 PM" src="https://user-images.githubusercontent.com/104805069/209457383-f9a4deed-e22b-43de-9e02-12cf40a8f771.png">
and finishing my experiment in this way
<img width="953" alt="Screenshot 2022-12-24 at 11 47 53 PM" src="https://user-images.githubusercontent.com/104805069/209457396-55fb23dc-8b2b-4c34-a584-9ab860f9f71c.png">
It throws the below exception

Exception in thread SockSrvRdThr:
Traceback (most recent call last):
File "/Users/samarpandutta/miniforge3/envs/banjo-accelerate-demo/lib/python3.9/threading.py", line 980, in _bootstrap_inner
self.run()
File "/Users/samarpandutta/miniforge3/envs/banjo-accelerate-demo/lib/python3.9/site-packages/wandb/sdk/service/server_sock.py", line 112, in run
shandler(sreq)
File "/Users/samarpandutta/miniforge3/envs/banjo-accelerate-demo/lib/python3.9/site-packages/wandb/sdk/service/server_sock.py", line 173, in server_record_publish
iface = self._mux.get_stream(stream_id).interface
File "/Users/samarpandutta/miniforge3/envs/banjo-accelerate-demo/lib/python3.9/site-packages/wandb/sdk/service/streams.py", line 199, in get_stream
stream = self._streams[stream_id]
KeyError: '3lxi4eq2'

where the key `3lxi4eq2` is actually the wandb run_id

### Expected behavior

```Shell
Exception should not be thrown at `accelerator.end_training()`
```

**Comment by sgugger** [comment]
cc @muellerzr

**Comment by somepago** [comment]
+1. I am facing the same issue.

**Comment by cloud441** [comment]
Hello,

I am facing the same problem, I trained a HF Transformers model using accelerate Multi-GPU (2 GPUs and no additional optimizations) and I run my script from a terminal.

By the way, Wandb interface shows all my training informations, just the `end_tracking()` method failed.

If you want additional information, I can help.

**Comment by yjw1029** [comment]
Hi, 

I meet the same problem when running "run_glue_no_trainer.py" script.

Here is my script.
```
export WANDB_API_KEY="xxxx"

accelerate launch run_glue_no_trainer.py \
--model_name_or_path bert-base-cased \
--task_name sst2 \
--max_length 128 \
--per_device_train_batch_size 32 \
--learning_rate 2e-5 \
--num_train_epochs 1 \
--output_dir ../checkpoint/sst2 \
--with_tracking \
--report_to wandb 
```

Here is my environment setup.
```
FROM pytorch/pytorch:1.13.0-cuda11.6-cudnn8-devel

RUN pip install --no-cache-dir \
    transformers==4.25.1 \
    accelerate>=0.12.0 \
    datasets>=1.8.0 \
    sentencepiece!=0.1.92 \
    evaluate==0.3.0 \
    scipy \
    protobuf==3.20.0 \
    scikit-learn \
    seaborn \
    ipython \
    wandb \
    tqdm \
    azure-datalake-store==0.0.51 \
    azure-storage-queue==12.1.5 \
    mlflow==1.26.0 \
    azureml-mlflow==1.43.0 \
    azureml-dataprep==4.2.2 \
    azureml-dataprep-native==38.0.0 \
    azureml-dataprep-rslex==2.8.1
```

**Comment by detkov** [comment]
Same problem
```
Python 3.10.8

accelerate==0.15.0
wandb==0.13.9
```

**Comment by muellerzr** [comment]
We've reached out to the W&B folks, we should have a solution soon!

**Comment by hmartiro** [comment]
I'm having the same issue

**Comment by duxiaodan** [comment]
Same issue here. I'm using accelerate 0.15.0

**Comment by nabarunbaruaAIML** [comment]
Solved it by passing keyword Setting in init_kwargs and then passing it to accelerate.init
init_kwargs={"wandb":{"group":wandb_dict['group_name'],"name":wandb_dict['display_name'],'settings':wandb.Settings(start_method="fork")}}
         
        accelerator.init_trackers(wandb_dict['project_name'], config=parameter, init_kwargs=init_kwargs)

**Comment by muellerzr** [comment]
@nabarunbaruaAIML thanks for the pointer! Will pass along to the W&B team.
They should have a fix by the next release as they've identified the problem as well.

The workaround they suggested was disabling the console for now:

```python
        init_kwargs = {"wandb":{"settings":{"console": "off"}}}
        accelerator.init_trackers("glue_no_trainer", experiment_config, init_kwargs=init_kwargs)
```

**Comment by somepago** [comment]
@nabarunbaruaAIML  - Can you  share the version of accelerate and wandb you are using? Thanks!

**Comment by nabarunbaruaAIML** [comment]
@somepago : I am using these versions accelerate=0.16.0 & wandb=0.13.9

**Comment by muellerzr** [comment]
The fix for this *should* be out now, let us know if you all are still seeing this issue
