### ISSUE TITLE
load_checkpoint_and_dispatch() method doesn't work with int8 quantized models

### ISSUE THREAD

**Issue by vdabravolski** [huggingface/accelerate#974]
### System Info

```Shell
accelerate-0.15.0
bitsandbytes-0.36.0.post2
huggingface-hub-0.11.1
tokenizers-0.13.2
transformers-4.25.1

Compute instance: AWS p4d (8x A100 40Gb)
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

I'm trying to use Accelerate in combination with bitsandbytes quantization library to load and dispatch model evenly across multiple GPUs on my compute node to do batch inference. 

I expect that load_checkpoint_and_dispatch() method will work regardless the precision of the model. However, that's not the case. Using load_checkpoint_and_dispatch() method with int8 models returns following error: ` "RuntimeError: Only Tensors of floating point and complex dtype can require gradients" `. Loading int8 model using  .from_pretrained() method works as expected.

Code sample to reproduce
```python
from transformers import (
    AutoConfig,
    AutoModelForCausalLM,
)
import torch
from accelerate import (
    infer_auto_device_map,
    init_empty_weights,
    load_checkpoint_and_dispatch,
)

# 1. Define initial model parameters
dtype = torch.int8
model_name = "EleutherAI/gpt-neox-20b"
model_config = AutoConfig.from_pretrained(model_name)
max_model_memory = 10

# 2. Define quantization parameters
loading_kwargs = dict()
loading_kwargs["load_in_8bit"] = True
loading_kwargs[
    "load_in_8bit_threshold"
] = 2.0

# 3. Instantiate empty model with int8 precision
with init_empty_weights():
    model = AutoModelForCausalLM.from_pretrained(
        args.model_name, **loading_kwargs
    )

# 4. Get device map based on max_model_memory parameter
max_memory_per_gpu = {
    0: f"{max_model_memory}GIB",
    1: f"{max_model_memory}GIB",
    2: f"{max_model_memory}GIB",
    3: f"{max_model_memory}GIB",
    4: f"{max_model_memory}GIB",
    5: f"{max_model_memory}GIB",
    6: f"{max_model_memory}GIB",
    7: f"{max_model_memory}GIB",
}

device_map = infer_auto_device_map(
    model,
    no_split_module_classes=model._no_split_modules,
    dtype=dtype,
    max_memory=max_memory_per_gpu,
)

# 5. Dispatch already instantiate int8 model
load_checkpoint_and_dispatch(
    model,
    model_name,
    offload_folder=None,
    offload_state_dict=False,
    dtype=args.dtype,
    device_map=device_map
)
```

The code below returns following stack trace:
```


Traceback (most recent call last):  
load_checkpoint_and_dispatch(  File "/opt/conda/lib/python3.8/site-packages/accelerate/big_modeling.py", line 375, in load_checkpoint_and_dispatch
load_checkpoint_in_model(  File "/opt/conda/lib/python3.8/site-packages/accelerate/utils/modeling.py", line 699, in load_checkpoint_in_model
set_module_tensor_to_device(model, param_name, param_device, value=param)  File "/opt/conda/lib/python3.8/site-packages/accelerate/utils/modeling.py", line 132, in set_module_tensor_to_device
new_value = param_cls(new_value, requires_grad=old_value.requires_grad, **kwargs).to(device)  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parameter.py", line 37, in __new__    return torch.Tensor._make_subclass(cls, data, requires_grad)
RuntimeError: Only Tensors of floating point and complex dtype can require gradients
```

If i load the same model with the same device map using .from_pretrained() method, it will work just fine.
```python
# 1. Define initial model parameters
dtype = torch.int8
model_name = "EleutherAI/gpt-neox-20b"
model_config = AutoConfig.from_pretrained(model_name)
max_model_memory = 10

# 2. Define quantization parameters
loading_kwargs = dict()
loading_kwargs["load_in_8bit"] = True
loading_kwargs[
    "load_in_8bit_threshold"
] = 2.0

# 3. Instantiate empty model with int8 precision
with init_empty_weights():
    model = AutoModelForCausalLM.from_pretrained(
        args.model_name, **loading_kwargs
    )

# 4. Get device map based on max_model_memory parameter
max_memory_per_gpu = {
    0: f"{max_model_memory}GIB",
    1: f"{max_model_memory}GIB",
    2: f"{max_model_memory}GIB",
    3: f"{max_model_memory}GIB",
    4: f"{max_model_memory}GIB",
    5: f"{max_model_memory}GIB",
    6: f"{max_model_memory}GIB",
    7: f"{max_model_memory}GIB",
}

device_map = infer_auto_device_map(
    model,
    no_split_module_classes=model._no_split_modules,
    dtype=dtype,
    max_memory=max_memory_per_gpu,
)

loading_kwargs['device_map'] = device_map

# 5. Loading model using Transformers API
model = AutoModelForCausalLM.from_pretrained(args.model_name, **loading_kwargs)
```

### Expected behavior

```Shell
I expect that load_checkpoint_and_dispatch() method works with all supported precisions, including quantized int8.
```

**Comment by sgugger** [comment]
I think the problem lies within the `dtype` passed to `load_checkpoint_and_dispatch`. Not all the weights are converted to int8s, so you can't just pass `dtype=torch.int8` like this. Leaving it as none would probably work better.

**Comment by vdabravolski** [comment]
@sgugger thanks. I tried setting `dtype=None` in `load_and_dispatch_mode()`, i believe that model is automatically considered as FP32 in this case. So not exactly what I expected to happen. I can confirm it by looking at final model memory footprint. Let me know if you need any additional details.
