### ISSUE TITLE
'NoneType' object is not callable and CalledProcessError

### ISSUE THREAD

**Issue by pldlgb** [huggingface/accelerate#99]
Hi! When I try the nlp sample code, some errors occur.

```bash
Traceback (most recent call last):
  File "./nlp_example.py", line 173, in <module>
    main()
  File "./nlp_example.py", line 169, in main
    training_function(config, args)
  File "./nlp_example.py", line 64, in training_function
    datasets = load_dataset("glue", "mrpc")
  File "/home/water/anaconda3/envs/Sodic/lib/python3.7/site-packages/datasets/load.py", line 741, in load_dataset
    **config_kwargs,
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "./nlp_example.py", line 173, in <module>
    main()
  File "./nlp_example.py", line 169, in main
    training_function(config, args)
  File "./nlp_example.py", line 64, in training_function
    datasets = load_dataset("glue", "mrpc")
  File "/home/water/anaconda3/envs/Sodic/lib/python3.7/site-packages/datasets/load.py", line 741, in load_dataset
    **config_kwargs,
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "/home/water/anaconda3/envs/Sodic/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/water/anaconda3/envs/Sodic/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/water/anaconda3/envs/Sodic/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/water/anaconda3/envs/Sodic/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/water/anaconda3/envs/Sodic/bin/python', '-u', './nlp_example.py']' returned non-zero exit status 1.

**Comment by sgugger** [comment]
It looks like there is something wrong with your installation of the `datasets` library, as the script fails on that line `datasets = load_dataset("glue", "mrpc")` which has nothing to do with Accelerate.

**Comment by pldlgb** [comment]
Ok, I will try it again
